### ISSUE TITLE
Installation fail in conda env

### ISSUE THREAD

**Issue by Jessime** [igraph/python-igraph#100]
I've just successfully compiled the C core library, and am now trying to install `python-igraph` in a anaconda environment. I did:

```bash
conda create --name kmers anaconda
source activate kmers
pip install python-igraph
```

which produced:

```
Collecting python-igraph
  Downloading python-igraph-0.7.1.post6.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 2.2MB/s 
Installing collected packages: python-igraph
  Running setup.py install for python-igraph ... done
Successfully installed python-igraph-0.7.1.post6
```

I then start IPython and do:

```python
In [1]: import igraph
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8e950eb5d8d8> in <module>()
----> 1 import igraph

/home/jessime/anaconda2/envs/kmers/lib/python2.7/site-packages/igraph/__init__.py in <module>()
     32 # pylint: disable-msg=W0401
     33 # W0401: wildcard import
---> 34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
     36 from igraph.clustering import *

ImportError: libigraph.so.0: cannot open shared object file: No such file or directory
```

[StackExchange](http://askubuntu.com/questions/587486/problem-linking-igraph-importerror-libigraph-so-0) suggested I might need to run `sudo ldconfig` to get things working. After running that, I still get:

```python
In [1]: import igraph
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8e950eb5d8d8> in <module>()
----> 1 import igraph

/home/jessime/anaconda2/envs/kmers/lib/python2.7/site-packages/igraph/__init__.py in <module>()
     32 # pylint: disable-msg=W0401
     33 # W0401: wildcard import
---> 34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
     36 from igraph.clustering import *

ImportError: /home/jessime/anaconda2/envs/kmers/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/lib/libigraph.so.0)
```

Thoughts on where to go next?

**Comment by ntamas** [comment]
The C core of the igraph library was probably compiled for a different ABI version of the standard C++ library than the one that is used by Anaconda Python. Your best bet is probably to uninstall the C core (run `make uninstall` if you still have the source code of the C core where you compiled it) and then just attempt to install the Python interface from within the Anaconda virtual environment. The `setup.py` script in the Python interface will download the source code of the C core and compile it together with the Python interface itself when it is not able to detect an already compiled and installed C core on your machine, so this way the C core will be compiled for the same ABI of the standard C++ library as Anaconda itself.

**Comment by Jessime** [comment]
Alright, I gave that a shot, but no luck:

```bash
source activate kmers
pip --no-cache-dir install python-igraph
```

works as expected and has to compile the C core:

```
Collecting python-igraph
  Downloading python-igraph-0.7.1.post6.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 4.4MB/s 
Installing collected packages: python-igraph
  Running setup.py install for python-igraph ... done
Successfully installed python-igraph-0.7.1.post6
```

But running IPython now gives:

```python
In [1]: import igraph
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8e950eb5d8d8> in <module>()
----> 1 import igraph

/home/jessime/anaconda2/envs/kmers/lib/python2.7/site-packages/igraph/__init__.py in <module>()
     32 # pylint: disable-msg=W0401
     33 # W0401: wildcard import
---> 34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
     36 from igraph.clustering import *

ImportError: /home/jessime/anaconda2/envs/kmers/lib/python2.7/site-packages/igraph/_igraph.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev
```

**Comment by ntamas** [comment]
There is no proof in the output that you have posted that it actually tries to download and compile the C core - all I can see is that it downloaded the Python interface and compiled that, but it does not show whether the Python interface was linked to a freshly downloaded and compiled version of igraph or one that was found on your system somewhere. On my machine, it looks like this when `pip` tries to download and compile the C core on its own:

```
Installing collected packages: python-igraph
  Running setup.py install for python-igraph
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1

    Using temporary directory: /Users/ntamas/.pyenv/versions/2.7.10/envs/test/build/python-igraph/tmp/igraph.qZrkG4
Downloading igraph-0.7.1.tar.gz... 100.00%
...
```

and then there is a huge chunk of compiler output, starting from the `./configure` script of the C core.

First, try looking for files named `libigraph0.so` or `igraph.pc` and similar on your machine. If you find such files, delete them. Then, uninstall `python-igraph` from Anaconda Python and try `pip install python-igraph` again, making sure that it actually downloads the C core instead of re-using some version of the C core that it finds on your machine. When it tries to re-use an existing version of the C core, the output of `pip` should look like this:

```
Installing collected packages: python-igraph
  Running setup.py install for python-igraph
    Build type: dynamic extension
    Include path: /usr/local/Cellar/igraph/0.7.1_3/include/igraph
    Library path: /usr/local/Cellar/igraph/0.7.1_3/lib
```

**Comment by Jessime** [comment]
I explained myself poorly in the last comment, sorry. I ran through the process twice before, the second time with `pip -vvv` to get the output you're mentioning. 

I've done a few things since then:
1. I looked for `libigraph0.so`, etc. but didn't find any files to delete.
2. Instead of just running `make uninstall` in my previous C core directory, I deleted the entire thing.
3. I tried installing `python-igraph` in my root Anaconda folder instead of the environment, to make sure that wasn't adding any unnecessary trouble.

Specifically,

     pip --no-cache-dir -vvv install python-igraph

It ran successfully, and printed the entire compilation process again. My output that's equivalent to what you mentioned is:

```
    ...
    Build type: static extension
    Include path: igraphcore/include
    Library path: igraphcore/lib /usr/local/lib /usr/lib /lib64 /lib
    Runtime library path:
    Linked dynamic libraries: xml2 z m stdc++
    Linked static libraries: igraphcore/lib/libigraph.a
    Extra compiler options:
    Extra linker options:
    building 'igraph._igraph' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    ....
```

I get the exact same error as before at this point. Do these paths and the linked dynamic libraries look correct?

**Comment by Jessime** [comment]
While I never solved the compilation problems, it turns out I didn't have to. All I needed was:

    conda install -c marufr python-igraph=0.7.1.post6

as found [here](https://anaconda.org/marufr/python-igraph). I can then do:

```python
In [1]: import igraph.test

In [2]: igraph.test.run_tests()
...
Ran 307 tests in 9.191s

OK
```

Thanks for all the help and sorry for the trouble!

**Comment by ntamas** [comment]
Great, thanks, I did not know about this last option. It looks like these are precompiled packages of igraph for Anaconda; I wonder whether the original author had to change anything to make it work. Anyway, I'm glad that it works now!

**Comment by Jessime** [comment]
Yea, hopefully it's a viable option for the next confused noob who comes around!
