### ISSUE TITLE
Jupyter notebook plotting does not work with pycairo

### ISSUE THREAD

**Issue by tschoppi** [igraph/python-igraph#102]
Trying to plot a graph in a jupyter notebook raises an exception, and displays no graph:

```python
igraph.plot(igraph.Graph.Tree(30, 2))
```

```
TypeError                                 Traceback (most recent call last)
/home/.../virtenv/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    309             method = get_real_method(obj, self.print_method)
    310             if method is not None:
--> 311                 return method()
    312             return None
    313         else:

/home/.../virtenv/lib/python3.5/site-packages/igraph/drawing/__init__.py in _repr_svg_(self)
    350         # No idea why this is needed but python crashes without
    351         context.show_page()
--> 352         surface.finish()
    353         # Return the raw SVG representation
    354         result = io.getvalue()

TypeError: a bytes-like object is required, not 'str'
```

This is with version `0.7.1.post6` of python-igraph, and persists even after cherry-picking in 3eb9f27139eb8d7dc2d7416181b03f6f6cd83862 (as shown in the traceback above), which should supposedly solve this issue (see #60).

**Comment by tschoppi** [comment]
The error also occurs with version `0.8.0-pre+17df5c3` of python-igraph.

**Comment by tschoppi** [comment]
So, after a lot of testing, I have figured out that the error arises when using `pycairo` instead of `cairocffi`.

This issue is simply fixed by uninstalling `pycairo` from the virtual environment and installing `cairocffi`. Seeing as how the rest of the program should also work fine with this other package, maybe the documentation should also reflect this fact, and recommend the `pip`-installable `cairocffi` package.

**Comment by ntamas** [comment]
Hmmm, must be some kind of a difference between the implementation of `pycairo` vs `cairocffi`. I thought they are API-compatible, so that's why I haven't emphasized `cairocffi` over `cairo` (I was thinking about it as a fallback solution if compiling `pycairo` is not feasible). Anyway, thanks!
