### ISSUE TITLE
add.edge (simplest case) always reorders source and target

### ISSUE THREAD

**Issue by paul-shannon** [igraph/python-igraph#105]
Surely I am missing something!

     g.add_vertices(3)
     g.add_edge(0, 1)
     g.add_edge(2, 1)
     g.es[0].source; g.es[0].target   # as expected: 0 -> 1
     g.es[1].source; g.es[1].target   # reordered:   1 -> 2 - not the 2 -> 1 requested

Yet the API specifies

    add_edge(source, target, **kwds)

Can you offer any help?

Thanks!

**Comment by ntamas** [comment]
Most likely the graph is undirected, in which case igraph is free to swap the source and the target of the edge. If the direction of the edge matters, construct the graph as directed:`Graph(directed=True)`.

**Comment by paul-shannon** [comment]
Of course!   Thank you.
