### ISSUE TITLE
fruchterman_reingold: lovely layout with an undirected graph; linear layout with directed

### ISSUE THREAD

**Issue by paul-shannon** [igraph/python-igraph#106]
Switching from an undirected to a directed graph, the fr layout produces a not-so-helpful straight line layout, rather than the pleasing tree-based layout of the undirected graph.

Perhaps this is related to this   [R stackoverflow question](http://stackoverflow.com/questions/20641165/layout-layout-reingold-tilford-issue-ploting-a-tree-in-r).

I am not sure how to apply this solution in the python API.

**Comment by ntamas** [comment]
The R question is different; it is about the Reingold-Tilford layout, not the Fruchterman-Reingold layout. Please upload an example graph somewhere (or paste it here) so I can take a look at it.

**Comment by paul-shannon** [comment]
Sorry I failed to provide a better bug report.   I herewith mend my ways, hoping this is more useful.  (As you point out, it is the RT layout that seems to behave oddly.)

The graph here is longer than what's needed to demonstrate the problem:  even with only the first four edges in a directed graph, all the y coordinates are equal, producing a straight line layout.

 - Paul

```
from igraph import *
tbl = [['R1', 'a'],
       ['R1',  'b'],
       ['R1',  'c'],
       ['g1',  'R1'],
       ['R2',  'a'],
       ['R2',  'd'],
       ['R2',  'e'],
       ['g2',  'R2'],
       ['g3',  'R2'],
       ['R3',  'c'],
       ['R3',  'f'],
       ['R3',  'h'],
       ['R3',  'i'],
       ['g4',  'R3'],
       ['g5',  'R3'],
       ['R4',  'x'],
       ['R4',  'y'],
       ['R4',  'z'],
       ['R4',  'w'],
       ['g6',  'R4'],
       ['R5',  'z'],
       ['R5',  'z1']]

vertices = list(set([x for row in tbl for x in row]))
gDirected = Graph(directed=True)

gDirected.add_vertices(vertices)
gDirected.add_edges(tbl)
ftd = gDirected.layout("reingold_tilford")
print("--- reingold_tilford layout of a directed graph")
for i in range(len(ftd)):   # just the y coordinaes, to display the problem
    print("%f, %f" % (ftd[i][0], ftd[i][1]))

gUndirected = Graph(directed=False)
gUndirected.add_vertices(vertices)
gUndirected.add_edges(tbl)
ftu = gUndirected.layout("reingold_tilford")
print("--- reingold_tilford layout of the same graph, this time undirected")
for i in range(len(ftu)): # again, just the y
    print("%f, %f" % (ftu[i][0], ftu[i][1]))
```

**Comment by ntamas** [comment]
Okay, the solution then is probably the same as in the original R question: you need to specify which node should be at the root of the tree. (igraph tries to make an educated guess by default, but apparently it fails in the directed case). Unfortunately the syntax is a bit clumsy because the `root=...` argument accepts integer vertex indices only, not vertex names, so you'll need to do something like this:

```
root = gDirected.vs.find("R1").index
ftd = gDirected.layout("reingold_tilford", root=root)
```

I hope this resolves the problem.

**Comment by paul-shannon** [comment]
Thanks, Tamas.  This solves the problem nicely.
