### ISSUE TITLE
Unusually long execution times for `Graph.maxflow`

### ISSUE THREAD

**Issue by aldur** [igraph/python-igraph#107]
I'm developing a project that makes heavy usage of the `Graph.maxflow` function (in the order of millions of calls, with different inputs, on the same underlying graph).

I'm running Python 3.5 and `python-igraph` from branch `release-0.7` to which I applied commit db0e2f1.
I noticed that some of the inputs make the function very slow:
Usually, it returns in significantly less than a second; with these particular inputs instead, it takes more than 10 minutes.

To furtherly complicate the matter is that the problem seems to be deterministic (i.e. on the same graph and the same inputs is always slow) but I have no easy ways to debug it. The best I can do is to attach a debugger to the CPython interpreter and confirm that it is stuck around here: `_igraph.cpython-35m-darwin.so-igraph_maxflow + 7319`.

Is there any way I can detail what is happening/where/why the C core is looping?

**Comment by ntamas** [comment]
You would need to compile the C core separately from the Python module first, using `./configure --enable-debug`, install it on your machine (`make && make install`), and then compile the Python interface separately. If you did everything correctly, the `setup.py` script in the Python interface would find the installed C core (if you have installed `pkg-config`), and link to it dynamically. Then the stack trace in the debugger would show the exact file and line number in `igraph_maxflow`.

However, if you upload one of the problematic inputs to some place where I could download it from, I'll take a look at it myself.
