### ISSUE TITLE
http://igraph.org/nightly is down

### ISSUE THREAD

**Issue by prene** [igraph/python-igraph#108]
http://igraph.org/nightly is down

`curl: (22) The requested URL returned error: 404 Not Found`
`Error: Failed to download resource "igraph"`
`Download failed: http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz`

Which results in all pip installs and brew installs to fail.

**Comment by ninsbl** [comment]
The Python docs are not available either (Error 404)...
http://igraph.org/python/doc/tutorial/tutorial.html

**Comment by ntamas** [comment]
@gaborcsardi is currently moving the old igraph.org homepage to be hosted at Github Pages. Stay tuned - this will probably be fixed soon.

**Comment by prene** [comment]
Thx for the quick fix - seems to work again.
