### ISSUE TITLE
Error while installing python-igraph on Ubuntu 16.04

### ISSUE THREAD

**Issue by Omer80** [igraph/python-igraph#109]
Hello, I've tried to install python-igraph through `pip install` and `anaconda`, but both give me errors during installations.
Installing through `pip install` gave:
`ImportError: /home/user/anaconda2/lib/python2.7/site-packages/igraph/_igraph.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev`

Full error description from the attempt through anaconda is given here - [link](http://dpaste.com/29EVF25)

The question in [stackoverflow](http://stackoverflow.com/questions/41360586/error-while-installing-python-igraph-on-ubuntu-16-04)

**Comment by prene** [comment]
As I commented already in stackoverflow, this is most likely related to https://github.com/igraph/python-igraph/issues/108

**Comment by ntamas** [comment]
The error message in your first comment is different from the error message found in the full error description link that you provided, so I'm confused - which one did you actually get?

Anyway, use the precompiled Anaconda Python package from [here]( https://anaconda.org/marufr/python-igraph).

**Comment by Omer80** [comment]
I got the first one from trying to install using `pip install python-igraph`, and the second one using `pip install -i https://pypi.anaconda.org/pypi/simple python-igraph`

**Comment by ntamas** [comment]
For the record (in case anyone else finds this page): The first one seems to be an incompatibility between the standard C++ library provided by Anaconda Python and the one used by the system itself. The second is a version mismatch between the C core of igraph that you probably have already installed on your system and the Python interface that Anaconda Python tries to compile.
