### ISSUE TITLE
Path connectivity

### ISSUE THREAD

**Issue by sr-murthy** [igraph/python-igraph#110]
I've been looking at the python-igraph tutorial, but I can't find any obvious way of determining if two vertices in an undirected graph are connected, i.e. if there is a path that connects them. For example, in the following simple undirected graph with three vertices and two edges:

    >>> g = Graph([(0,1), (1,2)])

    >>> print(g)
    IGRAPH U--- 3 2 --
    + edges:
    0--1 1--2

I need to be able to show that vertices `0` and `2` are connected by the path `0-1-2`, and that if I add any new edges between existing or new vertices then I am able to calculate the total number of connections that a given vertex `v` has to the other vertices. Obviously I can do this myself via backtracking, but is there already a way of doing this in the library?

**Comment by ntamas** [comment]
```
>>> g.get_shortest_paths(v=0, to=2)
[[0, 1, 2]]
```

If you plan to do this for lots of target vertices with the same source, you can also pass multiple vertices to the `to` argument (and it makes things faster).

Re the "total number of connections", I'm not sure how that is defined for a given vertex *v* - please clarify.

**Comment by sr-murthy** [comment]
Thanks. I note that if there isn't an edge between two vertices then `g.get_shortest_paths(v=v, to=w)` (where `v` and `w` are two vertices in the graph) generates a runtime warning, not an exception. This is convenient - the idea for the total number of connections/paths for a given vertex `v` is simply to sum `g.get_shortest_paths(v=v, to=w)` for all other vertices `w` in the graph, i.e.

    def connections(g, v):
        return sum(1 if g.get_shortest_paths(v=v, to=w) else 0 for w in g.vs())

but this assumes that `g.get_shortest_paths(v=v, to=w)` returns `None` if there is no such shortest path, which doesn't appear to be the case.

**Comment by ntamas** [comment]
You can use `shortest_paths` then - it will simply return the *length* of the shortest path and prints no warnings:

```
def connections(g, v):
    inf = float('inf')
    return sum(0 < path_length < inf for path_length in g.shortest_paths(source=0)[0]) - 1
```

**Comment by sr-murthy** [comment]
Thanks. I think `g.get_shortest_paths(v=v, to=<iterable>)` is sufficient for my purpose. I've also noticed something odd about the graph representation after adding an edge:

    >>> g.add_vertex(3)

    >>> g.add_edge(0,3)

    >>> print(g)
    IGRAPH UN-- 4 3 --
    + attr: name (v)
    + edges (vertex names):
    None--None, None--None, None--3

Why does the display format change? I was expected the last line to be

    0--1, 1--2, 0--3

or something similar.

**Comment by ntamas** [comment]
This is because the first argument of `add_vertex` is the *name* of the vertex being added. Before the call, your graph did not have vertex names (`g.is_named()` returns `False`), so igraph displayed the vertex indices in the output. When you called `add_vertex(3)`, you added a new vertex with its name set to `3`. However, since the remaining vertices did not have names, igraph simply used `None` as their names, and then used these made-up names in the output.

To avoid this, you should either call `g.add_vertex()` without the argument, or add names for the original vertices as well (by setting `g.vs["name"]` to a list of names).

**Comment by sr-murthy** [comment]
Thanks.

**Comment by mustaf86alasadi** [comment]
is there any way to find the edge betweenness for specific edge in directed graph , in which the edge has zero cost (imaginary edge) has no impact on betweenness score calculation
