### ISSUE TITLE
In Graph::write_svg, tkinter expects an integer for font size, is given a string

### ISSUE THREAD

**Issue by Sidnioulz** [igraph/python-igraph#114]
**Current behaviour:**
The write_svg function takes either an integer or a string of the form "12px", etc. as a font_size parameter. This parameter is converted into a string, and passed to tkinter (when graphs contain nodes of shape "3") on line 2081 of __init__.py:

    font = tkinter.font.Font(root=tk.Tk(), font=("Sans", font_size, tkinter.font.NORMAL))

This causes tkinter to fail to initialise a font and to raise the following exception:

    _tkinter.TclError: expected integer but got "12px"

**Expected outcome:**
No unhandled exception is raised. The font is properly initialised and a graph generated.

**Solution:**
Re-convert the "12px" string into an integer for this specific code path (to support current code which already returns parameters).

**Comment by ntamas** [comment]
thanks!
