### ISSUE TITLE
Read_GML() causes segmentation fault on macOS Sierra 10.12.3 and Ubuntu 12.04.5

### ISSUE THREAD

**Issue by isokrates** [igraph/python-igraph#116]
Hi,

I originally filed this here: https://github.com/igraph/igraph/issues/977.

I don't know whether it should be filed in igraph or in python-igraph, so apologies for the duplication.

In any case, could you possibly have a look at the issue?

Thanks very much!

**Comment by ntamas** [comment]
Most likely it belongs to igraph/igraph - I'll close this for the time being and I will reopen if it turns out that this is a Python-specific issue.
