### ISSUE TITLE
Installation fails with this message 

### ISSUE THREAD

**Issue by vsraptor** [igraph/python-igraph#117]
............................
u/4.8/../../../x86_64-linux-gnu/crtn.o    -Wl,-soname -Wl,libigraph.so.0 -o .libs/libigraph.so.0.0.0

/usr/bin/ld: cannot find -lxml2

collect2: error: ld returned 1 exit status

make[3]: *** [libigraph.la] Error 1

make[3]: Leaving directory `/tmp/pip_build_root/python-igraph/tmp/igraph.HXjqFk/igraph-0.7.1/src'

make[2]: *** [all] Error 2

make[2]: Leaving directory `/tmp/pip_build_root/python-igraph/tmp/igraph.HXjqFk/igraph-0.7.1/src'

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory `/tmp/pip_build_root/python-igraph/tmp/igraph.HXjqFk/igraph-0.7.1'

make: *** [all] Error 2

Extracting igraph-0.7.1.tar.gz...

Configuring igraph...

Could not download and compile the C core of igraph.

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6DrU3b-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/python-igraph
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)

**Comment by ntamas** [comment]
The `UnicodeDecodeError` at the end is irrelevant (it is a `pip` bug); the real error message is here:

> /usr/bin/ld: cannot find -lxml2

You need to install `libxml2-dev` and maybe also `libiconv-dev` (assuming that you are on Ubuntu).

**Comment by vsraptor** [comment]
thanks it worked out
