### ISSUE TITLE
Installing igraph dependancies

### ISSUE THREAD

**Issue by Herlderlord** [igraph/python-igraph#118]
Hello, 

When i follow the guide to install igraph (http://igraph.org/python/) i've a problem of dependancies : 
- lxml2 
- lz 

What is needed is just to install two packages in Ubuntu : 
```
sudo apt-get install -y libxml2  zlib1g-dev
```

my machine is on : Ubuntu Mate 16.04

Is it possible to add this information on the web guide (get started) ? 

PS : I hope this issue has not already been sent to you and sorry for my english. ^^

**Comment by fgonard** [comment]
Same here, except I installed the dev' version `libxml2-dev` following the C library requirements.
(Xubuntu 16.04, installation through `pip3`)

**Comment by ntamas** [comment]
Yes, `libxml2-dev` is the way to go, `libxml2` is not enough. I'll update the docs when I find some time, thanks for the heads up.
