### ISSUE TITLE
manylinux wheel deployment to PyPI

### ISSUE THREAD

**Issue by kozo2** [igraph/python-igraph#120]
Could I ask you to upload the python-igraph manylinux wheel to PyPI?
If we can `pip install python-igraph` without building from source code, we can use it on [Azure Notebooks](https://notebooks.azure.com/).

I created [a sample project ](https://github.com/kozo2/python-igraph-manylinux) to assist [the wheel creation](https://github.com/kozo2/python-igraph-manylinux/releases) .
Could you please consider to use Travis CI for creating the python-igraph manylinux wheels.

Though I know the [manylinux.docker](https://github.com/igraph/python-igraph/blob/master/docker/manylinux.docker) in this repository, 
it would be better to create another repository and make Travis CI create the manylinux wheels.
For example in [this project ](https://github.com/kozo2/python-igraph-manylinux), creating a tag will upload the wheel built in Travis CI to GitHub releases.

**Comment by ntamas** [comment]
Thanks a lot for this!

Let me check if I understand this correctly -- basically the idea would be for me to create a new `python-igraph-manylinux` repo under my ownership, and create a `.travis.yml` in it that does something similar to what you do in your own project, _but_ upload the wheels to PyPI instead? (I guess I could simply copy your `.travis.yml` file and then update the `deploy` section accordingly).

As a first step, is it okay if I take the manylinux wheels from your repo and then simply upload them to PyPI manually?

**Comment by kozo2** [comment]
Yes, that's right, except
```
but upload the wheels to PyPI instead?
```
You can replace [this line](https://github.com/kozo2/python-igraph-manylinux/blob/master/.travis.yml#L28) to `provider: pypi` and directly upload the wheels to PyPI.
But it would be better that once you deploy on *GitHub releases*, and check that the whls works well, and manually upload the whls to PyPI.

Because (as far as I know) once you upload a whl to PyPI, you cannot replace it with the same filename.
(And you will be forced to release again with the version up.)



Yes of course >>
```
As a first step, is it okay if I take the manylinux wheels from your repo and then simply upload them to PyPI manually?
```
I recommend using [twine](https://pypi.python.org/pypi/twine) for the upload.
You can upload the whl with this command
```
twine upload THE_WHL_YOU_DOWNLOAD_FROM_GITHUB
```

**Comment by kozo2** [comment]
BTW I created another project for Mac.
https://github.com/kozo2/python-igraph-macosx
https://github.com/kozo2/python-igraph-macosx/releases
 
Actually, there seems to be [a package](https://github.com/matthew-brett/multibuild) for executing the builds for manylinux, mac, appveyor in one .travis.yml at once, but it is difficult for me and I can not use it. So I separated the projects like this.

**Comment by flying-sheep** [comment]
Getting this set up would be super awesome!

Eventually Windows wheels would be amazing too, I still didn’t manage to compile python-igraph on Windows…

**Comment by ntamas** [comment]
I have finally found some time to work on this (hopefully). I was checking the Travis config file in @kozo2's [python-igraph-manylinux repo](https://github.com/kozo2/python-igraph-manylinux/blob/master/.travis.yml) to understand how it should work. @kozo2, why do you rename the static libs for `libxml2` before building?

**Comment by jankatins** [comment]
This is an example how to build wheels and upload to pypi for all three OS: https://github.com/joerick/cibuildwheel-autopypi-example

**Comment by scottgigante** [comment]
Bump!

**Comment by iosonofabio** [comment]
I just started a new job. I'll be on this in just a week or two

**Comment by ntamas** [comment]
We now build Python wheels in Appveyor and Travis so I consider this issue as resolved.

**Comment by kozo2** [comment]
👍
