### ISSUE TITLE
[Request] appveyor.yml

### ISSUE THREAD

**Issue by kozo2** [igraph/python-igraph#121]
Could you give me some clues to write appveyor.yml for python-igraph?
I would like to use build product from https://github.com/igraph/igraph/blob/master/appveyor.yml
for the creation of python-igraph wheel.
But I have no idea to connect them in the appveyor.yml for this repository.

I know that [the igraph appveyor.yml have worked well](https://ci.appveyor.com/project/kozo2/igraph-o5p9i).

**Comment by ntamas** [comment]
I'm not familiar with Appveyor; @janschulz wrote `appveyor.yml` for igraph. Maybe he can help.

**Comment by janschulz** [comment]
@kozo2 at some point I wanted to try writing a python-igraph appveyor but I got stuck with the work of compiling the main repo... At that time, the main setup.py way of downloading and compiling igraph wasn't working at all on windows :-/

I've uploaded my work, but it's WIP and probably not working https://github.com/janschulz/python-igraph/commit/8913d2e5ac6787e19dc7732b8083118f1ffe8bce

My idea was basically:
* Get the igraph downlaod+compile method to work on windows
* build a appveyor file to compile the python wheels 

A easier method (which relies on a precompiled igraph) is probably to download a specific igraph and compile against that.

**Comment by ntamas** [comment]
An appveyor.yml file is now provided and it will build Python wheels for python-igraph on Windows. Travis CI is used for building Python wheels for Linux and macOS. Closing this.

**Comment by kozo2** [comment]
@ntamas 
Great!
Can I see the link(URL) to the Appveyor build?

**Comment by ntamas** [comment]
There are still some issues with it in the linking stage so it's not working yet - stay tuned :)

Here is the [latest version](https://github.com/igraph/python-igraph/blob/master/appveyor.yml) of `appveyor.yml`, and here is the [latest build](https://ci.appveyor.com/project/ntamas/python-igraph). As you can see, the problem right now is that MSVC does not seem to find the `libxml2` library that I installed from MSYS before the build so it cannot link to it. The solution might be as simple as providing the proper library path to `setup.py`, but I haven't had time to continue experimenting with it yet.

**Comment by ntamas** [comment]
Appveyor now builds 64-bit wheels properly:

https://ci.appveyor.com/project/ntamas/python-igraph

32-bit wheels are not created yet.

**Comment by kozo2** [comment]
@ntamas Great!
We may not need the 32-bit version anymore.
