### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by NoamGit** [igraph/python-igraph#122]
Hi,

I've tried to install igraph with the following
```
sudo apt-get install -y libxml2-dev  zlib1g-dev
 pip install python-igraph
```
installation appeared to be successful, however when I try to import I get - 
`ImportError: /.../site-packages/igraph/_igraph.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev`

I am using python 3.6 (anaconda) on Ubuntu 16.04

Thanks

**Comment by ntamas** [comment]
If you use Anaconda Python, don't bother with compiling it from source; it probably won't work and I cannot support Anaconda Python officially as I don't use it on a daily basis. Just install the precompiled package:

`conda install -c marufr python-igraph=0.7.1.post6`

**Comment by ntamas** [comment]
(Also, if anyone manages to figure out why the package fails with Anaconda Python out-of-the-box and can send me a patch that fixes the issue, let me know).

**Comment by janschulz** [comment]
conda-forge also has igraph-python, but only for linux and macosx
