### ISSUE TITLE
Create random graph without vertices of zero degree 

### ISSUE THREAD

**Issue by ChihHsuLin** [igraph/python-igraph#123]
Hi, 
I am using ig.GraphBase.Static_Power_Law to generate random graph. Is it possible to generate graph without vertices of zero degree? I understand I can delete those vertices afterwards. However, the node number would become different from the assigned value. Thank you.

**Comment by ntamas** [comment]
No, that's not possible - but you can try to generate a degree distribution on your own and pass it to `Graph.Degree_Sequence`, which will generate graph with the exact degree distribution that you have specified if it is possible. Just use another software package to generate your desired degree distribution; e.g., https://github.com/ntamas/plfit could be used to generate power-law distributions with its `plgen` tool.

**Comment by ChihHsuLin** [comment]
Thank you.
