### ISSUE TITLE
Change seed in Louvain and Infomap algorithms

### ISSUE THREAD

**Issue by nahuelalmeira** [igraph/python-igraph#124]
Louvain and Infomap community detection algorithms are implemented in iGraph package through methods  Graph.community_multilevel() and Graph.community_infomap(). Both algorithms are stochastic and depends on the seed you give to initialize them. In these implementations though, seeds  cannot be changed and one gets always the same result. Could it be possible to modify the implementatios so as to be able to perform several realizations with different seeds each?

**Comment by ntamas** [comment]
`Graph.community_infomap()` is indeed stochastic, and it uses the built-in RNG of Python, so all you need to do is call `random.seed()` with different values right before calling `community_infomap()`.

`Graph.community_multilevel()` *could* be stochastic, but our current implementation is deterministic. Whenever a node could be placed in multiple communities with exactly the same amount of modularity gain, the current implementation will pick the community with the lowest index. One way to make the algorithm stochastic without touching the code in the C layer is by permuting the vertices of the graph using `g.permute_vertices()` before calling the community detection algorithm, then permuting the membership vector with the inverse of the original permutation.
