### ISSUE TITLE
Import error for python-igraph 

### ISSUE THREAD

**Issue by mohkar123** [igraph/python-igraph#126]
I'm using the OS python. Initially I tried using pip and I was getting and error and so I uninstalled the python-igraph installed using pip and installed python-igraph by downloading code from this repository, typing:
**sudo /usr/bin/python setup.py install**
When i try to import igraph, this is what I get:
**Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/igraph/_init_.py", line 34, in <module>
  File "build/bdist.linux-x86_64/egg/igraph/_igraph.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/igraph/igraph.py", line 6, in __bootstrap_
ImportError: /usr/local/lib/libigraph.so.0: undefined symbol: ZNKSt7_cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEcm**

What do I do?

**Comment by ntamas** [comment]
Get rid of whatever previously installed copies of the C core of the igraph library you have in `/usr/local`, uninstall `python-igraph` as well, and then just try `pip install python-igraph` from scratch. The previous copies of igraph in `/usr/local` interfere with the compilation of `python-igraph`.

**Comment by mohkar123** [comment]
I removed the C core files from my /usr/local/lib as indicated in the code above. I even uninstalled python-igraph from the system and then pip install python-igraph. I got the following error:

**Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-?packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libigraph.so.0: cannot open shared object file: No such file or directory**

From this I understand that the libigraph.so file is missing, which removed as part of uninstalling process.  What should I do now?

**Comment by mohkar123** [comment]
After this I got this error, I uninstalled python-igraph and I ran **sudo /usr/bin/python setup.py install** . What does this do, because when I tried to import igraph after this I got

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: No module named _igraph
>>>

**Comment by ntamas** [comment]
> From this I understand that the libigraph.so file is missing, which removed as part of uninstalling process. What should I do now?

Something was not removed properly if you got this message. Basically, when you run `python setup.py install`, one of two things will happen>

* if the setup script finds a previously installed version of the C core on your system, it will attempt to link to that version. The detection is done by running `pkg-config --libs --cflags igraph`, so as long as this statement succeeds and prints a bunch of compiler flags, the Python setup script assumes that the C core is installed so it won't try to download and compile the C core on its own -- it will simply attempt to link to the existing C core. If this happens, importing `igraph` will make it look for a file named `libigraph.so.0` somewhere on your system where `pkg-config` claimed it will be. Most likely you have forgotten to remove the file named `igraph.pc` from one of the folders where `pkg-config` looks for its data files.

* if the setup script does not find a previously installed version of the C core, it will download the C core, compile it and link it into the Python module directly. In this case, you will never see it complain about `libigraph.so.0`.

**Comment by ntamas** [comment]
> After this I got this error, I uninstalled python-igraph and I ran sudo /usr/bin/python setup.py install . What does this do, because when I tried to import igraph after this I got

Make sure that when you try to import igraph, you are _not_ standing in the folder where you have extracted the downloaded tarball from PyPI. The reason is because running `python setup.py install` copies the final, compiled Python interface of igraph into the Python path (typically to `/usr/lib/python*/dist-packages/igraph`), _but_ if the folder where you run `import igraph` from contains _another_ subfolder named `igraph`, it will take precedence over `/usr/lib/python*/dist-packages/igraph` and you'll get the error message that you saw (because `_igraph.so` is in `/usr/lib/python*/dist-packages/igraph`).

**Comment by mohkar123** [comment]
You were right. I hadn't removed **igraph.pc**. SO I removed it, ensured everything else was also removed, then downloaded the code from here and ran **sudo /usr/bin/python setup.py install** . Once I did that, I understand, it first does the config, then the make. In between that, I got this error
**/usr/bin/ld: cannot find -lxml2
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:2357: recipe for target 'libigraph.la' failed
make[3]: *** [libigraph.la] Error 1
make[3]: Leaving directory '/home/mohith/Downloads/python-igraph-0.7.1.post6/tmp/igraph.QF6X8x/igraph-0.7.1/src'
Makefile:1377: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/mohith/Downloads/python-igraph-0.7.1.post6/tmp/igraph.QF6X8x/igraph-0.7.1/src'
Makefile:480: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mohith/Downloads/python-igraph-0.7.1.post6/tmp/igraph.QF6X8x/igraph-0.7.1'
Makefile:382: recipe for target 'all' failed
make: *** [all] Error 2
Could not download and compile the C core of igraph.**

**Comment by mohkar123** [comment]
I fixed the above error by doing this  **sudo apt-get install libxml2-dev libgmp-dev zlib1g-dev**. But now I have a more specific error
I**n file included from src/indexing.c:25:0:
src/convert.h:63:57: error: unknown type name ‘igraph_layout_grid_t’
 int igraphmodule_PyObject_to_layout_grid_t(PyObject *o, igraph_layout_grid_t *r
                                                         ^
src/convert.h:66:63: error: unknown type name ‘igraph_random_walk_stuck_t’
 int igraphmodule_PyObject_to_random_walk_stuck_t(PyObject *o, igraph_random_wal
                                                               ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**

**Comment by mohkar123** [comment]
I cleared everything and did pip install and it worked. Thanks for all your help :)
