### ISSUE TITLE
How to add vertices with attributes

### ISSUE THREAD

**Issue by lance6716** [igraph/python-igraph#128]
I found a repo using this library, and it fails because of these code
```python
mygraph = igraph.Graph(n=y.size, edges=edges_to_add, directed=True, vertex_attrs={'y': ysort})
...
currgraph = mygraph.subgraph(range(y.size))
...
currgraph.add_vertices(2)
```
I think the reason is vertex has a attribute named 'y' and Graph.add_vertices(n) can't handle this.

I wrote this to prove
```python
y = [1,4,9]
g = igraph.Graph(n=len(y), directed=True, vertex_attrs={'y': y})
g.add_vertices(1)
```

So how can I add vertices with attributes?

**Comment by ntamas** [comment]
The code sample that you have provided works just fine on my machine:

```python
>>> y = [1,4,9]
>>> g = igraph.Graph(n=len(y), directed=True, vertex_attrs={'y': y})
>>> g.vcount()
3
>>> g.add_vertices(1)
>>> g.vcount()
4
>>> g.vs["y"]
[1, 4, 9, None]
```

What is the error message that you see?

**Comment by lance6716** [comment]
```python
InternalErrorTraceback (most recent call last)
<ipython-input-113-5dc04aeb068e> in <module>()
      1 y = [1,4,9]
      2 g = igraph.Graph(n=len(y), directed=True, vertex_attrs={'y': y})
----> 3 g.add_vertices(1)

/home/jupyter/anaconda2/lib/python2.7/site-packages/igraph/__init__.pyc in add_vertices(self, n)
    301             self.vs[m:]["name"] = names
    302             return result
--> 303         return GraphBase.add_vertices(self, n)
    304 
    305     def adjacent(self, *args, **kwds):

InternalError: Error at src/attributes.c:425: vertex attribute hash key is not a string, Invalid value
```

I'm using python 2.7 with anaconda, igraph was installed by pip, version is 0.7.1

**Comment by lance6716** [comment]
Server is jupyter on CentOS Linux release 7.2.1511 (Core)

**Comment by ntamas** [comment]
This is weird; can you send me the output of `g.vertex_attributes()` before calling `add_vertices()`?

**Comment by lance6716** [comment]
```python
y = [1,4,9]
g = igraph.Graph(n=len(y), directed=True, vertex_attrs={'y': y})
print g.vertex_attributes()
print g.vs["y"]
print g.vcount()
g.add_vertices(1)
```
```python
[u'y']
[1, 4, 9]
3
```

and I have `from __future__ import unicode_literals`. I'll run again in a clear env.

**Comment by lance6716** [comment]
sorry seems that `from __future__ import unicode_literals` causes this problem. thanks.

**Comment by ntamas** [comment]
No worries, this is still a problem if this is the case. In `src/attributes.c`, I have a check that enforces attribute names to be strings, and I am using `PyString_Check()` in the C layer to ensure that. Clearly, this does not work if strings are unicode literals. I'll try to do something about it.
