### ISSUE TITLE
 TypeError: plotting not available

### ISSUE THREAD

**Issue by guduxingzou** [igraph/python-igraph#129]
win7  Python2.7：
Traceback (most recent call last):

  File "<ipython-input-51-df59bbbf0497>", line 1, in <module>
    plot(g, layout = layout)

  File "C:\ProgramData\Anaconda2\lib\site-packages\igraph\drawing\__init__.py", line 446, in plot
    result = Plot(target, bbox, background=kwds.get("background", "white"))

  File "C:\ProgramData\Anaconda2\lib\site-packages\igraph\drawing\__init__.py", line 117, in __init__
    self._surface_was_created = not isinstance(target, cairo.Surface)

  File "C:\ProgramData\Anaconda2\lib\site-packages\igraph\drawing\utils.py", line 396, in __getattr__
    raise TypeError("plotting not available")

TypeError: plotting not available

**Comment by ntamas** [comment]
You need [`pycairo`](https://pypi.python.org/pypi/pycairo) or [`cairocffi`](https://pypi.python.org/pypi/cairocffi) for plotting.

**Comment by Dragut** [comment]
I have installed pycairo and can import cairo but still have the same error message.

**Comment by ntamas** [comment]
Please provide more details; e.g., how did you install `pycairo`, what happens when you type `import cairo` in the same interpreter where igraph fails to import it etc. Without such details, it's hard to tell anything.

(For what it's worth, one typical mistake people make is to have _multiple_ Python installations on their machine, installing `cairo` in one of them and `igraph` in another).

**Comment by Dragut** [comment]
It's the same anaconda environment. Installed pycario successfully. Import cairo successfully. Just plot reports error.

**Comment by vtraag** [comment]
You installed using Anaconda presumably (`conda`), not using `pip`? If not, please try to install again using Anaconda (and make sure to remove the library previously installed by `pip`). Perhaps the `pip` version is linked to an external `C` cairo library while the version imported by `python-igraph` is from elsewhere somehow.

Even better, you can also test in a completely clean environment:
`conda create -n test -c conda-forge python=3.7 python-igraph pycairo jupyter`
If that also does not work, please report any errors. If that does work, something is misconfigured in your other environment.

**Comment by FatemeMirzaeii** [comment]
I've got this error in google colab. after installing and importing pycairo, problem still exists.

**Comment by vtraag** [comment]
@FatemeMirzaeii, could you explain how you installed this in Google Colab? If I run `!pip install python-igraph leidenalg cairocffi` in Google Colab, this works correctly, and I can show `igraph` plots afterwards.

**Comment by vtraag** [comment]
Note that for `pycairo` I get an error on Google Colab: `ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly` Using `cairocffi` works well as an alternative.

**Comment by FatemeMirzaeii** [comment]
> 
> 
> Note that for `pycairo` I get an error on Google Colab: `ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly` Using `cairocffi` works well as an alternative.

yes I've got this error for installing pycairo too, so I installed it using these 2 commands from its documentation:
!apt install libcairo2-dev pkg-config python3-dev
!pip install pycairo

and it worked, but unfortunately still won't draw a plot. ('plotting not available')

and about cairocffi:
I've installed it using your command: 
!pip install python-igraph leidenalg cairocffi

it would run without any errors but still no plot have shown.

My code runs in Anaconda,correctly.

**Comment by iosonofabio** [comment]
FYI the latest version comes with matplotlib plotting via pyplot. You can try installing python-igraph from the master branch or wait for a new release and then happily use that.

Btw the python-igraph docs on installing from master and on plotting via matplotlib have also been added, they should be online in a few days if they aren't already (@ntamas)

**Comment by ntamas** [comment]
Just pushed them today - see [here](https://igraph.org/python/doc/tutorial/visualisation.html#plotting-graphs-within-matplotlib-figures).

**Comment by FatemeMirzaeii** [comment]
@iosonofabio @ntamas thank you both, I will try these.

**Comment by Rahul30032** [comment]
@FatemeMirzaeii  I am not able to plot graphs even after using ` !pip install python-igraph leidenalg cairocffi` . 
`igraph.plot(g, out_fig_name, **visual_style)` this is where it shows the following error : TypeError: plotting not available.
I am running it on colab. Please help me out if things worked out for you. @ntamas @vtraag

**Comment by iosonofabio** [comment]
See my last comment, there's matplotlib support now so no need to mess with cairo unless that's your concept of fun

**Comment by Rahul30032** [comment]
> See my last comment, there's matplotlib support now so no need to mess with cairo unless that's your concept of fun

`!pip install --upgrade python-igraph`
`import matplotlib.pyplot as plt `
 `fig, ax = plt.subplots()`
 `igraph.plot(g, target=ax)`

After using these commands I still am not able to plot it, getting the following error:
TypeError: plotting not available

P.S.   my graph summary (directed, 24441 vertices, 3203472 edges)
IGRAPH DNW- 24441 3203472 -- attr: name (v), weight (v), weight (e)

I am not able to understand the issue as to why the matplotlib support doesn't work in colab for me.
Nevertheless, thanks for the timely response @iosonofabio

**Comment by vtraag** [comment]
@Rahul30032, the matplotlib interface is not yet available from the release on PyPI. You will need to build the package yourself from source from the GitHub master branch.

**Comment by iosonofabio** [comment]
as @vtraag says, which was also in my last comment. Here the new (aesthetically somewhat suboptimal, but overall correct) documentation on how to install from the master branch:

https://igraph.org/python/doc/tutorial/install.html#compiling-python-igraph-from-source

or if that sounds too complicated, please wait until the next release. If this is absolutely urgent and essential for your work, please be really really nice to @ntamas and a minor release might happen.

**Comment by Rahul30032** [comment]
thanks @iosonofabio @vtraag . I will try to follow the instructions to install from master branch, meanwhile eagerly waiting for the next release.

**Comment by JiazhengZhang** [comment]
In colab ,By doing this , you can successfully plotting the network.
!pip install python-igraph==0.8.3
!apt install libcairo2-dev pkg-config python3-dev
!pip install python-igraph leidenalg cairocffi

**Comment by gitxiaoning** [comment]
> In colab ,By doing this , you can successfully plotting the network.
> !pip install python-igraph==0.8.3
> !apt install libcairo2-dev pkg-config python3-dev
> !pip install python-igraph leidenalg cairocffi

Thank you! This works :)

**Comment by szhorvat** [comment]
You should use the latest version though, not 0.8.3.

**Comment by ntamas** [comment]
And the package on PyPI is now called igraph, not python-igraph; python-igraph is planned to be deprecated in September AFAIK.

T.
