### ISSUE TITLE
Inconsistent `get_shortest_path` output for weighted and unweighted edges

### ISSUE THREAD

**Issue by xuhdev** [igraph/python-igraph#130]
When `from` and `to` are the same vertex, the output of `get_shortest_path` are different for weighted and unweighted edges. For unweighted edges, the output is the vertex. For weighted edges, the output is empty. An example is shown below.

```python
import igraph

g = igraph.Graph.Full(2)
g.es[0]["weight"] = 1.0
print(g.get_shortest_paths(0, 0))
print(g.get_shortest_paths(0, 0, weights="weight"))
```

Output

```
[[0]]
[[]]
```

**Comment by ntamas** [comment]
Probably a bug in the C layer - I'll have to check.
