### ISSUE TITLE
ImportError: libxml2.so.2 in python3

### ISSUE THREAD

**Issue by amisios** [igraph/python-igraph#133]
Hello,

I work on a centOS machine (CentOS Linux release 7.3.1611 (Core))
I installed igraph for python3 as such: `pip3 install --user --no-cache-dir python-igraph`

when I `import igraph` in python3 or I just call the command `$ igraph` I get the following error:
```
from igraph._igraph import *
ImportError: libxml2.so.2: cannot open shared object file: No such file or directory
```

While I have this library in more than one location:
```
~/.guix-profiles/ipython/lib/libxml2.so.2 (points to libxml2.so.2.9.4 in /gnu/storage/....)
/lib64/libxml2.so.2   (points to /lib64/libxml2.so.2.9.1)
```

Finally on the same machine I have the following packages installed:
```
libxml2.x86_64                                2.9.1-6.el7_2.3 
libxml2-devel.x86_64                          2.9.1-6.el7_2.3   
libxml2-python.x86_64                         2.9.1-6.el7_2.3 
```

I would appreciate any help on this matter.

Thanks
A.

===============

The exact error:
```
Traceback (most recent call last):
  File "/home/amisios/.local/bin/igraph", line 3, in <module>
    from igraph.app.shell import main
  File "/home/amisios/.local/lib/python3.5/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libxml2.so.2: cannot open shared object file: No such file or directory
```

pip version 9.0.1
python version 3.5.3
apparently I am also using guix.

**Comment by ntamas** [comment]
Is it the built-in system Python or are you running some custom-built Python distribution?

You could also try running Python as `LD_DEBUG=all python3`; it should print which libraries are imported and also the locations where the loader looks for the libraries; typing `import igraph` inside the Python prompt would then reveal where the loader is looking for `libxml2.so.2`.

**Comment by amisios** [comment]
Thank you.
