### ISSUE TITLE
Did anybody succeed in running igraph on windows 10 with either python 3.5 or 3.6?

### ISSUE THREAD

**Issue by uli22** [igraph/python-igraph#134]
Even with Gohlkes "python_igraph-0.7.1.post6-cp35-none-win_amd64.whl" there is no way to get around
from igraph import *  
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from igraph import *
  File "C:\Program Files\Python35\lib\site-packages\igraph\__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Thanks in advance
Uli

**Comment by ntamas** [comment]
Some DLL that the compiled igraph module depends on is missing from somewhere. You might try using [Dependency Walker](http://www.dependencywalker.com/) on the compiled igraph module (most likely with an extension `.pyd` or `.dll`) to figure out what is missing where.

**Comment by uli22** [comment]
Thanks for comment.
Got it working on python 3.5 with Gohlkes binary - but not on 3.6

**Comment by TiemenSch** [comment]
I'm having trouble finding a .whl for Python 3.6 on Windows. Also, the instructions on building the library are a bit above my grade. Someone at conda forge would like to help out, but he was struggling with the instructions too.

**Comment by ntamas** [comment]
The problem is that we don't use Windows either - personally, I'm on a Mac and I only have access to Linux machines. If I were you, I would probably send an email to [Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/) first -- he seems to have managed to compile python-igraph for Python 3.4 and 3.5 on his [unofficial page](http://www.lfd.uci.edu/~gohlke/pythonlibs/), so maybe it would only be a matter of running the same build process with Python 3.6.

**Comment by TiemenSch** [comment]
I looked into Gohlke's page indeed and reached out to him just now, but I don't know if he appreciates these kind of requests. I imagine he gets a lot of them every day...

**Comment by mvackel** [comment]
igraph is working on Python 3.5.3 on Windows 10 64-bits. Just download the corresponding .whl file from the Christoph Gohlke mentioned above and use the command line pip to install. 
The Christoph Gohlke page does not explain the build process. I'm trying to figure out how to do this and will post here, if I can make it.

**Comment by TiemenSch** [comment]
I moved my Python installation to Windows Subsystem for Linux (WSL) and it works like a charm with Anaconda and Python 3.6. Suddenly almost all "Linux only" Python packages are within reach from a Windows environment. 
My workaround:
1. Install Ubuntu from Windows Store
1. Install [Miniconda](https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh) in Ubuntu terminal
1. Operate Python from there

Downside is that my Windows editors like VSCode cannot use the environments in there. So the best editing experience there is to work in Jupyter Notebooks running from WSL.

**Comment by ntamas** [comment]
[This commit](https://github.com/igraph/python-igraph/commit/abb4a67b24b9ee8efcfb1629cc6c58358cc306c2#diff-32d2a59da2ec039816077b378595d915) contains a fix for the issue mentioned above with the `repr_svg()` method.

**Comment by cgohlke** [comment]
> So I've been able to install very simply with Chris Gohlke's .whl files on Anaconda python 2.7.
> This process works fine for python 3.5 if your just doing analysis NOT Visualization.

I can't reproduce this. This just works for me with the [igraph](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph) and [pycairo](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo) wheels:
```
from igraph import *
g = Graph.Famous("petersen")
plot(g)
```

The wheels include the mentioned [fix](https://github.com/igraph/python-igraph/commit/abb4a67b24b9ee8efcfb1629cc6c58358cc306c2#diff-32d2a59da2ec039816077b378595d915), which your installation seems missing. Try re-downloading and re-installing the wheels.

**Comment by uli22** [comment]
Thank you for your reply.
I succeeded on win 10 with
          pip install python_igraph-0.7.1.post6-cp36-cp36m-win_amd64.whl
No install errors nomore.
Then 
          from igraph import *
          g = Graph.Famous("petersen")
         plot(g)
runs perfectly
Thank you
Uli

**Comment by resharp** [comment]
This also works for Python 3.7 now. Thanks!
I have installed pycairo separately. Don't know if this was necessary.
However, python-igraph is up in running in Windows PyCharm now.

pip install pycairo-1.18.1-cp37-cp37m-win32.whl
pip install python_igraph-0.7.1.post6-cp37-cp37m-win32.whl

**Comment by Proteusiq** [comment]
> Downside is that my Windows editors like VSCode cannot use the environments in there. So the best editing experience there is to work in Jupyter Notebooks running from WSL.

VSCode now supports WSL

**Comment by vtraag** [comment]
FYI: there was a new [release](https://pypi.org/project/python-igraph/) of `python-igraph` (version 0.8.0), which includes binaries for Windows. Hence, you should be able to install simply using `pip install python-igraph`.
