### ISSUE TITLE
layout_reingold_tilford() funtion error

### ISSUE THREAD

**Issue by Aliceandwayne** [igraph/python-igraph#137]
I catch an error below when i use  layout_reingold_tilford():
>>from igraph import *
>>g = Graph.Tree(10,2)
>>layout = g.layout_reingold_tilford(root=0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: 'int' object is not iterable

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-3-f4bb55c8699a> in <module>()
----> 1 layout = g.layout_reingold_tilford(root=0)

~/anaconda2/envs/py3/lib/python3.6/site-packages/igraph/__init__.py in result(*args, **kwds)
   3947     """
   3948     def result(*args, **kwds):
-> 3949         layout = func(*args, **kwds)
   3950         if not isinstance(layout, Layout):
   3951             layout = Layout(layout)

SystemError: <built-in method layout_reingold_tilford of Graph object at 0x7ff6293864f8> returned a result with an error set
------------------------------------------------------------------------------------------------
how can i solve this problem? @ntamas 
Thanks for your help!

**Comment by ntamas** [comment]
Try `root=[0]`.

**Comment by ntamas** [comment]
Note that `root=[0]` is a workaround only - the bug happens if you pass a single number to a parameter that expects a vector and is parsed with the `igraphmodule_PyObject_to_vector_t` function in the C layer. Commit 787169d fixes the underlying cause.

**Comment by Aliceandwayne** [comment]
thank you ! it works , and will you update the eg on python-graph tutorial? 
![image](https://user-images.githubusercontent.com/13307567/30428107-f5dcb700-9984-11e7-9dff-0ff086de4464.png)

**Comment by ntamas** [comment]
I have fixed the source of the tutorial; the fix will eventually propagate to the homepage when I find some time to update it.
