### ISSUE TITLE
pagerank() kills kernel using iPython 6.1.0 

### ISSUE THREAD

**Issue by zzuum** [igraph/python-igraph#138]
As title. When I try to get pagerank measures from a graph, it kills the kernel. This happens no matter the graph--I've tried on ~ 100 node, 1500 edge graph, and an empty graph. I'm using python 3.6.2 on a Dell Latitude 7280. I'm new to this so I'm not sure what other information I could give. 

Edit: I tried this in a normal python kernel via the terminal, and same issue. I'm running Ubuntu 16.04.

**Comment by ntamas** [comment]
> I'm new to this so I'm not sure what other information I could give.
Please send us a short, self-contained example that definitely crashes your machine. Also, tell us how you installed igraph (i.e. compiled from source, installed using a pre-compiled package etc).

**Comment by zzuum** [comment]
I installed igraph through anaconda, and igraph through anaconda as well. crashing it is as simple as

import igraph
G = igraph.Graph()
G.pagerank()

In both spyder, and in a terminal simply calling python.

This is not an issue on my thinkpad x260, though on that machine I use python 2.7.

**Comment by ntamas** [comment]
This is most likely an issue with Anaconda Python. Unfortunately I don't use Anaconda Python myself so I don't know what the problem could be. Did you simply run `pip install python-igraph` from Anaconda Python to install igraph, or did you use a pre-compiled package (such as [this one](https://anaconda.org/marufr/python-igraph))?

**Comment by zzuum** [comment]
Pre-compiled. Conda install python-igraph

**Comment by ntamas** [comment]
Uninstall it and then try `conda install -c marufr python-igraph` - others have reported that this version works. (I am only guessing here).

**Comment by ntamas** [comment]
python-igraph 0.8.0 will include wheels for major Python distributions; hopefully a new wheel will also be published in Anaconda Python soon after the release. I'm closing this for the time being. Stay tuned for the release of 0.8.0.
