### ISSUE TITLE
Unable to understand why python-igraph not working in my system

### ISSUE THREAD

**Issue by StutzA** [igraph/python-igraph#140]
I'm new to Python, and m using Windows 8.1.
I was looking for package that helps in solving problems related to network flow and graphs. (eg Minimal spanning tree). I found this package **igraph** which has a method i was looking for:
spanning_tree(self, weights=None, return_tree=True)

After installing igraph, faced issue while importing it (where it said jgraph should be used). While i tried to find a solution on internet, i found that **python-igraph** should be installed instead of **igraph**.  

BUT i am again facing issue while trying to download that package:
I used the command (both before and after uninstalling igraph) :     pip install python-igraph
This is what I am getting in both cases:

![python-igraph issue](https://user-images.githubusercontent.com/32410832/31044316-9d9d9574-a5ea-11e7-89d6-77329e65bbd2.png)

What to do?

**Comment by ntamas** [comment]
Just use a precompiled package from 
http://www.lfd.uci.edu/~gohlke/pythonlibs/

T.
