### ISSUE TITLE
How to suppress plot?

### ISSUE THREAD

**Issue by viraj96** [igraph/python-igraph#142]
Hi, I wanted to know how does one ensure that a plot does not show up but is rather saved. Currently, I am doing this
```
plt = ig.plot(bestGraphPartition, mark_groups = True)
plt.save("Results/Plots/" + args.value[0] + "/karate_club_graph_exhaustive_" + str(budget) + "_" + args.algo[0] + ".png")
```
But this renders the plot and shows it.

**Comment by ntamas** [comment]
Pass the name of the file to save the plot to as the second argument of `ig.plot()` - the plot will be saved automatically instead of showing it.
