### ISSUE TITLE
subisomorphic_vf2 performance

### ISSUE THREAD

**Issue by YonatanTahan** [igraph/python-igraph#147]
when using said method, there is a huge gap in performance between sub-graphs that does exist in the large graph, and sub-graphs that do not exist.
I have a fixed large multi - graph, with no loops (only multiple edges), and I'm searching in it some sub-graphs. 
When sub-isomorphism does exist, the method usually takes, at most,  few secondst to find it (even when searching "half" of it - removing randomly chosen half of the edges/vertices - within itself).
However, using it to when no sub-isomorphism exist, takes very long time, even for small sub-graph (several minutes for small graphs, and doesn't really stop for larger graphs).
I would think that in the worst case, the two scenarios should take the same time (when the sub-isomorphism is found in the "last" search).
Is there any reasonable explanation for this phenomena?

**Comment by ntamas** [comment]
I don't know; it all depends on the internal VF2 algorithm implementation of the C core of igraph, which is in turn ported from the original implementation of the VF2 author (so we are not too familiar with intricate details of the implementation).

I can try and profile the VF2 implementation for the no sub-isomorphism case to see where it spends most of its time - if you can give me an example where it is demonstrably slow. However, I would bet that proving that there is no sub-isomorphism requires an exhaustive search, while finding a single sub-isomorphism if there is one can probably turn up very quickly during the search process - unless you manage to produce a really evil counter-example where the first sub-isomorphism is found only very late in the search process.
