### ISSUE TITLE
Provide some sample graphs

### ISSUE THREAD

**Issue by ebraminio** [igraph/python-igraph#150]
Maybe this should be moved to igraph or copied into rigraph tracker also, now that nexus is gone, it would be _nice_ if igraph could provide the classic Zachary Karate Club and Dolphins as test graphs at least for clustering algorithms, have a look at this [social.py](https://github.com/networkx/networkx/blob/master/networkx/generators/social.py) on networkx, and use of [karate_club_graph](https://github.com/networkx/networkx/search?p=2&q=karate_club_graph&type=&utf8=✓) on rest of the project.

I have no issue on using of both libraries at the same time, have a look at the simple conversion I wrote between [the libraries](https://stackoverflow.com/a/45127940), but felt this is at least what can be done now that nexus is gone, this also can be written just for importing Zachary from networkx,

```
import networkx as nx
import igraph as ig

G = nx.karate_club_graph()
g = ig.Graph.TupleList(G.edges(), directed=False)
g.vs['club'] = list(nx.get_node_attributes(G, 'club').values())
```

**Comment by ntamas** [comment]
Maybe the easiest would be simply to revive Nexus. The source code for Nexus is still in the `igraph` repo (see https://github.com/igraph/igraph/tree/master/nexus ) - it's quite dated, though, but I believe it wouldn't be too hard to re-write it as a "proper" Python web app using Flask and then just host it on Heroku using a free or hobby dyno for the time being.

Unfortunately I don't have the spare time to do it myself in the near future, but I can probably gain access to the DNS records and point `nexus.igraph.org` to the right place if someone manages to revive it.

**Comment by ebraminio** [comment]
No problem, you guys did your part very well :)

I was able to just run nexus.py on my machine and it seemed to work and web.py is already upload able to heroku https://coderwall.com/p/g4tqoa/publishing-for-the-web-py-python-framework-to-heroku what steps are needed to be taken to revive nexus? Of course I should try to put this on heroku but I guessed you may have other concerns also maybe.

**Comment by ntamas** [comment]
Since yesterday I have realized that the Nexus-related part in the repo does not include the actual data files and the database that we used to have there. There are scripts to obtain the hosted data files from the original sources, so we need to run those first. But then there's another problem: we cannot store large static files on Heroku so we need an Amazon AWS bucket or something like that for static storage. (Or I need to rent a small server from somewhere).

Let me think about this a bit.

**Comment by ntamas** [comment]
Okay, Nexus is gone and unfortunately we don't have the resources to revive it right now. Also, I'm pretty sure that there are other free dataset repositories out there on the Internet so maybe we should just do a quick research and find out what we could use in place of Nexus? Maybe networkrepository.com or Google Dataset Search? (Just throwing some ideas around).

As for providing sample graph: `Graph.Famous()` already includes the Zachary karate club network (just call `Graph.Famous("zachary")`). We could add the dolphins network there as a quick fix, although I'm not sure how significant it is (guess it's mostly used as community detection benchmark graph).

**Comment by szhorvat** [comment]
Just some random thoughts:

 * Maintaining a network repository is an entire project—we definitely can't afford to split resources.
 * The same applies to built-in data. I'm not sure it's worth adding more, as there'll always be requests for another one.
 * One would often want networks with attributes (weights, etc.) which can't be easily added to `igraph_famous`
 * What would be useful is to make it as easy as possible to create integrations for any online network or graph repository. As a comparison, in Mathematica can simply do `Import["https://gephi.org/datasets/lesmiserables.gml.zip", {"ZIP", "lesmiserables.gml"}]` which downloads the data, extracts the file and imports it as a ready-to-use network in one step. 
 * The igraph C core uses `FILE *` pointers, which are not extensible or interoperable, and can't really be hooked up to the host language. Compare `iostream` in C++ which can have any backend. Thus I can't fully integrate igraph's graph readers/writers into Mathematica's import/export framework. I'm not sure how this design affects the Python interface—probably the same? In the (very) long term, it would be useful to make import/export more flexible. Admittedly, that's a lot of work.

**Comment by ntamas** [comment]
> Thus I can't fully integrate igraph's graph readers/writers into Mathematica's import/export framework. I'm not sure how this design affects the Python interface—probably the same?

Yes - same issues there. On the other hand, I would prefer to keep igraph mostly a C library, not C++, so `iostream` is not an option (unless we are willing to turn igraph into a C++ library).

Most of the graph readers in the C core are based either on a Flex/Bison parser, except for the edgelist reader (probably hand-crafted) and the GraphML reader (which uses libxml2). We would need to investigate whether it is possible to "stream' chunks of bytes into a Flex/Bison parser or a libxml2 parser; if that is the case, we could separate the reading of bytes from the parsing so the C layer could provide separate functions for parsing input graphs from arbitrary byte sources. Then the higher level interfaces could implement their own readers / writers on top of it.

Another solution, at least for the Python interface, is to support HTTP URLs by downloading them to a temporary file first, feeding the temporary file to igraph, and then removing the temporary graph. But that's the topic of a separate issue I think.

**Comment by iosonofabio** [comment]
I just wrote the documentation for graph generation and one can just do

```python
from igraph import Graph
g = Graph.Famous('Zachary')
```

Is that what we need to close this one or am I missing the point?

**Comment by ebraminio** [comment]
> Is that what we need to close this one or am I missing the point?

Long time I weren't around… IIRC, yes, and one for dolphins would be nice if possible, thanks :)

**Comment by szhorvat** [comment]
One more thought on the dolphins (and why *not* to add it to `igraph_famous`):

It comes with attributes, specifically the names of the animals. `igraph_famous` does not support attributes. Generally, anything with attributes is the domain of high-level interfaces, as each one stores attributes differently in order to allow using the host language's datatypes.

**Comment by szhorvat** [comment]
I think Nexus was a good solution to providing example graphs: (1) it can be made to work with any high-level interface (2) supporting attributes is not a problem. But Nexus was effectively a separate project which took a lot of work to maintain and keep running. That's exactly the reason why it's gone now.

The discussion comes back to whether the igraph project should try to maintain a fully features example network repository. I think trying to do that is a bad idea: we don't have the resources, and there are several other repositories out there. Better to make interoperability with those easy.

`igraph_famous` was simply not meant for this, and trying to expand it would lead to a low-quality, half-baked solution (e.g. missing dolphin names). I would close this issue and move the Nexus discussion to https://igraph.discourse.group/

**Comment by ebraminio** [comment]
Okay, so let's close this, thanks everybody :)
