### ISSUE TITLE
Shuffle in community_label_propagation (node number 0 is not shuffled?)

### ISSUE THREAD

**Issue by gggsanna** [igraph/python-igraph#153]
Something is strange in the way nodes are shuffled in igraph_community_label_propagation.
If I create a graph which is the disjoint of two full graphs with NN nodes each (eg 3 or 4), and run label propagation on it, the probability that the first full graph is split into multiple communities is much lower (2.5 to 5 times) than that of the second one being split.

Some things that might help:
- If I add some "padding nodes" before creating the two disjoint full graphs, the imbalance disappears. For example, with three disjoint graphs of NN nodes each, the second and the third have the same probability of being split, but the first one has a lower probability.
- If I try with two graphs of different sizes (eg 3 and 4) and then exchange their sizes (4 and 3), there is still the same imbalance problem.
- If I try with two disjoint graphs and NN = 3, the first one containing vertices 0,4,5 and the second one containing vertices 1,2,3, the imbalance is still there: the one containing vertex number zero is less likely to be split.

It really looks like something is strange with how shuffle deals with the first node, and that this makes the nodes it is linked to more likely to be recognised as a community. Maybe the first node is always updated first? My current fix is that in all runs I do I insert a first dummy node without links :/.

Here is the python code to reproduce this:

```
import random
import igraph as ig
random.seed(309291)

ip = 0 # initial position of the relevant part of the graph, try 0 and 1
s1 = 3 # size of the 1st disjoint full graph
s2 = 3 # size of the 2nd disjoint full graph
test_g = ig.Graph.Full(ip) # add a few nodes which we won't check anything about
test_g = test_g.disjoint_union(ig.Graph.Full(s1)) # 1st disjoint full graph
test_g = test_g.disjoint_union(ig.Graph.Full(s2)) # 2nd disjoint full graph

ctr_1 = 0 # count times the 1st graph is not recognised as a community
ctr_2 = 0 # count times the 2nd graph is not recognised as a community
N_runs = 30000 # 30k-1M are reasonable values to see some effect with ss = 3,4
for i in range(N_runs):
    cl = test_g.community_label_propagation()
    if len(set(cl.membership[ip:ip+s1])) > 1: # 1st graph is not a community
        ctr_1 += 1
    if len(set(cl.membership[ip+s1:ip+s1+s2])) > 1: # 2nd graph is not a community
        ctr_2 += 1
print(ctr_1, ctr_2, ctr_2/(ctr_1+1e-9))
```
You can also define the `test_g` graph like this:
```
test_g = ig.Graph(6)
test_g.add_edges([(0,4),(4,5),(0,5),(1,2),(1,3),(2,3)])
```
to check that it's the first node's fault.

I hope this helps and that you can reproduce the issue,
thanks :)

**Comment by ntamas** [comment]
This might either be an OS-specific issue, or something that has been fixed already but not released yet. I am currently trying to reproduce it on Mac OS X with the head revision of the repo, using `N_runs = 300000` and I got this:

```
(10388, 10357, 0.9970157874469583)
```

However, on a Linux machine running Ubuntu 16.04 and stock igraph (0.7.1.post6), I got:

```
(3407, 11859, 3.4807748752558028)
```

I'll continue investigating.

**Comment by ntamas** [comment]
Okay, it is an some old bug that is still there in the released version but that has been fixed since in [this commit](https://github.com/igraph/igraph/commit/70c755e3905860decb84b8c1d676de724811bcd6#diff-5fcbcd5dceaf58e82bd258c17c274403). A workaround is to pass `initial=range(test_g.vcount())` as a keyword argument to the function call. The reason is that without the patch above, _sometimes_ vertex 0 ends up in a nonexistent community with index -1; the Python interface then "canonicalizes" the membership vector by re-numbering this community to a non-negative number so that's why you don't see -1 as a community index.

I'll try to find some time to release a new version in the future if @gaborcsardi agrees to do so with the C core.
