### ISSUE TITLE
Failing to get igraph working in spyder

### ISSUE THREAD

**Issue by pskugit** [igraph/python-igraph#154]
Hi, after following every installation step and downgrading my python version to 3.5 in order to make igraph work, it still does not so within spyder. 

When trying:
```
import igraph
print(igraph.__version__)
```

it results in `AttributeError: module 'igraph' has no attribute '__version__'`

I assume that spyder tries to access a different package (as far as i can judge from the autofill-options that pop up when writing "igraph."). However, I have selected the same python3.5 interpreter from the spyder preferences menu as the one accessed by IDLE and PyCharm, where the above stated code works just fine. 

Since I like working with spyder it would be nice if someone might be able to explain such a behavior. 
Thank you in advance!

**Comment by ntamas** [comment]
Try to figure out where the `igraph` import is coming from:

```
>>> print(igraph.__file__)
```

Then examine `sys.path` in Spyder and try to figure out why the "real" igraph package comes later in the import order than whatever other package you are importing as `igraph`.
