### ISSUE TITLE
Cannot link C core with Python installation

### ISSUE THREAD

**Issue by neocsbee** [igraph/python-igraph#158]
Hi,

Here are the error messages I get when trying to do 'python setup.py install --user' and 'python setup.py install --home=~'

![image](https://user-images.githubusercontent.com/3037022/35361134-2e3f4e26-012e-11e8-84b3-9cc50e99dea6.png)

I have changed the LIBIGRAPH_FALLBACK_INCLUDE_DIRS and LIBIGRAPH_FALLBACK_LIBRARIES accordingly, since this is my home directory installation.

I did not see any any error when I compiled the C core. The include and lib directories are correctly created with the files.

How can I link the C core with python setup?

Thanks.

**Comment by ntamas** [comment]
I cannot tell off the top of my head (I can look into this more thoroughly tomorrow), but it looks like you are trying to compile igraph on Windows; in that case, is there a reason why you cannot simply use the [unofficial pre-compiled packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph)? Are you trying to compile a patched version of igraph or is your Python version not supported by the unofficial packages?

**Comment by neocsbee** [comment]
This is not Windows. I was able to resolve this issue by manually giving the absolute path of the file searched by pkg-config utility.
