### ISSUE TITLE
Igraph compilation fails with pip install due to false usage of static libraries

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/python-igraph#16]
_From @neuralyzer on July 9, 2014 18:19_

When I pip install pyton-igraph, not having the igraph c core already installed I get the following error message:

```
gcc -pthread -shared build/temp.linux-x86_64-2.7/src/arpackobject.o build/temp.linux-x86_64-2.7/src/attributes.o build/temp.linux-x86_64-2.7/src/bfsiter.o build/temp.linux-x86_64-2.7/src/common.o build/temp.linux-x86_64-2.7/src/convert.o build/temp.linux-x86_64-2.7/src/edgeobject.o build/temp.linux-x86_64-2.7/src/edgeseqobject.o build/temp.linux-x86_64-2.7/src/error.o build/temp.linux-x86_64-2.7/src/filehandle.o build/temp.linux-x86_64-2.7/src/graphobject.o build/temp.linux-x86_64-2.7/src/igraphmodule.o build/temp.linux-x86_64-2.7/src/indexing.o build/temp.linux-x86_64-2.7/src/py2compat.o build/temp.linux-x86_64-2.7/src/pyhelpers.o build/temp.linux-x86_64-2.7/src/random.o build/temp.linux-x86_64-2.7/src/vertexobject.o build/temp.linux-x86_64-2.7/src/vertexseqobject.o igraphcore/lib/libigraph.a /usr/lib64/libxml2.a /usr/lib64/libz.a /usr/lib64/libm.a -Ligraphcore/lib -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib -L../../build/src/.libs -L../../src/.libs -L/usr/local/lib -L/usr/lib -L/home/anaconda/lib -lstdc++ -lpython2.7 -o build/lib.linux-x86_64-2.7/igraph/_igraph.so

/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libxml2.a(entities.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC

/usr/lib64/libxml2.a: could not read symbols: Bad value

collect2: ld returned 1 exit status

error: command 'gcc' failed with exit status 1
```

Apparently libxml2.a is mixed up with libxml2.so. The following very dirty workaround made igraph compile for me. I modified the setup.py as follows:

I changed the line

```
variants = ["lib{0}.a", "{0}.a", "{0}.lib", "lib{0}.lib"]
```

to

```
variants = ["lib{0}.so", "{0}.so"]
```

pip setup.py install did then finish. However igraph did still not work, since libigraph.so.0 was not copied to its destination. So I manually copied

```
cp ./igraphcore/lib/libigraph.so.0 ~/anaconda/lib
```

to python's lib. As you can see, I'm using the anaconda Python distribution.

_Copied from original issue: igraph/igraph#640_

**Comment by gaborcsardi** [comment]
_From @ntamas on July 24, 2014 12:33_

Linking to libxml2.a would be just fine because the Python setup script tries to create a fully static igraph library when it is compiling igraph on its own. The problem is that the version of libxml2.a that ships with SuSE Linux is not compiled with the `-fPIC` option, so it cannot be linked into dynamic libraries (e.g., dynamically loaded Python modules). We need to find a more-or-less reliable way to detect whether a static library was compiled with `-fPIC` or not and fall back to the dynamic version if necessary.

**Comment by gaborcsardi** [comment]
_From @neuralyzer on August 26, 2014 17:14_

It might be already enough to try to use the static libraries first and fall back to the dynamic ones in the case of an error being generated.

**Comment by neuralyzer** [comment]
It would be nice to integrate that kind of check into the next python-igraph release.

**Comment by catubc** [comment]
So I used the recommended variants replacement and I still got the same crash. Am I doing something else wrong?

```
/usr/bin/ld: /usr/local/lib/libxml2.a(entities.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libxml2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by ntamas** [comment]
It seems like `libxml2.a` is coming from `/usr/local/lib` and not from `/usr/lib` where it usually is. Which OS is this? Where does this library come from? (Probably not from the OS itself because then it would be in `/usr/lib`).

**Comment by catubc** [comment]
Hi. This issues seems to have solved itself after uninstalling and reinstalling the library. I also manually copied the file at issue. Thanks.

**Comment by u-u-h** [comment]
The issue still appears on a fresh install in a clean venv on a Cray XC30/40 system, where (of course) libm.a is not compiled with -fPIC.
