### ISSUE TITLE
Python-igraph similar function to make-ego-graph

### ISSUE THREAD

**Issue by EmilyYanW** [igraph/python-igraph#160]
Hello! As I read through the documentation, I found the subgraph() function but not ego graph function and I wonder whether there is a similar one for python-igraph?

**Comment by ntamas** [comment]
You can use [`Graph.neighborhood()`](http://igraph.org/python/doc/igraph.GraphBase-class.html#neighborhood) combined with [`Graph.induced_subgraph()`](http://igraph.org/python/doc/igraph.GraphBase-class.html#induced_subgraph) to roll your own.
