### ISSUE TITLE
Won't compile with the default version of C core

### ISSUE THREAD

**Issue by xuhdev** [igraph/python-igraph#162]
When I run `python setup.py develop`, I got the following error:

    In file included from src/indexing.c:25:0:
        src/convert.h:64:57: error: unknown type name ‘igraph_layout_grid_t’
         int igraphmodule_PyObject_to_layout_grid_t(PyObject *o, igraph_layout_grid_t *result);
                                                         ^~~~~~~~~~~~~~~~~~~~
        src/convert.h:67:63: error: unknown type name ‘igraph_random_walk_stuck_t’
         int igraphmodule_PyObject_to_random_walk_stuck_t(PyObject *o, igraph_random_walk_stuck_t *result);

It seems like the default version of C core is pretty outdated: These data types don't exist in the default downloaded version, but exist in the latest igraph C core.

**Comment by ntamas** [comment]
Well, if you are compiling from the head revision of `python-igraph`, you should probably be linking to the head revision of the C core and not the latest released version (which was indeed released a long time ago). If you want to link to igraph 0.7.1, check out the repo at https://github.com/igraph/python-igraph/tree/0.7.1.post6 instead.

**Comment by gokceneraslan** [comment]
I also get the same error when I run:

`pip install -U git+https://github.com/igraph/python-igraph.git`

and I don't have any igraph-core installed in the system. Is this normal? Doesn't python-igraph bring bundled igraph-core source and statically link to it?

**Comment by gokceneraslan** [comment]
Ah ok, so I have to run `python setup.py install` with `--c-core-url https://github.com/igraph/igraph/archive/master.tar.gz` option. 

Then my question is, is there a way to pass `--c-core-url https://github.com/igraph/igraph/archive/master.tar.gz` to `pip` to be able to install python-igraph from master with a single pip command without cloning it?

**Comment by ntamas** [comment]
> Doesn't python-igraph bring bundled igraph-core source and statically link to it?
No; it tries to find the C core using `pkg-config` and if it fails, it will attempt to download a matching C core and use that. The problem is that finding a matching C core is not possible for the head revision; it works only for versions that have been officially released. So, you need to provide `--c-core-url` if you are compiling the development version and you do not want to install the C core separately before.

> is there a way to pass `--c-core-url https://github.com/igraph/igraph/archive/master.tar.gz`
Use `--install-option="..."`, e.g.:

`pip install -U git+https://github.com/igraph/python-igraph.git --install-option="--c-core-url https://github.com/igraph/igraph/archive/master.tar.gz"`

I think this will do the trick.

**Comment by PalaChen** [comment]
use 
pip install -U git+https://github.com/igraph/python-igraph.git --install-option="--c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz"

but i  get an error
Could not download and compile the C core of igraph.


/usr/local/lib/python2.7/dist-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting git+https://github.com/igraph/python-igraph.git
  Cloning https://github.com/igraph/python-igraph.git to /tmp/pip-0L0Hhw-build
Installing collected packages: python-igraph
  Running setup.py install for python-igraph ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-0L0Hhw-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-HVon94-record/install-record.txt --single-version-externally-managed --compile --c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/igraph
    copying igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/__init__.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph
    creating build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/isomorphism.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/bipartite.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/generators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/iterators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/decomposition.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/structural.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/basic.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/__init__.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/rng.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/vertexseq.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/spectral.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/flow.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/matching.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/edgeseq.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/foreign.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/cliques.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/conversion.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/colortests.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/separators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/walks.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/operators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/indexing.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/layouts.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/atlas.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/games.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/unicode_issues.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/homepage.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/attributes.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/utils.py -> build/lib.linux-x86_64-2.7/igraph/test
    creating build/lib.linux-x86_64-2.7/igraph/app
    copying igraph/app/__init__.py -> build/lib.linux-x86_64-2.7/igraph/app
    copying igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app
    creating build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/__init__.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    creating build/lib.linux-x86_64-2.7/igraph/remote
    copying igraph/remote/__init__.py -> build/lib.linux-x86_64-2.7/igraph/remote
    copying igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote
    copying igraph/remote/nexus.py -> build/lib.linux-x86_64-2.7/igraph/remote
    creating build/lib.linux-x86_64-2.7/igraph/vendor
    copying igraph/vendor/__init__.py -> build/lib.linux-x86_64-2.7/igraph/vendor
    copying igraph/vendor/texttable.py -> build/lib.linux-x86_64-2.7/igraph/vendor
    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    
    Using temporary directory: /tmp/pip-0L0Hhw-build/tmp/igraph.CWRVXe
    Downloading master.tar.gz... please wait.
    Extracting master.tar.gz...
    Bootstrapping igraph...
    Finding out version number/string... bootstrap.sh: 5: bootstrap.sh: tools/getversion.sh: not found
    libtoolize or glibtoolize not found or not in the path!
    Could not download and compile the C core of igraph.
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-0L0Hhw-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-HVon94-record/install-record.txt --single-version-externally-managed --compile --c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz" failed with error code 1 in /tmp/pip-0L0Hhw-build/

**Comment by ntamas** [comment]
The log output says it all at the very end:

```
libtoolize or glibtoolize not found or not in the path!
```

Install `libtoolize` or ` glibtoolize` and then try again. You will need these for compiling the C core.

**Comment by mateuszwilinski** [comment]
I have a similar error to the above one when trying:
pip install -U git+https://github.com/igraph/python-igraph.git --install-option="--c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz"

However in my case it doesn't seem to be about libtoolize:

> /home/.../.local/lib/python2.7/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
>   cmdoptions.check_install_build_global(options)
> The directory '/home/.../.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/.../.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting git+https://github.com/igraph/python-igraph.git
>   Cloning https://github.com/igraph/python-igraph.git to /tmp/pip-T_TbSp-build
> Installing collected packages: python-igraph
>   Found existing installation: python-igraph 0.7.1.post6
>     Uninstalling python-igraph-0.7.1.post6:
>       Successfully uninstalled python-igraph-0.7.1.post6
>   Running setup.py install for python-igraph ... error
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-T_TbSp-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ExBYQp-record/install-record.txt --single-version-externally-managed --compile --c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/igraph
>     copying igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/__init__.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph
>     copying igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph
>     creating build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/basic.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/spectral.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/isomorphism.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/indexing.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/games.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/colortests.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/unicode_issues.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/generators.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/cliques.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/__init__.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/flow.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/structural.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/layouts.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/decomposition.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/homepage.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/utils.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/edgeseq.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/separators.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/conversion.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/atlas.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/rng.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/matching.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/bipartite.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/foreign.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/vertexseq.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/operators.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/iterators.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/walks.py -> build/lib.linux-x86_64-2.7/igraph/test
>     copying igraph/test/attributes.py -> build/lib.linux-x86_64-2.7/igraph/test
>     creating build/lib.linux-x86_64-2.7/igraph/app
>     copying igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app
>     copying igraph/app/__init__.py -> build/lib.linux-x86_64-2.7/igraph/app
>     creating build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/__init__.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     copying igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing
>     creating build/lib.linux-x86_64-2.7/igraph/remote
>     copying igraph/remote/nexus.py -> build/lib.linux-x86_64-2.7/igraph/remote
>     copying igraph/remote/__init__.py -> build/lib.linux-x86_64-2.7/igraph/remote
>     copying igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote
>     creating build/lib.linux-x86_64-2.7/igraph/vendor
>     copying igraph/vendor/__init__.py -> build/lib.linux-x86_64-2.7/igraph/vendor
>     copying igraph/vendor/texttable.py -> build/lib.linux-x86_64-2.7/igraph/vendor
>     running build_ext
>     Cannot find the C core of igraph on this system using pkg-config.
>     We will now try to download and compile the C core from scratch.
>     Version number of the C core: 0.7.1.post6
>     We will also try: 0.7.1
>     
>     Using temporary directory: /tmp/pip-T_TbSp-build/tmp/igraph.7TlaPd
>     Downloading master.tar.gz... 100.00%
>     Extracting master.tar.gz...
>     Bootstrapping igraph...
>     Finding out version number/string... 0.8.0-pre+a9be781
>     + aclocal
>     perl: warning: Setting locale failed.
>     perl: warning: Please check that your locale settings:
>     	LANGUAGE = (unset),
>     	LC_ALL = (unset),
>     	LC_CTYPE = "UTF-8",
>     	LANG = "en_US.UTF-8"
>         are supported and installed on your system.
>     perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
>     perl: warning: Setting locale failed.
>     perl: warning: Please check that your locale settings:
>     	LANGUAGE = (unset),
>     	LC_ALL = (unset),
>     	LC_CTYPE = "UTF-8",
>     	LANG = "en_US.UTF-8"
>         are supported and installed on your system.
>     perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
>     + /usr/bin/libtoolize --force --copy
>     libtoolize: putting auxiliary files in '.'.
>     libtoolize: copying file './ltmain.sh'
>     libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
>     libtoolize: and rerunning libtoolize and aclocal.
>     libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
>     + autoheader
>     perl: warning: Setting locale failed.
>     perl: warning: Please check that your locale settings:
>     	LANGUAGE = (unset),
>     	LC_ALL = (unset),
>     	LC_CTYPE = "UTF-8",
>     	LANG = "en_US.UTF-8"
>         are supported and installed on your system.
>     perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
>     perl: warning: Setting locale failed.
>     perl: warning: Please check that your locale settings:
>     	LANGUAGE = (unset),
>     	LC_ALL = (unset),
>     	LC_CTYPE = "UTF-8",
>     	LANG = "en_US.UTF-8"
>         are supported and installed on your system.
>     perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
>     + automake --add-missing --copy
>     perl: warning: Setting locale failed.
>     perl: warning: Please check that your locale settings:
>     	LANGUAGE = (unset),
>     	LC_ALL = (unset),
>     	LC_CTYPE = "UTF-8",
>     	LANG = "en_US.UTF-8"
>         are supported and installed on your system.
>     perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
>     perl: warning: Setting locale failed.
>     perl: warning: Please check that your locale settings:
>     	LANGUAGE = (unset),
>     	LC_ALL = (unset),
>     	LC_CTYPE = "UTF-8",
>     	LANG = "en_US.UTF-8"
>         are supported and installed on your system.
>     perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
>     configure.ac:22: installing './compile'
>     configure.ac:43: installing './config.guess'
>     configure.ac:43: installing './config.sub'
>     configure.ac:3: installing './install-sh'
>     configure.ac:3: installing './missing'
>     src/Makefile.am: installing './depcomp'
>     configure.ac: installing './ylwrap'
>     + autoconf
>     + patch -N -p0 -r-
>     + true
>     Configuring igraph...
>     checking for a BSD-compatible install... /usr/bin/install -c
>     checking whether build environment is sane... yes
>     checking for a thread-safe mkdir -p... /bin/mkdir -p
>     checking for gawk... gawk
>     checking whether make sets $(MAKE)... yes
>     checking whether make supports nested variables... yes
>     checking for gcc... gcc
>     checking whether the C compiler works... yes
>     checking for C compiler default output file name... a.out
>     checking for suffix of executables...
>     checking whether we are cross compiling... no
>     checking for suffix of object files... o
>     checking whether we are using the GNU C compiler... yes
>     checking whether gcc accepts -g... yes
>     checking for gcc option to accept ISO C89... none needed
>     checking whether gcc understands -c and -o together... yes
>     checking for style of include used by make... GNU
>     checking dependency style of gcc... gcc3
>     checking for g++... g++
>     checking whether we are using the GNU C++ compiler... yes
>     checking whether g++ accepts -g... yes
>     checking dependency style of g++... gcc3
>     checking how to run the C++ preprocessor... g++ -E
>     checking for flex... no
>     checking for lex... no
>     checking for bison... no
>     checking for byacc... no
>     checking how to run the C preprocessor... gcc -E
>     checking for grep that handles long lines and -e... /bin/grep
>     checking for egrep... /bin/grep -E
>     checking for ANSI C header files... yes
>     checking for sys/types.h... yes
>     checking for sys/stat.h... yes
>     checking for stdlib.h... yes
>     checking for string.h... yes
>     checking for memory.h... yes
>     checking for strings.h... yes
>     checking for inttypes.h... yes
>     checking for stdint.h... yes
>     checking for unistd.h... yes
>     checking sys/times.h usability... yes
>     checking sys/times.h presence... yes
>     checking for sys/times.h... yes
>     checking build system type... x86_64-pc-linux-gnu
>     checking host system type... x86_64-pc-linux-gnu
>     checking how to print strings... printf
>     checking for a sed that does not truncate output... /bin/sed
>     checking for fgrep... /bin/grep -F
>     checking for ld used by gcc... /usr/bin/x86_64-linux-gnu-ld
>     checking if the linker (/usr/bin/x86_64-linux-gnu-ld) is GNU ld... yes
>     checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
>     checking the name lister (/usr/bin/nm -B) interface... BSD nm
>     checking whether ln -s works... yes
>     checking the maximum length of command line arguments... 1572864
>     checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
>     checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
>     checking for /usr/bin/x86_64-linux-gnu-ld option to reload object files... -r
>     checking for objdump... objdump
>     checking how to recognize dependent libraries... pass_all
>     checking for dlltool... dlltool
>     checking how to associate runtime and link libraries... printf %s\n
>     checking for ar... ar
>     checking for archiver @FILE support... @
>     checking for strip... strip
>     checking for ranlib... ranlib
>     checking command to parse /usr/bin/nm -B output from gcc object... ok
>     checking for sysroot... no
>     checking for a working dd... /bin/dd
>     checking how to truncate binary pipes... /bin/dd bs=4096 count=1
>     checking for mt... mt
>     checking if mt is a manifest tool... no
>     checking for dlfcn.h... yes
>     checking for objdir... .libs
>     checking if gcc supports -fno-rtti -fno-exceptions... no
>     checking for gcc option to produce PIC... -fPIC -DPIC
>     checking if gcc PIC flag -fPIC -DPIC works... yes
>     checking if gcc static flag -static works... yes
>     checking if gcc supports -c -o file.o... yes
>     checking if gcc supports -c -o file.o... (cached) yes
>     checking whether the gcc linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
>     checking whether -lc should be explicitly linked in... no
>     checking dynamic linker characteristics... GNU/Linux ld.so
>     checking how to hardcode library paths into programs... immediate
>     checking for shl_load... no
>     checking for shl_load in -ldld... no
>     checking for dlopen... no
>     checking for dlopen in -ldl... yes
>     checking whether a program can dlopen itself... yes
>     checking whether a statically linked program can dlopen itself... no
>     checking whether stripping libraries is possible... yes
>     checking if libtool supports shared libraries... yes
>     checking whether to build shared libraries... yes
>     checking whether to build static libraries... yes
>     checking how to run the C++ preprocessor... g++ -E
>     checking for ld used by g++... /usr/bin/x86_64-linux-gnu-ld -m elf_x86_64
>     checking if the linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) is GNU ld... yes
>     checking whether the g++ linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
>     checking for g++ option to produce PIC... -fPIC -DPIC
>     checking if g++ PIC flag -fPIC -DPIC works... yes
>     checking if g++ static flag -static works... yes
>     checking if g++ supports -c -o file.o... yes
>     checking if g++ supports -c -o file.o... (cached) yes
>     checking whether the g++ linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
>     checking dynamic linker characteristics... (cached) GNU/Linux ld.so
>     checking how to hardcode library paths into programs... immediate
>     checking for ANSI C header files... (cached) yes
>     checking stdarg.h usability... yes
>     checking stdarg.h presence... yes
>     checking for stdarg.h... yes
>     checking for stdlib.h... (cached) yes
>     checking for string.h... (cached) yes
>     checking time.h usability... yes
>     checking time.h presence... yes
>     checking for time.h... yes
>     checking for unistd.h... (cached) yes
>     checking for stdint.h... (cached) yes
>     checking sys/int_types.h usability... no
>     checking sys/int_types.h presence... no
>     checking for sys/int_types.h... no
>     checking for expm1... yes
>     checking for rint... yes
>     checking for rintf... yes
>     checking for finite... yes
>     checking for log2... yes
>     checking for snprintf... yes
>     checking for log1p... yes
>     checking for round... yes
>     checking for fabsl... yes
>     checking for fmin... yes
>     checking for strcasecmp... yes
>     checking for isfinite... no
>     checking for isnan... yes
>     checking for strdup... yes
>     checking for _strdup... no
>     checking for ftruncate... yes
>     checking for stpcpy... yes
>     checking whether stpcpy is declared... yes
>     checking whether compiler supports -ffloat-store... yes
>     checking whether compiler supports -fstore... no
>     checking whether compiler accepts -Wall... yes
>     checking for xml2-config... /usr/bin/xml2-config
>     ./configure: line 17487: sw_vers: command not found
>     checking for xmlSAXUserParseFile in -lxml2... yes
>     checking libxml/parser.h usability... yes
>     checking libxml/parser.h presence... yes
>     checking for libxml/parser.h... yes
>     checking that generated files are newer than configure... done
>     configure: creating ./config.status
>     config.status: creating tests/Makefile
>     config.status: creating tests/atlocal
>     config.status: creating Makefile
>     config.status: creating src/Makefile
>     config.status: creating igraph.pc
>     config.status: creating igraph_Info.plist
>     config.status: creating doc/Makefile
>     config.status: creating include/igraph_version.h
>     config.status: creating include/igraph_threading.h
>     config.status: creating config.h
>     config.status: executing tests/atconfig commands
>     config.status: executing depfiles commands
>     config.status: executing libtool commands
>     igraph successfully configured.
>       GraphML format support -- yes
>       GMP library support    -- no
>       GLPK library support   -- yes
>       Thread-local storage   -- no
>       Use internal ARPACK    -- yes
>       Use internal LAPACK    -- yes
>       Use internal BLAS      -- yes
>       Use internal F2C       -- yes
>       Use internal GLPK      -- yes
>       Debug build            -- no
>       Clang AddressSanitizer -- no
>       Profiling              -- no
>     Building igraph...
>     make  all-recursive
>     make[1]: Entering directory '/tmp/pip-T_TbSp-build/tmp/igraph.7TlaPd/igraph-master'
>     Making all in src
>     make[2]: Entering directory '/tmp/pip-T_TbSp-build/tmp/igraph.7TlaPd/igraph-master/src'
>     /bin/bash ../ylwrap foreign-ncol-parser.y y.tab.c foreign-ncol-parser.c y.tab.h `echo foreign-ncol-parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output foreign-ncol-parser.output -- yacc -d
>     ../ylwrap: line 176: yacc: command not found
>     Makefile:9004: recipe for target 'foreign-ncol-parser.c' failed
>     make[2]: *** [foreign-ncol-parser.c] Error 127
>     make[2]: Leaving directory '/tmp/pip-T_TbSp-build/tmp/igraph.7TlaPd/igraph-master/src'
>     Makefile:496: recipe for target 'all-recursive' failed
>     make[1]: *** [all-recursive] Error 1
>     make[1]: Leaving directory '/tmp/pip-T_TbSp-build/tmp/igraph.7TlaPd/igraph-master'
>     Makefile:399: recipe for target 'all' failed
>     make: *** [all] Error 2
>     Could not download and compile the C core of igraph.
>     
>     
>     ----------------------------------------
>   Rolling back uninstall of python-igraph
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-T_TbSp-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ExBYQp-record/install-record.txt --single-version-externally-managed --compile --c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz" failed with error code 1 in /tmp/pip-T_TbSp-build/

**Comment by ntamas** [comment]
This is the root cause of the error:

```
yacc: command not found
```

You need to install `yacc` (or `bison`).

**Comment by mateuszwilinski** [comment]
Thanks! It worked perfectly now. I only had to install the mentioned 'bison' and 'flex'.
