### ISSUE TITLE
get_automorphisms_vf2 sometimes produces permutations which are not automorphisms

### ISSUE THREAD

**Issue by geraschenko** [igraph/python-igraph#166]
For some graphs, get_automorphisms_vf2 produces permutations which are not valid automorphisms. The simplest example I could find is a square in which two opposite edges are doubled. The automorphism group of this graph has size 4, but get_automorphisms_vf2 produces 8 permutations.
```
0===1
|   |
3===2
```

Note: I'm not able to build/install with `sudo python setup.py install` at master. This bug was produced using the version of python-igraph I was able to install with apt.

### Steps to reproduce
```
In [1]: import igraph

In [2]: igraph.__version__
Out[2]: '0.7.1'

In [3]: igraph.Graph([(0,1), (0,1), (1,2), (2,3), (2,3), (3,0)]).get_automorphisms_vf2()
Out[3]: 
[[0, 1, 2, 3],
 [0, 3, 2, 1],  # <-- invalid
 [1, 0, 3, 2],
 [1, 2, 3, 0],  # <-- invalid
 [2, 1, 0, 3],  # <-- invalid
 [2, 3, 0, 1],
 [3, 0, 1, 2],  # <-- invalid
 [3, 2, 1, 0]]
```

The invalid permutations swap single edges with double edges. My initial guess was that multiple edges are not handled properly, but the problem is more nuanced than that. If only one of the edges of the square is doubled, then the automorphisms are computed correctly:
```
In [4]: igraph.Graph([(0,1), (0,1), (1,2), (2,3), (3,0)]).get_automorphisms_vf2()
Out[4]: [[0, 1, 2, 3], [1, 0, 3, 2]]
```

### Workaround
You can throw away multiple edges and color the edges by their multiplicity:
```
In [5]: igraph.Graph([(0,1), (1,2), (2,3), (3,0)]).get_automorphisms_vf2(edge_color=[2,1,2,1])
Out[5]: [[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
```

**Comment by ntamas** [comment]
I strongly suspect that the VF2 algorithm does not handle multiple edges and the fact that it works for your second example is just a coincidence. (BLISS, the other isomorphism algorithm in igraph, does not handle multiple edges either, so I think this is a common limitation for both).

The C core should probably add a check that tests the simplicity of the graph and throw an error if the graph is not simple.

**Comment by szhorvat** [comment]
I ran into this in the past, and I can confirm that the VF2 algorithm, as implemented in igraph, doesn't support multi-edges.

A workaround is to use edge colouring to encode edge multiplicity. This is what I used in the Mathematica interface to provide a multigraph isomorphism function.

**Comment by szhorvat** [comment]
Just noting that the C core now has `igraph_simplify_and_colorize` for encoding edge multiplicities as edge colours and self-loop multiplicities as vertex colours.
