### ISSUE TITLE
Cannot import igraph

### ISSUE THREAD

**Issue by Xiaojieqiu** [igraph/python-igraph#169]
I couldn't find any information online about the following error I confronted when I was trying to import python. Any ideas on this? It seems like igraph cannot load libicui18n.58.dylib? 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-8e950eb5d8d8> in <module>()
----> 1 import igraph

/Users/xqiu/anaconda/lib/python3.5/site-packages/igraph/__init__.py in <module>()
     32 # pylint: disable-msg=W0401
     33 # W0401: wildcard import
---> 34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
     36 from igraph.clustering import *

ImportError: dlopen(/Users/xqiu/anaconda/lib/python3.5/site-packages/igraph/_igraph.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/xqiu/anaconda/lib/libigraph.0.dylib
  Reason: image not found
```

**Comment by ntamas** [comment]
Anaconda Python is not officially supported with igraph; googling for `libicui18n.58.dylib anaconda` reveals many similar issues in other Python packages that are implemented in C and that depend on the `libxml2` library. I think the dependency chain goes like this:

* igraph requires `libxml2` (actually, it's an optional dependency for GraphML parsing, but if igraph was compiled with GraphML support, then it's mandatory). `libxml2` ships with Anaconda, so its a-ok.
* `libxml2` requires `libicui18n` (or maybe it's an optional dependency, I'm not sure -- to be honest, this is the first time I see the name of this library in relation to `libxml2`)
* `libicui18n` does not ship with Anaconda

I think it's best to ask for help in the Anaconda Python forums. For instance, [this issue](https://github.com/conda-forge/libxslt-feedstock/issues/8) seems similar. I'll be happy to join the discussion with the Anaconda Python developers if they need more information. Until then, I'm closing this issue as it is likely outside the scope of `python-igraph`.

**Comment by flying-sheep** [comment]
Can be circumvented by doing `conda install icu=58`, but really should be fixed on the anaconda side.

**Comment by vtraag** [comment]
@flying-sheep is this currently still a problem in Anaconda? We now provide a supported build through the`conda-forge` channel. If this is still an issue, please do let us know.

**Comment by flying-sheep** [comment]
A friend of mine recently encountered it, but I don’t know what in his environment led to it, just that this made it work. I assume it works for most people, and others either find it or will be able to help debugging a possible issue.

**Comment by vtraag** [comment]
Ok, thanks for the update. If there is any additional information, we might be able to fix it in the `conda-forge` feedstock.
