### ISSUE TITLE
Layout algorithm (Davidson-Harel layout, layout-nicely)

### ISSUE THREAD

**Issue by dashng** [igraph/python-igraph#170]
Hi, Guys

I installed the version 0.7.1, this version doesn't support the layout algorithm (Davidson-Harel layout, layout-nicely).

But I found the source on github  provides more layouts including these two layout either.

https://github.com/igraph/python-igraph/blob/master/igraph/__init__.py

```
- C{dh}, C{davidson_harel}: Davidson-Harel layout (see
            L{Graph.layout_davidson_harel})

```

Is there anyone can give me some suggestions, which version i should try to support these two layouts?

Appreciate if anyone can help me on this. Thanks again.

**Comment by ntamas** [comment]
You need to check out the source code from GitHub (as well as the source code of the C core of igraph) and compile it yourself. The latest released version does not contain the Davidson-Harel layout.

`layout_nicely()` is an R-specific addition; it is not a part of the C core or the Python interface. In the Python interface, `layout_auto()` provides something similar (but not exactly the same algorithm).

**Comment by dashng** [comment]
Is there any detailed docs about compile install from source code?

**Comment by ntamas** [comment]
`pip install -U git+https://github.com/igraph/python-igraph.git --install-option="--c-core-url=https://github.com/igraph/igraph/archive/master.tar.gz"` should do the trick if you have all the required development tools on your machine. (E.g., a decent C compiler, glibtoolize, libxml2-dev and stuff). If you run into problems, provide some details (error message, compilation logs etc) and then I can help.

**Comment by dashng** [comment]
@ntamas Thanks a lot. Let me try then response to you.
