### ISSUE TITLE
Problem of plotting with igraph on jupyter notebook

### ISSUE THREAD

**Issue by anay94** [igraph/python-igraph#176]
Hi everyone,

I'm new in Github so sorry if I do mistake and forget to precise some details :
I did almost every update and download all modules for plotting (pycairo,cairo,cairocffi) but I still have this message error:

TypeError                                 Traceback (most recent call last)
<ipython-input-63-43c99bed2a74> in <module>()
      1 #graphe d'après matrice d'adjacence pondéré
      2 g = Graph.Weighted_Adjacency (S.tolist(), mode = ADJ_UNDIRECTED, loops = False)
----> 3 plot(g)

/home/netbook/anaconda3/lib/python2.7/site-packages/python_igraph-0.7.1.post6-py2.7-linux-x86_64.egg/igraph/drawing/__init__.py in plot(obj, target, bbox, *args, **kwds)
    444         bbox = BoundingBox(bbox)
    445 
--> 446     result = Plot(target, bbox, background=kwds.get("background", "white"))
    447 
    448     if "margin" in kwds:

/home/netbook/anaconda3/lib/python2.7/site-packages/python_igraph-0.7.1.post6-py2.7-linux-x86_64.egg/igraph/drawing/__init__.py in __init__(self, target, bbox, palette, background)
    115         """
    116         self._filename = None
--> 117         self._surface_was_created = not isinstance(target, cairo.Surface)
    118         self._need_tmpfile = False
    119 

/home/netbook/anaconda3/lib/python2.7/site-packages/python_igraph-0.7.1.post6-py2.7-linux-x86_64.egg/igraph/drawing/utils.py in __getattr__(self, _)
    394 
    395     def __getattr__(self, _):
--> 396         raise TypeError("plotting not available")
    397     def __call__(self, _):
    398         raise TypeError("plotting not available")

TypeError: plotting not available

I'm running on ubuntu 16.04.

Thk for your help,

**Comment by ntamas** [comment]
Chances are that you have multiple instances of Python installed on your system and you installed Cairo and the other stuff for the "wrong" Python.

To test whether the installation is correct, just type `import cairo` from the Python console. If it succeeds, you are okay. If it shows an error message, you haven't installed Cairo properly or you installed it for a different Python.
