### ISSUE TITLE
Installer for windows is missing.

### ISSUE THREAD

**Issue by EugeneLoy** [igraph/python-igraph#178]
The official [docs](http://igraph.org/python/):

> The preferred way to install the Python interface on Windows is to download one of the MSI installers from the Python Package Index.

... however, the link provided leads to the non-existing page.

**Comment by EugeneLoy** [comment]
On a first glance, it appears that it is just simply broken link in documentation. Ignoring that, I still cannot find official installers for Windows on [actual PyPI package page](https://pypi.org/project/python-igraph/#files).

**Comment by ntamas** [comment]
There are no official installers any more as it has become too complicated for me to maintain them without actually using Windows on a daily basis. [Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph) provides Python wheels for Windows. I will update the igraph/igraph.org repo soon.

**Comment by ntamas** [comment]
Updated in https://github.com/igraph/igraph.org/commit/10f60fe6897dc470890e293ab440cabe1702d272
