### ISSUE TITLE
BFSIter.next() 

### ISSUE THREAD

**Issue by Aliceandwayne** [igraph/python-igraph#179]
Hi, dear  ntamas , why BFSIter.next() can't work in the version '0.7.1', may bfs() be a replacement?

**Comment by ntamas** [comment]
It works for me:

```python
>>> g = Graph.GRG(100, 0.2)
>>> it = g.bfsiter(0)
>>> it.next()
igraph.Vertex(<igraph.Graph object at 0x10d7a4430>,0,{'y': 0.01780424506473033, 'x': 0.004674094394482076})
```

Please reopen and provide more details if needed.

**Comment by Aliceandwayne** [comment]
![image](https://user-images.githubusercontent.com/13307567/41694276-1abcf01a-753c-11e8-937b-83c195c8bf47.png)
it didn't work for me, do you know how to resolve this problem?

**Comment by ntamas** [comment]
So you are using Python 3.x. In Python 3, the `next()` method of iterators was renamed to `__next__()`, and it should not be used directly. You need to use the `next()` function instead like this:

```
next(it)
```
