### ISSUE TITLE
edges for get_all_shortest_paths

### ISSUE THREAD

**Issue by DragosChirila** [igraph/python-igraph#183]
Hi,

I am trying to find all shortest paths between 2 nodes in a graph. I want to be able to tell the edges for all of them.

To illustrate the problem, I am going to use a very basic graph with only 2 nodes:

```
from igraph import *

names = ['A', 'B']
edges = [(0, 1), (0, 1), (0, 1)]
weights = [20, 10, 10]
extras = ['link1', 'link2', 'link3']

g = Graph(
    vertex_attrs={
        'name': names
    },
    edges=edges,
    edge_attrs={
        'weight': weights,
        'extra': extras
    }
)

# shortest path
shortest_paths = g.get_shortest_paths(
    v='A',
    to='B',
    weights='weight',
    mode=ALL,
    output='epath'
)
print('shortest_path = {}'.format(shortest_paths[0]))
for edge in shortest_paths[0]:
    print(
        '\tedge {}: weight = {}, extra = {}'.format(
            edge, g.es[edge]['weight'], g.es[edge]['extra']
        )
    )

# all shortest path
all_paths = g.get_all_shortest_paths(
    v='A',
    to='B',
    weights='weight',
    mode=ALL
)
for idx, path in enumerate(all_paths, start=1):
    print('path {} = {}'.format(idx, path))
    for n in path:
        print('\tnode = {}'.format(g.vs[n]['name']))

```

The output is:
```
shortest_path = [2]
        edge 2: weight = 10, extra = link3
path 1 = [0, 1]
        node = A
        node = B
path 2 = [0, 1]
        node = A
        node = B
```

**Question**:
How can I get the correct edge for each path (e.g. link2 for path 1 and link3 for path 2), since **get_all_shortest_paths** method doesn't have the **output** parameter and returns only  vertices?

Thank you!

Kind regards,
Dragos

**Comment by ntamas** [comment]
Store the index of the edge with the smallest weight for each pair of vertices in advance in a dict, and then use that:

```python
from itertools import groupby
from operator import itemgetter

def canonicalize_vertex_pair(pair):
    u, v = pair
    return (u, v) if u <= v else (v, u)

edges_and_weights = sorted(zip(
    (canonicalize_vertex_pair(pair) for pair in g.get_edgelist()),
    g.es["weight"]
))
smallest_weight_by_vertex_pair = dict(
    (edge, min(weight for _, weight in group))
    for edge, group in groupby(edges_and_weights, key=itemgetter(0))
)
```

You might have to look up both `(u, v)` and `(v, u)` when looking for the smallest weight between vertices u and v

**Comment by DragosChirila** [comment]
@ntamas Thank you very much for your answer, but your solution doesn't quite solve my problem. The output of your script is

```
[((0, 1), 10), ((0, 1), 10), ((0, 1), 20)]
{(0, 1): 10}
```

As I stated in the original post, I want to get **all shortest paths** with the same weight, not just one. Also, your solution forces me to pickle another structure, besides the original graph; structure that must be loaded every time.

Furthermore, lets say I want to filter the edges with the same weight by some extra field (e.g. age, type of relation).

Is it possible to achieve this directly with **get_all_shortest_paths** or a similar method that returns edges?

**Comment by ntamas** [comment]
Okay, sorry, I have misunderstood your original question then. In that case, this is not possible without modifying the C core of igraph; the Python interface can only let you do what the C core allows you to do.

You can try filing a feature request for igraph/igraph (which is the repo for the C core); the corresponding function in the C core is called [`igraph_get_all_shortest_paths_dijkstra`](http://igraph.org/c/doc/igraph-Structural.html#igraph_get_all_shortest_paths_dijkstra). However, neither me nor Gábor has much time to dedicate to the development of igraph so I'm afraid it is unlikely to get implemented in the near future unless someone implements it on their own and sends a pull request.

**Comment by DragosChirila** [comment]
I have found an workaround for my problem: instead of adding multiple edges between 2 nodes, I am creating multiple paths by using additional _control_ nodes, like below:
```
from igraph import *

names = ['A', 'B', 'AB1', 'AB2', 'AB3']
# A - 0
# B - 1
# AB1 - 2
# AB2 - 3
# AB3 - 4
extras = ['', '', 'link1', 'link2', 'link3']
edges = [
    # A - AB1 - B
    (0, 2), (2, 1),
    # A - AB2 - B
    (0, 3), (3, 1),
    # A - AB3 - B
    (0, 4), (4, 1)
]
weights = [
    10, 10,
    5, 5,
    5, 5
]

g = Graph(
    vertex_attrs={
        'name': names,
        'extra': extras
    },
    edges=edges,
    edge_attrs={
        'weight': weights,
    }
)

# shortest path
shortest_paths = g.get_shortest_paths(
    v='A',
    to='B',
    weights='weight',
    mode=ALL,
    output='epath'
)
print('shortest_path = {}'.format(shortest_paths[0]))
for edge in shortest_paths[0]:
    print(
        '\tedge {}: weight = {}'.format(
            edge, g.es[edge]['weight']
        )
    )

# all shortest path
all_paths = g.get_all_shortest_paths(
    v='A',
    to='B',
    weights='weight',
    mode=ALL
)
for idx, path in enumerate(all_paths, start=1):
    print('path {} = {}'.format(idx, path))
    for n in path:
        print(
            '\tnode = {}{}'.format(
                g.vs[n]['name'],
                ' - {}'.format(g.vs[n]['extra']) if g.vs[n]['extra'] else ''
            )
        )
```
and the output:
```
shortest_path = [4, 5]
	edge 4: weight = 5
	edge 5: weight = 5
path 1 = [0, 4, 1]
	node = A
	node = AB3 - link3
	node = B
path 2 = [0, 3, 1]
	node = A
	node = AB2 - link2
	node = B
```
