### ISSUE TITLE
added support for weighted average_path_length

### ISSUE THREAD

**Issue by FdeFabricio** [igraph/python-igraph#184]
The same way we can provide weights for the diameter, it would be a good idea to have a weighted average_path_length

**Comment by ntamas** [comment]
The underlying C library does not provide a weighted average path length function, only an unweighted one. (The diameter function exists in both variants: `igraph_diameter()` and `igraph_diameter_dijkstra()`). The only way to get around it at the moment would be to calculate the full path length matrix and then do the averaging in the Python layer.

**Comment by szhorvat** [comment]
@ntamas This is now implemented in the C core, but it's some exposed in Python yet for some reason.

Also, the current docs are now wrong when they say,

> Otherwise for all unconnected vertex pairs,
>  a path length equal to the number of vertices is used.

Adding to 0.9.9 milestone, if that's okay.

**Comment by ntamas** [comment]
Implemented in 562c05f
