### ISSUE TITLE
The nodes of tree are overlap when plot a tree. Maybe a bug when plot compex trees.

### ISSUE THREAD

**Issue by yizhichun** [igraph/python-igraph#186]
- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

![igraph_bug2](https://user-images.githubusercontent.com/13977114/43893008-27097cea-9c00-11e8-8970-5b51d3add9dd.png)

The nodes of tree are overlap when plot a complex tree, as shown in attached figure.
May be has a bug.
My tree structure as following:
```
edges = 
[(0, 1), (1, 2), (2, 3), (3, 4), (3, 5), (2, 6), (6, 7), (6, 8), (8, 9), (9, 10), (8, 11), (11, 12), (8, 13), (6, 14), (14, 15), (14, 16), (14, 17), (14, 18), (1, 19), (19, 20), (20, 21), (20, 22), (22, 23), (22, 24), (22, 25), (20, 26), (26, 27), (27, 28), (27, 29), (27, 30), (26, 31), (26, 32), (32, 33), (32, 34), (26, 35), (35, 36), (35, 37), (1, 38), (38, 39), (38, 40), (38, 41), (41, 42), (41, 43), (1, 44), (44, 45), (45, 46), (45, 47), (47, 48), (48, 49), (47, 50), (50, 51), (47, 52), (52, 53), (44, 54), (54, 55), (54, 56), (56, 57), (57, 58), (58, 59), (58, 60), (57, 61), (56, 62), (56, 63), (63, 64), (44, 65), (65, 66), (66, 67), (66, 68), (68, 69), (65, 70), (65, 71), (71, 72), (72, 73), (65, 74), (65, 75), (75, 76), (75, 77)]
```
The plot codes as following:
```
from igraph import *
tree = Graph(edges = edges)
plot(tree,layout = tree.layout_reingold_tilford(root=[0]))
```

How to fix this, thank you!

**Comment by ntamas** [comment]
Yes, this is a bug in the underlying implementation of the Reingold-Tilford algorithm in the C core of igraph. I don't have too much spare time to deal with this, so if you would like to help, can you please try to construct a minimal example that still exhibits the problem, e.g., by removing leaf nodes one by one from the tree until the issue does not appear any more? This would be a great help to me so I could start exploring with the smallest example that is possible to be derived from the current one.

**Comment by yizhichun** [comment]
I am glad to help. This will be much helpful for plot-ing complex trees.

After testing a lot, I have found a typical example that exhibits the problem. As following:
```
from igraph import *
edges = [(0, 1),
 (1, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (0, 7),
 (7, 8),
 (7, 9),
 (7, 10),
 (10, 11),
 (10, 12),
 (10, 13),
 (10, 14)]
tree = Graph(edges=edges)
tree.vs['label'] = [v.index for v in tree.vs]
plot(tree,layout=tree.layout('rt',root=[0]),bbox=(300,300))
```
<img width="419" alt="screen shot 2018-08-21 at 3 05 21 pm" src="https://user-images.githubusercontent.com/13977114/44385977-ac83fd80-a553-11e8-8cff-2a51f064e7c6.png">

The keys of this example are like this: the nodes in Level 4 will be out of the drawing limitation, when there are two nodes, 8 and 9, on the left of 10, in the Level 3.

If the four nodes in Level 4 are children of node 9, which means just one node 8 on the left of 9, the trees drawing well.
<img width="435" alt="screen shot 2018-08-21 at 3 19 53 pm" src="https://user-images.githubusercontent.com/13977114/44386659-b9095580-a555-11e8-8df8-769dcc4a9e33.png">

If there are two node on the right of left root in Level 3, the trees are also drawing well.
<img width="433" alt="screen shot 2018-08-21 at 3 22 10 pm" src="https://user-images.githubusercontent.com/13977114/44386753-fff74b00-a555-11e8-8212-63844e5f6de3.png">

If the leaves are in Level 3, the trees are also drawing well.
<img width="418" alt="screen shot 2018-08-21 at 3 25 26 pm" src="https://user-images.githubusercontent.com/13977114/44386893-7300c180-a556-11e8-8a06-c0c2a2c9cfd8.png">

If the leaves are in Level 4 or higher, this bug will be appear.
<img width="415" alt="screen shot 2018-08-21 at 3 19 19 pm" src="https://user-images.githubusercontent.com/13977114/44386969-aba09b00-a556-11e8-84bc-b36222c8f0f0.png">

I hope this would be helpful. I'm pleasure to do whatever else I can do to fix it.
Thanks.

**Comment by doRemy** [comment]
Thank you for your help understanding this issue. 

Without modifying the edges list, how would you go about finding a solution to this problem? 

Is there a layout option to prevent these kind of overlapping nodes?

**Comment by szhorvat** [comment]
Likely the same as https://github.com/igraph/igraph/issues/879

**Comment by ntamas** [comment]
Yes, it's the same issue. Let's continue the discussion there as it has to be fixed in the C layer.
