### ISSUE TITLE
I cannot find any functions in python-igraph that deals with creating the ego graph

### ISSUE THREAD

**Issue by Cindy1122334455** [igraph/python-igraph#188]
I found ego_graph in NetworkX and make_ego_graph in igraph R which are all applied to create the ego graph but I cannot find any functions in python-igraph to deal with the ego graph. What should I do to create ego graph in python-igraph.

**Comment by ntamas** [comment]
_Note that this is not a support forum -- please send your igraph-related support questions to igraph-help@nongnu.org_

Use `graph.neighborhood()` with the appropriate parameterization, in combination with `graph.induced_subgraph()`.
