### ISSUE TITLE
Graph-aware community comparison measure.

### ISSUE THREAD

**Issue by vpoulin** [igraph/python-igraph#190]
How do we go to include a very simple "graph-aware measure" for comparing graph partitions, i.e., a similarity measure that takes the topology of the graph into account ([more details here](https://arxiv.org/abs/1806.11494)). 
The code can be found below.
The current implementation uses functionality from the python-igraph code (see below or file attached).
Thanks.

[adjusted_graphaware_rand_index.py.txt](https://github.com/igraph/python-igraph/files/2420519/adjusted_graphaware_rand_index.py.txt)

PYTHON CODE FOR THE FUNCTION:
This function requires comm1 OR comm2 to be VertexClustering.
If both comm1 and comm2 are of type VertexClustering, both need to be on same graph object.

def igraph_compare_communities_agri(comm1, comm2):
  if(isinstance(comm1, list) and isinstance(comm2, list)):
      raise ValueError("One of the two communities must be of type VertexClustering!")
  if(isinstance(comm1, list):
      comm1 = VertexClustering(comm2.graph, comm1)
  elif(isinstance(comm2, list):
      comm2 = VertexClustering(comm1.graph, comm2)
  if(comm1.graph != comm2.graph):
      raise ValueError("The VertexClustering objects must be on the same graph object!")
   bu = ~np.array(comm1.crossing)
   bv = ~np.array(comm2.crossing)
   su = sum(bu)
   sv = sum(bv)
   suv = sum(bu*bv)
   m = len(bu)
   return((suv - su*sv/m) / (0.5*(su+sv) - su*sv/m))

**Comment by ntamas** [comment]
The Python interface typically provides wrappers for low-level functions written in C in the igraph library itself (see [this repo](https://github.com/igraph/igraph) ); it rarely provides additional functionality on its own. Therefore, if you would like to get this measure included in igraph, the preferred course of action would be to re-write it in C and send a pull request to the [main igraph repo](https://github.com/igraph/igraph). The pull request should include the additional function along with a standalone test case that integrates with the test suite of the igraph C library.
