### ISSUE TITLE
pip install python-igraph

### ISSUE THREAD

**Issue by dimuthulakshan** [igraph/python-igraph#191]
With "pip install python-igraph" installation command it gives this error. Please help me to solve this issue.

Running setup.py install for python-igraph ... error
    Complete output from command c:\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DLAMIT~1\\AppData\\Local\\Temp\\pip-install-971vsbfg\\python-igraph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DLAMIT~1\AppData\Local\Temp\pip-record-b_03y9nm\install-record.txt --single-version-externally-managed --compile:

- [ ] This issue is for the Python interface of igraph.
- [ ] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
This is not the complete output of the command, but anyway, since you are trying to install igraph on Windows, try the [precompiled installers](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph).

**Comment by HabeebullahEbrahemi** [comment]
I solve the problem using this YouTube video 
https://www.youtube.com/watch?v=Xg3jBz5Mp24
