### ISSUE TITLE
Misspelling in readme of libxml2-dev

### ISSUE THREAD

**Issue by Xparx** [igraph/python-igraph#192]
A small thing but an easy fix
in the dependency package line `libxml2 libxml2-de zlib1g-dev`
`libxml2-de` should be `libxml2-dev`.

**Comment by Xparx** [comment]
It could also be a nice thing if this dependency list was available on the python-igraph homepage http://igraph.org/python/.

**Comment by ntamas** [comment]
README is now fixed in 1b5632e.
