### ISSUE TITLE
minimum spanning tree

### ISSUE THREAD

**Issue by istvanftoth** [igraph/python-igraph#195]
Is there any function in igraph which returns minimum spanning tree for DIRECTED and weighted networks ? If there is not, can you suggest any solution ?
Many thanks

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x ] This issue is for the Python interface of igraph.
- [ x] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
We support undirected graphs in igraph only; for directed graphs, edge directions will be ignored. I guess that for the general directed case, you are looking for an algorithm that would produce an in-arborescence or an out-arborescence (i.e. a subset of edges such that the root node is reachable from every other node via them, or that all other nodes can be reached from the root node via them). If this is the case, you need to implement [Edmonds' algorithm](https://www.wikiwand.com/en/Edmonds%27_algorithm), or use [this implementation](https://github.com/mlbright/edmonds) after figuring out how to convert your igraph graph into the format required by this implementation.
