### ISSUE TITLE
Error while running community_optimal_modularity()

### ISSUE THREAD

**Issue by jfoppe** [igraph/python-igraph#198]
Hello,
i try to run a community detection with python-igraph and the optimal_modularity method but it throws an error
my code:
`import igraph as ig`
`g = ig.read("arabidopsis.graphml")`
`clustered = g.community_optimal_modularity()`
`print(clustered)`

Error:
`glp_add_cols: ncs = 564060078; too many columns`
`Error detected in file api/prob1.c at line 365`
`Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

the problem must be in line 3, because other methods (like community_walktrap()) work perfect

[arabidopsis.graphml.zip](https://github.com/igraph/python-igraph/files/2536256/arabidopsis.graphml.zip)

**Comment by ntamas** [comment]
`optimal_modularity()` is suitable for small toy problems only where the exact maximization of the modularity function is feasible. In your case, the graph is too large and the resulting integer optimization problem will have too many columns so it would take ages to compute it anyway. Use one of the heuristics instead, e.g. `community_multilevel)`.
