### ISSUE TITLE
edge_betweenness may returns wrong result

### ISSUE THREAD

**Issue by yuxuesong1995** [igraph/python-igraph#207]
Hi, I was trying to calculate edge betweenness for unweighted networks, and there were 3 ways for me to do it, one is using python-igraph, one is using networkx, and the other is using my own c# codes.

Problem is that the results from networkx and my own c# codes are always the same, but sometimes (for some big complex networks) are different from using python-igraph.

So I just wondering how does edge_betweenness works? Is there any chance to have bug in some situation? Or is it just suggest that the other two codes are wrong?

**Comment by ntamas** [comment]
> Is there any chance to have bug in some situation?
Hard to tell without seeing your network and what the differences are.

> Or is it just suggest that the other two codes are wrong?
No, but they could have different interpretations of the edge betweenness measure itself. Typically the cause of confusion in such cases is the presence of multiple edges or loop edges - one implementation of the measure may treat them in one way (e.g., including them) and another implementation may treat them in another way (e.g., ignore them).

**Comment by yuxuesong1995** [comment]
Thanks for your replying so quick!

> Typically the cause of confusion in such cases is the presence of multiple edges or loop edges

Inspired by you, I`ve done some more test and find it was my fault of reading networks wrong, some network files record one edge (i,j) twice as i,j and j,i, somehow this influence the calculation of betweenness. And I fixed it, all results are the same.

Sorry for my carelessness, and thanks for your help
