### ISSUE TITLE
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Jessime** [igraph/python-igraph#208]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

I have a user running OS X (10.14) who can't install python-igraph (which I have listed as a dependency of my package in my `setup.py`). The full compiler output is long, but the end of the error is:

```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'gcc' failed with exit status 1
```

This error seems related to https://github.com/igraph/igraph/issues/973, but I'm unclear on what the fix is. Thanks!

**Comment by Jessime** [comment]
Pastebin fails cause I go over the size limit, but here's a gist:

https://gist.githubusercontent.com/Jessime/50c09ddf3a9d694046cdc63cee557924/raw/5c1323caa7b290608ecee49decbc3e609b05254e/.txt

There are actually three crashes here, since two of my other dependencies also depend on igraph. I didn't know if that would be useful or not. But you can quickly find different sections by doing `ctrl+f` "failed building".

**Comment by ntamas** [comment]
I suspect that this is related to the usage of Anaconda Python. Anaconda Python targets Mac OS X 10.7 and later when it compiles a Python extension, and it seems like XCode 10.1 does not support linking to `stdc++` when the deployment target is Mac OS X 10.7. On my machine, I am compiling igraph for a local Python installation built from source, and I use macOS 10.14 as the deployment target, so XCode does not complain.

Can you try `pip install` again after setting `MACOSX_DEPLOYMENT_TARGET` to `10.14`, according to [this comment](https://github.com/ContinuumIO/anaconda-issues/issues/10135#issuecomment-426736042)? (I think that simply running `MACOSX_DEPLOYMENT_TARGET=10.14 pip install python-igraph` should be enough).

**Comment by ngenator** [comment]
@ntamas Since the OP hasn't posted their results yet here's mine. I had the same problem on Mojave and setting that env variable did fix the build for me. Thanks for the fix!

Without the variable set:

```
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
```

With it set:

```
➜ MACOSX_DEPLOYMENT_TARGET=10.14 pip install python-igraph
Collecting python-igraph
  Using cached https://files.pythonhosted.org/packages/0f/a0/4e7134f803737aa6eebb4e5250565ace0e2599659e22be7f7eba520ff017/python-igraph-0.7.1.post6.tar.gz
Building wheels for collected packages: python-igraph
  Running setup.py bdist_wheel for python-igraph ... done
  Stored in directory: /Users/dng/Library/Caches/pip/wheels/41/d6/02/34eebae97e25f5b87d60f4c0687e00523e3f244fa41bc3f4a7
Successfully built python-igraph
Installing collected packages: python-igraph
Successfully installed python-igraph-0.7.1.post6

➜ python
Python 3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph as ig
>>> ig.__version__
'0.7.1'
>>>
```

**Comment by ntamas** [comment]
Thanks for the feedback! It seems like one should be linking to `c++` instead of `stdc++` when the deployment target (i.e. preferred compatibility level of the compiled Python extension) is macOS 10.9 or later. This seems to be the default for Anaconda Python. The system Python apparently uses 10.14 - I cannot even force `MACOSX_DEPLOYMENT_TARGET=10.9` on my machine because I am getting the following error:

```error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "10.14" during configure```

It would be nice to fix this in a more permanent manner by detecting Anaconda Python and then linking to `c++` instead of `stdc++`, but it's unlikely that I'll have time to debug this more thoroughly in the near future.

**Comment by Jessime** [comment]
Sorry for the delay in response, but `MACOSX_DEPLOYMENT_TARGET=10.14 pip install python-igraph` also worked for us, and does a clean install. Thanks for looking into this!

This does seem to be a common failure on Mac w/Anaconda though; I've had a second user run into the same issue. 

I guess in my `setup.py` I could try [detecting Anaconda](https://stackoverflow.com/questions/21282363/any-way-to-tell-if-users-python-environment-is-anaconda) and setting `MACOSX_DEPLOYMENT_TARGET=10.14` for the duration of the setup if the user is on Mac. Does that seem like a reasonable temporary hack?

**Comment by ntamas** [comment]
Yes, that's a reasonable temporary hack. As for me, in the long run I'd prefer something more robust in `python-igraph`'s own `setup.py` (if only I had the time to fix it), something that does not mess around with `MACOSX_DEPLOYMENT_TARGET`. I would need to track down where (in which macOS or XCode version) the change from `-lstdc++` to `-lc++` happened and use the right library name depending on the macOS or XCode version, irrespectively of whether igraph is compiled for Anaconda or not as other alternative Python distributions might also have the same problem.

**Comment by Jessime** [comment]
Unless I'm misunderstanding, I actually can't have `setup.py` export the environment variable in a way that pip can see it, since it's running in the parent process, or something (I'm a little hazy on the exact details). The best I've been able to do is a raising an error that tells the user to run `$ export MACOSX_DEPLOYMENT_TARGET=10.14`, and to try running pip again after that.

I wish I could help with the `-lstdc++` vs. `-lc++` but I don't have anywhere near enough experience.

**Comment by szhorvat** [comment]
Related to this, once having install python-igraph with a C/igraph installation being present, it will somehow cache the location of the C interface, and won't try to locate it again.  Not even if it was removed in the meantime.

Where is this cached, and how can I reset it (so it will attempt to compile from source again)?

**Comment by szhorvat** [comment]
I found the answer: it's `pip` that does the caching and this can be solved by

    MACOSX_DEPLOYMENT_TARGET=10.14 pip install --no-cache-dir python-igraph

**Comment by szhorvat** [comment]
> I would need to track down where (in which macOS or XCode version) the change from `-lstdc++` to `-lc++` happened

I think that would be 10.9 ...

**Comment by ntamas** [comment]
We will be providing pre-compiled wheels for macOS from python-igraph 0.8 onwards so I'll close this issue. Feel free to reopen if needed.
