### ISSUE TITLE
igraph tests fail using pre-compiled binaries for Windows

### ISSUE THREAD

**Issue by sfloery** [igraph/python-igraph#210]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x ] This issue is for the Python interface of igraph.
- [x ] This issue is a bug report or a feature request, not a support question.

I installed python-igraph using the compiled version from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph

I'm using Windows 10 (X64) with Python 3.7!

Running the tests result in the following errors:
import igraph.test
igraph.test.run_tests()

ERROR: testFormula (igraph.test.generators.GeneratorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\envs\test_env\lib\site-packages\igraph\test\generators.py", line 72, in testFormula
    g = Graph.Formula(formula)
  File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: invalid token found in edge specification: A

======================================================================
ERROR: testPickle (igraph.test.foreign.ForeignTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\envs\test_env\lib\site-packages\igraph\test\foreign.py", line 207, in testPickle
    g = Graph.Read_Pickle(pickle)
  File "c:\users\envs\test_env\lib\site-packages\igraph\__init__.py", line 1829, in Read_Pickle
    fp = open(fname, "rb")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

======================================================================
ERROR: testCohesiveBlocks2 (igraph.test.decomposition.CohesiveBlocksTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\envs\test_env\lib\site-packages\igraph\test\decomposition.py", line 329, in testCohesiveBlocks2
    g = Graph.Formula("1-2:3:4:5:6, 2-3:4:5:7, 3-4:6:7, 4-5:6:7, "
  File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
  File "<string>", line None
SyntaxError: invalid token found in edge specification: 1-2:3:4:5:6

----------------------------------------------------------------------
Ran 307 tests in 6.246s

FAILED (errors=3)

I also noticed that contracting vertices is not working as expected:
g = igraph.Graph.Full(5)
g.vcount() --> 5
g.contract_vertices([0,1,0,3,4])
g.vcount() --> 5 !!!!

I'm on windows 10 x64 with python 3.7

**Comment by sfloery** [comment]
> 
> 
> Make sure that these boxes are checked before submitting your issue -- thank you!
> 
>     * [x ] This issue is for the Python interface of igraph.
> 
>     * [x ] This issue is a bug report or a feature request, not a support question.
> 
> 
> I installed python-igraph using the compiled version from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph
> 
> I'm using Windows 10 (X64) with Python 3.7!
> 
> Running the tests result in the following errors:
> import igraph.test
> igraph.test.run_tests()
> ## ERROR: testFormula (igraph.test.generators.GeneratorTests)
> 
> Traceback (most recent call last):
> File "c:\users\envs\test_env\lib\site-packages\igraph\test\generators.py", line 72, in testFormula
> g = Graph.Formula(formula)
> File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 209, in construct_graph_from_formula
> for start_names, end_names, arrowheads in generate_edges(part):
> File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 90, in generate_edges
> raise SyntaxError(msg)
> File "", line None
> SyntaxError: invalid token found in edge specification: A
> ## ======================================================================
> ERROR: testPickle (igraph.test.foreign.ForeignTests)
> 
> Traceback (most recent call last):
> File "c:\users\envs\test_env\lib\site-packages\igraph\test\foreign.py", line 207, in testPickle
> g = Graph.Read_Pickle(pickle)
> File "c:\users\envs\test_env\lib\site-packages\igraph__init__.py", line 1829, in Read_Pickle
> fp = open(fname, "rb")
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> ## ======================================================================
> ERROR: testCohesiveBlocks2 (igraph.test.decomposition.CohesiveBlocksTests)
> 
> Traceback (most recent call last):
> File "c:\users\envs\test_env\lib\site-packages\igraph\test\decomposition.py", line 329, in testCohesiveBlocks2
> g = Graph.Formula("1-2:3:4:5:6, 2-3:4:5:7, 3-4:6:7, 4-5:6:7, "
> File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 209, in construct_graph_from_formula
> for start_names, end_names, arrowheads in generate_edges(part):
> File "c:\users\envs\test_env\lib\site-packages\igraph\formula.py", line 90, in generate_edges
> raise SyntaxError(msg)
> File "", line None
> SyntaxError: invalid token found in edge specification: 1-2:3:4:5:6
> 
> Ran 307 tests in 6.246s
> 
> FAILED (errors=3)
> 
> I also noticed that contracting vertices is not working as expected:
> g = igraph.Graph.Full(5)
> g.vcount() --> 5
> g.contract_vertices([0,1,0,3,4])
> g.vcount() --> 5 !!!!
> 
> I'm on windows 10 x64 with python 3.7

I just checked the tests using python 3.6 in an new  virtual environment; all tests succeed without error; but the contract_vertices behaviour is the same:

>>> g = igraph.Graph.Full(5)
>>> print(g)
IGRAPH U--- 5 10 --
+ edges:
0 -- 1 2 3 4   1 -- 0 2 3 4   2 -- 0 1 3 4   3 -- 0 1 2 4   4 -- 0 1 2 3
>>> g.contract_vertices([0,1,0,3,4])
>>> print(g)
IGRAPH U--- 5 10 --
+ edges:
0 -- 0 0 1 1 3 3 4 4   2 --                   4 -- 0 0 1 3
1 -- 0 0 3 4           3 -- 0 0 1 4
>>> g = g.simplify()
>>> print(g)
IGRAPH U--- 5 6 --
+ edges:
0 -- 1 3 4   1 -- 0 3 4   2 --         3 -- 0 1 4   4 -- 0 1 3

Is this the expected behaviour of contract_vertices()?

**Comment by ntamas** [comment]
The failures above have already been fixed in the code but there was no official released version since the fix (due to lack of time), so they are still there in the pre-built binaries as those are built from the latest official release. However, I think that in these cases the failures are in the test cases and not in igraph's code so you should not be worried about it.

As for `contract_vertices()`: yes, this is the correct behaviour. Essentially, with the mapping vector that you provided, you are reassigning all edges incident on vertex 2 to be incident on vertex 0 instead. The edge count stays the same. If you want to collapse multiple edges into a single one, you need to call `simplify()` explicitly.
