### ISSUE TITLE
Failure to install python-igraph on mac high sierra

### ISSUE THREAD

**Issue by 454400098** [igraph/python-igraph#211]
Hi i've tried `brew install cairo
brew install py2cairo
brew install igraph ` on my mac, and after I run the follow command `sudo pip install python-igraph`.
I have the following warning on terminal which I cannot solove:
`nbp-242-109:data-processing zhenghaodong$ sudo pip install python-igraph
Password:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/Users/zhenghaodong/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/zhenghaodong/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-igraph
  Downloading https://files.pythonhosted.org/packages/0f/a0/4e7134f803737aa6eebb4e5250565ace0e2599659e22be7f7eba520ff017/python-igraph-0.7.1.post6.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 8.7MB/s 
Installing collected packages: python-igraph
  Running setup.py install for python-igraph ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-o5d5mk/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-h5QEiH/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/configuration.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/clustering.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/compat.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/formula.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/layout.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/cut.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/__init__.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/matching.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/summary.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/datatypes.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/utils.py -> build/lib.macosx-10.6-intel-2.7/igraph
    copying igraph/statistics.py -> build/lib.macosx-10.6-intel-2.7/igraph
    creating build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/structural.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/colortests.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/attributes.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/rng.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/conversion.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/vertexseq.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/__init__.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/flow.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/games.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/matching.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/generators.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/isomorphism.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/basic.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/utils.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/edgeseq.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/decomposition.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/iterators.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/spectral.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/separators.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/homepage.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/atlas.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/indexing.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/operators.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/layouts.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/cliques.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/foreign.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    copying igraph/test/bipartite.py -> build/lib.macosx-10.6-intel-2.7/igraph/test
    creating build/lib.macosx-10.6-intel-2.7/igraph/app
    copying igraph/app/shell.py -> build/lib.macosx-10.6-intel-2.7/igraph/app
    copying igraph/app/__init__.py -> build/lib.macosx-10.6-intel-2.7/igraph/app
    creating build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/shapes.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/edge.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/baseclasses.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/graph.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/coord.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/__init__.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/vertex.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/utils.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/text.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/metamagic.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    copying igraph/drawing/colors.py -> build/lib.macosx-10.6-intel-2.7/igraph/drawing
    creating build/lib.macosx-10.6-intel-2.7/igraph/remote
    copying igraph/remote/__init__.py -> build/lib.macosx-10.6-intel-2.7/igraph/remote
    copying igraph/remote/nexus.py -> build/lib.macosx-10.6-intel-2.7/igraph/remote
    copying igraph/remote/gephi.py -> build/lib.macosx-10.6-intel-2.7/igraph/remote
    creating build/lib.macosx-10.6-intel-2.7/igraph/vendor
    copying igraph/vendor/texttable.py -> build/lib.macosx-10.6-intel-2.7/igraph/vendor
    copying igraph/vendor/__init__.py -> build/lib.macosx-10.6-intel-2.7/igraph/vendor
    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    
    Version 0.7.1.post6 of the C core of igraph is not found among the nightly builds.
    Use the --c-core-version switch to try a different version.
    
    Could not download and compile the C core of igraph.
    
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-o5d5mk/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-h5QEiH/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-o5d5mk/python-igraph/`
Could you please tell me how to solve this issue, I think this issus has something to do with the c-core

**Comment by ntamas** [comment]
The installer tries to download the C core of igraph from http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz; it might be the case that your network connection was not stable when you tried doing this or that our server was temporarily down. Can you try again now? I have just tried it a few minutes ago and the tarball was accessible.

**Comment by 454400098** [comment]
Thanks for answering ntamas, I've tries what you told, it does not work.
But, I solve this bug in another way: I found that the python2.7 was installed in a third part version like anaconda in my computer, and I uninstall python2.7, and clear bash profile. Restart the computer, clear any dependencies of old python using brew. Finally reinstall python 2.7 and python3 in my computer, and run pip install python-igraph successfully. Igraph works both on python2.7 and 3.7.2.

**Comment by redlockon** [comment]
@454400098 Hi, I got the same problem too. Can you tell me the instruction to solve this problem like uninstall, clear bash, and clear any dependencies of old python using brew?
