### ISSUE TITLE
installation errors on centos

### ISSUE THREAD

**Issue by Jessime** [igraph/python-igraph#212]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

I have a user trying to install my package on CentOS, but we're running into some issues. Here is the ongoing issue on my page: https://github.com/CalabreseLab/seekr/issues/4. 

There's a lot of content there, some of which is a little round about. But, I launched a EC2 CentOS vm and tried it myself. I've made progress but am still stuck. I installed miniconda then did:

```
sudo yum install gcc
sudo yum install gcc-c++
conda create -n seekr pip
conda activate seekr
pip install seekr
```

There's a lot of output, but the tail end of the fail is:

```
    /usr/bin/ld: cannot find -lxml2
    /usr/bin/ld: cannot find -lz
    collect2: error: ld returned 1 exit status
    make[3]: *** [libigraph.la] Error 1
    make[3]: Leaving directory `/tmp/pip-install-6x6uft62/python-igraph/tmp/igraph.w01270p2/igraph-0.7.1/src'
    make[2]: *** [all] Error 2
    make[2]: Leaving directory `/tmp/pip-install-6x6uft62/python-igraph/tmp/igraph.w01270p2/igraph-0.7.1/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/tmp/pip-install-6x6uft62/python-igraph/tmp/igraph.w01270p2/igraph-0.7.1'
    make: *** [all] Error 2
    Could not download and compile the C core of igraph.
    
    
    ----------------------------------------
Command "/home/centos/miniconda3/envs/seekr2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6x6uft62/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-n0akx0z4/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6x6uft62/python-igraph/
```

I then tried:

```
(seekr2) [centos@ip-172-31-38-102 ~]$ sudo yum install libxml2
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * extras: mirror.ash.fastserv.com
 * updates: mirror.cogentco.com
Package libxml2-2.9.1-6.el7_2.3.x86_64 already installed and latest version
Nothing to do
```

Which didn't really help.

Interestingly, I also tried to use a [pre-compiled binary](https://anaconda.org/vtraag/python-igraph). It installs without issue. But if you launch python and try something it fails:

```python
>>> import igraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/centos/miniconda3/envs/seekr/lib/python3.6/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libigraph.so.0: cannot open shared object file: No such file or directory
```

One reason this is interesting is because I opened a similar https://github.com/igraph/python-igraph/issues/100 over two years ago, haha. That time, using the pre-compiled binary was the solution. No such luck this time, it seems. Any thoughts?

**Comment by ntamas** [comment]
You need to install the development packages for `libxml2` and `libz` before trying to `pip install anything-that-depends-on-igraph`. Even with that, I'm not sure whether the compilation works with Anaconda Python because the general problem is that Anaconda Python ships its own versions of `libxml2` and `libz` (or, at least, it used to be last time I checked) and they might or might not be compatible with the headers that ship with CentOS.

As for the issue with the pre-compiled binary: it seems like it was linked to the C core of igraph dynamically, which basically means that you need the C core of igraph (i.e. `libigraph.so.0`) present somewhere on your system, and _then_ the pre-compiled lib provides the glue code between the C core and Python itself, but it does not contain the C core on its own.

**Comment by Jessime** [comment]
I created a fresh instance, and skipped the `miniconda` part. Here's the entire output of `history` on that machine:

```
(venv) [centos@ip-172-31-92-193 ~]$ history
    1  ls
    2  sudo yum install libxml2
    3  sudo yum install libz
    4  sudo yum install zlib-devel
    5  sudo yum install gcc
    6  sudo yum install gcc-c++
    7  sudo yum install python36-devel
    8  sudo yum install python36-dev
    9  sudo yum install https://centos7.iuscommunity.org/ius-release.rpm
   10  sudo yum install python36-devel
   11  python3.6
   12  which pip
   13  pip
   14  sudo yum install python36u-pip
   15  pip3.6
   16  pip3.6 --version
   17  python -m venv venv
   18  python3.6 -m venv venv
   19  ls
   20  source venv/bin/activate
   21  which pip
   22  pip -V
   23  sudo yum install zlib-devel
   24  sudo yum install libxml2
   25  pip install seekr
   26  histry
   27  history
```

The shorter version would be:

```
sudo yum install libxml2   # Says it's already installed
sudo yum install zlib-devel   # Installs 
sudo yum install gcc
sudo yum install gcc-c++
sudo yum install https://centos7.iuscommunity.org/ius-release.rpm
sudo yum install python36-devel
sudo yum install python36u-pip
python3.6 -m venv venv
source venv/bin/activate
pip install seekr   # Fails
```

The install fails with just `/usr/bin/ld: cannot find -lxml2`, the other previous error `/usr/bin/ld: cannot find -lz` is not present. This may or may not be useful, but I tried to check what files are present in `libxml2`:

```
(venv) [centos@ip-172-31-92-193 ~]$ rpm -ql libxml2
/usr/bin/xmlcatalog
/usr/bin/xmllint
/usr/lib64/libxml2.so.2
/usr/lib64/libxml2.so.2.9.1
/usr/share/doc/libxml2-2.9.1
/usr/share/doc/libxml2-2.9.1/AUTHORS
/usr/share/doc/libxml2-2.9.1/Copyright
/usr/share/doc/libxml2-2.9.1/NEWS
/usr/share/doc/libxml2-2.9.1/README
/usr/share/doc/libxml2-2.9.1/TODO
/usr/share/man/man1/xmlcatalog.1.gz
/usr/share/man/man1/xmllint.1.gz
/usr/share/man/man3/libxml.3.gz
```

**Comment by ntamas** [comment]
I'd say you probably need `libxml2-devel` as well (if there is such a package).

**Comment by Jessime** [comment]
That did it. So, a full solution would be:

```
sudo yum install libxml2-devel
sudo yum install zlib-devel
sudo yum install gcc
sudo yum install gcc-c++
sudo yum install https://centos7.iuscommunity.org/ius-release.rpm
sudo yum install python36-devel
sudo yum install python36u-pip
python3.6 -m venv venv
source venv/bin/activate
pip install seekr
```

**Comment by ntamas** [comment]
We will provide pre-compiled Python wheels of igraph from the next release so hopefully these types of compilation issues will not be present any more.
