### ISSUE TITLE
Cannot install python-igraph from pypy3 virtual env

### ISSUE THREAD

**Issue by gokcedilek** [igraph/python-igraph#213]
When I try to import igraph from my pypy3 virtual environment, I am getting the following error:

```>>>> import igraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/btl/gdilek/virtualEnv/site-packages/igraph/__init__.py", line 36, in <module>
    from igraph.clustering import *
  File "/projects/btl/gdilek/virtualEnv/site-packages/igraph/clustering.py", line 33, in <module>
    from igraph.compat import property
  File "/projects/btl/gdilek/virtualEnv/site-packages/igraph/compat.py", line 58, in <module>
    property = __builtins__["property"]
TypeError: 'module' object is not subscriptable
```
What exactly does this error mean; how could I fix that?

Thank you!

**Comment by ntamas** [comment]
This is probably an incompatibility between CPython (the reference implementation that we generally use for testing) and PyPy. In CPython, you can use the `[...]` operator on a module to get one of its members, while on PyPy3 you apparently can't. Try replacing `property = __builtins__["property"]` in `/projects/btl/gdilek/virtualEnv/site-packages/igraph/compat.py` with `getattr(__builtins__, "property")` and let me know whether it resolved the problem.

**Comment by gokcedilek** [comment]
Hi! Thank you for your reply!
This time, I am getting this error:
```ImportError: cannot import name 'property'```

**Comment by gokcedilek** [comment]
Sorry, I wrote the command incorrectly; it is fixed! Thank you very much!
