### ISSUE TITLE
Reading dot files

### ISSUE THREAD

**Issue by gokcedilek** [igraph/python-igraph#214]
Hi!

How can we read dot files in IGraph -- similar to NetworkX's read.dot()?

Thank you!

**Comment by ntamas** [comment]
There is no `.dot` reader in igraph.

Also, please note that this is an issue tracker, not a support forum. If you have questions regarding the usage of `python-igraph`, please [subscribe to the mailing list](https://lists.nongnu.org/mailman/listinfo/igraph-help).
