### ISSUE TITLE
Unable to Install Igraph for Anaconda

### ISSUE THREAD

**Issue by MohammadHeydari** [igraph/python-igraph#221]
Well, I'm trying to install igraph for anaconda distribution. I found some command from anaconda official repository but they didn't work at all.
is there any recent command to work fine on to install igraph on anaconda?

**Comment by ntamas** [comment]
I was told that [this one](https://anaconda.org/conda-forge/python-igraph) works. I don't use Anaconda myself so I cannot test it. Maybe @vtraag can give some hints here.

**Comment by vtraag** [comment]
Are you trying to install `python-igraph` or the C `igraph` library? Indeed the one from the `conda-forge` channel should work.

**Comment by ntamas** [comment]
We will strive to provide first-party Anaconda Python wheels for the next release. Closing the issue.
