### ISSUE TITLE
A detailed Python-igraph tutorial 

### ISSUE THREAD

**Issue by MohammadHeydari** [igraph/python-igraph#223]
I'm looking for a detailed Python-igraph tutorial to utilize it for a graph analytic project. i studied some tutorial on the web. can you introduce me some useful documentation or pdf tutorial ?

**Comment by ntamas** [comment]
[Here](https://igraph.org/python/doc/tutorial/tutorial.html) is a somewhat incomplete tutorial and [here](https://igraph.org/python/doc/igraph-module.html) is the generated API documentation.
