### ISSUE TITLE
Compilation using --static in conda yields error

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#225]
When compiling inside a `conda` environment using `python setup.py install --static` it yields the following error

    relocation R_X86_64_PC32 against symbol `igraph_i_interruption_handler' can not be used when making a shared object; recompile with -fPIC

This seems to be due to the usage of `compiler_compat/ld` inside the `conda` environment, which can be traced back to this issue https://github.com/conda/conda/issues/6030.

I am not sure yet what we could/should do about this, but I just wanted to report this to have a record of the problem.

**Comment by ntamas** [comment]
@vtraag Have you tried to compile a conda package for `python-igraph` recently, does this work now that we have switched to compiling the C core during the build process by default?

**Comment by vtraag** [comment]
No, I have not yet checked it. I will try to do so later this week.

**Comment by ntamas** [comment]
@vtraag Any updates on this? Is this still an issue?

**Comment by ntamas** [comment]
@vtraag is this still relevant to the conda package?

**Comment by vtraag** [comment]
This works with the latest `python-igraph` version from `master` and the latest `igraph` version from `master` using `python setup.py install --use-pkg-config --static`.

 In fact, I don't think it ever had anything to do with `conda`, but just my lack of understanding. That is, the static `igraph` library was compiled without position independent code, something I now again ran into. At least in the current CMake setup this is quite easy to do using `-DCMAKE_POSITION_INDEPENDENT_CODE`, which is indeed also how you build the `igraph` library internally in `setup.py`.

I think we can close this.
