### ISSUE TITLE
Graph.Incidence should accept weighted argument

### ISSUE THREAD

**Issue by jboynyc** [igraph/python-igraph#229]
- [X] This issue is for the Python interface of igraph.
- [X] This issue is a bug report or a feature request, not a support question.

The Python interface supports creating bipartite graphs from incidence matrices using [Graph.Incidence](https://igraph.org/python/doc/igraph.Graph-class.html#Incidence). The corresponding function `graph_from_incidence_matrix` in the R library accepts an argument `weighted` (see [documentation](https://igraph.org/r/doc/graph_from_incidence_matrix.html)) to treat non-zero matrix values as edge weights, while the Python library does not. 

It would be nice for python-igraph to have feature partity with R-igraph.

**Comment by PuneethaPai** [comment]
Hi @ntamas , @jboynyc 
I would like to contribute to this. Any help would be appreciated. I have contributed to pure python libraries.
But this is my first time trying to write a wrapper on c-igraph.
Any help on where to start, how to debug would be great.

I know this is the place
```python
    @classmethod
    def Incidence(klass, *args, **kwds):
        result, types = klass._Incidence(*args, **kwds)
        result.vs["type"] = types
        return result
```
But as soon as i pass `weighted=True` i get invalid error, but couldn't find from where it is thrown.

Thanks in advance.

**Comment by ntamas** [comment]
The `_Incidence` method is implemented in the glue code between Python and igraph's C core:

https://github.com/igraph/python-igraph/blob/master/src/_igraph/graphobject.c#L2528

As you can see, this function does not accept a `weighted` argument (neither as a positional nor as a keyword argument). You need to exclude that argument from `kwds` before calling `_Incidence` and then you need to take care of setting up the weights in the Python layer.

**Comment by PuneethaPai** [comment]
Hi @ntamas 
Can you check the linked pr and share feedback.
Thanks
_PS: sorry for bothering :)_

**Comment by ntamas** [comment]
I'll try to take care of it later today.
