### ISSUE TITLE
Could not download and compile the C core of igraph on Mac OS X

### ISSUE THREAD

**Issue by dinacmistry** [igraph/python-igraph#230]
Hi, I'm using Mac 10.14.5 Mojave and I'm trying to install python-igraph. I've tried using homebrew and then pip installing igraph in the hopes of avoiding the issue of not being able to download and compily the C core of igraph. In particular, I've run `brew install igraph` and `pip3 install python-igraph`. 

Pasting the error message I receive to Pastebin (link below) so that maybe someone can help me out. Unfortunately, I'm not super well versed to figure this out myself. Could someone help me out here? Thanks in advance!

https://pastebin.com/mMMNruUG

**Comment by ntamas** [comment]
Hello,

Your computer is having problems with downloading the C core of igraph. I have tested it now and it works for me, so either you were having intermittent network problems, or you are accessing the network via a proxy — the installer script is having problems with proxies as far as I know. If you are using a proxy, let me know and we’ll figure out a workaround.

T.

**Comment by dinacmistry** [comment]
Hi, 

Thanks for replying. I'm not sure what you mean by accessing the network via a proxy, however I just tried to pip install it again and now it's working. Thank you anyways for the help - wasn't sure what the problem was so this was helpful.
