### ISSUE TITLE
how to load a dataset such as MUTAG by igraph

### ISSUE THREAD

**Issue by LanxinL** [igraph/python-igraph#231]
Hi, I want to load MUTAG by igraph, but Nexus is not maintained. Besides, I can't load the dataset by igraph.load() or igraph.read(). 

your kind assistance will be greatly appreciated ：)

**Comment by szhorvat** [comment]
For support, it is better to use the mailing list.

The issue tracker is for bug reports. If you believe you found a bug (e.g. `load()` does not work as it should), please show a [minimal working example](http://sscce.org/) that demonstrates the problem. We can't fix a bug if we can't reproduce it.
