### ISSUE TITLE
Build issue in master (incompatible type for argument 3 of ‘igraph_avg_nearest_neighbor_degree’)

### ISSUE THREAD

**Issue by mooncake4132** [igraph/python-igraph#236]
It seems like upstream introduced a breaking change in [this PR](https://github.com/igraph/igraph/pull/1214) by [adding two new parameters to igraph_avg_nearest_neighbor_degree](https://github.com/vtraag/igraph/blob/cf12f2ee70908b7fc57099af00ea547ceab64232/include/igraph_structural.h#L115-L116). `python-igraph` has not been updated to address this change:
https://github.com/igraph/python-igraph/blob/b44f51517491b6ddef5e55bd6e49c91accd37232/src/graphobject.c#L1764

This is causing build errors in master. From [travis](https://travis-ci.org/igraph/python-igraph/jobs/567025533#L5549-L5563):
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -Iigraphcore/include -I/opt/python/3.7.1/include/python3.7m -c src/graphobject.c -o build/temp.linux-x86_64-3.7/src/graphobject.o
  src/graphobject.c: In function ‘igraphmodule_Graph_knn’:
  src/graphobject.c:1764:58: error: incompatible type for argument 3 of ‘igraph_avg_nearest_neighbor_degree’
     if (igraph_avg_nearest_neighbor_degree(&self->g, vids, &knn, &knnk, weights)) {
                                                            ^
  In file included from igraphcore/include/igraph.h:63:0,
                   from src/graphobject.h:27,
                   from src/arpackobject.h:28,
                   from src/graphobject.c:24:
  igraphcore/include/igraph_structural.h:113:13: note: expected ‘igraph_neimode_t {aka enum <anonymous>}’ but argument is of type ‘igraph_vector_t * {aka struct igraph_vector_t *}’
   DECLDIR int igraph_avg_nearest_neighbor_degree(const igraph_t *graph,
               ^
  src/graphobject.c:1764:64: error: incompatible type for argument 4 of ‘igraph_avg_nearest_neighbor_degree’
     if (igraph_avg_nearest_neighbor_degree(&self->g, vids, &knn, &knnk, weights)) {
```

**Comment by vtraag** [comment]
Thanks for the issue!

This is an unfortunate side effect of bugfixing the C core. In the future we plan to work with the C core directly (as a submodule) in the Python interface, so that it is clear with what C code the Python library should build. We can then more easily correct issues in the C core, without immediately requiring changes downstream.

**Comment by ntamas** [comment]
I have added a quick patch to `master` to make it compile again with the latest revision of `igraph`'s `master`. We do not provide an interface for the extra arguments yet, only provide reasonable defaults. A proper fix should come later when (if) I have some time (or someone else does it ;)).

**Comment by vtraag** [comment]
Thanks @ntamas! I would suggest we switch to the submodule setup as soon as possible (i.e. as soon as 0.8.0 is released). This would really ease the simultaneous development of python-igraph and igraph without immediately wrecking havoc.

**Comment by ntamas** [comment]
The repo has now been adjusted to use git submodules. `setup.py` automatically makes use of the submodule if it is present.

**Comment by vtraag** [comment]
That's quick, great!

**Comment by mooncake4132** [comment]
Thanks for the quick fix!
