### ISSUE TITLE
Conversion to other network packages

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#237]
It would be useful to provide users with some convenience functions to convert igraph objects to and from other Python packages, most notably for `networkx` and `graph-tool`.

**Comment by iosonofabio** [comment]
I'm happy to take this if nobody else would?

**Comment by iosonofabio** [comment]
I've started #242 for this, it's going pretty well I'd say

**Comment by ntamas** [comment]
Great, I'll take a look at it in the next few days.

**Comment by Vadims06** [comment]
How can I start to use it? Reinstall python-igraph from GIT? I just install it from pip3 and there is no such method

**Comment by ntamas** [comment]
Stalebot will soon come and close this issue so I'm adding a comment to prevent it from doing so.
