### ISSUE TITLE
summary function throwing an error

### ISSUE THREAD

**Issue by neocsbee** [igraph/python-igraph#24]
This is the line that is causing the bug:

    ig.summary(myg1.components(mode="weak").subgraphs()[1], verbosity=1,width=None,edge_list_format="edgelist")

This is the error message:

```
  File "build/bdist.linux-x86_64/egg/igraph/__init__.py", line 4091, in summary
    
  File "build/bdist.linux-x86_64/egg/igraph/__init__.py", line 3191, in summary
    
  File "build/bdist.linux-x86_64/egg/igraph/summary.py", line 369, in __str__
  File "build/bdist.linux-x86_64/egg/igraph/summary.py", line 210, in _construct_edgelist_edgelist
  File "build/bdist.linux-x86_64/egg/igraph/vendor/texttable.py", line 315, in add_rows
  File "build/bdist.linux-x86_64/egg/igraph/summary.py", line 285, in _edge_attribute_iterator
  File "build/bdist.linux-x86_64/egg/igraph/summary.py", line 285, in <genexpr>
NameError: free variable 'names' referenced before assignment in enclosing scope
when using the following line:
ig.summary(myg1.components(mode="weak").subgraphs()[1], \
 verbosity=1,width=None,edge_list_format="edgelist"
)
```

**Comment by ntamas** [comment]
Probably fixed this in the commit referenced above. Please try applying this patch to your source tree and let me know if this resolved the issue for you.

**Comment by neocsbee** [comment]
I installed python-igraph following the steps given in http://igraph.org/python/. How do I apply this patch in this case?

**Comment by ntamas** [comment]
Open a Python prompt and type the following:

>>> import igraph
>>> print igraph.__file__

This will tell you the full path of the `__init__.py` file of the installed copy of igraph. The file to modify (`summary.py`) is in the same folder.

**Comment by neocsbee** [comment]
I still couldn't find this file. Here is the screenshot showing the path:
![summ_install1](https://cloud.githubusercontent.com/assets/3037022/6595984/389e36b0-c7c6-11e4-9492-2490b8d3f82b.png)

I only found an .egg file instead of a directory in that path.

**Comment by ntamas** [comment]
Ah, okay, so you have a Python egg - that is essentially a ZIP file, but it's easier not to mess with it. Let's do the following:

# Go to http://pypi.python.org/pypi/python-igraph and download the source code ZIP file.
# Extract the ZIP file somewhere.
# Modify the file named `igraph/summary.py` in the extracted directory.
# Run `python setup.py install`.

**Comment by neocsbee** [comment]
Will there be any problem with my old installation? Is it possible to overwrite the old one, so that I have only one version in the machine?

**Comment by ntamas** [comment]
Theoretically, `python setup.py install` would just overwrite the old version (or at least make it inaccessible). If you are worried, you can delete the `.egg` file after you have confirmed that the new version is working.

**Comment by neocsbee** [comment]
There seems to be some syntax error in the patch. Here are the screenshots:

![summ_install2](https://cloud.githubusercontent.com/assets/3037022/6598789/6a3ec336-c7dc-11e4-8030-5d4838c5c948.png)

![summ_install3](https://cloud.githubusercontent.com/assets/3037022/6598793/6c0d7f68-c7dc-11e4-82bd-e35cbffa20cb.png)

**Comment by ntamas** [comment]
That's not a syntax error; you seem to have downloaded some kind of an HTML file. This is the "raw" file that you should replace `summary.py` with:

https://raw.githubusercontent.com/igraph/python-igraph/e3becce7fd9076ab6b119c29a70e0b2b1a5f1881/igraph/summary.py

**Comment by neocsbee** [comment]
You are correct!  The function call works as expected. A small issue, though. It also prints an extra line with "None" at the end. Here is the screenshot.

![summ_install4](https://cloud.githubusercontent.com/assets/3037022/6599875/9f8f08d8-c7e2-11e4-807e-0acf6e0f607a.png)

**Comment by ntamas** [comment]
You were probably typing `print(summary(g))` and not `summary(g)`. `summary(g)` prints the summary on its own (so you could use it easily at interactive Python prompts) and then returns `None`. When you type `print(summary(g))`, Python ends up printing that `None` value at the end as well.

**Comment by neocsbee** [comment]
Perfect! Thanks, @ntamas.
