### ISSUE TITLE
can it be used on Windows?

### ISSUE THREAD

**Issue by Sandy4321** [igraph/python-igraph#241]
Make sure that these boxes are checked before submitting your issue -- thank you!
can it be used on Windows?
- [ x] This issue is for the Python interface of igraph.
- [x ] This issue is a bug report or a feature request, not a support question.

**Comment by iosonofabio** [comment]
It can but installation is currently not straightforward. We are actively working on a better Windows installer and hope to fix that problem in the near future.

**Comment by vtraag** [comment]
For the moment you can install in Anaconda, from the [`conda-forge`](https://anaconda.org/conda-forge/python-igraph) channel, or you can download a binary wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph.
