### ISSUE TITLE
PyPy-friendly Release Request

### ISSUE THREAD

**Issue by luav** [igraph/python-igraph#244]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

The latest python-igraph release installable from PyPI (python-igraph==0.7.1.post6) fails execution under PyPy because of the minor bug, which was fixed in March (#213) and have not been released yet:
```sh
$ pypy3  algorithms/fast_consensus.py ...
Traceback (most recent call last):
  File "algorithms/fast_consensus.py", line 11, in <module>
    import igraph as ig
  File "/home/ubuntu/.local/lib/pypy3.6/site-packages/igraph/__init__.py", line 36, in <module>
    from igraph.clustering import *
  File "/home/ubuntu/.local/lib/pypy3.6/site-packages/igraph/clustering.py", line 33, in <module>
    from igraph.compat import property
  File "/home/ubuntu/.local/lib/pypy3.6/site-packages/igraph/compat.py", line 58, in <module>
    property = __builtins__["property"]
TypeError: 'module' object is not subscriptable (key 'property')
```

Can you please **release some version of the python-igraph after that fix** to simplify distribution of the dependent projects that rely on igraph and assumed to be executed under PyPy?!

**Comment by szhorvat** [comment]
A new release is going to be issued within a month or so. A lot of work is being currently done to make this happen.

**Comment by szhorvat** [comment]
I should note that I am not deeply involved with the Python interface (I contribute to the C core), thus I can't comment on plans about PyPy support. All I can say is that a release is coming

**Comment by ntamas** [comment]
@luav can PyPy install stuff with `pip` from git repos directly? If so, you can probably run `pip -U git+https://github.com/igraph/python-igraph.git`; `pip` is smart enough to check out the submodule with the required revision of the C core of igraph and do the compilation.

**Comment by luav** [comment]
@ntamas Thanks, pip install of the repository works fine:
```sh
$ sudo apt-get install -y libtool flex
$ pypy3 -m pip install --user -U git+https://github.com/igraph/python-igraph.git
```

**Comment by ntamas** [comment]
@luav Do you happen to know whether `pypy` can make use of Python wheels, and if so, how shall we build a Python wheel in advance for the next release so there is no need to compile anything when installing `python-igraph`? I cannot promise that we will implement this for 0.8 but it would be great if we could set it up at least in a CI environment.

**Comment by luav** [comment]
@ntamas Typically, `PyPy` uses own version of the wheels: https://doc.pypy.org/en/latest/install.html#installing-more-modules. From the user perspective it works exactly like the `CPython` wheels but generates different binaries. In practice, you can use `CPython` wheels with `PyPy` but then in most cases end up with [such issues](https://bitbucket.org/cffi/cffi/issues/182/building-a-wheel-with-pypy-accidentally).  
Thus, to support both `CPython` and `PyPy`, you should have the dedicated environments for each of them. I'm not sure that there exists a straight-forward way to avoid the dedicated compilation for `PyPy`... To speed up the compilation by avoiding unnecessary recompilation, you can [employ caching](https://ccache.dev/).
