### ISSUE TITLE
error with "python setup.py build"

### ISSUE THREAD

**Issue by rachelglenn** [igraph/python-igraph#248]
Hi. I installed igraph from https://github.com/igraph/igraph.

I then downloaded python-igraph and ran "python setup.py build"

I get several errors:

src/graphobject.c:1675:58: error: incompatible type for argument 3 of ‘igraph_avg_nearest_neighbor_degree’
   if (igraph_avg_nearest_neighbor_degree(&self->g, vids, &knn, &knnk, weights)) {
                                                          ^
In file included from /usr/local/include/igraph/igraph.h:63:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_structural.h:113:13: note: expected ‘igraph_neimode_t {aka enum <anonymous>}’ but argument is of type ‘igraph_vector_t * {aka struct igraph_vector_t *}’
 DECLDIR int igraph_avg_nearest_neighbor_degree(const igraph_t *graph,
             ^
src/graphobject.c:1675:64: error: incompatible type for argument 4 of ‘igraph_avg_nearest_neighbor_degree’
   if (igraph_avg_nearest_neighbor_degree(&self->g, vids, &knn, &knnk, weights)) {
                                                                ^
In file included from /usr/local/include/igraph/igraph.h:63:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_structural.h:113:13: note: expected ‘igraph_neimode_t {aka enum <anonymous>}’ but argument is of type ‘igraph_vector_t * {aka struct igraph_vector_t *}’
 DECLDIR int igraph_avg_nearest_neighbor_degree(const igraph_t *graph,
             ^
src/graphobject.c:1675:7: error: too few arguments to function ‘igraph_avg_nearest_neighbor_degree’
   if (igraph_avg_nearest_neighbor_degree(&self->g, vids, &knn, &knnk, weights)) {
       ^
In file included from /usr/local/include/igraph/igraph.h:63:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_structural.h:113:13: note: declared here
 DECLDIR int igraph_avg_nearest_neighbor_degree(const igraph_t *graph,
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_neighborhood’:
src/graphobject.c:4824:7: error: too few arguments to function ‘igraph_neighborhood’
   if (igraph_neighborhood(&self->g, &res, vs, (igraph_integer_t) order, mode)) {
       ^
In file included from /usr/local/include/igraph/igraph.h:65:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_neighborhood.h:34:13: note: declared here
 DECLDIR int igraph_neighborhood(const igraph_t *graph, igraph_vector_ptr_t *res,
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_neighborhood_size’:
src/graphobject.c:4877:7: error: too few arguments to function ‘igraph_neighborhood_size’
   if (igraph_neighborhood_size(&self->g, &res, vs, (igraph_integer_t) order, mode)) {
       ^
In file included from /usr/local/include/igraph/igraph.h:65:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_neighborhood.h:31:13: note: declared here
 DECLDIR int igraph_neighborhood_size(const igraph_t *graph, igraph_vector_t *res,
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_layout_circle’:
src/graphobject.c:6156:11: error: too few arguments to function ‘igraph_layout_circle’
     ret = igraph_layout_circle(&self->g, &m);
           ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:44:13: note: declared here
 DECLDIR int igraph_layout_circle(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_layout_kamada_kawai’:
src/graphobject.c:6424:73: error: incompatible type for argument 7 of ‘igraph_layout_kamada_kawai’
       (&self->g, &m, (igraph_integer_t) niter, sigma, initemp, coolexp, kkconst, use_seed,
                                                                         ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:61:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘double’
 DECLDIR int igraph_layout_kamada_kawai(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c:6424:82: warning: passing argument 8 of ‘igraph_layout_kamada_kawai’ makes pointer from integer without a cast [-Wint-conversion]
       (&self->g, &m, (igraph_integer_t) niter, sigma, initemp, coolexp, kkconst, use_seed,
                                                                                  ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:61:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘igraph_bool_t {aka int}’
 DECLDIR int igraph_layout_kamada_kawai(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c:6423:11: error: too many arguments to function ‘igraph_layout_kamada_kawai’
     ret = igraph_layout_kamada_kawai
           ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:61:13: note: declared here
 DECLDIR int igraph_layout_kamada_kawai(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c:6428:73: error: incompatible type for argument 7 of ‘igraph_layout_kamada_kawai_3d’
       (&self->g, &m, (igraph_integer_t) niter, sigma, initemp, coolexp, kkconst, use_seed, 0,
                                                                         ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:106:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘double’
 DECLDIR int igraph_layout_kamada_kawai_3d(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c:6428:82: warning: passing argument 8 of ‘igraph_layout_kamada_kawai_3d’ makes pointer from integer without a cast [-Wint-conversion]
       (&self->g, &m, (igraph_integer_t) niter, sigma, initemp, coolexp, kkconst, use_seed, 0,
                                                                                  ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:106:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘igraph_bool_t {aka int}’
 DECLDIR int igraph_layout_kamada_kawai_3d(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c:6427:11: error: too many arguments to function ‘igraph_layout_kamada_kawai_3d’
     ret = igraph_layout_kamada_kawai_3d
           ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:106:13: note: declared here
 DECLDIR int igraph_layout_kamada_kawai_3d(const igraph_t *graph, igraph_matrix_t *res,
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_layout_fruchterman_reingold’:
src/graphobject.c:6660:75: error: incompatible type for argument 7 of ‘igraph_layout_fruchterman_reingold’
         (&self->g, &m, (igraph_integer_t) niter, maxdelta, area, coolexp, repulserad,
                                                                           ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:49:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘double’
 DECLDIR int igraph_layout_fruchterman_reingold(const igraph_t *graph,
             ^
src/graphobject.c:6661:10: warning: passing argument 8 of ‘igraph_layout_fruchterman_reingold’ makes pointer from integer without a cast [-Wint-conversion]
          use_seed, weights, minx, maxx, miny, maxy);
          ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:49:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘igraph_bool_t {aka int}’
 DECLDIR int igraph_layout_fruchterman_reingold(const igraph_t *graph,
             ^
src/graphobject.c:6659:11: error: too many arguments to function ‘igraph_layout_fruchterman_reingold’
     ret = igraph_layout_fruchterman_reingold
           ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:49:13: note: declared here
 DECLDIR int igraph_layout_fruchterman_reingold(const igraph_t *graph,
             ^
src/graphobject.c:6664:64: error: incompatible type for argument 6 of ‘igraph_layout_fruchterman_reingold_3d’
       (&self->g, &m, (igraph_integer_t) niter, maxdelta, area, coolexp, repulserad,
                                                                ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:93:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘double’
 DECLDIR int igraph_layout_fruchterman_reingold_3d(const igraph_t *graph, 
             ^
src/graphobject.c:6664:73: error: incompatible type for argument 7 of ‘igraph_layout_fruchterman_reingold_3d’
       (&self->g, &m, (igraph_integer_t) niter, maxdelta, area, coolexp, repulserad,
                                                                         ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:93:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘double’
 DECLDIR int igraph_layout_fruchterman_reingold_3d(const igraph_t *graph, 
             ^
src/graphobject.c:6665:8: warning: passing argument 8 of ‘igraph_layout_fruchterman_reingold_3d’ makes pointer from integer without a cast [-Wint-conversion]
        use_seed, weights, minx, maxx, miny, maxy, minz, maxz);
        ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:93:13: note: expected ‘const igraph_vector_t * {aka const struct igraph_vector_t *}’ but argument is of type ‘igraph_bool_t {aka int}’
 DECLDIR int igraph_layout_fruchterman_reingold_3d(const igraph_t *graph, 
             ^
src/graphobject.c:6663:11: error: too many arguments to function ‘igraph_layout_fruchterman_reingold_3d’
     ret = igraph_layout_fruchterman_reingold_3d
           ^
In file included from /usr/local/include/igraph/igraph.h:69:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_layout.h:93:13: note: declared here
 DECLDIR int igraph_layout_fruchterman_reingold_3d(const igraph_t *graph, 
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_canonical_permutation’:
src/graphobject.c:8054:46: warning: passing argument 2 of ‘igraph_canonical_permutation’ from incompatible pointer type [-Wincompatible-pointer-types]
   if (igraph_canonical_permutation(&self->g, &labeling, sh, 0)) {
                                              ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:262:13: note: expected ‘const igraph_vector_int_t * {aka const struct igraph_vector_int_t *}’ but argument is of type ‘igraph_vector_t * {aka struct igraph_vector_t *}’
 DECLDIR int igraph_canonical_permutation(const igraph_t *graph, const igraph_vector_int_t *colors, igraph_vector_t *labeling,
             ^
src/graphobject.c:8054:57: error: incompatible type for argument 3 of ‘igraph_canonical_permutation’
   if (igraph_canonical_permutation(&self->g, &labeling, sh, 0)) {
                                                         ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:262:13: note: expected ‘igraph_vector_t * {aka struct igraph_vector_t *}’ but argument is of type ‘igraph_bliss_sh_t {aka enum <anonymous>}’
 DECLDIR int igraph_canonical_permutation(const igraph_t *graph, const igraph_vector_int_t *colors, igraph_vector_t *labeling,
             ^
src/graphobject.c:8054:7: error: too few arguments to function ‘igraph_canonical_permutation’
   if (igraph_canonical_permutation(&self->g, &labeling, sh, 0)) {
       ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:262:13: note: declared here
 DECLDIR int igraph_canonical_permutation(const igraph_t *graph, const igraph_vector_int_t *colors, igraph_vector_t *labeling,
             ^
src/graphobject.c: In function ‘igraphmodule_Graph_isomorphic_bliss’:
src/graphobject.c:8176:52: warning: passing argument 3 of ‘igraph_isomorphic_bliss’ from incompatible pointer type [-Wincompatible-pointer-types]
   if (igraph_isomorphic_bliss(&self->g, &other->g, &result, map12, map21,
                                                    ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:264:13: note: expected ‘const igraph_vector_int_t * {aka const struct igraph_vector_int_t *}’ but argument is of type ‘igraph_bool_t * {aka int *}’
 DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
             ^
src/graphobject.c:8176:61: warning: passing argument 4 of ‘igraph_isomorphic_bliss’ from incompatible pointer type [-Wincompatible-pointer-types]
   if (igraph_isomorphic_bliss(&self->g, &other->g, &result, map12, map21,
                                                             ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:264:13: note: expected ‘const igraph_vector_int_t * {aka const struct igraph_vector_int_t *}’ but argument is of type ‘igraph_vector_t * {aka struct igraph_vector_t *}’
 DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
             ^
src/graphobject.c:8176:68: warning: passing argument 5 of ‘igraph_isomorphic_bliss’ from incompatible pointer type [-Wincompatible-pointer-types]
   if (igraph_isomorphic_bliss(&self->g, &other->g, &result, map12, map21,
                                                                    ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:264:13: note: expected ‘igraph_bool_t * {aka int *}’ but argument is of type ‘igraph_vector_t * {aka struct igraph_vector_t *}’
 DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
             ^
src/graphobject.c:8177:7: error: incompatible type for argument 6 of ‘igraph_isomorphic_bliss’
       sh1, sh2, 0, 0)) {
       ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:264:13: note: expected ‘igraph_vector_t * {aka struct igraph_vector_t *}’ but argument is of type ‘igraph_bliss_sh_t {aka enum <anonymous>}’
 DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
             ^
src/graphobject.c:8177:12: error: incompatible type for argument 7 of ‘igraph_isomorphic_bliss’
       sh1, sh2, 0, 0)) {
            ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:264:13: note: expected ‘igraph_vector_t * {aka struct igraph_vector_t *}’ but argument is of type ‘igraph_bliss_sh_t {aka enum <anonymous>}’
 DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
             ^
src/graphobject.c:8176:7: error: too few arguments to function ‘igraph_isomorphic_bliss’
   if (igraph_isomorphic_bliss(&self->g, &other->g, &result, map12, map21,
       ^
In file included from /usr/local/include/igraph/igraph.h:66:0,
                 from src/graphobject.h:27,
                 from src/arpackobject.h:28,
                 from src/graphobject.c:24:
/usr/local/include/igraph/igraph_topology.h:264:13: note: declared here
 DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
             ^
error: command 'gcc' failed with exit status 1

**Comment by vtraag** [comment]
From where did you download `python-igraph`? If you install the `igraph` C core from the `master` branch from GitHub you should make sure that you use the `python-igraph` source code from the `master` branch from GitHub. 

Note that you don't *need* to install the `igraph` C core first. If you want the latest (non-released) version of `python-igraph` you can simply install using
```
pip -U git+https://github.com/igraph/python-igraph.git
```

If you want the released version (0.7.1) you can do
```
pip install python-igraph
```

Both ways should compile the appropriate version of the `igraph` C core automatically.

**Comment by rachelglenn** [comment]
Thank you for the quick response. I am doing an offline installation, so I downloaded python-igraph from this github site released version 0.7.1 and tried to install it. I complained that it could not find the C core. That is why I installed igraph from https://github.com/igraph/igraph.

**Comment by vtraag** [comment]
In that cass it would be best to simply install the latest version from GitHub. You can clone the repository using

```
git clone --recurse-submodules git://github.com/igraph/python-igraph.git
```

and then run

```
python setup.py install
```

from inside the cloned repository. 

Once the repository is cloned (including submodules), it does not need any internet connection anymore, so you can move it offline and install it there.

**Comment by rachelglenn** [comment]
Thank you.
