### ISSUE TITLE
all simple paths from src to dst in directed graph

### ISSUE THREAD

**Issue by dmikrav** [igraph/python-igraph#258]
Is there a function in python igraph that returns all simple paths from source vertex to destination in directed graph?

**Comment by vtraag** [comment]
Yes, there is, it is `get_all_simple_paths`. 

I believe it is not yet in the currently released version of `python-igraph`, but you can install the latest development version using `pip -U git+https://github.com/igraph/python-igraph.git`.

Hopefully we will be able to release a new version somewhere in the coming months.
