### ISSUE TITLE
Install Error on Anaconda RedHat Linux

### ISSUE THREAD

**Issue by Dragut** [igraph/python-igraph#260]
Installation of Python-igraph encounters error on Anaconde py37_1 and Rh Linux 3.10.0 X86_64.
 running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1

    Version 0.7.1.post6 of the C core of igraph is not found among the nightly builds.
    Use the --c-core-version switch to try a different version.

    Could not download and compile the C core of igraph.

    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/cloud-user/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q2o3jcjk/python-igraph/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q2o3jcjk/python-igraph/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9zjt2mo7/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

It looks like a bug somewhere.

**Comment by ntamas** [comment]
Try installing from Github; we are in the process of dropping support for downloading the C core of the igraph library during the installation process as it is very fragile (as you can see above). So, try this:

```
pip install git+https://github.com/igraph/python-igraph#egg=python-igraph
```

**Comment by Dragut** [comment]
Thanks. I encountered error in that as well, but solved by set tht PKGCONFIG environmental variable.

**Comment by vtraag** [comment]
@Dragut, could you post some more details of the output? It is not immediately obvious what the problem is. Possibly, you do not have compilers or Python headers installed?

By the way, it would be much easier if you simply installed `python-igraph` from the [`conda-forge`](https://anaconda.org/conda-forge/python-igraph) channel, if you have no need for the `master` branch.
