### ISSUE TITLE
igraph plot not available

### ISSUE THREAD

**Issue by Dragut** [igraph/python-igraph#261]
I have installed successfully pycario, cairocffi and even py2cario. But still cannot plot any graph.
import cairo 
g = Graph.Full(10)
only_odd_vertices = g.vs.select(lambda vertex: vertex.index % 2 == 1)
layout = g.layout("kk")
igraph.plot(g, layout = layout)

TypeError                                 Traceback (most recent call last)
<ipython-input-129-fd132260a0a9> in <module>
      3 only_odd_vertices = g.vs.select(lambda vertex: vertex.index % 2 == 1)
      4 layout = g.layout("kk")
----> 5 igraph.plot(g, layout = layout)

~/anaconda3/lib/python3.7/site-packages/igraph/drawing/__init__.py in plot(obj, target, bbox, *args, **kwds)
    444         bbox = BoundingBox(bbox)
    445 
--> 446     result = Plot(target, bbox, background=kwds.get("background", "white"))
    447 
    448     if "margin" in kwds:

~/anaconda3/lib/python3.7/site-packages/igraph/drawing/__init__.py in __init__(self, target, bbox, palette, background)
    115         """
    116         self._filename = None
--> 117         self._surface_was_created = not isinstance(target, cairo.Surface)
    118         self._need_tmpfile = False
    119 

~/anaconda3/lib/python3.7/site-packages/igraph/drawing/utils.py in __getattr__(self, _)
    394 
    395     def __getattr__(self, _):
--> 396         raise TypeError("plotting not available")
    397     def __call__(self, _):
    398         raise TypeError("plotting not available")

TypeError: plotting not available

**Comment by ntamas** [comment]
See my response in #129.
