### ISSUE TITLE
How do I add titles and legends to an iGraph diagram

### ISSUE THREAD

**Issue by zhengyzh** [igraph/python-igraph#263]
How do I add titles and legends to an iGraph diagram? It seems that iGraph does not support this function.

**Comment by ntamas** [comment]
It is outside the scope of igraph. You can use Cairo directly to draw on a Cairo surface that igraph has created; alternatively, you can [integrate igraph with Matplotlib](https://stackoverflow.com/a/36154077/156771).

Note that this is not a support forum; please send support requests to igraph-help@nongnu.org instead.
