### ISSUE TITLE
community_walktrap fails at missing nodes and nodes starting with 1: Python 3.6.9

### ISSUE THREAD

**Issue by bala2409** [igraph/python-igraph#265]
Using networkx edges method inside igraph add_edges() method

```
import networkx as nx
from igraph import *
G = nx.parse_edgelist(file, delimiter=',', nodetype=int)
g = Graph()
g.add_vertices(G.nodes())
g.add_edges(G.edges())
dendrogram = g.community_walktrap(steps=1)
community = dendrogram.as_clustering()
membership = community.membership

#netscience dataset
(1461, 1461)
Traceback (most recent call last):
  File "/home/Documents/ttt.py", line 21, in <module>
    g.add_vertices(G.nodes())
  File "/home/.local/lib/python3.6/site-packages/igraph/__init__.py", line 301, in add_vertices
    self.vs[m:]["name"] = names
  File "/home/.local/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
**KeyError: 19**
[Finished in 7.0s with exit code 1]

#karate club dataset
(34, 34)
Traceback (most recent call last):
  File "/home/Documents/ttt.py", line 21, in <module>
    g.add_vertices(G.nodes())
  File "/home/.local/lib/python3.6/site-packages/igraph/__init__.py", line 301, in add_vertices
    self.vs[m:]["name"] = names
  File "/home/.local/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
**KeyError: 0**
[Finished in 1.0s with exit code 1]
```

- [ missing nodes: dataset: 'netscience.csv' ] This issue is for the Python interface of igraph.
- [ using karate club dataset which starts at node: 1] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
`G.nodes()` and `G.edges()` are NetworkX-specific data types; they cannot simply be added to igraph graphs. Use `list(G.nodes)` and `list(G.edges)` instead.

**Comment by bala2409** [comment]
Well networkx's G.edges() returns a list of edges  (i.e [(1,2),(2,3),...]) the same structure required to add edges in igraph which supposed to work and i tried your method as well : list(G.nodes) also list (G.nodes())

(1461, 1461)
Traceback (most recent call last):
  File "/home/Documents/ttt.py", line 22, in <module>
    g.add_edges(list(G.edges))
  File "/home/.local/lib/python3.6/site-packages/igraph/__init__.py", line 255, in add_edges
    return GraphBase.add_edges(self, es)
igraph._igraph.InternalError: Error at type_indexededgelist.c:272: cannot add edges, Invalid vertex id
[Finished in 10.0s with exit code 1]

**Comment by ntamas** [comment]
> networkx's G.edges() returns a list of edges

No, it does not:

```
>>> from networkx import path_graph
>>> g = path_graph(10)
>>> type(g.edges)
<class 'networkx.classes.reportviews.EdgeView'>
>>> type(g.edges())
<class 'networkx.classes.reportviews.EdgeView'>
```

You can convert it to a list, though:

```
>>> list(g.edges)
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9)]
```

> i tried your method as well : list(G.nodes) also list (G.nodes()) but still the issue persists

Please provide an example data file and a [_self-contained_ example](http://sscce.org/) on which I could reproduce the problem.

**Comment by bala2409** [comment]
Thanks for the clarification, here i attached data files and scripts used

**Datasets attached:** 
edges karate (node starts from 1)
edges netscience (contains missing nodes, i.e: node 19)

**Files**: 
[csv_files.zip](https://github.com/igraph/python-igraph/files/3995099/csv_files.zip)

**Scripts/Code:**
import networkx as nx
from igraph import *
file=open('edges netscience.csv',"r")
#file=open('edges karate.csv',"r")
G = nx.parse_edgelist(file, delimiter=',', nodetype=int)
nodes = list(G.nodes)
edges = list(G.edges)
g = Graph()
g.add_vertices(nodes)
g.add_edges(edges)

**Output**
Traceback (most recent call last):
  File "/home/Documents/ttt.py", line 15, in <module>
    g.add_edges(edges)
  File "/home/.local/lib/python3.6/site-packages/igraph/__init__.py", line 255, in add_edges
    return GraphBase.add_edges(self, es)
igraph._igraph.InternalError: Error at type_indexededgelist.c:272: cannot add edges, Invalid vertex id
[Finished in 1.0s with exit code 1]

**Comment by ntamas** [comment]
This is not an igraph bug; the `nodes` list contains 1-based vertex indices, while igraph works with 0-based vertex indices _and_ it only supports strings as vertex "names". (Basically, when igraph sees a number for a node, it treats it as a 0-based node index, and when it sees a string, it assumes that it is the `name` attribute of one of the nodes).

The documentation of `add_vertices()` clearly states that you can use either a _single_ number as its argument (in which case it specifies _how many_ nodes you want to add), or a _single_ string or a list of strings (in which case these are treated as vertex names). You cannot use a list of numbers and then expect igraph to treat them as vertex names.

The easiest that you can probably do is to import the CSV file into NetworkX with strings as the node identifiers, not numbers. This way igraph will simply create a `name` vertex attribute that contains the numeric identifiers of the vertices from the CSV file, _and_ use a numeric vertex ID that it just makes up on its own.
