### ISSUE TITLE
Add Windows wheels to PyPi

### ISSUE THREAD

**Issue by lewtun** [igraph/python-igraph#266]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

As explained in the [docs](https://igraph.org/python/), the preferred way to install python-igraph on Windows is via the unofficial binaries on Gohlke's [webpage](https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph). 

However, it would be much more convenient if these binaries could be included as part of the PyPi release, especially for users working on remote machines without access to a browser. (Gohlke's website runs javascript for the downloads and thus not easy to get with tools like wget or curl.)

I realise that the developers of python-igraph do not use Windows, but perhaps a simple solution would be to use Azure pipelines for CI that automatically test whether the package can be successfully built and tested on Linux, macOS and Windows. 

We encountered a similar challenge in developing [giotto-learn](https://github.com/giotto-ai/giotto-learn) and found the pipelines enabled us to provide cross-platform support.

**Comment by vtraag** [comment]
It is our intention to make binary releases available for all platforms.

We are currently in the process of preparing a new release of the `igraph` C core. After that we are revising the current installation method of `python-igraph`. That revised installation method should make it easier to support binary builds on all platforms, including proper Windows support, and also properly supporting `conda` packaging.

We hope to release the new `igraph` C core end of January. It is not yet clear how soon after that we will be able to release a new `python-igraph` package, but hopefully it will not take too long.

**Comment by lewtun** [comment]
Thanks a lot for the information @vtraag - it's very useful!

**Comment by ntamas** [comment]
I have given `cibuildwheel` a go in our Travis setup, but it seems like building python-igraph with `cibuildwheel` uses way too much time in Travis and the jobs get killed before they have a chance to terminate:

https://travis-ci.org/igraph/python-igraph/jobs/629951424

I might be doing something wrong, though. One thing that I noticed is that since we are testing igraph with multiple Python versions in multiple Travis jobs, `cibuildwheel` gets invoked in all of them, and it would probably be better to have a separate Travis job that builds the wheels _only_ if all the tests have passed. I'm not familiar enough with Travis to figure out how to do it yet, but I'll return to this if I have some time again. Any inputs are appreciated in the meanwhile.

**Comment by flying-sheep** [comment]
You can do it using [stages](https://docs.travis-ci.com/user/build-stages/).

**Comment by ntamas** [comment]
[This is where things are](https://travis-ci.org/igraph/python-igraph/jobs/633468983) after last night; even with a separate deployment stage, the time limit (50 mins) is not enough to build the wheels for all Python versions for a single architecture. The Linux and Windows jobs are still broken, but the macOS job shows that the build process times out after 50 mins.

There is only one dependency: igraph itself. There is a git subrepo within the python-igraph repo that points to the appropriate revision of igraph; it is checked out and compiled with the rest of the extension. I think that a low-hanging fruit is that right now the C core of igraph seems to be compiled once per Python version, even though it should be completely identical. It would be nice if we could somehow get igraph compiled only once and then just link the Python extensions for the various Python extensions to the same igraph library instance. For this we would need to ask `cibuildwheel` to keep the built version of igraph around and re-use it for subsequent versions.

**Comment by gaborcsardi** [comment]
GitHub Actions has very generous usage limits and supports Linux (VM or Docker), macOS and Windows: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits

**Comment by flying-sheep** [comment]
> the time limit (50 mins) is not enough to build the wheels for all Python versions for a single architecture.

What’s shared between different building for the different Python versions? If not much is shared, you could make it a separate job for each combination of python version and arch.

Builds also only need to happen for tags, so you can add something like `if: tag =~ /^v\d/` for that stage, then it won’t be wasteful.

**Comment by vtraag** [comment]
@ntmas, have you confirmed the `wheel` building with `cibuildwheels` works correctly in a local environment?

**Comment by vtraag** [comment]
It seems that `cibuildwheel` tries to build for all Python versions by default for each job. That is, even though different versions listed under `python` in `.travis.yml` will result in multiple parallel jobs, in each parallel job, `cibuildwheel` tries to build for multiple versions of Python. We should somehow pass the information about the Python version to `cibuildwheel` using something like `CIBW_BUILD: cp36-*` (see https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip). I am not sure how to do that though.

It successfully creates a wheel for four versions of Python, but times out after that.

**Comment by ntamas** [comment]
I have created separate build stages for testing and wheel building now; testing runs in parallel for all Python versions that we support, while wheel building runs parallel for Linux, Windows and macOS. Last night I have also figured out why it is removing the previously built C core at every iteration; I'll fix that today if I have some time.

**Comment by flying-sheep** [comment]
Ooooh, great stuff, this sounds like we’re really close! Thank you so much for digging into this.

**Comment by ntamas** [comment]
Yes, exactly what I was thinking :) Anyway, it looks like [the trick might work](https://travis-ci.org/igraph/python-igraph/jobs/634461773) after all - managed to build wheels for all supported Python flavors for Linux `x86_64` and `i686` in a bit more than 16 mins. Windows and macOS still have to be sorted out.

**Comment by ntamas** [comment]
Windows 64-bit wheels are now also working.

**Comment by vtraag** [comment]
> Windows 64-bit wheels are now also working.

Great work! This will make a lot of people very happy!

**Comment by vtraag** [comment]
@ntamas, I'm looking into the build process now. If I understand the build process correctly, you now build the C core one for all Python versions, so that only the Python interface is compiled differently. I believe it uses MSVC 14.16 (Visual Studio 2017) for the C core. For compiling for Python 3.5-3.8 this is definitely no problem, since they use the same MSVC. But might this not run into problems for Python 2.7?

**Comment by ntamas** [comment]
I don't know, but the unit tests are executed as part of the build (a new venv is created, the generated Python wheels are installed in it, and then the unit tests are executed) so it's probably okay.

Also, Python 2.7 has reached its end of life this month so I wouldn't mind not supporting it after this release.

**Comment by vtraag** [comment]
> Also, Python 2.7 has reached its end of life this month so I wouldn't mind not supporting it after this release.

Yes, couldn't agree more!

**Comment by Marmeladenbrot** [comment]
> 
> 
> Windows 64-bit wheels are now also working.

Haven't found an other way to contact you, sorry for the inconvenience.

Would it be possible to upload this wheel? My python-igraph stopped working after some package update and now python-igraph won't update anymore after a clean install from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph.

Before pip found some update which fixed a bug with https://github.com/igraph/python-igraph/issues/235 that was not upstream in the wheel.

Now my python-igraph is broken again and I see no way to fix it but have to get my master thesis done and need a last network analysis.

**Comment by ntamas** [comment]
You can find a few compiled wheels [here](https://ci.appveyor.com/project/ntamas/python-igraph/builds/30505899/artifacts). Tested only in CI, so beware :)

**Comment by Marmeladenbrot** [comment]
Python 3.7.6 x64

> ERROR: python_igraph-0.7.1.post6-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

When trying via "pip install python_igraph-.....whl"

That's probably not gonna be fixable from my side until an official wheel is released. Thanks for the help nonetheless.

**Comment by vtraag** [comment]
@Marmeladenbrot, if you need something in the short term, you should be able to install `python-igraph` using Anaconda python from the `conda-forge` channel.

**Comment by Marmeladenbrot** [comment]
@vtraag sadly that does not work.

Installed Anaconda, conda 4.8.2

`conda install -c conda-forge python-igraph`

> PackagesNotFoundError: The following packages are not available from current channels:
>   - python-igraph
> Current channels:
>   - https://conda.anaconda.org/conda-forge/win-64
> ...

**Comment by vtraag** [comment]
Sorry, for Windows you can use my channel `vtraag`.

**Comment by Marmeladenbrot** [comment]
Installed Anaconda 2019.10 x64 (Python 3.7.4), set vtraag as channel, installed python-igraph from vtraag (conda install -c vtraag python-igraph), got  vtraag/win-64::python-igraph-0.7.1.post7-py37_0, set Anaconda as Interpreter in PyCharm, removed already existing Python installation from my system, python-igraph is listed in PyCharm interpreter package list with version 0.7.1.post7.

Still getting issue https://github.com/igraph/python-igraph/issues/235

**Comment by vtraag** [comment]
Ah, sorry, I didn't understand #235 was critical for you. Indeed it is not yet included in that build. I just thought you couldn't get `python-igraph` working anymore. I'm afraid you will have to wait for the release of 0.8.0.

**Comment by ntamas** [comment]
> ERROR: python_igraph-0.7.1.post6-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

@Marmeladenbrot Are you sure that you were not accidentally trying to use a 64-bit wheel with a 32-bit Python instance? Note that it does not matter if your computer is 64-bit; Python comes in 32-bit and 64-bit flavours and you need to match it with the wheel itself. @szhorvat has also been bitten by this during the weekend.

Anyway, for what it's worth, I have now managed to build [32-bit wheels as well](https://ci.appveyor.com/project/ntamas/python-igraph/build/job/rwxrh84jdu3lplyc/artifacts). They are tested in the CI env, which is 64-bit, but the wheels should have been compiled with a 32-bit Python instance so hopefully they work.

**Comment by Marmeladenbrot** [comment]
> Are you sure that you were not accidentally trying to use a 64-bit wheel with a 32-bit Python instance?

I could have sworn my Python was x64, that's also what the console in PyCharm said. Reinstalled Python, wheel installed, it works, network analysis finishes without an error ....... kudos to you, thanks a lot for your help and your time.

**Comment by ntamas** [comment]
Thanks for the feedback - and now we also know that the wheels built in the CI env work fine.
