### ISSUE TITLE
Bug in similarity_jaccard

### ISSUE THREAD

**Issue by llambourne** [igraph/python-igraph#267]
Unless I'm not understanding something, `similarity_jaccard` appears to be counting self-loops for every vertex when there are no self-loops in the network. As an example:

```
import igraph
g = igraph.Graph.TupleList([(0, 1),
                            (1, 2)],
                           directed=False)
print(g.similarity_jaccard(pairs=[(0, 2)], loops=True))
print(g.similarity_jaccard(pairs=[(0, 2)], loops=False))

>>> [0.3333333333333333]
>>> [1.0]
```

The versions I have are:
python-igraph      0.7.1.post6
igraph 0.7.1

Best,
Luke

**Comment by ntamas** [comment]
When `loops=True`, igraph will simply _assume_ that there is a loop edge incident on every vertex, even if you haven't explicitly included one in your graph. In other words, `loops=True` means that every vertex is included in its own "neighbor set" when it comes to calculating the Jaccard similarity. Depending on your particular use-case, it might or might not make the results more sense - but it does not make the calculation invalid as it clearly does what the documentation says about the `loops` argument:

> loops: whether vertices should be considered adjacent to themselves. Setting this to `True` assumes a loop edge for all vertices even if none is present in the graph. Setting this to `False` may result in strange results: nonadjacent vertices may have larger similarities compared to the case when an edge is added between them -- however, this might be exactly the result you want to get.

To see how this can happen in an existing graph: take a cycle of length 4, and then calculate the Jaccard similarity between vertices 0 and 2 with `loops=False` - it will be 1.0. Then add an edge between vertices 0 and 2 and watch the similarity drop to 0.5.

**Comment by llambourne** [comment]
Ah, I see. Thanks for the quick response! Apologies, I should have read the documentation more closely.
