### ISSUE TITLE
Switch documentation from epydoc to Sphinx

### ISSUE THREAD

**Issue by ntamas** [igraph/python-igraph#268]
Most of python-igraph is documented in Epydoc (Epytext), which is not maintained any more (plus it's Python 2.x only). We should probably stick with it until the next release, but after that it would be important to switch to Sphinx. It looks like the docstrings can be converted automatically on-the-fly with [sphinx-epytext](https://github.com/jayvdb/sphinx-epytext).

**Comment by iosonofabio** [comment]
I'm looking at current master in `doc/Makefile` and there is only sphinx stuff, is this issue still current? Thank you

**Comment by ntamas** [comment]
Yes, because all the docstrings are still in Epydoc format and the API documentation is generated with Epydoc (see `scripts/mkdoc.sh` and `scripts/epydoc-patched`).

**Comment by tristanlatr** [comment]
Hello,
If you wanna help your markup, [pydoctor](https://github.com/twisted/pydoctor) supports Epytext and it's actively used and maintained by the twisted community :)

**Comment by tristanlatr** [comment]
And here is what it would be like: https://tristanlatr.github.io/python-igraph/

**Comment by ntamas** [comment]
Looks good! I'll give it a go soon, hopefully for the next release, once we are finished with the transition to CMake in the main igraph repo. I'll need to work a bit on the integration with the main igraph.org site, though.

**Comment by tristanlatr** [comment]
> I'll need to work a bit on the integration with the main igraph.org site, though.

PyDoctor is almost a drop in replacement for Epydoc, so if your current setup works well with Epydoc it won't be a lot of work.

**Comment by ntamas** [comment]
FYI @iosonofabio I have started working on the migration to PyDoctor now that I tagged 0.9.0 and I realized that I cannot generate the docs anymore :)

**Comment by ntamas** [comment]
It seems like there is a bug in PyDoctor that prevents it from parsing the docstrings in `igraph._igraph`. I have started a discussion over in the PyDoctor issue tracker [here](https://github.com/twisted/pydoctor/issues/287#issuecomment-789075622) and I'm hoping to get an answer soon about how to proceed.

**Comment by ntamas** [comment]
Documentation is now generated with PyDoctor; closing this.
