### ISSUE TITLE
To implement graph union and graph difference by vertex names in Python, in the same way it is already implemented in R

### ISSUE THREAD

**Issue by cndesantana** [igraph/python-igraph#269]
The native C core of igraph supports graph union only by IDs and not
by vertex names. The R interface contains an implementation of "graph
union by vertex names", and it is selected automatically if your graph
has vertex names. However, There is no equivalent function in the Python
interface.

It would be great if you could implement graph union and graph difference by vertex names in Python, in the same way it is already implemented in R.

This issue was also discussed here: https://lists.nongnu.org/archive/html/igraph-help/2015-09/msg00083.html

Thanks

**Comment by ntamas** [comment]
No, it's not solved yet; there are too many corner cases to consider (see my [earlier comment](https://github.com/igraph/python-igraph/issues/269#issuecomment-263817279) and I haven't had time to implement it properly.

**Comment by ntamas** [comment]
Implemented in #310 so closing.
