### ISSUE TITLE
Build fails with igraph 0.8.0

### ISSUE THREAD

**Issue by limburgher** [igraph/python-igraph#272]
[build-log.txt](https://github.com/igraph/python-igraph/files/4140438/build-log.txt)
This is with gcc10 and igraph 0.8.0 on Fedora 32.

**Comment by ntamas** [comment]
How did you try to build `python-igraph`, what command(s) did you run? The build log does not show it unfortunately.

**Comment by limburgher** [comment]
/usr/bin/python3 setup.py  build --executable="/usr/bin/python3 -s"

**Comment by ntamas** [comment]
I assume that you checked out the source code of `python-igraph` from GIthub. Is that correct? If. so, did you also run `git submodule update --init` to fetch the C core of igraph as well? I'm asking because judging from the build log it seems that the setup script does not even attempt to build the C core, which usually happens when the C core is not checked out into `vendor/source/igraph`.

**Comment by limburgher** [comment]
No. This is from the post6 tarball. I'm the Fedora RPM maintainer, and we don't have network access for builds, so it has the igraph C libraries and headers installed beforehand.

**Comment by limburgher** [comment]
This worked before igraph 0.8.0.

**Comment by ntamas** [comment]
Yes, true, but things are changing.

First of all, the API of igraph changed between 0.7.1 and 0.8.0 so the old 0.7.1post6 Python extension won't work with igraph 0.8.0.

Second, we have now switched to a different distribution model with python-igraph such that python-igraph's tarball will contain the source code of the matching version of the C core so there will be no need to download the C core separately doing build time (as it used to be with python-igraph 0.7.1).

All in all, we are in the process of releasing `python-igraph 0.8.0` (which will be based on igraph 0.8.0), but we need a few more days to tie up some loose ends. Until then, you can install `python-igraph` from Github:

```
pip install -e git+https://github.com/igraph/python-igraph
```

This will check out python-igraph's source code (the most recent revision), fetch the corresponding C core version automatically (pip does it on its own), and then compiles everything on its own.

Please let me know if the command above does not work for you; our goal is to make it work out-of-the-box for most Linux distributions.

**Comment by limburgher** [comment]
I'll wait for the 0.8.0 release; the fetching of external modules is non-starter for us.

**Comment by ntamas** [comment]
Okay, closing this issue then; feel free to reopen after the release of 0.8.0 if you are still having problems.
