### ISSUE TITLE
Could not build and install python-igraph on OSX 10.15

### ISSUE THREAD

**Issue by vishalmhjn** [igraph/python-igraph#275]
- [x] This issue is for the Python interface of igraph.

brew install cairo
brew install py2cairo
brew install igraph

I get the following error when running `sudo pip install python-igraph `

`ERROR: Command errored out with exit status 1:
     command: /Users/home/opendata/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-install-fg3snf7r/python-igraph/setup.py'"'"'; __file__='"'"'/private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-install-fg3snf7r/python-igraph/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-record-obx9enfc/install-record.txt --single-version-externally-managed --compile --install-headers /Users/home/opendata/bin/../include/site/python3.7/python-igraph
         cwd: /private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-install-fg3snf7r/python-igraph/
    Complete output (156 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.7
    creating build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/configuration.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/clustering.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/compat.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/formula.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/layout.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/cut.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/matching.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/summary.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/datatypes.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/utils.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    copying igraph/statistics.py -> build/lib.macosx-10.15-x86_64-3.7/igraph
    creating build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/structural.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/colortests.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/attributes.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/rng.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/conversion.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/vertexseq.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/flow.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/games.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/matching.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/generators.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/isomorphism.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/basic.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/utils.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/edgeseq.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/decomposition.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/iterators.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/spectral.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/separators.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/homepage.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/atlas.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/indexing.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/operators.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/layouts.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/cliques.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/foreign.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    copying igraph/test/bipartite.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/test
    creating build/lib.macosx-10.15-x86_64-3.7/igraph/app
    copying igraph/app/shell.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/app
    copying igraph/app/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/app
    creating build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/shapes.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/edge.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/baseclasses.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/graph.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/coord.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/vertex.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/utils.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/text.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/metamagic.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    copying igraph/drawing/colors.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/drawing
    creating build/lib.macosx-10.15-x86_64-3.7/igraph/remote
    copying igraph/remote/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/remote
    copying igraph/remote/nexus.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/remote
    copying igraph/remote/gephi.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/remote
    creating build/lib.macosx-10.15-x86_64-3.7/igraph/vendor
    copying igraph/vendor/texttable.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/vendor
    copying igraph/vendor/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/igraph/vendor
    Fixing build/lib.macosx-10.15-x86_64-3.7/igraph/configuration.py build/lib.macosx-10.15-x86_64-3.7/igraph/clustering.py build/lib.macosx-10.15-x86_64-3.7/igraph/compat.py build/lib.macosx-10.15-x86_64-3.7/igraph/formula.py build/lib.macosx-10.15-x86_64-3.7/igraph/layout.py build/lib.macosx-10.15-x86_64-3.7/igraph/cut.py build/lib.macosx-10.15-x86_64-3.7/igraph/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/matching.py build/lib.macosx-10.15-x86_64-3.7/igraph/summary.py build/lib.macosx-10.15-x86_64-3.7/igraph/datatypes.py build/lib.macosx-10.15-x86_64-3.7/igraph/utils.py build/lib.macosx-10.15-x86_64-3.7/igraph/statistics.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/structural.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/colortests.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/attributes.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/rng.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/conversion.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/vertexseq.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/flow.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/games.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/matching.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/generators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/isomorphism.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/basic.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/utils.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/edgeseq.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/decomposition.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/iterators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/spectral.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/separators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/homepage.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/atlas.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/indexing.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/operators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/layouts.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/cliques.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/foreign.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/bipartite.py build/lib.macosx-10.15-x86_64-3.7/igraph/app/shell.py build/lib.macosx-10.15-x86_64-3.7/igraph/app/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/shapes.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/edge.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/baseclasses.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/graph.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/coord.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/vertex.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/utils.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/text.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/metamagic.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/colors.py build/lib.macosx-10.15-x86_64-3.7/igraph/remote/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/remote/nexus.py build/lib.macosx-10.15-x86_64-3.7/igraph/remote/gephi.py build/lib.macosx-10.15-x86_64-3.7/igraph/vendor/texttable.py build/lib.macosx-10.15-x86_64-3.7/igraph/vendor/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib.macosx-10.15-x86_64-3.7/igraph/configuration.py build/lib.macosx-10.15-x86_64-3.7/igraph/clustering.py build/lib.macosx-10.15-x86_64-3.7/igraph/compat.py build/lib.macosx-10.15-x86_64-3.7/igraph/formula.py build/lib.macosx-10.15-x86_64-3.7/igraph/layout.py build/lib.macosx-10.15-x86_64-3.7/igraph/cut.py build/lib.macosx-10.15-x86_64-3.7/igraph/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/matching.py build/lib.macosx-10.15-x86_64-3.7/igraph/summary.py build/lib.macosx-10.15-x86_64-3.7/igraph/datatypes.py build/lib.macosx-10.15-x86_64-3.7/igraph/utils.py build/lib.macosx-10.15-x86_64-3.7/igraph/statistics.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/structural.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/colortests.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/attributes.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/rng.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/conversion.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/vertexseq.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/flow.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/games.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/matching.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/generators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/isomorphism.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/basic.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/utils.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/edgeseq.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/decomposition.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/iterators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/spectral.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/separators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/homepage.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/atlas.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/indexing.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/operators.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/layouts.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/cliques.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/foreign.py build/lib.macosx-10.15-x86_64-3.7/igraph/test/bipartite.py build/lib.macosx-10.15-x86_64-3.7/igraph/app/shell.py build/lib.macosx-10.15-x86_64-3.7/igraph/app/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/shapes.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/edge.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/baseclasses.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/graph.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/coord.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/vertex.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/utils.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/text.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/metamagic.py build/lib.macosx-10.15-x86_64-3.7/igraph/drawing/colors.py build/lib.macosx-10.15-x86_64-3.7/igraph/remote/__init__.py build/lib.macosx-10.15-x86_64-3.7/igraph/remote/nexus.py build/lib.macosx-10.15-x86_64-3.7/igraph/remote/gephi.py build/lib.macosx-10.15-x86_64-3.7/igraph/vendor/texttable.py build/lib.macosx-10.15-x86_64-3.7/igraph/vendor/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    Build type: dynamic extension
    Include path: /usr/local/Cellar/igraph/0.8.0/include/igraph
    Library path: /usr/local/Cellar/igraph/0.8.0/lib
    Runtime library path:
    Linked dynamic libraries: igraph
    Linked static libraries:
    Extra compiler options:
    Extra linker options:
    building 'igraph._igraph' extension
    creating build/temp.macosx-10.15-x86_64-3.7
    creating build/temp.macosx-10.15-x86_64-3.7/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/igraph/0.8.0/include/igraph -I/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/edgeobject.c -o build/temp.macosx-10.15-x86_64-3.7/src/edgeobject.o
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/igraph/0.8.0/include/igraph -I/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/common.c -o build/temp.macosx-10.15-x86_64-3.7/src/common.o
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/igraph/0.8.0/include/igraph -I/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/py2compat.c -o build/temp.macosx-10.15-x86_64-3.7/src/py2compat.o
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/igraph/0.8.0/include/igraph -I/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/graphobject.c -o build/temp.macosx-10.15-x86_64-3.7/src/graphobject.o
    src/graphobject.c:1675:78: error: too few arguments to function call, expected 7, have 5
      if (igraph_avg_nearest_neighbor_degree(&self->g, vids, &knn, &knnk, weights)) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                     ^
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_structural.h:113:9: note: 'igraph_avg_nearest_neighbor_degree' declared here
    DECLDIR int igraph_avg_nearest_neighbor_degree(const igraph_t *graph,
            ^
    src/graphobject.c:4824:77: error: too few arguments to function call, expected 6, have 5
      if (igraph_neighborhood(&self->g, &res, vs, (igraph_integer_t) order, mode)) {
          ~~~~~~~~~~~~~~~~~~~                                                   ^
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_neighborhood.h:37:9: note: 'igraph_neighborhood' declared here
    DECLDIR int igraph_neighborhood(const igraph_t *graph, igraph_vector_ptr_t *res,
            ^
    src/graphobject.c:4877:82: error: too few arguments to function call, expected 6, have 5
      if (igraph_neighborhood_size(&self->g, &res, vs, (igraph_integer_t) order, mode)) {
          ~~~~~~~~~~~~~~~~~~~~~~~~                                                   ^
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_neighborhood.h:34:9: note: 'igraph_neighborhood_size' declared here
    DECLDIR int igraph_neighborhood_size(const igraph_t *graph, igraph_vector_t *res,
            ^
    src/graphobject.c:6156:44: error: too few arguments to function call, expected 3, have 2
        ret = igraph_layout_circle(&self->g, &m);
              ~~~~~~~~~~~~~~~~~~~~             ^
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_layout.h:44:9: note: 'igraph_layout_circle' declared here
    DECLDIR int igraph_layout_circle(const igraph_t *graph, igraph_matrix_t *res,
            ^
    src/graphobject.c:6425:37: error: too many arguments to function call, expected 11, have 12
           /*bounds*/ minx, maxx, miny, maxy);
                                        ^~~~
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_layout.h:61:9: note: 'igraph_layout_kamada_kawai' declared here
    DECLDIR int igraph_layout_kamada_kawai(const igraph_t *graph, igraph_matrix_t *res,
            ^
    src/graphobject.c:6429:43: error: too many arguments to function call, expected 13, have 15
           /*bounds*/ minx, maxx, miny, maxy, minz, maxz);
                                              ^~~~~~~~~~
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_layout.h:106:9: note: 'igraph_layout_kamada_kawai_3d' declared here
    DECLDIR int igraph_layout_kamada_kawai_3d(const igraph_t *graph, igraph_matrix_t *res,
            ^
    src/graphobject.c:6661:41: error: too many arguments to function call, expected 11, have 13
             use_seed, weights, minx, maxx, miny, maxy);
                                            ^~~~~~~~~~
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_layout.h:49:9: note: 'igraph_layout_fruchterman_reingold' declared here
    DECLDIR int igraph_layout_fruchterman_reingold(const igraph_t *graph,
            ^
    src/graphobject.c:6665:45: error: too many arguments to function call, expected 12, have 15
           use_seed, weights, minx, maxx, miny, maxy, minz, maxz);
                                                ^~~~~~~~~~~~~~~~
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_layout.h:93:9: note: 'igraph_layout_fruchterman_reingold_3d' declared here
    DECLDIR int igraph_layout_fruchterman_reingold_3d(const igraph_t *graph,
            ^
    src/graphobject.c:8054:62: error: too few arguments to function call, expected 5, have 4
      if (igraph_canonical_permutation(&self->g, &labeling, sh, 0)) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                           ^
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_topology.h:263:9: note: 'igraph_canonical_permutation' declared here
    DECLDIR int igraph_canonical_permutation(const igraph_t *graph, const igraph_vector_int_t *colors, igraph_vector_t *labeling,
            ^
    src/graphobject.c:8177:21: error: too few arguments to function call, expected 10, have 9
          sh1, sh2, 0, 0)) {
                        ^
    /usr/local/Cellar/igraph/0.8.0/include/igraph/igraph_topology.h:265:9: note: 'igraph_isomorphic_bliss' declared here
    DECLDIR int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
            ^
    10 errors generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/home/opendata/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-install-fg3snf7r/python-igraph/setup.py'"'"'; __file__='"'"'/private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-install-fg3snf7r/python-igraph/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gf/v279v4ks7n3bl5xlr3ylsnl40000gn/T/pip-record-obx9enfc/install-record.txt --single-version-externally-managed --compile --install-headers /Users/home/opendata/bin/../include/site/python3.7/python-igraph Check the logs for full command output.`

please help me out.

**Comment by ntamas** [comment]
igraph in Homebrew has recently been updated to version 0.8. The Python interface on PyPI is for version 0.7.1. You need to install python-igraph from Github until we publish the next version of the Python interface:

```
pip install -e git+https://github.com/igraph/python-igraph
```
