### ISSUE TITLE
Tutorial: TypeError: g.add_edges((x, y))

### ISSUE THREAD

**Issue by mpatek** [igraph/python-igraph#276]
In the tutorial, on lines 140 and 155, you make method calls of the form `g.add_edges((x, y))`

Those appear to raise TypeErrors (at least in version 0.7.1). It seems like they should be either `g.add_edge(x, y)` or `g.add_edges([(x, y)])`.

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
Thanks, it is fixed now!

I'll regenerate the homepage soon, but I need to spend some more time on fixing the styling issues there.
