### ISSUE TITLE
 shortest_paths error: Runtime to terminate it in an unusual way

### ISSUE THREAD

**Issue by AbufoudaMohammed** [igraph/python-igraph#28]
I am trying to call the shortest_paths() function for a relatively large network ( IGRAPH DN-- 13679 76741 -- ). Unexpectedly

, I got the following error:

```
"Assertion failed: q->stor_begin != 0, file c:\dev\igraph\igraph-0.6.5-msvc\src\dqueue.pmt, line 284

This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information. "
```

what does this error mean?

---

here is the code:
g = Graph.Read_Ncol('file.edgelist')
g.delete_vertices(g.vs.select(_degree=0))
g.vs["color"] = "Green"
summary(g)  
t = time.time()
g.shortest_paths()
print time.time() - t

---

and here is a link to the network that I used when this error occurred:  https://github.com/medoos/files/blob/master/network.rar

**Comment by ntamas** [comment]
This runs just fine for me in igraph 0.7.1 on Mac OS X. Please consider upgrading igraph to version 0.7.1 as you seem to be using 0.6.5 and the bug could have been fixed in the meanwhile. If the bug persists with 0.7.1, feel free to reopen this issue and then we'll investigate again.

**Comment by medoos** [comment]
I've update the igraph to the version 0.7.1, but the same error appears again!

**Comment by medoos** [comment]
Do I need to open a new issue or this issue will be reopened?

**Comment by ntamas** [comment]
I haven't had time to deal with it yet but now I've reopened the issue so at least it appears in the list of open issues for others. I'll try and reproduce it soon(ish).

**Comment by ntamas** [comment]
Still no luck - it's working fine for me on Mac OS X. Which OS are you using?

**Comment by medoos** [comment]
Windows 8.1 64.
