### ISSUE TITLE
Biconnected components algorithm is slow

### ISSUE THREAD

**Issue by harenbergsd** [igraph/python-igraph#281]
The biconnected components algorithm is very slow on larger graphs, compared to connected components and other graph packages.

For example, take the following code
```python
import sys
import igraph as ig
import graph_tool as gt
import graph_tool.topology as gtt
import time 

gfile = sys.argv[1]

G = ig.Graph.Read(gfile, format="edges")

st = time.time()
comps = G.components()
print(f"igraph strongly connected elapsed = {time.time()-st}")

st = time.time()
comps = G.biconnected_components()
print(f"igraph biconnected elapsed = {time.time()-st}, num bicomps = {len(comps)}")

G = gt.load_graph_from_csv(gfile, directed=True, csv_options={'delimiter': '\t'})
st = time.time()
comp, art, hist = gtt.label_biconnected_components(G)
print(f"graph_tool biconnected elapsed = {time.time()-st}, num bicomps = {len(hist)}")
```
On [the Amazon graph from SNAP](https://snap.stanford.edu/data/amazon0302.html), I get the following results:
```
igraph strongly connected elapsed = 0.1865100860595703
igraph biconnected elapsed = 6.894217014312744, num bicomps = 7849
graph_tool biconnected elapsed = 0.1410079002380371, num bicomps = 7849
```
On [the web-Google graph from SNAP](http://snap.stanford.edu/data/web-Google.html), I get the following results:
```
igraph strongly connected elapsed = 1.2485511302947998
igraph biconnected elapsed = 1056.809671163559, num bicomps = 175274
graph_tool biconnected elapsed = 0.5269908905029297, num bicomps = 175274
```

**Comment by ntamas** [comment]
The C core is probably okay, but the Python interface is doing lots of extra legwork in `Graph.biconnected_components()`; basically it is converting every single biconnected component into a `VertexCover` object. The bottleneck is most likely in this conversion; calling straight into the C core to obtain the biconnected components as lists make things much faster:

```
>>> st = time.time(); len(GraphBase.biconnected_components(g)); print(time.time() - st)
7849
0.257159948348999
```

Can you test it on your machine please so we can compare the elapsed times directly? (My computer most likely has different specs than yours).

**Comment by harenbergsd** [comment]
Yeah, that is much faster, I get:
igraph biconnected elapsed = 0.273540735244751, num bicomps = 7849
and
igraph biconnected elapsed = 1.055016279220581, num bicomps = 175274

**Comment by ntamas** [comment]
Okay, this is consistent with what I see when calling the function directly from C, so the Python overhead is now negligible:

```c
❯ gcc -o test test.c `pkg-config --cflags --libs igraph` && ./test
7849 0.2476s
```

I'll do some profiling to see whether there are any obvious low-hanging fruits where we could speed things up.
