### ISSUE TITLE
Indexing problem using numpy array cast to a list

### ISSUE THREAD

**Issue by pflugfelder** [igraph/python-igraph#288]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

I experience a strange bug when indexing graph vertecies. I can access vetrices using a list. It also works using a numpy array casted to a list with the 'tolist()' method. However it fails when casting a numpy array to a list using the python 'list()' command. Here a minimal example:

    import igraph
    import numpy as np
    t = igraph.Graph(100)
    t.vs['x'] = range(100, 200)
    # access some nodes:
    ind = [1, 5, 2, 42]

    # works as expected:
    t.vs[ind]['x']
    # Out[10]: [101, 105, 102, 142]

    # works as expected:
    t.vs[np.asarray(ind).tolist()]['x']
    # Out[11]: [101, 105, 102, 142]

    # fails:
    t.vs[list(np.asarray(ind))]['x']
    # Out[12]: []

I use anaconda python 3.7.6 on Windows 10, numpy 1.18.1 and tried python-igraph 0.7.1 (form https://www.lfd.uci.edu/~gohlke/pythonlibs/ ) as well as python-igraph 0.8.0 from pip. The issue appeared while trying to switch my application from python 2.7 to python 3, i.e. casting using list() worked on python 2.7. It does not seem to be a numpy issue since indexing works on numpy arrays:

    x = np.arange(100, 200)
    x[list(np.asarray(ind))]
    # Out[15]: array([101, 105, 102, 142])

**Comment by ntamas** [comment]
This is the difference:

```
>>> l = list(numpy.asarray(ind))
>>> type(l[0])
<class 'numpy.int64'>
>>> l2 = numpy.asarray(ind).tolist()
>>> type(l2[0])
<class 'int'>
```

It seems like igraph is not really happy with indexing when the index is a `numpy.int64` and not a regular Python int. I'll check whether there's an easy way around it without having to pull in NumPy as a hard dependency.

**Comment by ntamas** [comment]
Okay, I think it's fixed now; unfortunately I needed to patch the C glue code. 0.8.1 is coming soon anyway.
