### ISSUE TITLE
Could not compile the C core of igraph

### ISSUE THREAD

**Issue by amosleeday** [igraph/python-igraph#291]
Install python-igraph on ubuntu 16.04

`
pip install python-igraph

Collecting python-igraph
  Using cached https://files.pythonhosted.org/packages/3a/3b/bb574a95abb019636d2525a2622d7ea94a740ec91b5b65b909d34cf87174/python-igraph-0.8.0.tar.gz
Collecting texttable>=1.6.2 (from python-igraph)
  Using cached https://files.pythonhosted.org/packages/ec/b1/8a1c659ce288bf771d5b1c7cae318ada466f73bd0e16df8d86f27a2a3ee7/texttable-1.6.2-py2.py3-none-any.whl
Building wheels for collected packages: python-igraph
  Running setup.py bdist_wheel for python-igraph ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yzawam/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpgfb_Kxpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/__init__.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph
  copying src/igraph/version.py -> build/lib.linux-x86_64-2.7/igraph
  creating build/lib.linux-x86_64-2.7/igraph/app
  copying src/igraph/app/__init__.py -> build/lib.linux-x86_64-2.7/igraph/app
  copying src/igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app
  creating build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/__init__.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying src/igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  creating build/lib.linux-x86_64-2.7/igraph/remote
  copying src/igraph/remote/__init__.py -> build/lib.linux-x86_64-2.7/igraph/remote
  copying src/igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote
  running build_ext
  running build_c_core
  We are going to build the C core of igraph.
    Source folder: vendor/source/igraph
    Build folder: vendor/build/igraph
    Install folder: vendor/install/igraph
  
  Bootstrapping igraph...
  Finding out version number/string... fatal: Not a git repository: ../../../.git/modules/vendor/source/igraph
  0.8.0-pre+
  + aclocal
  bootstrap.sh: 21: bootstrap.sh: aclocal: not found
  + /usr/bin/libtoolize --force --copy
  libtoolize: putting auxiliary files in '.'.
  libtoolize: copying file './ltmain.sh'
  libtoolize: putting macros in 'm4'.
  libtoolize: copying file 'm4/libtool.m4'
  libtoolize: copying file 'm4/ltoptions.m4'
  libtoolize: copying file 'm4/ltsugar.m4'
  libtoolize: copying file 'm4/ltversion.m4'
  libtoolize: copying file 'm4/lt~obsolete.m4'
  libtoolize: Remember to add 'LT_INIT' to configure.ac.
  libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
  libtoolize: and rerunning libtoolize and aclocal.
  + autoheader
  bootstrap.sh: 23: bootstrap.sh: autoheader: not found
  + automake --add-missing --copy
  bootstrap.sh: 24: bootstrap.sh: automake: not found
  + autoconf
  bootstrap.sh: 25: bootstrap.sh: autoconf: not found
  + patch -N -p0 -r-
  + true
  Configuring igraph...
  sh: 0: Can't open /tmp/pip-build-yzawam/python-igraph/vendor/source/igraph/configure
  Could not compile the C core of igraph.
  
  
  ----------------------------------------
  Failed building wheel for python-igraph
  Running setup.py clean for python-igraph
Failed to build python-igraph
Installing collected packages: texttable, python-igraph
  Running setup.py install for python-igraph ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yzawam/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lzvVSe-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/__init__.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph
    copying src/igraph/version.py -> build/lib.linux-x86_64-2.7/igraph
    creating build/lib.linux-x86_64-2.7/igraph/app
    copying src/igraph/app/__init__.py -> build/lib.linux-x86_64-2.7/igraph/app
    copying src/igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app
    creating build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/__init__.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying src/igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    creating build/lib.linux-x86_64-2.7/igraph/remote
    copying src/igraph/remote/__init__.py -> build/lib.linux-x86_64-2.7/igraph/remote
    copying src/igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote
    running build_ext
    running build_c_core
    We are going to build the C core of igraph.
      Source folder: vendor/source/igraph
      Build folder: vendor/build/igraph
      Install folder: vendor/install/igraph
    
    Bootstrapping igraph...
    Finding out version number/string... fatal: Not a git repository: ../../../.git/modules/vendor/source/igraph
    0.8.0-pre+
    + aclocal
    bootstrap.sh: 21: bootstrap.sh: aclocal: not found
    + /usr/bin/libtoolize --force --copy
    libtoolize: putting auxiliary files in '.'.
    libtoolize: copying file './ltmain.sh'
    libtoolize: putting macros in 'm4'.
    libtoolize: copying file 'm4/libtool.m4'
    libtoolize: copying file 'm4/ltoptions.m4'
    libtoolize: copying file 'm4/ltsugar.m4'
    libtoolize: copying file 'm4/ltversion.m4'
    libtoolize: copying file 'm4/lt~obsolete.m4'
    libtoolize: Remember to add 'LT_INIT' to configure.ac.
    libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
    libtoolize: and rerunning libtoolize and aclocal.
    + autoheader
    bootstrap.sh: 23: bootstrap.sh: autoheader: not found
    + automake --add-missing --copy
    bootstrap.sh: 24: bootstrap.sh: automake: not found
    + autoconf
    bootstrap.sh: 25: bootstrap.sh: autoconf: not found
    + patch -N -p0 -r-
    + true
    Configuring igraph...
    sh: 0: Can't open /tmp/pip-build-yzawam/python-igraph/vendor/source/igraph/configure
    Could not compile the C core of igraph.
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yzawam/python-igraph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lzvVSe-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-yzawam/python-igraph/

`

**Comment by ntamas** [comment]
This is normal; you need a bunch of developer tools to compile igraph from source code if you are using an old OS or Python distribution that does not support precompiled Python wheels. Install `autoconf`, `automake` and `libxml2-dev` as a starter, and then try again.

**Comment by amosleeday** [comment]
thanks, it worked.

**Comment by mehditlili** [comment]
@ntamas the installation is just broken. The readme clearly refers to pip install python-igraph as "install" and not compilation. Can you suggest an alternative on how to install it otherwise?

Here is where it fails

```
  make[1]: Entering directory '/tmp/pip-build-7alziV/python-igraph/vendor/build/igraph'
  Making all in src
  make[2]: Entering directory '/tmp/pip-build-7alziV/python-igraph/vendor/build/igraph/src'
    YACC     foreign-ncol-parser.c
  byacc: e - line 74 of "/tmp/pip-build-7alziV/python-igraph/vendor/build/igraph/src/../../../source/igraph/src/foreign-ncol-parser.y", syntax error
  %output="y.tab.c"
  ^
  Makefile:9045: recipe for target 'foreign-ncol-parser.c' failed
  make[2]: *** [foreign-ncol-parser.c] Error 1
  make[2]: Leaving directory '/tmp/pip-build-7alziV/python-igraph/vendor/build/igraph/src'
  Makefile:497: recipe for target 'all-recursive' failed
  make[1]: *** [all-recursive] Error 1
  make[1]: Leaving directory '/tmp/pip-build-7alziV/python-igraph/vendor/build/igraph'
  Makefile:404: recipe for target 'all' failed
  make: *** [all] Error 2
  Could not compile the C core of igraph.
  
  
  ----------------------------------------
  Failed building wheel for python-igraph

```
