### ISSUE TITLE
Small typo in installation instructions

### ISSUE THREAD

**Issue by caleb-lindgren** [igraph/python-igraph#296]
I think there's a type in the instructions for installing igraph via Conda. Both [here](https://igraph.org/python/doc/tutorial/install.html#installing-igraph-via-conda) and [here](https://github.com/igraph/python-igraph/blob/master/doc/source/install.rst#installing-igraph-via-conda) the command it givies is `$ conda install -c conda-forge python-graph`. However, I believe the package name should have 'i' prepended to 'graph'--`python-igraph` instead of `python-graph`. This is what is shown on [the Anaconda page](https://anaconda.org/conda-forge/python-igraph).

**Comment by ntamas** [comment]
Thanks a lot, it is now fixed in b6b8d6d

The homepage will also be updated in a few minutes.
