### ISSUE TITLE
Document supported versions of Python in readme

### ISSUE THREAD

**Issue by miparnisari** [igraph/python-igraph#300]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Please add a line in the readme specifying what versions of Python are supported. According to [this](https://travis-ci.org/github/igraph/python-igraph/builds/694198411), it's been tested on 2.7, 3.5, 3.6, 3.7, 3.8.

**Comment by ntamas** [comment]
Thanks for the suggestion! Added a paragraph in the README about the policy that we follow; we always aim to support all non-EOL branches of Python 3.x. Python 2.x is still supported in `python-igraph` 0.8.x but Python 2 support will be dropped in 0.9.
