### ISSUE TITLE
Long node labels collide in tree layout

### ISSUE THREAD

**Issue by stelmath** [igraph/python-igraph#302]
Hello there,

I am using the `tree` layout to plot a pretty big taxonomy and my node labels are quite long strings. Is there a way to keep the hierarchy but space out nodes so that labels do not collide and become illegible? Example of issue: 
![error](https://user-images.githubusercontent.com/38814495/84284397-cc2f5000-ab44-11ea-89a2-6affd9693bff.png)

**Comment by iosonofabio** [comment]
I've used this before:

https://github.com/Phlya/adjustText

So we could add that to the docs and adapt our code a little. Please provide example code that makes the tree so I can play and see how to fix this.

**Comment by vtraag** [comment]
Actually, avoiding text overlaps is quite a general problem in network graphs. It would be great if some automatic method could be introduced into igraph. A somewhat related problem is overlapping nodes.

A simple one-off solution to this particular problem may be to simple rotate the graph 90 degrees and let the hierarchy grow to the side.

**Comment by ntamas** [comment]
> Actually, avoiding text overlaps is quite a general problem in network graphs. It would be great if some automatic method could be introduced into igraph. A somewhat related problem is overlapping nodes.

I fear that graph drawing is a topic that is complicated enough on its own and I'm not sure that we can deal with all the complexities given the limited manpower that we have for this project. The key problem to drawing nice layouts in igraph is that the layout phase (i.e. all the `igraph_layout_...()` functions in the C core) are concerned with infinitely small points and no labels at all - none of the layout methods are aware of the fact that nodes typically have a finite size and that labels also have to be accomodated somehow.

**Comment by szhorvat** [comment]
It looks like your graph is a directed tree. GraphViz produces excellent layouts for small trees. [igraph can export to GraphViz's format.](https://igraph.org/python/doc/igraph.GraphBase-class.html#write_dot)

**Comment by iosonofabio** [comment]
Let's close this one. It's a general problem and in no way specific to our python interface. We might possibly do something like adjustText or GraphViz in the future, but it's probably a Summer Of Code on its own since it depends on fontsize and -width, alignment, etc. etc.
