### ISSUE TITLE
Hub and Authority scores for large matrices

### ISSUE THREAD

**Issue by ForumWhiner** [igraph/python-igraph#306]
The Hub and authority scores computed by igraph for large matrices is different from the result from HITS algorithm. In fact, the scores from networkx and HITS are the same but igraph gives different results. Perhaps it has to do with multiplicity of eigenvalues or the way inverse is computed. I think this is an issue that needs to be addressed. 

Please follow [this link](https://stackoverflow.com/questions/62536368/hub-and-authority-scores-networkx-vs-igraph) for a detailed description.

**Comment by szhorvat** [comment]
Can you give a minimal reproducible example? The links post does not include one.

**Comment by ForumWhiner** [comment]
I will post an example shortly. I am trying to locate the source code but unfortunately it is not easy to find. I see the module igraph_authority_score() [here](https://github.com/igraph/igraph/blob/master/src/centrality.c) at line 910 but I can't find the code where computation is done. Any help is appreciated.

**Comment by szhorvat** [comment]
Please simply post a complete, reproducible example that illustrates the difference. Attach a graph, along with igraph's result as well as the result you believe to be correct. Indicate what igraph version you used and where you obtained it from (PyPI, some Linux distro's package repository, MacPorts/Homebrew, etc.)

igraph uses ARPACK to find the leading eigenvectors.

----

BTW hub and authority scores are simply eigenvectors. You can always verify if an eigenvector is correct by multiplying it with the associated matrix. Furthermore, the leading eigenvalue may be degenerate in which case there will be more than one correct solution.

**Comment by szhorvat** [comment]
I identified an issue where igraph may return a non-matching pair of hub and authority scores. Note that neither vector is *incorrect*. They are simply non-matching.

https://github.com/igraph/igraph/issues/1424

**Comment by szhorvat** [comment]
@ForumWhiner Did you manage to create a small reproducible example?
