### ISSUE TITLE
community_spinglass with negative weights gives error in pyhton

### ISSUE THREAD

**Issue by ejjordan** [igraph/python-igraph#31]
I had previously posted this on the main igraph issue list but it is still not working for me so I thought I would post here, since its a python issue. Basically if you try to call `spinglass=graph.community_spinglass(weights=graph.es['weight'])` where some of the weights are negative, you will get the following error if you try to then call `spinglass.modularity`

``` python
InternalError: Error at community.c:900: negative weight in weight vector, Invalid value
```

I am no C programmer, but after a little digging, I think I might have a solution. I just don't know how to implement it. The program community.c (the one which throws the error), has a function to calculate the modularity which cannot tolerate negative weights. In this case, it may be better to catch the return value (which in this case is a pointer to the modularity) of the call to `igraph_i_community_spinglass_negative` in clustertool.cpp and not allow the `recalculate_modularity` python functionality to work. It might even be possible to regain this functionality by wrapping the `PottsModel::calculate_Q()` call in pottsmodel_2.cpp in the python layer. Let me know if this makes sense or if you have any advice on how to do this. Thanks!

**Comment by ntamas** [comment]
Sorry for the delay, I've been swamped with other things lately. I'll try to take a closer look at this again soon.

**Comment by ejjordan** [comment]
And I am sorry for being pushy. I don't mean to try to rush you, I just didn't know if you read comments on closed issues. Let me know if you have any insights on how I can help.

**Comment by ntamas** [comment]
Okay, I have just tried it now with the patch I proposed in https://github.com/igraph/igraph/issues/825, and it works for me with the following code:

```
from igraph import Graph

g = Graph.GRG(100, 0.25)
g.es["weight"] = [-x for x in range(g.ecount())]
sp = g.community_spinglass(weights=g.es["weight"], implementation="neg")
print sp.modularity
```

The code above prints `None` for me instead of throwing an exception - this was my original intention as I still need to read the original paper about the extension of the Potts model for negative weights to check whether the modularity definition used there could be used safely here. Does the above code throw an exception for you after applying the patch?

**Comment by ejjordan** [comment]
Your fix does indeed work. Thanks for figuring that out. I think I may have a temporary/partial solution to the issue of calculating modularity for the Potts model with negative weights. If my understanding of the model is correct, the way it works is more or less just computing modularity for a W_ij for both the set of edges with positive weights and again for the set of edges with negative weights. There are other wrinkles like the parameter lambda which controls the relative importance of positive or negative links and of course there is the resolution parameter gamma, but I think the following modification is one way to get the modularity without actually having to get into the inner workings of the c code (which I am unqualified to do).

```python
def community_spinglass(self, *args, **kwds):
        membership = GraphBase.community_spinglass(self, *args, **kwds)
        if "weights" in kwds:
            if 'implementation' not in kwds:
                modularity_params=dict(weights=kwds["weights"])
            else:
                implementation=kwds["implementation"]
                if implementation=='neg':
                    pos_graph=self
                    for i in pos_graph.es:
                        if i['weight']<0:
                            i['weight']=0
                    modularity_params=dict(weights=pos_graph.es['weight'])
                    pos_cluster=VertexClustering(pos_graph, membership, modularity_params=modularity_params)
                    neg_graph=self
                    for i in neg_graph.es:
                        if i['weight']>0:
                            i['weight']=0
                        else:
                            i['weight']=-i['weight']
                    modularity_params=dict(weights=neg_graph.es['weight'])
                    neg_cluster=VertexClustering(neg_graph, membership, modularity_params=modularity_params)
                    return pos_cluster, neg_cluster, VertexClustering(self, membership, modularity_params=modularity_params)
        else:
            modularity_params={}
        return VertexClustering(self, membership,
                modularity_params=modularity_params)
```

This is not a stable solution as it has different return values based on whether the ```implementation='neg'``` or not, but at least it allows modularity to be calculated in this case. Let me know if this makes sense.
