### ISSUE TITLE
Canonical labels for colored graph

### ISSUE THREAD

**Issue by avcopan** [igraph/python-igraph#311]
I want to resurrect Issue #27 because it appears that the original reason for dismissing it was that the C layer does not take coloring into account. From what I can tell in the C documentation, it appears that [this is no longer true](https://igraph.org/c/doc/igraph-Isomorphism.html#igraph_canonical_permutation), and so I imagine this should be a simple feature to add in the python layer. This is something that would be very useful to a project I am working on.

Make sure that these boxes are checked before submitting your issue -- thank you!

- [X ] This issue is for the Python interface of igraph.
- [X ] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
It look like you are in luck: `canonical_permutation()` already supports a `color` argument, it was simply not documented properly. Can you please try it and confirm that it indeed works for your use-case?

**Comment by avcopan** [comment]
I see. I'm actually running version 0.8.2 from conda-forge, so I will need to try building the code from source in order to try out the current version. Thank you so much for your prompt response! Is there any possibility of adding in an edge_color argument at some stage?

**Comment by ntamas** [comment]
The `color` argument is already supported in 0.8.2, judging from the [source code](https://github.com/igraph/python-igraph/blob/0.8.2/src/_igraph/graphobject.c#L8268), so you shouldn't need to build it from source - just try the conda-forge version.

> Is there any possibility of adding in an edge_color argument at some stage?

I can add it to the Python interface only if the C core gains support for such an argument. Please file a feature request in the [repo of the C core](https://github.com/igraph/igraph/issues).

**Comment by szhorvat** [comment]
> Is there any possibility of adding in an edge_color argument at some stage?

The underlying library, Bliss, does not support this directly.

If you have no self-loops, and only want to test isomorphisms, it may be possible to hack something together: subdivide each edge and assign the edge colour to the subdividing vertex. Be sure to use non-conflicting colours for normal vertices and subdividing vertices.

**Comment by avcopan** [comment]
@ntamas Okay I figured it out, thank you. I am running version 0.8.2 now and can verify that the code works with the color argument. Here is an example:

```
>>> import igraph
>>> gra = igraph.Graph([(0, 1), (0, 2), (0, 3), (0, 4)])
>>> gra.canonical_permutation()
[4, 3, 2, 1, 0]
>>> gra.canonical_permutation(color=[1, 2, 2, 2, 3])
[0, 3, 2, 1, 4]
```

@szhorvat Thank you for the advice. I actually want a proper graph canonicalization for other purposes, but I think that we may be able to hack our own internal canonicalization through some combination of this function and the one for generating automorphisms -- I'll have to think about it.

**Comment by avcopan** [comment]
Thank you for all of your help!

**Comment by szhorvat** [comment]
> I actually want a proper graph canonicalization for other purposes

Can you clarify what you want to do with it?



> may be able to hack our own internal canonicalization through some combination of this function and the one for generating automorphisms -- I'll have to think about it.

If you can come up with a working prototype using existing functionality, consider sharing it. It could form the basis of a future implementation in the C core of igraph.

**Comment by ntamas** [comment]
Closing this as the original issue is resolved; feel free to continue the discussion nevertheless (or move it to the [Discourse group](https://igraph.discourse.group) if you want to.

**Comment by avcopan** [comment]
Thanks @ntamas 

In reply to your questions, @szhorvat 

> > I actually want a proper graph canonicalization for other purposes
> 
> Can you clarify what you want to do with it?

I am involved in a project, one component of which requires storing chemical information in a file system. We have been using the InChI canonicalization algorithm thus far, which relies on graph canonicalization to determine a unique chemical identifier. However, we have found that the InChI code fails for several of our use cases (it doesn't handle radical species well, and we are dealing with combustion chemistry) and we need to go beyond it in any case. For example, we need a unique and canonical way to identify different transition states connecting the same reactants and products in a chemical reaction. To do that, we need a canonical permutation of the chemical graphs involved so that we can identify which bonds are broken and formed in one transition state versus another.

The reason for needing vertex and edge coloring is that the canonicalization must consider information about the atom type and whether or not the atom or bond is a stereo center -- so not all atoms and bonds can be considered interchangeable.

The relevant codes are the following:

https://github.com/Auto-Mech/autofile
https://github.com/Auto-Mech/automol

Any suggestions you have would be welcome!

> > may be able to hack our own internal canonicalization through some combination of this function and the one for generating automorphisms -- I'll have to think about it.
> 
> If you can come up with a working prototype using existing functionality, consider sharing it. It could form the basis of a future implementation in the C core of igraph.

Will do! Thanks!
