### ISSUE TITLE
Update tutorial.rst to stop using deprecated syntax for Graph.degree

### ISSUE THREAD

**Issue by chrisfalter** [igraph/python-igraph#312]
- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Summary:** Update Graph.degree argument from deprecated syntax.

Was:
`g.degree(type='in')` and `g.degree(type='out')`

Becomes:
`g.degree(mode='in')` and `g.degree(mode='out')`

Note: I am submitting a pull request that fixes this issue.

**Comment by ntamas** [comment]
Merged, thanks!
