### ISSUE TITLE
import of igraph causes numpy to crash

### ISSUE THREAD

**Issue by RocketRider** [igraph/python-igraph#318]
Python 3.7.8
igraph 0.8.2
numpy 1.19.1
stable-baselines 2.10.0
tensorflow-gpu 1.15.3
Windows 10 Enterprise 2004

I try to use igraph in an reinforment learning project.
But as soon as I import igraph tensorflow does not work anymore.

Error:

> Traceback (most recent call last):
>   File "D:/test/testim/test.py", line 15, in <module>
>     model = A2C(CustomPolicy, 'CartPole-v1', verbose=1)
>   File "D:\test\venv_3_7_64\lib\site-packages\stable_baselines\a2c\a2c.py", line 105, in __init__
>     self.setup_model()
>   File "D:\test\venv_3_7_64\lib\site-packages\stable_baselines\a2c\a2c.py", line 136, in setup_model
>     n_batch_step, reuse=False, **self.policy_kwargs)
>   File "D:/test/testim/test.py", line 13, in __init__
>     feature_extraction="mlp")
>   File "D:\test\venv_3_7_64\lib\site-packages\stable_baselines\common\policies.py", line 561, in __init__
>     pi_latent, vf_latent = mlp_extractor(tf.layers.flatten(self.processed_obs), net_arch, act_fun)
>   File "D:\test\venv_3_7_64\lib\site-packages\stable_baselines\common\policies.py", line 83, in mlp_extractor
>     latent_policy = act_fun(linear(latent_policy, "pi_fc{}".format(idx), pi_layer_size, init_scale=np.sqrt(2)))
>   File "D:\test\venv_3_7_64\lib\site-packages\stable_baselines\common\tf_layers.py", line 123, in linear
>     weight = tf.get_variable("w", [n_input, n_hidden], initializer=ortho_init(init_scale))
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 1500, in get_variable
>     aggregation=aggregation)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 1243, in get_variable
>     aggregation=aggregation)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 567, in get_variable
>     aggregation=aggregation)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 519, in _true_getter
>     aggregation=aggregation)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 933, in _get_single_variable
>     aggregation=aggregation)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variables.py", line 258, in __call__
>     return cls._variable_v1_call(*args, **kwargs)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variables.py", line 219, in _variable_v1_call
>     shape=shape)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variables.py", line 197, in <lambda>
>     previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 2519, in default_variable_creator
>     shape=shape)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variables.py", line 262, in __call__
>     return super(VariableMetaclass, cls).__call__(*args, **kwargs)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variables.py", line 1688, in __init__
>     shape=shape)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variables.py", line 1818, in _init_from_args
>     initial_value(), name="initial_value", dtype=dtype)
>   File "D:\test\venv_3_7_64\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 905, in <lambda>
>     partition_info=partition_info)
>   File "D:\test\venv_3_7_64\lib\site-packages\stable_baselines\common\tf_layers.py", line 37, in _ortho_init
>     u, _, v = np.linalg.svd(gaussian_noise, full_matrices=False)
>   File "<__array_function__ internals>", line 6, in svd
>   File "D:\test\venv_3_7_64\lib\site-packages\numpy\linalg\linalg.py", line 1661, in svd
>     u, s, vh = gufunc(a, signature=signature, extobj=extobj)
>   File "D:\test\venv_3_7_64\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
>     raise LinAlgError("SVD did not converge")
> numpy.linalg.LinAlgError: SVD did not converge
> 
> Process finished with exit code 1
> 

Code to reproduce the issue:
```
import gym

from stable_baselines.common.policies import FeedForwardPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import A2C

#Import igraph to make it crash:
import igraph

# Custom MLP policy of three layers of size 128 each
class CustomPolicy(FeedForwardPolicy):
    def __init__(self, *args, **kwargs):
        super(CustomPolicy, self).__init__(*args, **kwargs,
                                           net_arch=[dict(pi=[128, 128, 128], vf=[128, 128, 128])],
                                           feature_extraction="mlp")

model = A2C(CustomPolicy, 'CartPole-v1', verbose=1)
# Train the agent
model.learn(total_timesteps=100000)

```

**Comment by RocketRider** [comment]
Just a node to others who encounter this:
I created a own process for the igraph with a multiprocessing pool. That is the only way I get both running at the moment.

**Comment by ntamas** [comment]
Unfortunatelz I could not get the complex tensorflow+numpy+igraph setup to work on two of my machines (one running macOS, another one running Linux) so I cannot confirm this yet. What I can see is that the error happens when trying to calculate the SVD of some matrix with Gaussian noise. I have no idea how this could be related to simply _importing_ igraph, but before we go further, can you please try the following>

# Open `D:\test\venv_3_7_64\lib\site-packages\stable_baselines\common\tf_layers.py`, and before line 37, add a step to save the matrix that the SVD is about to be performed on.
# Save the matrix _with_ and _without_ igraph being imported, and upload both to somewhere where I could download them -- I would like to check the differences between the two.

**Comment by ntamas** [comment]
Update: I managed to get it to run on Linux, but I did not manage to reproduce the crash, not even when importing `igraph`. It has been running for ~85000 timesteps so far. For how long I need to run the script to observe the crash?

**Comment by RocketRider** [comment]
Thank you for trying to reproduce it.
I forgot to mention that I am using Windows 10.
And you don't need to run it for long as it is crashing before it starts to train.

The gaussian_noise looks ok too me with and without igraph.


I can reproduce it just with numpy:
```
# Import igraph to make it crash:
import igraph

import numpy as np

np.random.seed(42)
gaussian_noise = np.random.normal(0.0, 1.0, (4, 128))
print(gaussian_noise)
u, _, v = np.linalg.svd(gaussian_noise, full_matrices=False)

```
The data is now 100% the same. They are both calling the "_umath_linalg.svd_m_s" with the same data.
But if the igraph is imported I get the execption "numpy.linalg.LinAlgError: SVD did not converge"

> Traceback (most recent call last):
>   File "D:/test/test.py", line 9, in <module>
>     u, _, v = np.linalg.svd(gaussian_noise, full_matrices=False)
>   File "<__array_function__ internals>", line 6, in svd
>   File "D:\test\venv_3_7_64\lib\site-packages\numpy\linalg\linalg.py", line 1661, in svd
>     u, s, vh = gufunc(a, signature=signature, extobj=extobj)
>   File "D:\test\venv_3_7_64\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
>     raise LinAlgError("SVD did not converge")
> numpy.linalg.LinAlgError: SVD did not converge

**Comment by RocketRider** [comment]
I am not sure if this is maybe connected to this numpy issue: https://github.com/numpy/numpy/issues/16744

**Comment by ntamas** [comment]
Thanks for the info. The fact that it only depends on NumPy and not the entire Tensorflow machinery makes it somewhat easier to debug this issue. On the other hand, the fact that it seems to be Windows 10 only makes it a bit harder as I don't have a Windows machine at hand :)

One thing that I could think of right now is that both NumPy and igraph includes a copy of LAPACK. NumPy needs it for the SVD calculations, while igraph needs it because it needs ARPACK for eigenvector calculations, and ARPACK is dependent on LAPACK. My conjecture is that NumPy somehow starts using igraph's LAPACK instead of its own -- maybe when NumPy is imported, it already detects that LAPACK is already in the address space of the process (from igraph)?

Can you try what happens if you reverse the order of imports (i.e. import `numpy` before `igraph`)?

In the meantime, I'll try to find a Windows machine somewhere :)

**Comment by bashtage** [comment]
This is 100% numpy/numpy#16744. The solution for now if you are on 2004 is to use Anaconda-provided NumPy or an another NumPy build that uses MKL.

**Comment by bashtage** [comment]
> Update: I managed to get it to run on Linux, but I did not manage to reproduce the crash, not even when importing `igraph`. It has been running for ~85000 timesteps so far. For how long I need to run the script to observe the crash?

It is Windows only and then only on 2004 or later (build 19041+). It does not appear on Windows 10 1909 (which was 18xxx).

**Comment by ntamas** [comment]
Thanks for the useful insight @bashtage. Do you have an explanation why it seems like `import igraph` is triggering the bug? @RocketRider reported that the exception is not thrown if he is not importing `igraph`.

**Comment by bashtage** [comment]
Without any explicit checking: tensorflow _might_ have its own SVD that it uses if something else hasn't already imported NumPy linalg.

**Comment by bashtage** [comment]
It may be the case that the order of import matters as well.

**Comment by RocketRider** [comment]
I have no idea why igraph is triggering it. But When I use the mkl version from anaconda it is running fine.
Still really strange. But thank you for looking into it.
