### ISSUE TITLE
`community_spinglass` returns "unconnected graph" error on connected input

### ISSUE THREAD

**Issue by remysucre** [igraph/python-igraph#322]
Running `community_spinglass` on the [LiveJournal community dataset](https://snap.stanford.edu/data/com-LiveJournal.html) gives the following error: 

`igraph._igraph.InternalError: Error at /project/vendor/source/igraph/src/clustertool.cpp:284: Cannot work with unconnected graph, Invalid value`

However I can verify the input graph is connected. 

Python code to replicate: 

```python
import igraph as ig

G = ig.Graph.Read_Edgelist("com-lj.ungraph.txt", directed=False);
parts = G.community_spinglass()
```

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by szhorvat** [comment]
`Read_Edgelist` assumes that vertices are labelled with consecutive integers starting with 0. Is this true  for your dataset? It appears to me that it is not. Assuming this property gives you many isolated (0-degree) vertices.

**Comment by remysucre** [comment]
That makes sense. For now I can first convert to GML with networkx and re-import with iGraph. It would be great if the function can take an optional argument that specifies one of the two behaviors (create 0-degree nodes or not). At least the current assumption should be documented (I couldn't find it in either the C or python manual).

**Comment by szhorvat** [comment]
The python-igraph documentation [says](https://igraph.org/python/doc/igraph.GraphBase-class.html#Read_Edgelist):

> Please note that the vertex indices are zero-based.

While the description could be expanded, I think this makes it pretty clear that vertices are consecutive integers starting at 0.

**Comment by ntamas** [comment]
You can also use `Read_Ncol`. The limitation that the vertices are indexed from zero and that vertex IDs must form a continuous range comes from the underlying C library and there's nothing we can do about that in the Python interface. `Read_Ncol` works around this by creating a vertex attribute named `name` that contains the original numeric ID that was found in the input file, cast into a string.

**Comment by szhorvat** [comment]
I clarified the documentation a bit on the C side: https://github.com/igraph/igraph/commit/6df74ee241da60796a43396110edabe10c129bb7

**Comment by remysucre** [comment]
@ntamas that would work great for me. @szhorvat I made a PR #323 for the python doc expanding it.
