### ISSUE TITLE
Confusing documentation for VertexClustering.giant()

### ISSUE THREAD

**Issue by remysucre** [igraph/python-igraph#324]
`Graph.clusters()` returns a `VertexClustering` object which should be the connected components, but `VertexClustering.giant()` is said to return a community in the doc. The source of `giant` does not seem to involve community detection, so is it actually just returning the largest connected component?

**Comment by ntamas** [comment]
Thanks, I'll fix this somehow. `VertexClustering` is used to represent the result of a decomposition of a graph into connected components as well as the result of a community detection, and I have forgotten about the first use-case when I wrote the documentation for `giant()`.
