### ISSUE TITLE
Port igraph_bridges function to Python

### ISSUE THREAD

**Issue by alezok** [igraph/python-igraph#328]
Could anyone port to Python the `igraph_bridges` function (with the ability of handling multi-graphs) that is already present in the C igraph repository?

**Comment by szhorvat** [comment]
@ntamas This is a rather simple function. Perhaps it would be good to take the opportunity to write up a short guide on how to integrate existing C core functions into the Python interface? Hopefully then people will be more willing to contribute in the future.

**Comment by iosonofabio** [comment]
I could help doing this one, both the specific function and writing the guide.

Any opinion as of where such a guide could land? Possibilities:

- igraph.org
- wiki of this repo

**Comment by iosonofabio** [comment]
@alezok do you have any bandwidth to help with this or is this a zero-effort request?

Not trying to be confrontational, just thinking of the best way to approach this as we are all busy people.

**Comment by alezok** [comment]
I slightly modified the code provided for simple graphs in https://www.geeksforgeeks.org/bridge-in-a-graph/ (also referenced in the https://github.com/igraph/igraph/issues/1180) and it seems to work, but I don't know understand how to make it work for multi-graphs (possibly useful https://github.com/igraph/igraph/pull/1335). Bandwidth close to zero, but the my main problem is that being not proficient in Python nor familiar with github, it would take me ages to understand how to write a well optimized function in good pythonic code that leverages well all the classes/functions already existing in igraph.

**Comment by iosonofabio** [comment]
Alright thank you, let's see what @ntamas thinks and I can try and have a look in my spare time

**Comment by szhorvat** [comment]
`igraph_bridges` fully supports multigraphs, and requires no changes.

**Comment by ntamas** [comment]
I'll take care of the implementation today; it look like we basically need to copy `igraphmodule_Graph_articulation_points()` only and add some test cases.

**Comment by iosonofabio** [comment]
Awesome thank you!

**Comment by ntamas** [comment]
As for documenting the addition of new functions from the C core to the Python interface: the current process is quite involved as you need to be familiar not only with the internals of the igraph C core (which are complicated enough) but also with the intricacies of writing extensions to Python in C (including all the reference counting magic and whatnot). It takes a lot of time to document all that and maybe it wouldn't incentivize newcomers to contribute at all once they realize how complicated the process could be.

The long-term solution would probably be to "generate" a low-level glue layer between Python and the C core of igraph using SWIG or some other mechanism (maybe `ctypes`?), and then build a better, more "pythonic" interface on top of the low-level glue layer, in pure Python. In retrospect, I don't really like the current API either as it basically puts everything as a method on the top-level Graph object, making its API surface enormously large. It would be an interesting experimental project to build a new Python API for igraph with a lightweight Graph object and lots of standalone functions built around it. But this is probably not the right place to discuss it; we should do it in the Discourse group instead.

**Comment by iosonofabio** [comment]
YES! 😊
