### ISSUE TITLE
igraph doc vanished

### ISSUE THREAD

**Issue by UzLA** [igraph/python-igraph#33]
iGraph Python tutorial at http://igraph.org/python/doc/tutorial/tutorial.html references ("In the meanwhile, check out the full API documentation which should provide information about almost every igraph class, function or method. A good starting point is the documentation of the Graph class.") to http://igraph.org/doc/python/, which renders 404 error from Gator hoster.

The whole http://igraph.org/doc/ does not exist. Is it possible to fix with the links to correct urls on pyton page at http://igraph.org/python/doc/tutorial/tutorial.html or restore documentations in http://igraph.org/doc/ ?

**Comment by gaborcsardi** [comment]
Hi, some links are wrong, but the content is there imo. Go there from http://igraph.org/python/#docs

**Comment by ntamas** [comment]
@gaborcsardi I have fixed the links in https://github.com/igraph/python-igraph/commit/c5c5eb0239c52dc74cb1d74e4762d5f370e68a3f - how can I push it to the webpage?

**Comment by gaborcsardi** [comment]
Write the version number in https://github.com/igraph/igraph.org/blob/master/Makefile and then do `make Python`, AFAIR.

But as I look at it now, you can only specify proper versions. :( I'll update it "by hand" in a sec.

**Comment by gaborcsardi** [comment]
OK. Done. I clearly had no idea how to run a website back then. :(

**Comment by sara-02** [comment]
Hey, looks like https://igraph.org/doc/python/ and https://igraph.org/doc/python/igraph.Graph-class.html originating from the [Where to go next](https://igraph.org/python/doc/tutorial/tutorial.html#where-to-go-next) is giving 404 :confused:

**Comment by ntamas** [comment]
The links are fixed already in the source code of the Python tutorial; it's not deployed to the homepage yet.

**Comment by vtraag** [comment]
Ah, right, good!
