### ISSUE TITLE
installation issue, cannot read GraphML file

### ISSUE THREAD

**Issue by ZeZhouAalto** [igraph/python-igraph#330]
I want to install igraph module at anaconda 3,8 on Windows system. But GraphML support is disabled, I cannot read GraphML file. 
So I decided to compile igraph package following the instructions on how to compile from source on Windows(https://igraph.org/python/). Everything goes well until " Open the MSYS2 shell, enter this folder and run python setup.py build_c_core". After running the command, I got some errors which show “Could not compile the C core of igraph”. Hope you can help with this problem, thanks.

Here is the error:

zhouz@LAPTOP-R1C02RB1 MINGW64 ~
$ pacman --needed --noconfirm -Sy pacman-mirrors
:: 正在同步软件包数据库...
 mingw32 已经是最新版本
 mingw64 已经是最新版本
 msys 已经是最新版本
警告：pacman-mirrors-20200329-1 已经为最新 -- 跳过
 今日无事可做

zhouz@LAPTOP-R1C02RB1 MINGW64 ~
$ pacman --noconfirm -Sy
:: 正在同步软件包数据库...
 mingw32 已经是最新版本
 mingw64 已经是最新版本
 msys 已经是最新版本

zhouz@LAPTOP-R1C02RB1 MINGW64 ~
$ pacman --noconfirm -S autoconf automake bison flex \
>         libtool mingw-w64-x86_64-libtool zip \
>         mingw-w64-i686-libxml2 mingw-w64-x86_64-libxml2
警告：autoconf-2.69-5 已经为最新 -- 重新安装
警告：automake-wrapper-11-1 已经为最新 -- 重新安装
警告：bison-3.6.4-1 已经为最新 -- 重新安装
警告：flex-2.6.4-1 已经为最新 -- 重新安装
警告：libtool-2.4.6-9 已经为最新 -- 重新安装
警告：mingw-w64-x86_64-libtool-2.4.6-18 已经为最新 -- 重新安装
警告：zip-3.0-3 已经为最新 -- 重新安装
警告：mingw-w64-i686-libxml2-2.9.10-4 已经为最新 -- 重新安装
警告：mingw-w64-x86_64-libxml2-2.9.10-4 已经为最新 -- 重新安装
正在解析依赖关系...
正在查找软件包冲突...

软件包 (9) autoconf-2.69-5  automake-wrapper-11-1  bison-3.6.4-1  flex-2.6.4-1
           libtool-2.4.6-9  mingw-w64-i686-libxml2-2.9.10-4
           mingw-w64-x86_64-libtool-2.4.6-18  mingw-w64-x86_64-libxml2-2.9.10-4
           zip-3.0-3

全部安装大小：  34.10 MiB
净更新大小：   0.00 MiB

:: 进行安装吗？ [Y/n]
(9/9) 正在检查密钥环里的密钥                       [#####################] 100%
(9/9) 正在检查软件包完整性                         [#####################] 100%
(9/9) 正在加载软件包文件                           [#####################] 100%
(9/9) 正在检查文件冲突                             [#####################] 100%
(9/9) 正在检查可用存储空间                         [#####################] 100%
:: 正在处理软件包的变化...
(1/9) 正在重新安装 autoconf                        [#####################] 100%
(2/9) 正在重新安装 automake-wrapper                [#####################] 100%
(3/9) 正在重新安装 bison                           [#####################] 100%
(4/9) 正在重新安装 flex                            [#####################] 100%
(5/9) 正在重新安装 libtool                         [#####################] 100%
(6/9) 正在重新安装 mingw-w64-x86_64-libtool        [#####################] 100%
(7/9) 正在重新安装 zip                             [#####################] 100%
(8/9) 正在重新安装 mingw-w64-i686-libxml2          [#####################] 100%
(9/9) 正在重新安装 mingw-w64-x86_64-libxml2        [#####################] 100%
:: 正在运行事务后钩子函数...
(1/1) Updating the info directory file...

zhouz@LAPTOP-R1C02RB1 MINGW64 ~
$ cd E:/complex/pyPackage/dist/python-igraph-0.8.2

zhouz@LAPTOP-R1C02RB1 MINGW64 /e/complex/pyPackage/dist/python-igraph-0.8.2
$ python setup.py build_c_core
running build_c_core
configure: loading site script E:/Joe/mingw64/etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... no
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C++ preprocessor... g++ -E
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for bison... bison -y
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/times.h usability... no
checking sys/times.h presence... no
checking for sys/times.h... no
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
checking for as... as
checking for dlltool... dlltool
checking for objdump... objdump
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... c:/mingw_w64/i686-w64-mingw32/bin/ld.exe
checking if the linker (c:/mingw_w64/i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /c/MinGW_w64/bin/nm -B
checking the name lister (/c/MinGW_w64/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-w64-mingw32 file names to x86_64-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert x86_64-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for c:/mingw_w64/i686-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... (cached) objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... (cached) dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /c/MinGW_w64/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... no
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (c:/mingw_w64/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... c:/mingw_w64/i686-w64-mingw32/bin/ld.exe
checking if the linker (c:/mingw_w64/i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking whether the g++ linker (c:/mingw_w64/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (c:/mingw_w64/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking for stdint.h... (cached) yes
checking sys/int_types.h usability... no
checking sys/int_types.h presence... no
checking for sys/int_types.h... no
checking for expm1... yes
checking for rint... yes
checking for rintf... yes
checking for finite... yes
checking for log2... yes
checking for snprintf... yes
checking for log1p... yes
checking for round... yes
checking for fabsl... yes
checking for fmin... yes
checking for strcasecmp... yes
checking for isnan... yes
checking for strdup... yes
checking for _strdup... yes
checking for ftruncate... yes
checking for stpcpy... no
checking whether isfinite is declared... yes
checking whether stpcpy is declared... no
checking whether compiler supports -ffloat-store... yes
checking whether compiler supports -fstore... no
checking whether compiler accepts -Wall... yes
checking for xml2-config... /mingw64/bin/xml2-config
/E/complex/pyPackage/dist/python-igraph-0.8.2/vendor/source/igraph/configure: line 17485: sw_vers: command not found
checking for xmlSAXUserParseFile in -lxml2... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking for __gmpz_add in -lgmp... yes
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating tests/Makefile
config.status: creating tests/atlocal
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating igraph.pc
config.status: creating igraph_Info.plist
config.status: creating doc/Makefile
config.status: creating include/igraph_version.h
config.status: creating include/igraph_threading.h
config.status: creating config.h
config.status: executing tests/atconfig commands
config.status: executing depfiles commands
config.status: error: in `/e/complex/pyPackage/dist/python-igraph-0.8.2/vendor/build/igraph':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
We are going to build the C core of igraph.
  Source folder: vendor\source\igraph
  Build folder: vendor\build\igraph
  Install folder: vendor\install\igraph

Configuring igraph...
Could not compile the C core of igraph.

**Comment by vtraag** [comment]
I am closing this issue in favour of discussing the issue at our discussion forum, where you also [posted](https://igraph.discourse.group/t/windows-installation-issue/437) the issue. Better to keep the discussion in one place. Moteover, this issue tracker is meant for reporting bugs.

**Comment by vtraag** [comment]
For anyone coming across this issue for the GraphML support, please see https://github.com/igraph/python-igraph/issues/342.
