### ISSUE TITLE
Wrong behaviour of adding two graphs

### ISSUE THREAD

**Issue by topl0305** [igraph/python-igraph#333]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [X] This issue is for the Python interface of igraph.
- [X] This issue is a bug report or a feature request, not a support question.

Lets say I create empty graph and then I want to add a lot of smaller graphs created with vertices' names. After adding graph with names they will be lost! That defies logic of having unique names for vertices and overall - attributes. Not tested, but maybe all attributes are lost. 

import igraph
g = igraph.Graph(directed=True)
g_help = igraph.Graph.TupleList([["A", "B"], ["A", "C"], ["C", "D"], ["C", "E"]], directed=True)
g += g_help
print(g_help.vertex_attributes()) #output -> ['name']
print(g.vertex_attributes())          #output -> []

Version of igraph 0.8.2

**Comment by ntamas** [comment]
Most of the graph operators did not handle attributes, not even in version 0.8.2. We have recently merged a pull request into `master` that adds support for attributes for union and intersection. Excerpt from the terminal:

```
>>> import igraph
>>> g = igraph.Graph(directed=True)
>>> g_help = igraph.Graph.TupleList([["A", "B"], ["A", "C"], ["C", "D"], ["C", "E"]], directed=True)
>>> g += g_help
>>> print(g_help.vertex_attributes())
['name']
>>> print(g.vertex_attributes())
['name']
>>> g.vs["name"]
['A', 'B', 'C', 'D', 'E']
```

A new version with this feature is due in a few days at most, so stay tuned. If you really need this feature, you can install `python-igraph` directly from Github with `pip` -- this will install the most recent revision:

```
pip install git+https://github.com/igraph/python-igraph.git
```
