### ISSUE TITLE
python equivalent for head_of and tail_of

### ISSUE THREAD

**Issue by bayesfactor** [igraph/python-igraph#335]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x ] This issue is for the Python interface of igraph.
- [x ] This issue is a bug report or a feature request, not a support question.

The R igraph package has very handy `head_of` and `tail_of` functions to find edges of a directed graph. I cannot find equivalents in python-igraph. It would be very nice to have a way to find the ends of a graph. When I try to do it myself via recursion, for larger graphs, I hit the limit of python recursion:

    RecursionError: maximum recursion depth exceeded while calling a Python object

Thank you!

**Comment by iosonofabio** [comment]
I'd be happy to take this one if that's ok for everyone else

**Comment by vtraag** [comment]
I believe this is actually already possible in Python using `G.es.select(_source=i)` or `G.es.select(_target=i)`. See https://igraph.org/python/doc/igraph.EdgeSeq-class.html#select. @bayesfactor , does this do what you want? If so, we can close this issue.

**Comment by iosonofabio** [comment]
I'd be happy to try and add a function to mimick the R API if you think that's useful. That way people migrating from R would have an easier time

**Comment by vtraag** [comment]
> I'd be happy to try and add a function to mimick the R API if you think that's useful.

I think the R API is quite bit different because there are typically no functions on objects. This is how many things are implemented in Python. Both languages have their own structures and idiosyncrasies, and I think it makes sense that the interfaces reflect that.

**Comment by ntamas** [comment]
I don't think it's worth mimicking the R API -- `g.es[i].source` and `g.es[i].target` gives you the tail and the head of the `i`-th edge, it is a different syntax but it is more natural in Python than the functional form (`head_of()` and `tail_of()`). We can maybe add `head` and `tail` as aliases here if that is more natural in English than `source` and `target`.

**Comment by szhorvat** [comment]
I always get confused by "head" and "tail", probably because of the expression "head to tail" which is the opposite of how a directed edge would go. I think source/target are less ambiguous. But of course it's subjective to some extent.

**Comment by szhorvat** [comment]
Sinks/sources are easy to find: they are vertices with zero out- and in-degree, respectively. No recursion is needed, no graph traversal is needed.

**Comment by iosonofabio** [comment]
True, so I'm confused about the original question then.
