### ISSUE TITLE
Text shows up as boxes

### ISSUE THREAD

**Issue by shardulc** [igraph/python-igraph#339]
When I run the following:
```
import igraph
igraph.drawing.text.test()
```
I get [this](https://user-images.githubusercontent.com/10349624/98434196-665adc00-2082-11eb-9e24-3fe87069bc57.png). Note that the text is displayed as boxes, except for the punctuation which appears as normal. I discovered this issue when trying to draw a graph with vertex labels which had the same issue.

**Version information**
 * python-igraph 0.8.3
 * cairocffi 1.0.2
 * Python 3.7
 * standard Ubuntu 18.04

Have not previously experienced any font issues. Maybe this is connected to the fact that cairocffi [only implements Cairo's "toy font" API](https://cairocffi.readthedocs.io/en/stable/api.html#fonts-text)? I have not tried installing pycairo to test this yet because it would require me to install many other dependencies.

**Comment by ntamas** [comment]
It is definitely not the fault of `cairocffi` -- I just tried the same thing on my computer and it worked perfectly. The only difference between your setup and mine is that I'm on macOS 10.15.

I suspect that there's something wrong with `cairocffi` itself; can you try assembling a short test script that uses `cairocffi` only to draw text, and run that?

**Comment by shardulc** [comment]
I installed pycairo and ran into the same issue. I tried running this script:
```python

import cairo
# import cairocffi as cairo

surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 300, 200)
context = cairo.Context(surface)

context.set_source_rgb(1, 1, 1)
context.paint()

context.set_source_rgb(0, 0, 0)
context.move_to(90, 140)
context.set_font_size(20)
context.show_text('Hi from cairo!')
surface.write_to_png('example.png')
```

This also gives the same issue, regardless of which cairo package is imported. Strangely, nobody else on the Internet seems to be having this problem with cairo and fonts! So while this isn't an issue with igraph, I would appreciate any insight :)

**Comment by vtraag** [comment]
The problem might be with the actual C Cairo library. How did you install the C library, and which version is that?

**Comment by shardulc** [comment]
@vtraag Cairo was installed using `apt` as usual (on Ubuntu). Packages `libcairo2` and `libcairo2-dev` are at version 1.15.10 (the latest available according to apt). I haven't had font issues before, but then again, I don't know if I've used a purely Cairo-based application before either.

**Comment by ntamas** [comment]
@shardulc Can you try selecting a font face explicitly in your toy example with `context.select_font_face(...)` -- I think it should accept installed font names as the first argument as well as the generic `"sans-serif"`, `"serif"`, `"cursive"`, `"fantasy"` and `"monospace"` aliases. Do you get the same boxes no matter which font you select? (Documentation for `select_font_face` is [here](https://pycairo.readthedocs.io/en/latest/reference/context.html#cairo.Context.select_font_face) ).

Note that Cairo also delegates the text drawing to an underlying OS-level library such as `freetype`, `pango`, `fontconfig` or something else), so it might even be the case that the issue is not with Cairo but one more level deeper in the rabbit hole.

**Comment by shardulc** [comment]
That worked! The generics "sans-serif", "cursive", and "fantasy" do not work (i.e. produce boxes). The generic "serif" produces text in a font that I can't quickly identify, but it works. Providing an actual font face name works as intended.

If possible, I'd like to submit a PR that lets an igraph user choose what font labels are displayed in. Any nuances I should be aware of before I do so? Thanks for all your help.

**Comment by ntamas** [comment]
@iosonofabio is working on improving the tutorial page and the documentation now (and I am deeply grateful for that), so this will be added soon. Thanks for the suggestion!
