### ISSUE TITLE
Graph.Read_GraphML()   ERROR

### ISSUE THREAD

**Issue by godjb** [igraph/python-igraph#342]
g = Graph.Read_GraphML("test_graphml.graphml")
NotImplementedError: Error at c:\projects\python-igraph-jst2e\vendor\build\igraph\igraph-0.8.3-msvc\src\foreign-graphml.c:1446: GraphML support is disabled, Unimplemented function call

**Comment by vtraag** [comment]
Please note that GraphML support is not enabled on Windows at the moment. We are working on a new build system for the igraph C core. Once that is done, we should be able to properly support GraphML on Windows as well.

**Comment by vtraag** [comment]
GraphML is now supported on Windows in `python-igraph` 0.9.1 using the binary wheels from PyPI. In other words, you should be able to simply install `pip install python-igraph` and get GraphML support.

**Comment by vtraag** [comment]
In addition, GraphML is also supported in builds from the `conda-forge` channel from `python-igraph` 0.9.1 onwards.
