### ISSUE TITLE
create  a python_igraph-0.8.3-cp35-cp35mu-manylinux2010_x86_64.whl version

### ISSUE THREAD

**Issue by shiyi-pan** [igraph/python-igraph#345]
Hi, I want to install python_igraph from the source code but faild . I figured that I need to install the automake ,autoconf and libxml2 first . So I installed the automake and autoconf . But when I installed the libxml2, I met the following error:

types.c: In function 'libxml_PyFileGet':
types.c:34: warning: implicit declaration of function '_PyVerify_fd'
types.c:34: warning: nested extern declaration of '_PyVerify_fd'
types.c: In function 'libxml_xmlXPathObjectPtrConvert':
types.c:639: warning: pointer targets in passing argument 2 of 'PyUnicode_AsUTF8AndSize' differ in signedness
/ds3512/home/panyp/ruanjian/python36/include/python3.6m/unicodeobject.h:1144: note: expected 'Py_ssize_t *' but argument is of type 'size_t *'
types.c:640: warning: pointer targets in passing argument 1 of 'xmlStrndup' differ in signedness
../include/libxml/xmlstring.h:43: note: expected 'const xmlChar *' but argument is of type 'const char *'
  CCLD   libxml2mod.la
/usr/bin/ld: /ds3512/home/panyp/ruanjian/python36/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/ds3512/home/panyp/ruanjian/python36/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[4]: *** [libxml2mod.la] Error 1
make[4]: Leaving directory `/ds3512/home/panyp/NN1138-2/05.sv_detection/04.syri_data/libxml2-2.9.1/python'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/ds3512/home/panyp/NN1138-2/05.sv_detection/04.syri_data/libxml2-2.9.1/python'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/ds3512/home/panyp/NN1138-2/05.sv_detection/04.syri_data/libxml2-2.9.1/python'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/ds3512/home/panyp/NN1138-2/05.sv_detection/04.syri_data/libxml2-2.9.1'
make: *** [all] Error 2

This is beyond my ability. I wander if it is convenient for you to provide a wheel file of cp35-cp35mu-manylinux2010_x86_64.whl version . It will help me a lot . Thank you very much.

**Comment by vtraag** [comment]
Python 3.5 has reached end-of-life on  September 5, 2020. We therefore dropped support. The easiest is simply to upgrade to Python 3.6 or up. Is there any reason why you are unable to upgrade?

**Comment by ntamas** [comment]
Also, these compiler errors seem to have nothing to do with Igraph; for me it looks like they are related to libxml2. We cannot provide support for compiling libxml2 from source.
