### ISSUE TITLE
Issue with plotting in Jupyter

### ISSUE THREAD

**Issue by kushasareen** [igraph/python-igraph#346]
I've installed python-igraph, cairo, py2cairo, and cairocffi on my Windows 10 machine. I installed them through pip and also tried through the unoffical binaries on Christoph Gohlke's website (https://www.lfd.uci.edu/~gohlke/pythonlibs/). I'm able to import and use cairo in my notebook and don't have it installed on multiple versions of Python (I've checked). I read through another post on here and also installed 2 other dependencies that were previously not included (I can't find what they were called anymore),

Unfortunately, I still get the common error:

<code>
c:\python37\lib\site-packages\igraph\drawing\__init__.py in plot(obj, target, bbox, *args, **kwds)
    453     if not isinstance(bbox, BoundingBox):
    454         bbox = BoundingBox(bbox)
--> 455 
    456     result = Plot(target, bbox, background=kwds.get("background", "white"))
    457 

c:\python37\lib\site-packages\igraph\drawing\__init__.py in __init__(self, target, bbox, palette, background)
    118           is understood by L{igraph.drawing.colors.color_name_to_rgba}.
    119         """
--> 120         self._filename = None
    121         self._surface_was_created = not isinstance(target, cairo.Surface)
    122         self._need_tmpfile = False

c:\python37\lib\site-packages\igraph\drawing\utils.py in __getattr__(self, _)
    394 
    395     def __getattr__(self, _):
--> 396         raise TypeError("plotting not available")
    397     def __call__(self, _):
    398         raise TypeError("plotting not available")

TypeError: plotting not available

</code>

**Comment by iosonofabio** [comment]
Hi @kushasareen 

I'm working on a plotting function that just works with plain matplotlib independent of backend. Hope to have it in a development branch in a week or two for you to try.

**Comment by kushasareen** [comment]
Thanks! Just as an update, re-installation using conda fixed the issue and I was able to get it to plot using python from the command line. Plotting in the notebook still doesn't work (no error message but also no plot). It seems to me that this is cairo/cairocffi issue but I'm not going to bother trying to fix the installation.

**Comment by iosonofabio** [comment]
Great. We also support plotting with matplotlib now if you pass in a `pyplot.Axes` so that should fix these kind of issues.
