### ISSUE TITLE
Graph constructor from scipy.sparse adjacency matrix

### ISSUE THREAD

**Issue by iosonofabio** [igraph/python-igraph#357]
**What is the feature or improvement you would like to see?**
Large, sparse graphs are often represented using `scipy.sparse` adjacency matrices. Currently `igraph.Graph.Adjacency` expects a list of lists, it would be great to teach it to load the standard scipy matrix formats.

Even a single format (e.g. COO) would be great, because one can (somewhat expensively) convert between formats in `scipy` anyway.

**Use cases for the feature**
Large, sparse graphs:

```python
adj = scipy.sparse.coo_matrix([[0, 1], [1, 0]])

# Goal
g = igraph.Graph.Adjacency(adj)

# Current
adj_list_of_lists = [list(x) for x in adj.todense()]  # <-- this can be expensive!
g = igraph.Graph.Adjacency(adj_list_of_lists)
```

**Draft implementation**
Scipy sparse matrices contain the nonzero entries in some attribute (e.g. `adj.data`). We could make an empty graph with the right number of vertices (`adj.shape[0]`) and then fill in only the edges we need, with the right weights if the matrix is not bool.

```python
if isinstance(mat, scipy.sparse.spmatrix):
    mat = mat.tocoo()
    edges = list(zip(mat.row, mat.col))  # <- this stays sparse
    g = igraph.Graph(mat.shape[0], edges)
    if mat.dtype != bool:
        g.es['weights'] = list(mat.data)   # <- also sparse
    return g
```

**References**

https://docs.scipy.org/doc/scipy/reference/sparse.html

**PS:** I'd be happy to add this in a PR.

**Comment by ntamas** [comment]
This would be a great addition. There are two things to watch out for:

1. Currently `Graph.Adjacency` is implemented in the C glue code. You need to override it in the Python layer and use `super()` to fall back to the original implementation if you did _not_ receive a SciPy sparse matrix.

2. When testing for `scipy.sparse.spmatrix` with `isinstance()`, you need to import `scipy.sparse.spmatrix` lazily and handle `ImportError` exceptions gracefully so we don't introduce a hard dependency on SciPy.

**Comment by iosonofabio** [comment]
Good point and yes - that's the plan. I'll write a PR then! Thx

**Comment by ntamas** [comment]
I had to fix a few corner cases in the tests (the number of vertices must be taken explicitly from the size of the input matrix in case we have all-zero rows or cols at the end, and the `min` case had to be treated in a special manner because all items that are missing from the sparse matrix are implicitly zeros, which affects the outcome of `min()`). I think it's okay now -- take a look at my recent commits in `master` if you are interested in the things I had to change.

**Comment by ntamas** [comment]
The relevant commit is https://github.com/igraph/python-igraph/commit/ddc53b66c03cdf0ced19836addfa81fc045c1aab

**Comment by iosonofabio** [comment]
Thank you, yes I hadn't covered those.

Cheers,
Fabio
