### ISSUE TITLE
Avoid dependency on bison & flex.

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#361]
At the moment, the `python-igraph` source tarball release requires `bison` and `flex`. This is a bit strange compared to `igraph` source tarball releases, for which `bison` and `flex` are not required. Preferably, we should ensure that a `python-igraph` source tarball does not require `bison` and `flex` either. 

The new upcoming CMake build system might make it a bit easier to do this. Perhaps one way of doing this is by first calling `CMake --build . --target dist` to generate the source distribution that can be compiled (using `CMake --build [dist_dir] --target igraph`), and only include that source code in the `python-igraph` source tarball. Hence, if `python-igraph` would be built from GitHub, it would first run `CMake --build . --target dist`, but if it is run from a source tarball release, it can simply skip that step because the source distribution is already available.

**Comment by ntamas** [comment]
I think this is now solved in https://github.com/igraph/python-igraph/commit/f4ddb0086c66324f0e3ea93c16aa2d5d0c355634
