### ISSUE TITLE
Add python wrapper for the new harmonic centrality functions

### ISSUE THREAD

**Issue by Silmathoron** [igraph/python-igraph#362]
Harmonic centrality has been implemented at the C level (see [this thread](https://igraph.discourse.group/t/user-defined-distance-for-unconnected-node-in-closeness-and-harmonic-centrality/183/11)) and will be part of the next release so it would be nice if the associated wrapper could be included in the python release.
You can ping me if you need reviewers.

**Comment by iosonofabio** [comment]
Hi @Silmathoron, fellow Tuebingen dweller, I did my PhD at the MPI for Dev Bio next door!

I've make a PR #364 

Cheers,
Fabio

**Comment by Silmathoron** [comment]
Hi there and thanks for the PR :)
I'd love to help with the review but I'm afraid I'm unable to install this branch with the `develop` branch of igraph... I get a bunch of errors about ``igraph_harmonic_centrality`` (incompatible types for arguments 3 and 5 and too many arguments)...

**Comment by iosonofabio** [comment]
Don't worry too much, we are in the middle of releasing an API-breaking update on the C core of igraph, so it'll take a few days to sort this one out. We'll get it tested on CI and once that works you can clone the master branch and test it yourself.

**Comment by ntamas** [comment]
#364 is merged into master now.
