### ISSUE TITLE
Bug with g.vs.find() function

### ISSUE THREAD

**Issue by matrixfang** [igraph/python-igraph#367]
**Describe the bug**
Can't find the name of vertex if the name is int.

**To reproduce**

```
g = igraph.Graph()  
g.add_vertices([1,2,5])  
print(g.vs.find(name =5).index)
```

the result should be 2, but I can only get 0. If replace the int name with char, the expected results can be obtained.
 
**Version information**
Which version of `python-igraph` are you using and where did you obtain it?
I'm using python-igraph-0.8.3 with python3.7.3 on mac

**Comment by ntamas** [comment]
Should be fixed now. `python-igraph` 0.9 is expected in a few days (after igraph 0.9) so I won't make a patch release for it now; it will be in 0.9
