### ISSUE TITLE
hash(graph) is not deterministic

### ISSUE THREAD

**Issue by JanSchulz** [igraph/python-igraph#37]
The following seems to result in different hashes each time I restart the interpreter and, much more importantly, all three prints result in the same hash, although they clearly represent different graphs:

``` python
import igraph
mygraph = {"A" : {"B" : 2, "C" : 4}, "B" : {"A" : 2}, "C" : {"A" : 4}, "D":{}}
g = igraph.Graph(directed=False)
print(hash(g))
g.add_vertices(mygraph.keys())
print(hash(g))
edges = [(start, end) for start in mygraph.keys() for end in mygraph[start].keys()]
edges = [edge for edge in edges if edge[0] > edge[1]]
g.add_edges(edges)
print(hash(g)) 
```

[Prints out three times the same hash, but the hash changes between interpreter runs and sometimes also between executions]

IMO: if igraph can't/won't do deterministic hashes based on edges/vertices and their properties, then `__hash__()` should raise a `TypeError`. Note: `pandas.DataFrames` does error out the same way as lists.

I was just bitten by this as I implemented a caching decorator based on hashed inputs to a function and when I used a graph as input sometimes it used the cached values and sometimes recomputed the values (which takes 15min...).

**Comment by ntamas** [comment]
Good catch; I have left the hash function unimplemented intentionally and assumed that in such cases the object remains unhashable. It turns out that there is a default hashing mechanism built into Python, and the default hash of `x` is derived from `id(x)`. I'll add a hashing function that throws a `TypeError` instead.
