### ISSUE TITLE
Plotting VertexClustering fails when targeting matplotlib

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#370]
**Describe the bug**
Ordinarily, one could plot a `VertexClustering`, for example using

```python
G = ig.Graph.Famous('Zachary')
comms = G.community_leiden('modularity')
ig.plot(comms)
```
![image](https://user-images.githubusercontent.com/6057804/109939568-7c477900-7cd1-11eb-9e0c-1f2a971d1794.png)

However, when doing `ig.plot(comms, target=ax)`, where `ax` is a `matplotlib` `Axes`, this throws the error
`AttributeError: 'VertexClustering' object has no attribute 'layout'`.

**To reproduce**
```python
import igraph as ig
import matplotlib.pyplot as plt
G = ig.Graph.Famous('Zachary')
comms = G.community_leiden('modularity')
fig, ax = plt.subplots()
ig.plot(comms, target=ax)
```

**Version information**
`python-igraph` version 0.9.0, linked against external shared `igraph` library version 0.9.0-135-g4019b1f29.

**Comment by vtraag** [comment]
@iosonofabio, presumably there is simply no support yet for this functionality. I am not sure how difficult it is to include this, but it would be nice to have. Alternatively, if this is really complicated, it would be nice to raise an error that this functionality is not (yet) supported.

**Comment by iosonofabio** [comment]
Sure, I'll take care of it! Let me have a look and I'll get back to you

**Comment by iosonofabio** [comment]
![graph_clustering_test](https://user-images.githubusercontent.com/1200640/110049134-5a1f2b00-7da5-11eb-8bcf-c46aa5f1dd95.png)

That's how it looks here, with default parameters. Colors can be set manually from outside on a per-vertex basis, or default to equally spaced "viridis" otherwise.

@vtraag is this good enough or shall I add some more things since I'm at it?

**Comment by vtraag** [comment]
Looks great, thanks! I was thinking that maybe the option `mark_groups` would be nice to implement, but I now see this is broken also in the default plotting, at least when passing in a `VertexClustering` object. I will open another issue for that.

**Comment by iosonofabio** [comment]
How would you like the groups marked?

**Comment by vtraag** [comment]
The [`mark_groups` option](https://igraph.org/python/doc/igraph.Graph-class.html#__plot__) draws a (convex) polygon around the nodes in the same community. I opened an issue for the `mark_groups` problem in https://github.com/igraph/python-igraph/issues/372.

**Comment by iosonofabio** [comment]
I understand roughly. A naive version is easy to implement, could do it right now:

- find the convex hull
- add a matplotlib patch with the right color

Or do you want like a 5% "expansion" to make it more pretty?

The color means solid face color of the whole polygon (probably with some 30% opacity?) or a transparent-filled polygon with colored border?

**Comment by iosonofabio** [comment]
Here the options:

1. face color and border, no expansion

![graph_clustering_test4](https://user-images.githubusercontent.com/1200640/110091591-b8bbc780-7dec-11eb-9897-26a58575d342.png)

2. face color and border, 15% expansion

![graph_clustering_test3](https://user-images.githubusercontent.com/1200640/110091588-b8233100-7dec-11eb-81f2-fab475b0ab16.png)

3. just border, 15% expansion

![graph_clustering_test2](https://user-images.githubusercontent.com/1200640/110091580-b6f20400-7dec-11eb-80f5-861d74e96fdd.png)

**Comment by vtraag** [comment]
Nice! Personally, I think option 2 looks best...

**Comment by iosonofabio** [comment]
Alright, going for option 2 plus now it understands the `mark_groups` option (in theory). I'll write tests and it should be done

**Comment by ntamas** [comment]
@vtraag This will be merged into master in a few minutes; can you test a bit to see if it meets your expectations?

**Comment by vtraag** [comment]
Yep, looks good to me! Thanks @iosonofabio!
