### ISSUE TITLE
mark_groups in plotting is failing

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#372]
**Describe the bug**
Plotting a graph with the `mark_groups` option fails with the error `NameError: name 'long' is not defined`.

**To reproduce**
```python
import igraph as ig
G = ig.Graph.Famous('Zachary')
comms = G.community_leiden('modularity')
ig.plot(comms, mark_groups=comms)
```

The same problem also appears when using
```python
ig.plot(comms, mark_groups=[(c, i) for c, i in enumerate(comms)])
```

**Version information**
`python-igraph` version 0.9.0.

**Comment by ntamas** [comment]
This is probably a leftover from Python 2.x; `long` used to be a separate type there but there is no such type any more in Python 3.x. I'll take care of this.
