### ISSUE TITLE
Self-loops are distorted with matplotlib backend

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#394]
**Describe the bug**
The self-loops are distorted, i.e. stretched in one direction with the matplotlib backend. I would expect the self-loop to look the same in any plot that has been set to use an aspect ratio compatible with the plot range ("axes equal").

**To reproduce**
```
import matplotlib.pyplot as plt

g = ig.Graph.Formula('0-1-2-3-4-5-0,0-3,3-3,1-6,2-7-8-9-10-11-12-13-14-15',simplify=False)

fig, ax = plt.subplots()
ax.set_aspect('equal', 'box')
ig.plot(
    g,
    target=ax,
    vertex_size=8, edge_alpha=0.3,
)

plt.show()
```

![image](https://user-images.githubusercontent.com/1212871/119014602-6bd1a100-b998-11eb-970d-1af892c79d6b.png)

This is horizontally compressed.

Compare with the following, which is not:

```
g = ig.Graph.Formula('0-1-2-3-4-5-0,0-3,3-3,1-6,2-7',simplify=False)
```

![image](https://user-images.githubusercontent.com/1212871/119014719-8ad03300-b998-11eb-8f7f-4b9af12c0c32.png)

Notice that the vertices are always perfect circles, regardless of the aspect ratio of the plot frame. Ideally, the self-loops would behave the same. If they don't, they should look proportional when the aspect ratio follow the plot range.

**Version information**
0.9.1

**Comment by iosonofabio** [comment]
See the other bug about loops, I'm closing this one.

Basically this can be fixed but doing so properly takes a decent amount of restructuring, so I'd be happy to do it if we agree that mpl is the future as opposed to a class B obscure option.

**Comment by szhorvat** [comment]
> See the other bug about loops

Is there another issue on the same topic? If yes, can you please link to it directly?

Whether this is truly a bug, and whether we currently have the resources to fix it are two orthogonal questions. I do not thikn that a lack of resources to fix it justifies closing it.

**Comment by ntamas** [comment]
> Is there another issue on the same topic?

I think he meant #393, which you filed just before this one :)

Reopening this as it is something that should be fixed eventually, even if we don't have the resources for it right now.
