### ISSUE TITLE
Unclear error when ig.Graph.Read() given bad file path

### ISSUE THREAD

**Issue by nickeubank** [igraph/python-igraph#40]
In python 3.4, when one uses ```ig.Read.Graph('file', format='pickle')``` and passes a bad file name (with a typo or something), the error is very hard to understand -- the error is:
    
    TypeError: 'str' does not support the buffer interface"

The error occurs at line ~1801 of __init__.py at the line ```result = pickle.loads(fname)```

I've offered one solution in PR #41

**Comment by ntamas** [comment]
#41 is merged now so I'll close this.
