### ISSUE TITLE
vertex_label_angle has no affect on plot

### ISSUE THREAD

**Issue by Teculos** [igraph/python-igraph#411]
It appears that rotation of vertex labels doesn't work.

Here's an minimal example of the issue:

```
import igraph as ig
import numpy as np

Graph = ig.Graph()
Graph.add_vertex("root")

Graph.add_vertex("node1")
Graph.add_vertex("node2")
Graph.add_vertex("node11")
Graph.add_vertex("node12")

Graph.add_edge("root", "node1")
Graph.add_edge("root", "node2")
Graph.add_edge("node1", "node11")
Graph.add_edge("node1", "node12")

visual_style = {}
visual_style["vertex_label"] = Graph.get_vertex_dataframe()["name"]
visual_style["vertex_label_size"] = 20
visual_style["vertex_size"] = 30
visual_style["vertex_color"] = "blue"

visual_style["vertex_label_angle"] = -45 * (np.pi / 180) #angle is in radians

ig.plot(Graph, **visual_style)
```

Other attributes like color, node size, and label size can be changed but vertex_label_angle doesn't seem to have any affect. 

I'm using python 3.7.4 on ubuntu 18.04.5 with igraph version 0.9.1

**Comment by ntamas** [comment]
You also need to set `vertex_label_dist` to a nonzero value. `vertex_label_dist` and `vertex_label_angle` work together like a polar coordinate system; `dist` specifies the distance to offset the label from the center of the node (1 equals the radius of the node, 1.2 usually gives nice results) while `angle` specifies the direction.

**Comment by yjgeno** [comment]
Hi, wondering if any argument can actually rotate the text on the graph?
