### ISSUE TITLE
New 0.9.5 igraph doesn't work with drawing module

### ISSUE THREAD

**Issue by dschult** [igraph/python-igraph#415]
The NetworkX examples page threw an error upon release of igraph 0.9.5 with the following report.
It looks like the new feature `mark_groups=True` listed in the igraph Changelog for this release breaks
drawing.py line 1114. 

On that line, kwds["mark_groups"] is assumed to return a dict, but now can return a bool.

```
Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/circleci/repo/examples/external/plot_igraph.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/repo/examples/external/plot_igraph.py", line 39, in <module>
    ig.plot(h, layout=layout, target=ax1)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 480, in plot
    result.draw(obj, *args, **kwds)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/igraph/drawing/graph.py", line 1114, in draw
    for idx, color in kwds["mark_groups"].items():
AttributeError: 'bool' object has no attribute 'items'
```

**Comment by ntamas** [comment]
I think that the commit referenced above should do the trick; can you test it quickly in CI or shall I just make another release and hope for the best?

**Comment by iosonofabio** [comment]
Sorry for reopening, but I have a question about the commit. Let me have a quick look

**Comment by ntamas** [comment]
Sure, it was auto-closed by Github when I mentioned "fixes #415" in the commit message.

**Comment by iosonofabio** [comment]
My bad, yes this is a bug that came out of a last minute decision of mine as of default states. Reclosing, we should probably make a new release if that's not too much hassle.

**Comment by ntamas** [comment]
I can make a release tomorrow (well, today, but after my next sleep cycle :)) if @dschult can confirm that the fix works for them as well.

**Comment by dschult** [comment]
I can confirm that the fix works for NetworkX.
Thanks for the speedy response. :}

**Comment by ntamas** [comment]
Okay, thanks for the feedback. 0.9.6 is now on PyPI so you can revert to using that.
