### ISSUE TITLE
Dendogram to cluster does not allow n=2

### ISSUE THREAD

**Issue by danski3456** [igraph/python-igraph#416]
**Describe the bug**

Converting a dendogram to a cluster while specifiying the number of clusters fails.

**To reproduce**
```python
!wget "https://gist.githubusercontent.com/gus0k/aeaf2cd06a6d57e2b50e933eee05a464/raw/6315088901e9f6927907eca842c0dcee1b6621e7/political.graphml"
g_political = ig.Graph.Read_GraphML("political.graphml")
fastgreedy = g_political.as_undirected().community_fastgreedy()
fastgreedy.as_clustering(n=2)
```

If you are confident that the issue is not in the Python interface but in the
C core of igraph, please add it to the main [igraph repo](https://github.com/igraph/igraph)
instead.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
Which version of `python-igraph` are you using and where did you obtain it?

**Comment by szhorvat** [comment]
This is not a bug. Your graph is not connected. It has 268 connected components. It is not possible to ask for fewer clusters than the number of components.
