### ISSUE TITLE
igraph crashes when drawing an edge between two vertices with objects for names

### ISSUE THREAD

**Issue by MrMorden81** [igraph/python-igraph#42]
I'm using igraph 0.7.1 with Python 3.4 under Windows 7, and the following code crashes:

    import igraph

    class Person:
        def __init__(self, name):
            self.name = name

    alice = Person('Alice')
    bob = Person('Bob')
    g = igraph.Graph()
    g.add_vertex(alice)
    g.add_vertex(bob)
    print(g.vs[0]['name'] == alice)
    print(g.vs[1]['name'] == bob)
    g.add_edge(alice, bob)
The output is as follows:

    True
    True
    File "C:\Python34\lib\site-packages\igraph\__init__.py", line 237, in add_edge
    return self.add_edges([(source, target)])
    File "C:\Python34\lib\site-packages\igraph\__init__.py", line 255, in add_edges
    return GraphBase.add_edges(self, es)
    TypeError: only numbers, vertex names or igraph.Vertex objects can be converted to vertex IDs

It seems that this code should work, as both alice and bob are vertex names in this case.  Is this a bug?

**Comment by ntamas** [comment]
This is an issue with the error message, not with igraph itself. The Python interface only allows strings as vertex names. What the error message *means* is that whenever a vertex ID is needed (as in `Graph.add_edges` for instance), igraph only knows how to handle numbers (just convert it to an integer), Vertex objects (just use its `index` property) or *strings* (look up the string in the `name` vertex property of the graph). I'll fix the wording of the exception.

**Comment by MrMorden81** [comment]
Thank you for the clarification.

**Comment by ivan-marroquin** [comment]
Hi @ntamas 

Thanks for the clarification. However, the error message still persist in its original format:
GraphBase.__init__(self, nverts, edges, directed)
TypeError: only numbers, strings or igraph.Vertex objects can be converted to vertex IDs

I am using igraph 0.9.4, to replicate the error message:

# make a csr_matrix
sources, targets= csr_matrix.nonzero()
edgelist= list(zip(sources, targets))

g= ig.Graph(n= data.shape[0], edges= edgelist, edge_attrs= {'weight': csr_matrix.data.to_list())

Kind regards,
Ivan

**Comment by ivan-marroquin** [comment]
I forgot this command line:

edgelist= np.asarray(edgelist, dtype= np.float32) # the type is the mistake, it should be np.int32

**Comment by ntamas** [comment]
I've modified the error message a bit to make it it clear that node IDs must be integers (floats are not okay, even if they are integral). See the commit referenced above.

**Comment by ivan-marroquin** [comment]
Thanks!
