### ISSUE TITLE
Align Graph.DataFrame with the Rest of DataFrame API

### ISSUE THREAD

**Issue by fwitter** [igraph/python-igraph#420]
The class method `Graph.DataFrame` should by default align with the rest of the DataFrame API, i.e. `Graph.get_edge_dataframe` and `Graph.get_vertex_dataframe`. An alignment would allow using `g_clone = Graph.DataFrame(g.get_edge_dataframe(), g.is_directed(), g.get_vertex_dataframe())` to clone a graph `g`.

This requires changing the default parameter value of `use_vids` to `True` in `Graph.DataFrame`.

**Comment by ntamas** [comment]
#421 will solve this; I'll close the issue when #421 is merged.
