### ISSUE TITLE
`ig.union` when `a_name` not in `a_conflict` due to `graph_union` not having `pop` method

### ISSUE THREAD

**Issue by sztal** [igraph/python-igraph#422]
**Describe the bug**

As in the title. One conditional branch in the source code cannot be executed because it expects a `graph_union` object, which is of class `igraph.Graph`, to behave like a standard Python `dict` or `set` and have `pop` method defined.

This happens in lines `181-185` in the `operators.py` module.

```
    181             if a_name not in a_conflict:
    182                 # New conflict
    183                 a_conflict.add(a_name)
    184                 igf = a_first_graph[a_name]
--> 185                 graph_union["{:}_{:}".format(a_name, igf)] = graph_union.pop(a_name)
```

**To reproduce**

I cannot reproduce without sharing some data which I would prefer not to share. However, it is obvious that this is a bug just from reading the source code. The code expects `graph_union` to be a `dict` or `set` and define a name-based `pop` method.

**Version information**

Python igraph 0.9.6.

**Comment by iosonofabio** [comment]
Please provide an example with some data that is not private. If it's obvious from the code, making up a simple example should be easy as well and it makes my life a lot easier, thank you
