### ISSUE TITLE
How does community_spinglass work exactly?

### ISSUE THREAD

**Issue by davdavsen** [igraph/python-igraph#43]
I want to use community_spinglass for my research, but I cannot figure out exactly what it does. I read the reference "Statistical Mechanics of Community Detection", which states that they use simulated annealing, but not exactly how. So I would like to know what update rules are used for the simulated annealing: How are the nodes moved between communities in each time step?

**Comment by ntamas** [comment]
Please refer to the source code of the spinglass clustering.

* Main entry point: https://github.com/igraph/igraph/blob/master/src/clustertool.cpp
* The simulated annealing process of the Potts model is implemented in: https://github.com/igraph/igraph/blob/master/src/pottsmodel_2.cpp
* In particular, the update function starts from this line: https://github.com/igraph/igraph/blob/master/src/pottsmodel_2.cpp#L1802
