### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [igraph/python-igraph#431]
Problem
---------
On aarch64, ‘pip install python-igraph’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, ‘pip install python-igraph’ should download the wheels from PyPI.

@ntamas, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by ntamas** [comment]
Thanks a lot! I have no objections against merging this if the CI tests run successfully in #432.

**Comment by vtraag** [comment]
As an alternative, until binary wheels for `aarch64` become available, you can install `aarch64` packages from the `conda-forge` channel in `conda`, i.e. `conda install -c conda-forge python-igraph`.

**Comment by ntamas** [comment]
The PR has been merged so closing this.

**Comment by odidev** [comment]
@ntamas, can you please let me know if when AArch64 wheels are targeted for release?

**Comment by ntamas** [comment]
There was a recent bugfix in the C core regarding Gomory-Hu trees that I would like to get included in the Python interface as well. So, there will be a new release of the C core this week, in the next few days, and shortly after that a Python patch release will also follow, also in this week. At least that's the plan.
