### ISSUE TITLE
Construct graph from adjacency list

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#433]
**What is the feature or improvement you would like to see?**

A function to construct a graph from its adjacency list.

It should work with general vertex names (e.g. a mapping from vertex names to their neighbours as a Python dictionary), not just vertex IDs.

**Use cases for the feature**

The adjacency list is probably the most used graph representation when implementing various graph algorithms. igraph should have full support for it.

**References**

 - Request for the feature here: https://igraph.discourse.group/t/does-igraph-accept-json-format-and-why-are-nodes-represented-as-numbers/840
 - networkx has multiple such functions: https://networkx.org/documentation/stable/reference/convert.html
 - IGraph/M has it as well, and I use it regularly

**Comment by iosonofabio** [comment]
I believe this has been implemented now, closing. Please reopen if incorrect.
