### ISSUE TITLE
`Read_Ncol` crashes when being passed a pandas dataframe

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#446]
**Describe the bug**
When a `pandas` dataframe is passed to `Graph.Read_Ncol` it crashes. Of course, a dataframe should not be passed to `Graph.Read_Ncol`, but this should not cause the Python session to crash, but should be correctly handled.

**To reproduce**
```python
import igraph as ig
import pandas as pd
df = pd.DataFrame({'from': [1, 2],
                   'to': [2, 3]})
g = ig.Graph.Read_Ncol(df)
```
**Version information**
This is using version 0.9.6 installed from `conda`.

**Comment by ntamas** [comment]
Can you please try it with the latest dev version? I cannot reproduce it with the dev version on my machine; nevertheless I have added a regression test for it so we can see it in the CI if this fails on some platform.

On my machine, I get an exception like this:

```
TypeError: argument must be an int, or have a fileno() method
```

**Comment by ntamas** [comment]
@vtraag Can you test now with the latest `master` to see if the problem is still there on your machine? (CI seems to pass now).
