### ISSUE TITLE
write_graphml rounds float values to 4 decimal digits

### ISSUE THREAD

**Issue by rajanski** [igraph/python-igraph#45]
node in gml_file:

node
  [
    id 822
    lat 52.5857663
    lon 13.4500575
    label "278215038"
  ]

same node in graphml_file (written after being read in though read_GML)

<node id="n822">
      <data key="v_lat">52.5858</data>
      <data key="v_lon">13.4501</data>
      <data key="v_id">822</data>
      <data key="v_name">None</data>
      <data key="v_label">278215038</data>
    </node>

**Comment by rajanski** [comment]
tried write_dot, this doesnt round the values..

**Comment by ntamas** [comment]
Cannot reproduce on my machne; tried with the following test program:

```
#!/usr/bin/env python

from igraph import Graph, load

g = Graph(1)
g.vs["lat"] = 52.5857663
g.vs["lon"] = 13.4500575
g.write_gml("test.gml")
g2=load("test.gml")
g2.write_graphml("test.graphml")
```

It works just fine for me. The GraphML writer uses `igraph_real_fprintf_precise` from `types.c` in the C layer to ensure that floating-point values are written with the highest possible precision. It could be the case that this function does not work correctly due to some platform-dependent behaviour, but then I would need to know which platform you are working with.

**Comment by rajanski** [comment]
Hi Tamas, I am on Ubuntu 14.04 LTS 64 bit

**Comment by ntamas** [comment]
Did you compile the Python interface of igraph on your own or did you install it from a `.deb` package (via the package manager)? If so, where did you get the package from and which version of the Python interface are you using? (Try printing `igraph.__version__` from Python).

**Comment by rajanski** [comment]
Hi, I installed igraph via pip. The interface version is 0.7.1

**Comment by ntamas** [comment]
I'll try to install it soon in a virtual machine and test it.

**Comment by ntamas** [comment]
Managed to confirm this in an Ubuntu 14.04 VM when installing igraph via `pip` without pre-installing the C core. Will investigate further.

**Comment by ntamas** [comment]
Okay, it turns out that this has been fixed already in the C core of igraph, but there was no new version released from the C core since the fix.

The commit in the source code of the C core is here: https://github.com/igraph/igraph/commit/fdcaa1475b01eeade4be10494d253524cac1c855 .

**Comment by ntamas** [comment]
Related issue: https://github.com/igraph/igraph/issues/796

**Comment by ntamas** [comment]
A workaround for the time being is to convert the floating-point attributes of your graph to strings before you save them, and then convert them back after loading. We'll have to wait until the next bugfix release of the C core to fix this properly.
