### ISSUE TITLE
Disjoint union should produce names that make it easy to refer to orginal vertices

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#455]
**What is the feature or improvement you would like to see?**

Disjoint union should produce vertex names which make it easy to identify where each vertex originally came from. I propose that the names in the result graphs should be of the form `(i, n)` where `i` is the index of the graph in the input list and `n` is the original name.

For example, if the input graphs had vertex names `a, b, c` and `c, d, e`, then the result graph should have vertex names `(1, a), (1, b), (1, c), (2, c), (2, d), (2, e)`.

I have this implemented in IGraph/M, and I find it very useful.

**Use cases for the feature**

It avoids name collisions. We should try to not create graphs with duplicate names, as it happens right now:

```
g1 = ig.Graph.Formula('a-b-c')
g2 = ig.Graph.Formula('x-y-c')
g = ig.disjoint_union([g1, g2])
g.vs['name']
```

```
['a', 'b', 'c', 'x', 'y', 'c']
```

It also makes it easy to take a vertex from the result graph, and determine where it came from: Which original graph did it come from? What name did it have there?

Here is an example application (an actual user request), which demonstrates usefulness in Mathematica: https://mathematica.stackexchange.com/q/257710/12 The task was to take `n` copies of a certain small graph, then join them together on the same vertex.

I'll repeat the construction here for completeness. Take this graph:

```
g = IGShorthand["a-b-c-a-d-c"]
```

<img width="206" alt="image" src="https://user-images.githubusercontent.com/1212871/140313614-4d3c8ca5-a4d0-4714-8120-25867825177b.png">

Make three copies and create a disjoint union:

```
bg = IGDisjointUnion[ConstantArray[g, 3], VertexLabels -> "Name"]
```

<img width="154" alt="image" src="https://user-images.githubusercontent.com/1212871/140313629-6c0483bc-2d36-42df-ae68-0f42e2403589.png">

It is now very easy to join the copied on "vertex `d`" as we know which these vertices are by name:

```
IGVertexContract[bg, {Cases[VertexList[bg], {_, "d"}]}, VertexLabels -> "Name"]
```

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1212871/140313745-2a416981-f80b-4703-9be7-f7b990c90fdf.png">

Without this information, we'd have to keep juggling vertex indices in error-prone ways.

**References**

None.

**Comment by iosonofabio** [comment]
Great point, happy to implement. Of course, until we have a plan the vertex names, I'd prefer to not use tuples. One option is underscore joining the original names, but my favourite is to add a vertex attribute called "origin_graph" (name could be a function arg) that tells you.

I wouldn't want to start using tuples if they have no overlap in vertex names, that is really unfriendly towards recursion...

**Comment by ntamas** [comment]
> I wouldn't want to start using tuples if they have no overlap in vertex names, that is really unfriendly towards recursion...

That's one side of the coin. The other side is that it is unfortunate if the _type_ of the new vertex attribute essentially depends on whether there is an overlap between the vertex names or not; if we do that, it means that as a user I wouldn't be able to figure out what the new name of vertex A from graph 1 is going to be unless I check for overlaps first. Always using tuples _or_ always using underscored-prefixed names is nice and predictable.

This issue also raises the question of consistency between the various higher level interfaces of igraph. For instance, right now the R interface does the same thing as the Python interface (okay, it also prints a warning if there are overlaps). However, I feel that maintaining consistency between higher level interfaces will become nearly impossible in the future anyway, at least when it comes to features that are _not_ part of the core C library and are up to the higher level interfaces to decide. So maybe it's not too big of a concern, but it's good if we can agree on letting consistency fall by the wayside.

Of course the real flexible solution would be a callback function that takes all the vertex names as arguments (one for each graph), and returns a new list that contains the proposed vertex names for the result :) One can then decide whether to use strings or tuples or the original names as is. String aliases could be provided for the common cases so people don't have to re-implement the same name callback functions over and over again.
