### ISSUE TITLE
"Graph object has no attribute 'community_leiden'" - did the new release get rid of this ?

### ISSUE THREAD

**Issue by h2kh** [igraph/python-igraph#456]
**Describe the bug**
It looks like community_leiden doesn't exist as a Graph method in the new release while the other ten clustering algorithms are still available.

**To reproduce**
g is a Graph
g.community_leiden() gives me the error message

Using igraph(0.9.8) and got it through pip install igraph

**Comment by ntamas** [comment]
Can you please post the full error message that you see? `community_leiden()` works just fine for me with a fresh install from `pip` using Python 3.9.7.

**Comment by h2kh** [comment]
You are correct. I don't have any issues while using igraph 0.9.8. 

I had forgotten to activate my virtual environment and ended up using python-igraph 0.7.1.post6 with the 'import igraph' command. It seems like there's no community_leiden method for the Graph object in that package. In any case, no further work needed on this non-issue.
