### ISSUE TITLE
returned adjacency matrix is not a csr_matrix

### ISSUE THREAD

**Issue by ivan-marroquin** [igraph/python-igraph#459]
**Describe the bug**
The command "get_adjacency_sparse" does not return a sparse matrix (i.e., csr_matrix) instead it returns an igraph matrix object. However the documentation mentions that a csr_matrix should be returned.

I am using python-igraph 0.9.4 with Python 3.6.5 on a windows machine.

**To reproduce**
import igraph as ig
from scipy.sparse import csr_matrix

g= ig.Graph.Tree(127, 2)

adj= g.get_adjacency()

type(adj) # produces an igraph.datatypes.Matrix

adj= csr_matrix(adj.data) # additional code to get a sparse matrix

If you are confident that the issue is not in the Python interface but in the
C core of igraph, please add it to the main [igraph repo](https://github.com/igraph/igraph)
instead.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
Which version of `python-igraph` are you using and where did you obtain it?
0.9.4

**Comment by GroteGnoom** [comment]
In you example you call `get_adjacency`, not `get_adjacency_sparse`. Is that the problem maybe?

**Comment by szhorvat** [comment]
Closing, since this seems to be due to a typo, as pointed out above. I just double checked that `get_adjacency_sparse` works as expected.

BTW I strongly suggest using the latest version, which is 0.9.8.

**Comment by ivan-marroquin** [comment]
Hi @GroteGnoom and @szhorvat 

thanks for the suggestion. i checked the reference manual (https://igraph.org/python/api/0.9.8/igraph._igraph.GraphBase.html) and couldn't find the function 'get_adjacency_sparse'. The documentation only mentions the function 'get_adjacency'

Ivan

**Comment by szhorvat** [comment]
It's in Graph, not GraphBase:

https://igraph.org/python/api/latest/igraph.Graph.html#get_adjacency_sparse

But you yourself mentioned the function above, so I assumed you knew about it:

> The command "get_adjacency_sparse" does not return a sparse matrix
