### ISSUE TITLE
write_gml throwing exception: iterable must yield numbers

### ISSUE THREAD

**Issue by rajanski** [igraph/python-igraph#46]
I am adding some vertices to a graph using ```g.add_vertex(name='bla')``` and afterwards the mentioned error comes upo when I try to write the graph to gml.

It does work if I remove the id attribute by  ```del g.vs['id'] ``` beforehand.

May it be that the ids of the added vertices are "None" or such?

**Comment by ntamas** [comment]
Yes, exactly; the `id` attribute has no special meaning for igraph so newly added vertices get an `id` attribute with value `None` if you have an `id` attribute for *other* vertices. However, the GML reader uses the `id` attribute by default to determine the IDs in the GML file, so if your IDs are not numeric, you must delete the attribute before you call `write_gml`, or pass the name of some other (nonexistent) vertex attribute to` write_gml`:

    g.write_gml("test.gml", ids="no-such-attribute")
