### ISSUE TITLE
Cannot set edge_curved parameter while plotting

### ISSUE THREAD

**Issue by Kasaneru** [igraph/python-igraph#461]
I am trying to set *edge_curved* parameter to 0 or False while plotting in order to get edges directed in both directions but get a *TypeError: 'int' object is not subscriptable* and graph without edges.

**Code**
```python
g = Graph(directed=True)
V = [*range(0, 5)]
E = [(0, 1), (0, 2), (0, 3),
     (1, 2), (2, 3), (3, 4),
     (4, 3)]
g.add_vertices(V)
g.add_edges(E)

fig, ax = plt.subplots()
style = {}
style['layout'] = g.layout("fr")
style['vertex_label'] = V
style['edge_curved'] = 0
plot(g, target=ax, **style)
```

**Traceback**
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-32-26594dce59bd> in <module>()
      4 style['vertex_label'] = V
      5 style['edge_curved'] = 0
----> 6 plot(g, target=ax, **style)

1 frames
/usr/local/lib/python3.7/dist-packages/igraph/drawing/graph.py in draw(self, graph, *args, **kwds)
   1312 
   1313             else:
-> 1314                 curved = ecurved[ie]
   1315                 if curved:
   1316                     aux1 = (2 * x1 + x2) / 3.0 - curved * 0.5 * (y2 - y1), (

TypeError: 'int' object is not subscriptable
```

**Version information**
Using Google Colab
igraph 0.9.8
matplotlib 3.2.2

**Comment by ntamas** [comment]
Thanks for the report! A workaround for the time being is to pass a list of values to `edge_curved`, i.e. as many entries as the number of edges that you have. I'll look into this later.

**Comment by ntamas** [comment]
It looks like the Matplotlib backend does not implement the flexible keyword argument handling that the Cairo backend does. The Cairo backend allows keyword arguments like `edge_curved` to be a single value (in which case it applies to all edges) or a list (in which case the i-th element applies to the i-th edge). This was achieved in the Cairo backend with the `VisualVertexBuilder` and `VisualEdgeBuilder` classes, which used some arcane metaclass magic; the behaviour was not ported over to the Matplotlib interface so it's all a bit mixed there as most of the edge attributes cannot be defined on a per-edge basis as a keyword argument, _except_ `edge_curved`, which _must_ be specified on a per-edge basis.

This definitely needs to be fixed for the next version, especially if we are phasing out the Cairo backend. I cannot promise anything about when it will be sorted out, but definitely before python-igraph 0.10.

**Comment by iosonofabio** [comment]
A lot of this is in the develop branch, but yes, happy to make a PR for the remainder

**Comment by ntamas** [comment]
I have to admit I've lost track of what has already been implemented and what has not been implemented yet. Let's make a list first that summarizes what works and what doesn't work from the Cairo backend so we can see how much work is ahead of us. We don't need to backport things to `master`, just make sure that most of the things that used to work with the Cairo backend still work with Matplotlib.

**Comment by iosonofabio** [comment]
Sounds good. The obvious outstanding items are edge labels and generally plot margins when labels are used.

**Comment by iosonofabio** [comment]
This definitely works in `develop`, perhaps has to do with the recent bugfix in the `curved` parameter in both Cairo and  mpl

![test](https://user-images.githubusercontent.com/1200640/145729502-2b43af94-db57-4329-8869-e86b7e555a14.png)

**Comment by iosonofabio** [comment]
@Kasaneru: this is fixed in the `develop` branch, which will be in the next API-breaking release. Because a huge amount has changed since the latest release from `master`, this is not really back-portable, so please use either `develop` or wait for the next release.

Thanks for reporting!
