### ISSUE TITLE
Matplotlib backend throws an exception when there is only a single vertex in the graph

### ISSUE THREAD

**Issue by ntamas** [igraph/python-igraph#462]
**Describe the bug**

Plotting a graph with a single vertex crashes the Matplotlib plotting backend.

**To reproduce**

```
from igraph import Graph
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
plot(Graph([(0,0)]), target=ax)
```

The code above throws an exception:

```
/usr/local/lib/python3.7/dist-packages/igraph/drawing/graph.py in shrink_vertex(ax, aux, vcoord, vsize_squared)
    994             aux_display, vcoord_display = ax.transData.transform([aux, vcoord])
    995             d = sqrt(((aux_display - vcoord_display) ** 2).sum())
--> 996             fr = sqrt(vsize_squared) / d
    997             end_display = vcoord_display + fr * (aux_display - vcoord_display)
    998             end = ax.transData.inverted().transform(end_display)

ZeroDivisionError: float division by zero
```

**Version information**

igraph 0.9.8
matplotlib 3.2.2
Google Colab

**Comment by ntamas** [comment]
@iosonofabio Can you help me with finding where [this patch](https://github.com/igraph/python-igraph/commit/3d074b2f3433abbfbbf4e7748c328a1c91da39a7#) should be merged to in the `develop` branch (if it is needed at all)? The Matplotlib drawing backend has changed so much that I can't find the appropriate place, but maybe this is not even an issue any more.

**Comment by iosonofabio** [comment]
No problem, I'll take a look tomorrow
