### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by pradkrish** [igraph/python-igraph#464]
**Describe the bug**
After following all the steps in the `Contributing` section, I get `ModuleNotFoundError: No module named 'igraph'` when importing igraph for the first time. Is there a missing instruction?

**To reproduce**
These are the steps I followed
```
git clone https://github.com/igraph/python-igraph.git
cd python-igraph
sudo apt install bison flex
git submodule update --init
python setup.py develop

```

**Comment by iosonofabio** [comment]
Thanks for reporting. Is the newly compiled package in your `PYTHONPATH`? If not, please add it and try again

**Comment by vtraag** [comment]
Is `develop` still working correctly @ntamas? I remember that it isn't working properly anymore, but I don't remember the details. If not, we should obviously correct that in the `README.md`. Perhaps we could use a separate `CONTRIBUTING.md` also?

**Comment by pradkrish** [comment]
Also, isn't building it in a `venv` a better option? If so, I see no mention of it in `README.md` either.

**Comment by ntamas** [comment]
I use virtualenvs on my own machine. From scratch (i.e. fresh clone):

```
git submodule update --init --recursive
python3 -m venv .venv
.venv/bin/pip install .
.venv/bin/python -c 'import igraph; print(igraph.__version__)'
```

I'll check why the `setup.py develop` route does not work, but as the whole setup is pretty complex, maybe it's somewhat expected.

You should know that the build process works like this:

* first the C core of igraph (which is a submodule in `vendor/source/igraph`) is built into `vendor/build/igraph` and then installed into `vendor/install/igraph`
* then the Python interface is built; it links into the installed igraph in `vendor/install/igraph`
* the Python interface actually consists of two modules: `igraph._igraph` and `igraph`. `igraph._igraph` is a C extension module that links the Python world with the C world. `igraph` is pure Python but it imports stuff from `igraph._igraph`. The source codes of the two modules reside in `src/_igraph` and `src/igraph`.
* the unit tests have extra dependencies that are not part of the mandatory dependencies of `igraph`, so if you want to run unit tests (which you should do if you want to develop `python-igraph` further), you need to install the `plotting` and `test` extras, and then use `pytest` to run the unit tests as `.venv/bin/pytest tests`

It looks like the instructions in the readme need some updating, so thanks for reporting this.

**Comment by ntamas** [comment]
Also, there's a `test.sh` script in the `develop` branch that I currently use for running unit tests in the virtualenv; it may prove useful. The reason why it's not mentioned anywhere is that I'm not quite satisfied with it yet.

**Comment by pradkrish** [comment]
This is what I have done after pulling the `seup.py develop` fix:

**Comment by pradkrish** [comment]
This is what I have done after pulling the `seup.py develop` fix:

```
git clone https://github.com/igraph/python-igraph.git
cd python-igraph
sudo apt install bison flex
git submodule update --init --recursive
python3 -n venv venv
source venv/bin/activate 

# after activating venv 
git checkout master
python setup.py develop
python -m unittest
```
This gives
```
Ran 397 tests in 2.866s
OK (skipped=19)

```
is that the total number of tests? Does it look complete?

**Comment by ntamas** [comment]
Yes, that seems OK, but some tests are skipped because NumPy, SciPy, Pandas and Matplotlib are not installed in the venv. These are optional dependencies so a simple `setup.py develop` will not download them. You can probably run `pip install -e '.[plotting,test]'` to install the package in "editable" mode and install the testing / plotting dependencies as well.

Note that in editable mode (or with `setup.py develop`), igraph will not get recompiled if you modify the C glue code in `src/_igraph` so the `develop` mode works only if you are going to work on `src/igraph` only.

**Comment by pradkrish** [comment]
ah I think I get it. I was under the impression that I can change the C code, build the python interface and test the changes. I am primarily interested in contributing to the igraph C library. In that case, I guess I follow the instructions [here](https://igraph.org/c/) and [here](https://github.com/igraph/igraph/blob/master/CONTRIBUTING.md)

**Comment by ntamas** [comment]
> I was under the impression that I can change the C code, build the python interface and test the changes.

In theory you can do that; you need to change the C source in `vendor/source/igraph` (this part is _not_ aware of Python at all), update the C-to-Python glue code in `src/_igraph`, recompile (`rm -rf vendor/build vendor/install && python setup.py develop`), and then test the changes. But if you want to change things deep in the C core, and you want the changes to end up in the official C-igraph repo eventually, it is better to do the changes directly in the C core (and you will need to add unit tests there anyway, in pure C).

**Comment by szhorvat** [comment]
Can this be closed now? If we want to fix develop mode, a new issue with a descriptive title and body should be opened.
