### ISSUE TITLE
Main page links to version-specific tutorial

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#466]
The main webpage links to a version-specific tutorial:

https://igraph.org/python/#docs

Notice this link: https://igraph.org/python/tutorial/0.9.8/tutorial.html

Instead of linking to `0.9.8`, it should link to `latest`. We should avoid search engines picking up on version-specific documentation.

**Comment by ntamas** [comment]
Should be fixed now in https://github.com/igraph/igraph.org/commit/90c2784ef124daea5620fff89abdd28a0a2fd1ea
