### ISSUE TITLE
A setting to change the plotting backend

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#472]
To use the matplotlib backend, we need to do something like `plot(g, target=plt.axes())`. This is very tedious during interactive work.

This is a proposal to have a setting that changes the backend either permanently, or for the duration of the session.

**Comment by iosonofabio** [comment]
Actually, see the tutorial PR for examples: it's better to create the figure and axes first, but in the fly.

Also, this config option exists already, but the config singleton is not terribly well documented. So we can leave this issue open until we make a tutorial that uses it and add a page on the website

**Comment by szhorvat** [comment]
Can you demonstrate how changing the configuration, with a code example?

**Comment by szhorvat** [comment]
```
from igraph import config
config['plotting.backend'] = 'matplotlib'
```
