### ISSUE TITLE
Plots are stretched with matplotlib backend

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#473]
**Describe the bug**

Plots are horizontally stretched with the matplotlib backend.

In a notebook, I see this:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1212871/145707095-cb79c002-1af8-4375-a523-699813dec0f9.png">

During interactive usage, there should not be any need for adjustments (such as setting "equal axes") to get a good plot.

**To reproduce**

```
import igraph as ig
ig.config['plotting.backend'] = 'matplotlib'
ig.plot(ig.Graph.Erdos_Renyi(n=20,m=30))
```

**Version information**

Current `develop` branch.

**Comment by iosonofabio** [comment]
Fair enough: just fixed in 4ba66b3.

@Gomango999: can you please delete all those `ax.set_aspect(1)` from the new tutorials?

**Comment by szhorvat** [comment]
Awesome!

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1212871/145708607-2c40aa0e-a88c-4f54-8d73-b476ee23c755.png">

**Comment by Gomango999** [comment]
> can you please delete all those ax.set_aspect(1) from the new tutorials?

On it!
