### ISSUE TITLE
ImportError: DLL load failed while importing _igraph

### ISSUE THREAD

**Issue by ricky711** [igraph/python-igraph#479]
python version: 3.9.1
the way to install igraph: pip install igraph
error: 
import igraph
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import igraph
  File "D:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\igraph\__init__.py", line 26, in <module>
    from igraph._igraph import (
ImportError: DLL load failed while importing _igraph:

**Comment by ricky711** [comment]
so how to fix this? please help, thanks~!

**Comment by ntamas** [comment]
That's totally fine, there should be no `_igraph.py`. The `_igraph` module is implemented in C so you should see `_igraph.cp39-win_amd64.pyd` there. Seems like the installation is okay, and I've just tried it on a stock Windows machine with Python 3.9.9 and the installation worked just fine.

Are you using a 32-bit or 64-bit Python? Is your Windows 32-bit or 64-bit? Also, the end of the error message seems to be missing from your original post so please post the full error message.

**Comment by szhorvat** [comment]
What version of Windows are you using?

Please post the full error message and check carefully if there are additional popup windows with errors. If yes, show a screenshot of those windows.

I expect you have an old version of Windows and will need to install the VC redistributables:

https://igraph.discourse.group/t/dll-load-failed-while-importing-igraph-on-windows/668/5?u=szhorvat

**Comment by ricky711** [comment]
> That's totally fine, there should be no `_igraph.py`. The `_igraph` module is implemented in C so you should see `_igraph.cp39-win_amd64.pyd` there. Seems like the installation is okay, and I've just tried it on a stock Windows machine with Python 3.9.9 and the installation worked just fine.
> 
> Are you using a 32-bit or 64-bit Python? Is your Windows 32-bit or 64-bit? Also, the end of the error message seems to be missing from your original post so please post the full error message.

1、Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
2、the full error message is: 
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import igraph
  File "D:\Users\richardgao\AppData\Local\Programs\Python\Python39\lib\site-packages\igraph\__init__.py", line 26, in <module>
    from igraph._igraph import (
ImportError: DLL load failed while importing _igraph: 找不到指定的模块。
![image](https://user-images.githubusercontent.com/28643892/145778172-df252e59-37fb-4ac4-b4b9-3f5e9a1f5f0b.png)

**Comment by ricky711** [comment]
> 



> > That's totally fine, there should be no `_igraph.py`. The `_igraph` module is implemented in C so you should see `_igraph.cp39-win_amd64.pyd` there. Seems like the installation is okay, and I've just tried it on a stock Windows machine with Python 3.9.9 and the installation worked just fine.
> > Are you using a 32-bit or 64-bit Python? Is your Windows 32-bit or 64-bit? Also, the end of the error message seems to be missing from your original post so please post the full error message.
> 
> 1、Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec 7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32 2、the full error message is: Traceback (most recent call last): File "<pyshell#0>", line 1, in import igraph File "D:\Users\richardgao\AppData\Local\Programs\Python\Python39\lib\site-packages\igraph__init__.py", line 26, in from igraph._igraph import ( ImportError: DLL load failed while importing _igraph: 找不到指定的模块。 ![image](https://user-images.githubusercontent.com/28643892/145778172-df252e59-37fb-4ac4-b4b9-3f5e9a1f5f0b.png)

64-bit python, 64-bit windows

**Comment by szhorvat** [comment]
Which version of Windows are you using? Windows 7, 8, 10? 

Did you try installing the VC++ redistributables I linked to?

**Comment by ricky711** [comment]
> Which version of Windows are you using? Windows 7, 8, 10?
> 
> Did you try installing the VC++ redistributables I linked to?

1. windows 10
2. It works with VC++ redistributables, vc_redist.x64.exe, thanks a lot :)

**Comment by szhorvat** [comment]
Good. We should write this up in a troubleshooting guide somewhere.

**Comment by ntamas** [comment]
Actually, the Python installers should contain the Visual C++ redistributable since Python 3.5, _except_ when someone installs the [embeddable distribution](https://docs.python.org/3.9/using/windows.html#the-embeddable-package), which, as its name implies, should be embedded in a larger application and it is the responsibility of the embedding application to provide the runtime.

@ricky711 Did you install the embeddable distribution of Python or did you use the installer package? On the Python [download page](https://www.python.org/downloads/release/python-3101/), the embeddable distribution is listed as "Windows embeddable package", while the installer is listed as "Windows installer". Strangely enough, the installer comes later in the list, but at least it says "recommended" next to it.
