### ISSUE TITLE
Provide docker support

### ISSUE THREAD

**Issue by ntamas** [igraph/python-igraph#48]
_From @nealmcb on November 4, 2015 14:16_

Provide a Dockerfile so we can deploy and test igraph via [Docker](https://www.docker.com/).

Basing it `FROM jupyter/notebook` might make sense, at least as an option, and would conveniently provide a [Jupyter](http://jupyter.org/) web interface to igraph in an IPython notebook.  See [jupyter/notebook](https://github.com/jupyter/notebook)

_Copied from original issue: igraph/igraph#892_

**Comment by ntamas** [comment]
I can probably create a `Dockerfile` once at some point but I cannot promise that it will be maintained as I am not using Linux on a daily basis any more.

**Comment by ntamas** [comment]
For future reference (if I manage to find some time to create a Dockerfile): I had to issue the following commands in a vanilla Ubuntu 14.04 LTS server VM to install the Python interface of igraph from scratch (without installing the C core first):

```
apt-get install build-essential python-dev python-pip libxml2-dev pkg-config zlib1g-dev
pip install python-igraph
```

**Comment by ntamas** [comment]
So I've created a pretty simple `Dockerfile` that seems to work for me:

```
FROM ubuntu:latest
MAINTAINER Tamas Nepusz <ntamas@gmail.com>
LABEL Description="Simple Docker image that contains a pre-compiled version of igraph's Python interface"
RUN apt-get -y update && apt-get -y install build-essential libxml2-dev zlib1g-dev python-dev python-pip pkg-config libffi-dev libcairo-dev
RUN pip install python-igraph
RUN pip install cairocffi
CMD /usr/local/bin/igraph
```

It can be executed with `docker -it run python-igraph` (assuming that it's built using `python-igraph` as the image name). I'm not too experienced with Docker, though - is this enough or can this be improved further?

**Comment by nealmcb** [comment]
Cool - that sounds like a great step!

You might try `FROM jupyter/notebook` instead to get a more full-featured ipython notebook environment.  You wouldn't need the CMD step since they take care of that.  Combine it with some tips about  running with local disks mounted, e.g.

    docker run -it -p 8888:8888 -v ~/localnotebooks:/notebooks python-igraph

and folks should be off and running in no time.

**Comment by ntamas** [comment]
Docker images are now provided on Docker Hub:

* https://hub.docker.com/r/ntamas/python-igraph-notebook/ for the Jupyter Notebook version
* https://hub.docker.com/r/ntamas/python-igraph/ for a minimal image with a Python prompt

They are currently for version 0.7.1post6, but I'll try to keep them up-to-date.

**Comment by nealmcb** [comment]
Great - thank you @ntamas!
