### ISSUE TITLE
Tutorial should not encourage adding edges and vertices one by one

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#480]
As I mentioned [here](https://igraph.discourse.group/t/igraph-is-much-slower-than-networkx-when-generating-a-graph/853/9), the tutorial clearly encourages adding vertices and edges one by one. This is extremely inefficient in igraph, and should be avoided. Right now, people are simply doing what the tutorial suggests, and end up with bad performance. That is demonstrated by both the forum post I linked, as well as [code like this retwork benchmark](https://github.com/mtreinish/retworkx-comparison-benchmarks/commit/94cb8d1b007a41a8cb152f9de7397fc0d671d4f6), which is [already being discussed on forums](https://discourse.julialang.org/t/retworkx-new-high-performance-python-graph-library/71109/). In fact, it was pointed out to me that the benchmark was done this way precisely because of what the igraph tutorial suggested. I hope this convinced you @iosonofabio to put some resources on this.

A proper fix involves a significant rewrite of the beginning of the tutorial, and takes some work.

**Comment by iosonofabio** [comment]
I was already aware of this and more issues with the long tutorial... why do you think @Gomango999 is here? :smirk:

**Comment by iosonofabio** [comment]
This is fixed in `develop`, closing. Please reopen if you feel like this deserves further attention.
