### ISSUE TITLE
Marking groups using a vertex cover does not work with the matplotlib background

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#481]
**Describe the bug**
Highlighting a vertex cover does not work correctly with the matplotlib background.

**To reproduce**
```
import igraph as ig
import matplotlib.pyplot as plt
g = ig.Graph.Famous("Zachary")
cliques = g.cliques(4, 4)
fig, ax = plt.subplots()
ig.plot(ig.VertexCover(g, cliques), mark_groups=True, target=ax)
```
Doing
```
ig.plot(ig.VertexCover(g, cliques), mark_groups=True)
```
correctly yields
![image](https://user-images.githubusercontent.com/6057804/146072548-8c8b3b2f-973f-4d27-9f84-3c67c373955e.png)

This was identified earlier in https://github.com/igraph/usability-benchmarks/pull/1.

**Version information**
`igraph` 0.9.8 installed from `conda-forge` channel.

**Comment by iosonofabio** [comment]
Is this `develop` or `master`?

**Comment by vtraag** [comment]
Released 0.9.8. Should this already be corrected in `develop`?

**Comment by iosonofabio** [comment]
Sorry I had missed the last line. `develop` has a LOT of changes in matplotlib, so I'd suggest we base off that for this kind of improvs and not worry too much about backfilling.

**Comment by vtraag** [comment]
OK, I'll check whether it's already solved in `develop`.

**Comment by vtraag** [comment]
OK, I confirm this is working in `develop`

![image](https://user-images.githubusercontent.com/6057804/146078880-ffb8ac7f-0645-4e4b-8461-63c1a497fc49.png)
