### ISSUE TITLE
spanning_tree docs

### ISSUE THREAD

**Issue by Yaminyam** [igraph/python-igraph#490]
**Describe the bug**
![image](https://user-images.githubusercontent.com/31057849/146734500-d7ea9a60-03dc-4226-a669-54d042fca152.png)
The description of the function describes MST, but the function name points to ST, so I actually executed the function.

The graph as shown in the following picture was used to obtain a tree with the corresponding function, but in reality it seems to return ST rather than MST.

**To reproduce**
Steps or minimal example code to reproduce the problem.

![image](https://user-images.githubusercontent.com/31057849/146734833-2e1b5760-6361-498f-9c20-6c8875c06b12.png)
![image](https://user-images.githubusercontent.com/31057849/146734845-3414eee7-0667-4fcc-b8de-99341fb0df71.png)

If you are confident that the issue is not in the Python interface but in the
C core of igraph, please add it to the main [igraph repo](https://github.com/igraph/igraph)
instead.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
Which version of `python-igraph` are you using and where did you obtain it?

**Comment by vtraag** [comment]
You have to pass in the `weights` explicitly to `spanning_tree`, see the [docs](https://igraph.org/python/api/latest/igraph.Graph.html#spanning_tree).

**Comment by iosonofabio** [comment]
@vtraag I asked @Gomango999 to perhaps make a tutorial on MST without/with weights?

**Comment by Yaminyam** [comment]
@vtraag thank you! I have checked the link you sent.
However, there is a weight attr in the graph, so why not use it and pass a new weight vector as an argument?
And if it is a function that returns mst, wouldn't it be better to name the function as minimum_spanning_tree rather than spanning_tree?

**Comment by iosonofabio** [comment]
@Yaminyam

1. silent assumptions lead to bugs, copying the weights out is literally 1 LOC - and you're guarateed to know what you're doing. Perhaps in the future if igraph becomes more intuitive all round this kind of things might change
2. historical reasons: changing the API breaks people's existing code, and should be done only if the benefit is clear

**Comment by szhorvat** [comment]
I think the name `spanning_tree()` is good, regardless of backwards compatibility consideration.

I'd like to point out that in the unweighted case all spanning trees have the same "total weight", i.e. same number of edges. Thus, "spanning tree" is not a bad description. Naming the function `minimum_spanning_tree` would suggest that it is specifically for weighted graphs, which is not the case.

Regarding using the 'weights' attribute automatically:

First, note that none of the igraph functions do this, so `spanning_tree` is consistent with other functions.

Would it be good to use this attribute by default? It would certainly not be a bad choice (networkx uses it), but I do not think that it is objectively better than the current one. The Mathematica interface of igraph, which I maintain, uses the standard `EdgeWeight` attribute by default. So do all built-in Mathematica functions. It has happened to me that I wanted to calculate some unweighted graph metric, but I simply did not realize that the graph I was working with got edge weights added to it at some point: I was getting wrong results (or at least I wasn't getting what I though I was). The advantage of having `weights=None` by default is predictability: you always get the same result with the same function call.

This is basically the 1st point of @iosonofabio above, but I wanted to back it up with some personal experience.
