### ISSUE TITLE
Label edge between two nodes in graph gives error.

### ISSUE THREAD

**Issue by Losbarthos** [igraph/python-igraph#501]
**Describe the bug**
Based on my stackoverflow issue (see [here](https://stackoverflow.com/questions/70659155/python-igraph-keyerror-while-plotting)) I want to report a bug  which occurs, if I want to illustrate a graph (directed or not) with a label on edge between two nodes, with plot.

**To reproduce**
```
from igraph import *

p = Graph()

p.add_vertices(1)
p.vs["label"] = ['Tom']

p.add_vertices(1)
p.vs[-1]["label"] = 'Anna'

p.add_edge(p.vs.find(label='Tom'), p.vs.find(label='Anna'))
p.es[-1]["label"] = 'sister'

print(p)

layout = p.layout("kk")
plot(p, layout=layout)
```

**Error message**

```
Traceback (most recent call last):
  File "~/test.py", line 18, in <module>
    plot(p, layout=layout)
  File "~/.local/lib/python3.9/site-packages/igraph/drawing/__init__.py", line 510, in plot
    result.show()
  File "~/.local/lib/python3.9/site-packages/igraph/drawing/__init__.py", line 333, in show
    self.redraw(ctx)
  File "~/.local/lib/python3.9/site-packages/igraph/drawing/__init__.py", line 276, in redraw
    plotter(ctx, bbox, palette, *args, **kwds)
  File "~/.local/lib/python3.9/site-packages/igraph/__init__.py", line 4166, in __plot__
    drawer.draw(self, palette, *args, **kwds)
  File "~/.local/lib/python3.9/site-packages/igraph/drawing/graph.py", line 489, in draw
    (x, y), (halign, valign) = edge_drawer.get_label_position(
  File "~/.local/lib/python3.9/site-packages/igraph/drawing/edge.py", line 159, in get_label_position
    if edge['curved']:
KeyError: 'Attribute does not exist'
```

**Version information**
0.9.9

**Comment by ntamas** [comment]
@iosonofabio This seems like right up your alley, but let me know if you are overwhelmed or have other things to do and then I'll investigate.

**Comment by iosonofabio** [comment]
This is 99% fixed in`develop`. @Losbarthos can you please test it?

**Comment by szhorvat** [comment]
The instructions for installing the dev version are here: https://github.com/igraph/python-igraph/#compiling-the-development-version  Perhaps this section should be made more prominent, and a bit more detailed, and self-contained. It seems more relevant than the preceding "Installation from source" sections which are somewhat confusing and do not seem to be entirely correct (`pip install igraph` won't install from source, will it?).

**Comment by ntamas** [comment]
`pip install igraph` _will_ install from source if there is no pre-built binary package for the platform, which happens more often on Linux (at least it used to happen until we started providing `manylinux` wheels). `pip install igraph` will also compile from source if a new minor Python version is released until we upload wheels for that minor version (e.g., a Python 3.9 wheel won't work on Python 3.10). This latter problem will be solved once we switch to using the stable Python ABI only - which already happened on the `develop` branch but will not happen on `master` until we merge `develop` into it.

**Comment by Losbarthos** [comment]
Now I get the error:
```
  File "~/test.py", line 1, in <module>
    from igraph import *
  File "~/.local/lib/python3.9/site-packages/igraph/__init__.py", line 26, in <module>
    from igraph._igraph import (
ImportError: /home/linuxbrew/.linuxbrew/lib/libgomp.so.1: version `GOMP_4.5' not found (required by /home/martin/.local/lib/python3.9/site-packages/igraph/_igraph.cpython-39-x86_64-linux-gnu.so)
```

**Comment by szhorvat** [comment]
To make things simple, disable OpenMP when compiling python-igraph. Set this environment variable before compiling:

```
IGRAPH_CMAKE_EXTRA_ARGS=-DIGRAPH_OPENMP_SUPPORT=OFF
```

That said, make sure you are compiling with the same compiler that Python was compiled with. If you are using the system Python, use the system compiler. If you are using Linuxbrew's Python, use Linuxbrew's compiler. This is a just a guess: it might not be the real cause of the problem. But it looks like the libgomp shared library that is loaded here is not the same one that python-igraph was compiled with.

**Comment by Losbarthos** [comment]
Thanks, how exactly can I set this environment variable is it an easy "set IGRAPH_CMAKE_EXTRA_ARGS=-DIGRAPH_OPENMP_SUPPORT=OFF" in linux terminal or did I have to set it somewere in source code of igraph libaries?

**Comment by szhorvat** [comment]
`export IGRAPH_CMAKE_EXTRA_ARGS=-DIGRAPH_OPENMP_SUPPORT=OFF` in the Linux terminal, _before_ (compiling igraph.

**Comment by iosonofabio** [comment]
FWIW we have a PR that improves installation instructions for `python-igraph`, and adds a troubleshooting section. I can add whatever ends up being the solution of this struggle to that section so that future users will be grateful for your pain...

**Comment by iosonofabio** [comment]
Also, this is fixed in `develop`, e.g. with the `matplotlib` backend:

```python
import matplotlib.pyplot as plt
from igraph import Graph, plot

p = Graph()
p.add_vertices(1)
p.vs["label"] = ['Tom']

p.add_vertices(1)
p.vs[-1]["label"] = 'Anna'
 
p.add_edge(p.vs.find(label='Tom'), p.vs.find(label='Anna'))
p.es[-1]["label"] = 'sister'
   
print(p)
 
layout = p.layout("kk")
fig, ax = plt.subplots()
plot(p, layout=layout, target=ax)
```

![igraph_bug](https://user-images.githubusercontent.com/1200640/149021077-7c00adc8-bb04-4249-ba34-d37bcdc85eed.png)

Also, using star imports is not a good idea, most users like `import igraph as ig`.

**Comment by Losbarthos** [comment]
thank you
