### ISSUE TITLE
tutorial output mistake

### ISSUE THREAD

**Issue by iszhi** [igraph/python-igraph#502]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

If you focus on the section (Selecting vertices and edges), the output from `g.vs.select(_degree=g.maxdegree())["name"]` should be ['Claire'], not ["Alice", "Bob"].

**Comment by iosonofabio** [comment]
Thank you, fixed in 909adfd
