### ISSUE TITLE
The matplotlib drawer doesn't allow different edge colors

### ISSUE THREAD

**Issue by Doomse** [igraph/python-igraph#505]
It would be great if one could pass a list of colors to the `edge_color` keyword to color edges individually.
Implementing that doesn't seem to complicated at first glance, since the `edge_order` keyword is already treated in a similar way.

If I get around to it, I might supply a possible implementation myself, in the meantime, any sort of feedback is appreciated.

**Comment by iosonofabio** [comment]
Check the develop branch, I'm quite sure this is already there

**Comment by Doomse** [comment]
You are absolutely right, sorry for bothering. Should've checked more thoroughly

**Comment by iosonofabio** [comment]
Thanks for checking, hopefully we can release the current `develop` soon :-)
