### ISSUE TITLE
normalized betweenness 

### ISSUE THREAD

**Issue by jmyerston** [igraph/python-igraph#506]
Hi,

I am porting an app from R to Python in which I used the igraph function  betweenness and realized that python-igraph does not have the normalization option.

Is there a work around to produce a normalized  betweenness in python-igraph? If not, do you plan to add this functionality any tine soon?

J.

**Comment by szhorvat** [comment]
You can easily implement it yourself: divide by the number of vertex pairs between which shortest paths are considered. That is `(n-1) \choose 2` for undirected and twice as many for directed graphs.

The issue to implement it for more complicated types of betweenness (such as the cutoff version) is here: https://github.com/igraph/igraph/issues/1797
