### ISSUE TITLE
I cannot plot graph with labels with matplotlib

### ISSUE THREAD

**Issue by Lebsasha** [igraph/python-igraph#510]
I cannot plot graph  with labels with matplotlib

Suppose the following example code.
```
import matplotlib.pyplot as plt
import igraph as ig

g = ig.Graph([(2, 3), (3, 4), (4, 5), (5, 3)])
g.vs["label"] = ["0", "1", "2", "3", "4", "5"]
g.vs["name"] = ["0", "1", "2", "3", "4", "5"]  # I'm not sure if I need this line, but just in case, let it be

fig, ax = plt.subplots()
layout = g.layout("kk")
ig.plot(g, layout=layout, bbox=(300, 300), margin=20, target=ax)
plt.show()
```
When I run this code, the following image without labels is obtained.
![image](https://user-images.githubusercontent.com/56230099/154860096-5f7d1c54-e15e-4fe8-bf25-aac3198ccfbe.png)

If I run the same code without passing the option `target=ax`, then I obtain the image with labels, but as far as I know, it plots via cairo, not matplotlib. But for some reason, I need to plot graph with matplotlib
I have Igraph 0.9.9 installed by pip, matplotlib 3.5.1, pycairo 1.16.2, cairocffi 1.3.0, Python 3.7.3, Linux Debian 10.

**Comment by iosonofabio** [comment]
Matplotlib plotting has improved a lot in the develop branch which will be released as 0.10. until then, I'd recommend just plotting the vertex labels using a for loop of `ax.text` commands.

**Comment by Lebsasha** [comment]
If somewho, like I, faced with this problem before releasing version 0.10, I post code for doing this
```
import matplotlib.pyplot as plt
import igraph as ig

g = ig.Graph([(2, 3), (3, 4), (4, 5), (5, 3)])
g.vs["label"] = ["0", "1", "2", "3", "4", "5"]

fig, ax = plt.subplots(constrained_layout=True)
layout = g.layout_kamada_kawai()
ig.plot(g, layout=layout, target=ax)
x_length = ax.viewLim.xmax - ax.viewLim.xmin  # same as x_length = ax.get_xlim()[1] - ax.get_xlim()[0]
y_length = ax.viewLim.ymax - ax.viewLim.ymin  # same as y_length = ax.get_ylim()[1] - ax.get_ylim()[0]
for i, coord in enumerate(layout.coords):
    ax.text(coord[0]+0.01*x_length, coord[1]-0.01*y_length, g.vs["label"][i], verticalalignment='top', fontsize='large')
plt.show()

```
It produces following graph with labels
![image](https://user-images.githubusercontent.com/56230099/155135682-494a2171-8576-4438-baa3-1b8b8535b459.png)

**Comment by iosonofabio** [comment]
yep, that's the poor man's version :smirk:

Thanks @Lebsasha
