### ISSUE TITLE
Minor memory leak in igraphmodule_PyObject_to_vector_ptr_t()

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#512]
It seems to me that there is a memory leak in this function:

https://github.com/igraph/python-igraph/blob/master/src/_igraph/convert.c#L2249

`subvec` is allocated on the heap with `igraph_Calloc`, but it is never freed, only destroyed. 

There should be a `free(subvec)` at these locations:

https://github.com/igraph/python-igraph/blob/master/src/_igraph/convert.c#L2285
https://github.com/igraph/python-igraph/blob/master/src/_igraph/convert.c#L2294

This affects the master branch.

Am I misunderstanding something Tamás?

**Comment by iosonofabio** [comment]
Happy to include this in the PR if confirmed

**Comment by ntamas** [comment]
@szhorvat is correct, please add the missing `free()` calls. Luckily this affects only the case when the conversion fails so it's not a problem in normal operation.

**Comment by iosonofabio** [comment]
I think I've done the right thing in #511 now, @szhorvat please take a look when you have a minute, thanks
