### ISSUE TITLE
Weighted shortest_paths crashes on edgeless graphs.

### ISSUE THREAD

**Issue by ivandkh** [igraph/python-igraph#513]
**Describe the bug**
Running `shortest_paths` with the `weights` parameter on an edgeless graph triggers the fatal error and crashes python: `Fatal error at src/core/vector.c:1181 : Assertion failed: v->stor_begin != v->end`

**To reproduce**
```python
>>> import igraph
>>> g = igraph.Graph()
>>> g.add_vertices(1)
>>> g.es['attr'] = []
>>> g.shortest_paths(weights='attr')
```

**Version information**
Crashes in 0.9.9.
Also tested in 0.7.1.post6, everything works fine.

**Comment by szhorvat** [comment]
I believe the crash happens on this line:

https://github.com/igraph/python-igraph/blob/master/src/_igraph/graphobject.c#L5812

`igraph_vector_min()` must never be called on an empty vector. Most such issues have been fixed in the C core, but it seems some remain in the Python interface.
