### ISSUE TITLE
write_dimacs() only works with weigth attributes

### ISSUE THREAD

**Issue by crptcusco** [igraph/python-igraph#516]
**Describe the bug**
I was trying save one igpraph object in all the formats, but i have one problem with  write_dimacs. i work with python, not is a critical bug, but i think gonna help someone.

/.local/lib/python3.8/site-packages/igraph/__init__.py:2988: RuntimeWarning: weights attribute does not exists at src/io/lgl.c:249
  return writer(f, *args, **kwds)

ValueError: source vertex must be provided in the 'source' graph attribute or in the 'source' argument of write_dimacs()

**To reproduce**
`list_formats = ["lgl", "adjacency", "dimacs", "dl", "edgelist", "graphviz", "gml", "graphml", "graphmlz", "leda", "ncol", "pajet", "pickle"]
        if export_graph:
            for v_format in list_formats:
                o_graph.save(path + "_file." + v_format ,format=v_format)`

**Version information**
0.9.9

**Comment by szhorvat** [comment]
Yes, `write_dimacs()` only supports the DIMACS format for flow problems. This format requires capacities to be present.

The feature request to support other variants of the format is here: https://github.com/igraph/igraph/issues/1924 I am going to close this issue now in favour of the other one. You can add your vote there.

You can help us implement this feature in multiple ways. If you have the expertise, you can implement it yourself and open a PR. If not, you can still in several ways, as described in that linked issue.
