### ISSUE TITLE
memory leak about creating igraph in for loop

### ISSUE THREAD

**Issue by blackDZS** [igraph/python-igraph#517]
**Describe the bug**
I use igraph to caculate average_path_length in the different data range, so I create graph from the subset of data and repate it in for loop, but the igraph object memory didn't free after re-assignment even though I del the variable by hand

**To reproduce**
```
for i in tqdm(range(start, end, batch_size)):
        data = load_data_by_id_range(start=i, end=i+batch_size)
        i_graph = create_graph_from_edges(data)
        result[f"{i}-{i+batch_size}"]["average_distance"] = i_graph.average_path_length()
        del i_graph
        gc.collect()
```
And I analysis the function using `memory_profile` get the result:
![image](https://user-images.githubusercontent.com/38283850/157153451-abf410fc-1c59-4770-ad1a-38eceaea3829.png)

It shows a clear memory leak problem, how can I solve it!

**Version information**

- Python 3.8.3
- igraph 0.9.9

**Comment by iosonofabio** [comment]
This appears legit.

I don't have a lot of time right now, so it would be fantastic if one of you guys took it. When I'm back I could spend some time profiling a bunch of unit tests with memory profiler if you guys think it's a good idea?

**Comment by ntamas** [comment]
Thanks for the report. Can you provide a full example with the missing functions that we can run on our own to reproduce the problem? What happens if you do not call `average_path_length()`, does the leak still appear? (It would help us to decide whether to look around in `average_path_length()` or the graph constructors).

**Comment by blackDZS** [comment]
@ntamas Thanks for your reply 
To facilitate your test, I simplify my code like this:
```
import gc
import json
import pickle

import igraph
from tqdm import tqdm

def create_graph_from_edges(data: list):
    _edges = [(int(d[0]), int(d[1])) for d in data if "-1" not in d]
    i_graph = igraph.Graph(edges = _edges, directed=True)
    ## i_graph will create more vertices than actual, so many vertices' degree are 0
    delete_vertices = [v.index for v in i_graph.vs if i_graph.degree(v.index) == 0]
    i_graph.delete_vertices(delete_vertices)
    print("nodes numbers: ", i_graph.vcount())
    print("edges numbers: ", i_graph.ecount())
    del data, _edges, delete_vertices
    return i_graph

@profile
def main():
    with open("data.txt", 'rb') as f:
        data = pickle.load(f)
    result = {}
    for i in tqdm(range(10)):
        i_graph = create_graph_from_edges(data)
        # result[f"{i}"]["average_distance"] = i_graph.average_path_length()
        del i_graph
        gc.collect()
    
    with open("result.json", 'w', encoding="utf8") as f:
        json.dump(result, f)

if __name__=="__main__":
    main()


```
and the [data.txt](https://github.com/igraph/python-igraph/files/8205802/data.txt) you can get here!

The memory using test I use `memory_profiler` get this:
![image](https://user-images.githubusercontent.com/38283850/157232843-81377985-5dc5-4dd9-be55-78d126c095c2.png)

**Comment by blackDZS** [comment]
@ntamas Thanks for your advise to optimize my code exec efficiency, that's useful for me. 
You said the latest revision of the develop branch can solve my probelm, I have attempt it follow the README.md,  and My operation process is:
```
sudo apt install build-essential python-dev libxml2 libxml2-dev zlib1g-dev
pip install git+https://github.com/igraph/python-igraph@develop
```

but I can't compile successfully, it stops in this https://github.com/igraph/python-igraph/blob/9cfdb4fbb0de527375cade1dc0df34143956e9b2/setup.py#L284  
and report a error:
```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-kkdst7hu/setup.py", line 902, in <module>
      setup(**options)
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-kkdst7hu/setup.py", line 407, in run
      self.run_command("build_c_core")
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-kkdst7hu/setup.py", line 373, in run
      buildcfg.c_core_built = buildcfg.compile_igraph_from_vendor_source()
    File "/tmp/pip-req-build-kkdst7hu/setup.py", line 607, in compile_igraph_from_vendor_source
      libraries = igraph_builder.compile_in(
    File "/tmp/pip-req-build-kkdst7hu/setup.py", line 214, in compile_in
      return self._compile_in(source_folder, build_folder, install_folder)
    File "/tmp/pip-req-build-kkdst7hu/setup.py", line 283, in _compile_in
      raise RuntimeError(
  RuntimeError: no igraph.pc was found in the installation folder of igraph
  ----------------------------------------
  ERROR: Failed building wheel for igraph
```

And I use:

- Linux f67460815f84 4.19.0-12-amd64  SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
- Python 3.8.10
- CMake 3.23.0-rc2


I would appreciate it if you can give me a wheel compiled!

**Comment by szhorvat** [comment]
Note that you don't need the `develop` branch, which is changing quickly at the moment. The fix is included on the `master` branch. 

Can you try the following? [Purge the `pip` cache](https://pip.pypa.io/en/stable/cli/pip_cache/) to make sure you have a clean start, then use the `--log` option to `pip install` to save the verbose output. Something like:

```
pip install --log pyigraph.log git+https://github.com/igraph/python-igraph
```

Now look for the "Installing: ..." part of the log file and see where `igraph.pc` is copied to.

```
grep 'Installing.*igraph\.pc' pyigraph.log
```

It should end in either `vendor/install/igraph/lib/pkgconfig/igraph.pc` or `vendor/install/igraph/lib64/pkgconfig/igraph.pc`. Is this the case?

**Comment by blackDZS** [comment]
@szhorvat Yes, I get `2022-03-09T17:00:27,424   -- Installing: /tmp/pip-req-build-vkxgz9eu/vendor/install/igraph/lib/x86_64-linux-gnu/pkgconfig/igraph.pc` after exec `grep 'Installing.*igraph\.pc' pyigraph.log`, the full log in here 
[pyigraph.log](https://github.com/igraph/python-igraph/files/8213296/pyigraph.log)

**Comment by szhorvat** [comment]
Then we have a diagnosis. The Python code only looks in these places:

https://github.com/igraph/python-igraph/blob/master/setup.py#L275

@ntamas Perhaps you can do recursive search for `igraph.pc` within the appropriate directory, instead of relying on these hard-coded paths?

**Comment by ntamas** [comment]
f29f20a adds recursive search for `igraph.pc` in the `master` branch; a1cb061 does the same in `develop`. Hopefully this fixes the build problems for @blackDZS

**Comment by blackDZS** [comment]
@ntamas now, it gives me another error
```
2022-03-10T11:00:05,178     /usr/bin/ld: cannot find -ligraph
2022-03-10T11:00:05,178     collect2: error: ld returned 1 exit status
2022-03-10T11:00:05,179     error: command 'g++' failed with exit status 1
```
the full log is here
[pyigraph.log](https://github.com/igraph/python-igraph/files/8220023/pyigraph.log)

**Comment by ntamas** [comment]
I've tested the build process on Ubuntu with CMake 3.16.3 (the official version in Ubuntu 20.04) and it definitely worked there. As a workaround, try building igraph like this:

```
IGRAPH_CMAKE_EXTRA_ARGS=-DCMAKE_INSTALL_LIBDIR=lib pip install git+https://github.com/igraph/python-igraph@develop
```

This attempts to force the library directory to `lib/`.

**Comment by blackDZS** [comment]
Thanks for all your help, it solves my problem, I use @ntamas method and compile success, Now the code has no memory leak 
![image](https://user-images.githubusercontent.com/38283850/157788546-0e0a0121-f458-45b6-9adb-d01d6979fc8f.png)

As for the questions @szhorvat raises, I'm not familiar to compile and cmake, I don't kow why. May be I compile in root or others, note that I run these in docker and the docker images info in there [python3.8_image.txt](https://github.com/igraph/python-igraph/files/8228606/python3.8_image.txt) hope that will help you

Thanks again for all your help！

**Comment by szhorvat** [comment]
I checked what the lib directory is with CMake 3.20 and 3.23rc3 on Ubuntu 20.04.  Only 3.23 has this behaviour. We should report this to CMake and hope they fix it before release, otherwise there'll be a ton of complaints after CMake 3.23 comes out.

**Comment by ntamas** [comment]
@blackDZS Thanks for reporting back; I'll release a new version of `python-igraph` with this fix soon.

In the meantime, can you let me know which Docker image are you using? The attached file does not help much in identifying where the image came from; is this an official Python Docker image, or an image that someone built on his own?

**Comment by blackDZS** [comment]
@ntamas I don't remember where the image from, I upload my image to docker hub repositories, you can get the image by 
```
docker pull dizhensheng/python:3.8
```

**Comment by ntamas** [comment]
Release process for 0.9.10 has started; expect a new release in at most a day.
