### ISSUE TITLE
"Parse error" when reading gzip compressed edgelist

### ISSUE THREAD

**Issue by rjoberon** [igraph/python-igraph#518]
**Describe the bug**
Reading a gzip compressed edgelist file with `Graph.Read` results in a parse error in `edgelist.c`.

**To reproduce**
Create a file `test.tsv` with the following content and compress it using gzip (resulting in `test.tsv.gz`):
```
0 3
1 2
2 3
```
Run the following code (`demo.py`):
```python
import gzip
import igraph

print(igraph.__version__)
with gzip.open("test.tsv.gz", "rb") as f:
    g = igraph.Graph.Read(f, format="edgelist")
```
This results in the following error message:
```
0.9.9
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    g = igraph.Graph.Read(f, format="edgelist")
  File "/REDACTED/lib/python3.8/site-packages/igraph/__init__.py", line 2929, in Read
    return reader(f, *args, **kwds)
igraph._igraph.InternalError: Error at src/io/edgelist.c:94: parsing edgelist file failed. -- Parse error
```

When using `open("test.tsv, "rb")` instead of `gzopen` everything works fine. Using "rt" as option instead of "rb" does not make any difference in both cases.

The relevant code in `edgelist.c` is:
```c
        read = fscanf(instream, "%li", &from);  // line 92
        if (read != 1) {
            IGRAPH_ERROR("parsing edgelist file failed", IGRAPH_PARSEERROR);
        }
```

Running the program in gdb, I can inspect the variable "from" with a breakpoint in line 93. It's value is "3", which is strange, since the first line of "test.tsv" is "0 3" and thus "from" should be "0". I suspect that the first (or first two) bytes somehow got lost by opening the file as a wrapped gzip stream (maybe `ungetc` in line 85 of `edgelist.c` does not work in such cases)?

I am not sure, if that's a problem of the Python wrapper or igraph itself, thus I post it here.

**Version information**
I am running version 0.9.9 in a venv and got it via pip.

**Comment by ntamas** [comment]
Okay, so what happens behind the scenes is that we are calling `PyObject_AsFileDescriptor()` on the object that you pass to `Read_Edgelist`, which is supposed to return a C file descriptor that we can then pass to `fdopen()` so we can pass it to igraph's C core as a `FILE*`. It looks like this trick does not work for file-like objects returned from the `gzip` module. Actually, it could even be platform-dependent. I added some debugging code to `edgelist.c` to see what's going on behind the scenes. On macOS, with Python 3.10 compiled from Homebrew, the first character I get from the file is ASCII 31, which happens to be the first byte of the _compressed_ gzip file, and it has nothing to do with the original, uncompressed content.

I'm afraid there's not much we can do about this. The C core of igraph is completely ignorant of higher-level file-like objects; it absolutely needs a `FILE*` as an input. The best I could do is to extract the input into a temporary file and open that temporary file with `fopen()`, but that would probably defeat the whole point of gzipping it in the first place.

I'll leave this open in case I happen to get an idea about this in the next few days / weeks.
