### ISSUE TITLE
TypeError: 'VisualEdgeBuilder.Element' object is not subscriptable

### ISSUE THREAD

**Issue by AndreaGuarracino** [igraph/python-igraph#519]
**Describe the bug**
I can't plot the partition of an undirected graph.

**To reproduce**
```
import igraph as ig
g = ig.read( filename=args.edge_list, format='edgelist', directed=False)
partition = g.community_leiden()
ig.plot(partition)
```

Removing `, directed=False` it would work, but the `Leiden algorithm is only implemented for undirected graphs`.

**Version information**
Which version of igraph are you using and where did you obtain it?
`0.9.9`

**Comment by szhorvat** [comment]
Please show a complete minimal example with all information needed to reproduce the problem. Describe in what way your program fails. See here for guidance: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by iosonofabio** [comment]
This keeps coming up and has been fixed in`develop`. @AndreaGuarracino please try that branch if you can.

@ everyone else: you know what I'mma say 😉

**Comment by ntamas** [comment]
I'm probably gonna fix this tomorrow for 0.9.10 -- there were a few other memory leaks etc that were fixed recently.

**Comment by AndreaGuarracino** [comment]
@iosonofabio would you please indicate to me how should I install the branch version for trying it? I want to be super-sure to do it right. For installing the library, I've followed the `pip install igraph` way

**Comment by szhorvat** [comment]
You must compile it from source. Instructions are here: https://github.com/igraph/python-igraph/#compiling-the-development-version

**Comment by AndreaGuarracino** [comment]
Thank you @szhorvat, I apologize for not reading the documentation first.

For me, the bug is solved. When will the fix be merged in the master and installable with the standard `pip install igraph` way?

**Comment by szhorvat** [comment]
Can't give any promises about the release date at the moment. There are many blocker issues in the C core of igraph to be resolved first.

**Comment by ntamas** [comment]
0.9.10 will be out soon and will fix this issue.
