### ISSUE TITLE
Verify that attribute table does not get corrupted when graph modification fails

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#521]
This task is to verify that the attribute table does not get corrupted when graph modification fails. This issue is specifically for the attribute handler of python-igraph.

This relates to https://github.com/igraph/igraph/issues/1976 and https://github.com/igraph/igraph/issues/1999

**Comment by ntamas** [comment]
Working on this, see 1d5a310 (more to come)

**Comment by ntamas** [comment]
Fixed ultimately in a30ca7c
