### ISSUE TITLE
Deleting vertices may break node references

### ISSUE THREAD

**Issue by mdondrup** [igraph/python-igraph#522]
**Describe the bug**
Deleting vertices invalidates python references to other vertices. Given a node reference n, when deleting a different node with index < n.index the node reference n changes or invalidates. This behavior is at least unexpected. If it is intentional it should be documented.

**To reproduce**
```
from igraph import Graph
g = Graph()
g.add_vertices(5, attributes = {'name':['a','b','c','d','e']})
n = g.vs.find(name='c') # vertex 'c'
print(n)
n_str = str(n)
g.delete_vertices([3]) # deleting vertex with index > n.index 
print(n)
assert n_str == str(n), 'Vertex object changed' # not happening
g.delete_vertices([0]) # deleting vertex with index < n.index
print(n)
assert n_str == str(n), 'Vertex object changed'
```

**Output**

```
igraph.Vertex(<igraph.Graph object at 0x7fc77da886d0>, 2, {'name': 'c'})
igraph.Vertex(<igraph.Graph object at 0x7fc77da886d0>, 2, {'name': 'c'})
igraph.Vertex(<igraph.Graph object at 0x7fc77da886d0>, 2, {'name': 'e'})
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [40], in <module>
     10 g.delete_vertices([0]) # deleting vertex with index < n.index
     11 print(n)
---> 12 assert n_str == str(n), 'Vertex object changed'

AssertionError: Vertex object changed
```

**Version information**
0.9.9

**Comment by ntamas** [comment]
While somewhat unintuitive, this is expected and documented [here](https://igraph.org/python/api/latest/igraph._igraph.Vertex.html):

> The vertex is referenced by its index, so if the underlying graph changes, the semantics of the vertex object might change as well (if the vertex indices are altered in the original graph).

This is because under the hood, there are no "real" vertex objects in the C core of igraph and a `Vertex` instance provided by Python is simply a pair containing a graph and an index.
