### ISSUE TITLE
Test suite should not fail when matplotlib is not present

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#524]
The test suite should not fail when _optional_ dependencies such as matplotlib are not installed. Instead, affected tests should be skipped.

There is value in running the test suite without these dependencies. For example, LeakSanitizer proved useful in identifying multiple memory leaks in python-igraph, thus it will be useful to integrate it into CI runs. However, it also discovers some leaks in numpy and a very large number of leaks in matplotlib. Using it is only feasible when excluding tests that depend on these libraries.

**Comment by ntamas** [comment]
Which dependency did you have problems with? Most of the unit tests try to import optional dependencies but then fall back to skipping the corresponding tests if the dependency is not available.

**Comment by szhorvat** [comment]
`matplotlib`.

**Comment by ntamas** [comment]
I've made a few changes in a6e9be3; this should hopefully work now. The previous solution was okay with some unit test runners (e.g., `nosetests`) but not the "official" unit test runner in Python.

**Comment by szhorvat** [comment]
This is broken again. Some tests fail without matplotlib.

**Comment by ntamas** [comment]
Should be fixed again in e653676 ; please try it and close if it works for you.

**Comment by szhorvat** [comment]
Sorry, yes, it worked for me.
