### ISSUE TITLE
Py_None is not part of the limited API

### ISSUE THREAD

**Issue by ntamas** [igraph/python-igraph#528]
**Describe the bug**

`Py_None` does not seem to be part of the limited API of CPython; it is not in the [official list](https://docs.python.org/3/c-api/stable.html#contents-of-limited-api), but it happens to work (along with `Py_True` and `Py_False`) in all versions of CPython so far. PyPy takes the rules more seriously and it does not provide `Py_None` from PyPy 3.9 onwards. As a consequence, compilation fails on PyPy 3.9, but it may break any time for CPython as well.

The `develop` branch should be updated to get rid of `Py_None`, `Py_True` and `Py_False`, or we should seek clarification from the CPython devs to see if this is an oversight and in fact `Py_None`, `Py_True` and `Py_False` are part of the limited API.

**Version information**

`develop` branch, from Github.

**Comment by ntamas** [comment]
Started a thread [here](https://discuss.python.org/t/is-py-none-part-of-the-limited-api/15045) on Python's discussion board.

**Comment by iosonofabio** [comment]
Running into this in #529 - just to clarify what's going on there

**Comment by ntamas** [comment]
This is now fixed in the current `develop` branch -- we pre-fetch an instance of `Py_None` using `Py_BuildValue("")` in the module initialization if `Py_None` is not part of the exposed API and we use that everywhere else.
