### ISSUE TITLE
Unnecessary dynamic memory allocation for matrices

### ISSUE THREAD

**Issue by iosonofabio** [igraph/python-igraph#530]
**Describe the bug**
During #529 @szhorvat noticed matrices are allocated dynamically in a few places where a static allocation would do and reduce the risk of memory leaks.

@ntamas found it in a few instances throughout, <10.

Let's fix that - I can make a PR after the UMAP one is merged

**Comment by ntamas** [comment]
I think this has been done; a quick grep for `malloc` and `calloc` revealed only a few places where we use dynamic allocations and they make sense in that context.
