### ISSUE TITLE
Implement File I/O using filename besides the file object

### ISSUE THREAD

**Issue by luav** [igraph/python-igraph#54]
To have exhaustive support of [PyPy](http://pypy.org/) it seems [only PyFile_AsFile](https://github.com/rfk/pypy/blob/master/pypy/module/cpyext/stubsactive.py)() call  should be overcome.

Now graph read/write -ing API like Graph.Read_Ncol() uses [reader](/igraph/python-igraph/blob/master/igraph/__init__.py#L2263)/[writer](/igraph/python-igraph/blob/master/igraph/__init__.py#L2320) that operates with file objects. It should extended to work with string file names as well (or at least under `PYPY_VERSION`).

**Comment by luav** [comment]
PS  I might Implement it next weekend or during the New year holidays.
PPS  It would be good to be able to set labels for the submitted issues and assign them to yourself if possible.

**Comment by ntamas** [comment]
I have recently committed a patch that does exactly this; see https://github.com/igraph/python-igraph/commit/f7bc6a31bd93595f2c9ab9a4eaf19db5a5222991. For ordinary files, one could try invoking its `fileno()` method to get a file descriptor and then call `fdopen()` from the C side to convert it into a `FILE*` - I will follow this up soon.

**Comment by luav** [comment]
Super! Thanks!

**Comment by ntamas** [comment]
Implemented in 45f0a0e.
