### ISSUE TITLE
 cairo.MemoryError: out of memory

### ISSUE THREAD

**Issue by LUCAS-1873** [igraph/python-igraph#540]
When I try to save the net-work  as a pic in PDF format,I got an ERROR :
I try to save it as SVG and png or eps/ps, all them can be done.

---------------------------------------------------------------------------
cairo.MemoryError                         Traceback (most recent call last)
<ipython-input-544-4737b2a816e8> in <module>
----> 1 ig.plot(sub_tax_net_aer_12,'robust_net_uncul.pdf')

D:\local\software\Anaoconda\lib\site-packages\igraph\drawing\__init__.py in plot(obj, target, bbox, *args, **kwds)
    510         result.show()
    511     elif isinstance(target, str):
--> 512         result.save()
    513 
    514     # Also return the plot itself

D:\local\software\Anaoconda\lib\site-packages\igraph\drawing\__init__.py in save(self, fname)
    307             warn("filename is ignored for surfaces other than ImageSurface")
    308 
--> 309         self._ctx.show_page()
    310         self._surface.finish()
    311 

cairo.MemoryError: out of memory

**Comment by ntamas** [comment]
PDF rendering is probably much more complex than SVG / PNG rendering. In the case of a PNG, you only need to allocate an image buffer (fixed size, depends on the width and height that you specify when plotting starts) and then the memory usage is fixed. With SVG, Cairo can probably stream the file into disk on-the-fly as new nodes and edges are added to the plot. With PDF, I don't know, all bets are off.

All in all, this is probably outside igraph's turf; we rely on Cairo to do the heavy lifting when drawing a graph, and you might have simply reached the limitations of Cairo. Out of curiosity, how large is your graph (how many nodes / edges)? When I was doing my [Last.fm artist map](http://sixdegrees.hu/last.fm/), Cairo worked fine but I was using the PNG and SVG backends only. If you really need a PDF, one option would be to save the graph in SVG, then open it in Inkscape and export it to PDF.

**Comment by LUCAS-1873** [comment]
Dear ntamas,
  Thanks for your answers, however, what the kind of data with different sizes (even 3 nodes and 3 edges), I got the same ERROR as well. I tried to drag the output from igraph-python which is SVG format into Adobe illustrate, but the picture showed  abnormal with a lot of bold black lines and the picture can't be edited.

My python version = 3.85 and igraph version = 0.910 and my work IDE is jupyter-notebook.
Please help me !

**Comment by ntamas** [comment]
What is the version of the Cairo library on your system? I can plot small graphs into PDF just fine on my machine, e.g., this works just fine:

```
>>> import cairocffi
>>> import igraph
>>> print(cairocffi.version)
1.17.2
>>> g = igraph.Graph.GRG(100, 0.2)
>>> igraph.plot(g, "test.pdf")
```

**Comment by LUCAS-1873** [comment]
> What is the version of the Cairo library on your system? I can plot small graphs into PDF just fine on my machine, e.g., this works just fine:
> 
> ```
> >>> import cairocffi
> >>> import igraph
> >>> print(cairocffi.version)
> 1.17.2
> >>> g = igraph.Graph.GRG(100, 0.2)
> >>> igraph.plot(g, "test.pdf")
> ```

I install igraph in python by the following steps:
```
pip install igraph  
pip install pycairo 
```

**Comment by LUCAS-1873** [comment]
> 

I try it，but even the igraph can't import 
when I import cairocffi, the error happen:

```
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'D:\local\software\Inkscape\bin\libcairo-2.dll': error 0x7f
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7f
```

I have successfully install cairocffi-1.3.0.

**Comment by LUCAS-1873** [comment]
> Please read the `cairocffi` documentation, in particular its section about installing `cairocffi` on Windows:
> 
> https://cairocffi.readthedocs.io/en/stable/overview.html#installing-cairo-on-windows

Thank you for your reply, I successfully update my cairocffi package, and now my cairocffi version is same as yours. BUT the ERROR is still there.
```
>>> import cairocffi
>>> import igraph
>>> print(cairocffi.version)
1.17.2
>>> g = igraph.Graph.GRG(100, 0.2)
>>> igraph.plot(g, "test.pdf")
>>>cairo.MemoryError                         Traceback (most recent call last)
<ipython-input-12-142283595523> in <module>
----> 1 igraph.plot(g,"x.pdf")

D:\local\software\Anaoconda\lib\site-packages\igraph\drawing\__init__.py in plot(obj, target, bbox, *args, **kwds)
    510         result.show()
    511     elif isinstance(target, str):
--> 512         result.save()
    513 
    514     # Also return the plot itself

D:\local\software\Anaoconda\lib\site-packages\igraph\drawing\__init__.py in save(self, fname)
    307             warn("filename is ignored for surfaces other than ImageSurface")
    308 
--> 309         self._ctx.show_page()
    310         self._surface.finish()
    311 

cairo.MemoryError: out of memory

What should I do? SOS~

**Comment by LUCAS-1873** [comment]
> Please read the `cairocffi` documentation, in particular its section about installing `cairocffi` on Windows:
> 
> https://cairocffi.readthedocs.io/en/stable/overview.html#installing-cairo-on-windows

Yeah, I tried to install GTK3 with win-64 version which is not mentioned in https://cairocffi.readthedocs.io/en/stable/overview.html#installing-cairo-on-windows.
And now, I got the correct cairocffi module, and successfully resolve the problem! Thank for your ans~

**Comment by ntamas** [comment]
I'm glad that it worked in the end!
