### ISSUE TITLE
Vertex label (declared fixed in "community_label_propagation") changes after the label propagation process

### ISSUE THREAD

**Issue by manuelP88** [igraph/python-igraph#541]
**Describe the bug**
Vertex label (declared fixed in "community_label_propagation") changes after the label propagation process.

The vertex field "ver_comm" contains an integer greater than or equal to zero if the label is not to change, otherwise the value -1.
The vertex field "fixed" contains a boolean True if the label associated with the vertex is to remain fixed, False otherwise.

At the end of the label propagation process in the "ver_comm_prop" field of the graph, I do not find the same (integer) value as at the start (present in "ver_comm").
I attach a segment of my code. I don't understand if I am using the interface incorrectly or if it is a bug. 

**To reproduce**
```
    rt_network: ig.Graph = ig.Graph(directed=False)

    for vtx in tqdm(from_dict_to_uniques_node(adjacency_list), desc="Adding vertex"):

        to_dict_value_if_exist = lambda d, _user_id, key: d.get(_user_id)[key] if _user_id in d else ""

        cname = to_dict_value_if_exist(user_details_by_uid, vtx, "name")
        usr_TAG = to_dict_value_if_exist(user_details_by_uid, vtx, "usr_TAG")
        curr_ver_comm = to_dict_value_if_exist(user_details_by_uid, vtx, "ver_comm")
        ver_comm = -1 if curr_ver_comm=="" else int(curr_ver_comm)
        ver_comm_TAG = to_dict_value_if_exist(user_details_by_uid, vtx, "ver_comm_TAG")
        fixed = False if ver_comm==-1 else True

        rt_network.add_vertex(
                          name=vtx, cname=cname, 
                          usr_TAG=usr_TAG, 
                          ver_comm=ver_comm, 
                          ver_comm_TAG=ver_comm_TAG, 
                          fixed=fixed)

    #Adding edges
    edges = produce_edge_list(adjacency_list)
    rt_network.add_edges(edges)

    # focus on largest connected components
    lcc: ig.Graph = rt_network.clusters().giant()

    label_propagated:ig.VertexClustering = lcc.community_label_propagation(initial="ver_comm", fixed="fixed")

    lcc.vs['ver_comm_prop'] = label_propagated.membership
```

**Version information**
`python-igraph` version 0.9.10
on Windows 11 Home (I tried also with Linux, the problem still occurs)

Thanks in advance

**Comment by szhorvat** [comment]
Note that the specific label _values_ are not guaranteed to be preserved. However if two vertices were fixed to be in the same component, that will be respected. At the end, communities are relabelled consecutively.

**Comment by ntamas** [comment]
@szhorvat raised a good point here; even I missed that so it is indeed not a bug. We are going to extend the documentation to clarify this.
