### ISSUE TITLE
Building for alpine linux

### ISSUE THREAD

**Issue by benney-au-le** [igraph/python-igraph#544]
**What is the feature or improvement you would like to see?**
Add alpine linux build for pre-compiled igraph c core binaries.

**Use cases for the feature**
We use alpine linux for our base container image. This distribution is popular amongst docker users due to its small size. However, existing binaries that are published to pypi don't support alpine linux. This means that we need to build it from source and it increases build times significantly.

**Comment by iosonofabio** [comment]
Thanks @benney-au-le 

It sounds like you know it builds *correctly* on alpine and passes tests, and you're asking just for the convenience. Is that correct?

Second Q: would it be possible for you to make a PR for this? Happy to review it.

**Comment by szhorvat** [comment]
It might make sense to request this directly from Alpine.

https://wiki.alpinelinux.org/wiki/Alpine_Linux:FAQ#Can_you_build_an_apk_package_for_....3F

**Comment by szhorvat** [comment]
All that said, it would be appreciated if you could support the project by requesting inclusion in Alpine.

**Comment by ntamas** [comment]
@benney-au-le The build artifacts of [this CI run](https://github.com/igraph/python-igraph/actions/runs/2454343989) now contain `musllinux` wheels. Can you please test whether they work on Alpine Linux and report back? If everything is all right, I'll release python-igraph 0.9.11 with `musllinux` wheels on PyPI.

**Comment by ntamas** [comment]
igraph 0.9.11 was recently uploaded to PyPI with pre-compiled `musllinux` wheels. Feel free to reopen this issue if they don't work for you.
