### ISSUE TITLE
Seeming error when computing bridges

### ISSUE THREAD

**Issue by adamoppenheimer** [igraph/python-igraph#547]
I want to start by saying I am extremely grateful for your package - it is excellent! I've seen considerable speedups in my code after switching from `networkx` to `igraph`!

**Describe the bug**
I believe the method `graph.bridges()` is not giving the correct results.

I apologize for the long example code below, but I tried out the examples in the tests and they work for me, but the code I wrote isn't giving the results I would expect.

A short summary is that I found a way to manually compute bridges [here](https://igraph.discourse.group/t/function-to-find-edges-which-are-bridges-in-r-igraph/154/2) that passes some tests I wrote, but the built-in method doesn't pass the tests.

The example is from my work on [pytwoway](https://github.com/tlamadon/pytwoway), so it's a bipartite graph of firms and workers. In the code, I am creating a graph that treats both firms and workers as nodes, where the edges are between workers and the firms where they work.

**To reproduce**
First, some imports:
```python
import numpy as np
import pandas as pd
from igraph import Graph
```

Next, this code generates the data:
```python
    worker_data = []
    ## Group 1 is firms 0 to 2 ##
    # Worker 0
    # Firm 0 -> 1 -> 3 -> 3 -> 2
    worker_data.append({'i': 0, 'j': 0, 'y': 1, 't': 1})
    worker_data.append({'i': 0, 'j': 1, 'y': 1.5, 't': 2})
    worker_data.append({'i': 0, 'j': 3, 'y': 2.5, 't': 3})
    worker_data.append({'i': 0, 'j': 3, 'y': 1.5, 't': 4})
    worker_data.append({'i': 0, 'j': 2, 'y': 1, 't': 5})
    # Worker 1
    # Firm 1 -> 0 -> 2
    worker_data.append({'i': 1, 'j': 1, 'y': 1, 't': 1})
    worker_data.append({'i': 1, 'j': 0, 'y': 1.5, 't': 2})
    worker_data.append({'i': 1, 'j': 2, 'y': 2.5, 't': 3})
    ## Group 2 is firms 3 to 5 ##
    # Worker 2
    # Firm 3 -> 4 -> 5
    worker_data.append({'i': 2, 'j': 3, 'y': 2, 't': 1})
    worker_data.append({'i': 2, 'j': 4, 'y': 1, 't': 2})
    worker_data.append({'i': 2, 'j': 5, 'y': 2, 't': 3})
    # Worker 3
    # Firm 4 -> 7 -> 3 -> 7 -> 5
    worker_data.append({'i': 3, 'j': 4, 'y': 2.5, 't': 1})
    worker_data.append({'i': 3, 'j': 7, 'y': 1.75, 't': 2})
    worker_data.append({'i': 3, 'j': 3, 'y': 1, 't': 3})
    worker_data.append({'i': 3, 'j': 7, 'y': 1.75, 't': 4})
    worker_data.append({'i': 3, 'j': 5, 'y': 2, 't': 5})
    ## Group 3 is firms 6 to 8 ##
    # Worker 4
    # Firm 6 -> 7 -> 8
    worker_data.append({'i': 4, 'j': 6, 'y': 1, 't': 1})
    worker_data.append({'i': 4, 'j': 7, 'y': 1, 't': 2})
    worker_data.append({'i': 4, 'j': 8, 'y': 1.5, 't': 3})
    # Worker 5
    # Firm 7 -> 6 -> 8 -> 10
    worker_data.append({'i': 5, 'j': 7, 'y': 1.5, 't': 1})
    worker_data.append({'i': 5, 'j': 6, 'y': 2.25, 't': 2})
    worker_data.append({'i': 5, 'j': 8, 'y': 1.75, 't': 3})
    worker_data.append({'i': 5, 'j': 10, 'y': 2, 't': 4})
    ## Group 4 is firms 9 to 11 ##
    # Worker 6
    # Firm 9 -> 10 -> 11
    worker_data.append({'i': 6, 'j': 9, 'y': 1.25, 't': 1})
    worker_data.append({'i': 6, 'j': 10, 'y': 1, 't': 2})
    worker_data.append({'i': 6, 'j': 11, 'y': 1.5, 't': 3})
    # Worker 7
    # Firm 10 -> 9 -> 11
    worker_data.append({'i': 7, 'j': 10, 'y': 1.35, 't': 1})
    worker_data.append({'i': 7, 'j': 9, 'y': 0.75, 't': 2})
    worker_data.append({'i': 7, 'j': 11, 'y': 2.25, 't': 3})

    df = pd.concat([pd.DataFrame(worker, index=[i]) for i, worker in enumerate(worker_data)])
```

Next, we generate a graph from this data:
```python
    def construct_graph(data):
        '''
        Construct numpy array linking firms by movers.
        '''
        i_col = data.loc[:, 'i'].to_numpy()
        j_col = data.loc[:, 'j'].to_numpy()
        max_j = np.max(j_col)
        linkages = np.stack([i_col + max_j + 1, j_col], axis=1)

        return Graph(edges=linkages, directed=False)
```

Finally, we want to find the bridges. I found an alternative method [on your forum, here](https://igraph.discourse.group/t/function-to-find-edges-which-are-bridges-in-r-igraph/154/2), which I am very grateful for and works in some tests I wrote (unfortunately the tests aren't directly checking that the bridges are computed, they check something else, so I'm not including them here). The code for the alternative method is as follows:
```python
G = construct_graph(df)
bridges = [a for a in G.biconnected_components() if len(a) == 2]
```

However, the code for the built-in bridges method fails the tests that I wrote. The code I use is as follows:
```python
G = construct_graph(df)
bridges = [G.es[edge].tuple for edge in G.bridges()]
```

I hope this helps - I am just going to revert back to the alternative for now, because it is working for me. However, I would be grateful to get working built-in code as I expect it will be considerably faster.

I also would like to apologize if the difference is arising because I am not understanding what the definition of a bridge is properly, I don't have any formal training in graph theory.

Thank you!

**Version information**
v0.9.11 on MacOS v10.15.7

EDIT: I apologize for the title, I shouldn't have written "error" as no errors are being raised, I should have written bug.
EDIT 2: I just tried out the code and realized it needed some changes to work, so now it should work!

**Comment by szhorvat** [comment]
Can you boil this down into a simple example, with _minimal_ Python code, in the following form?

 - This is my input graph
 - These are the bridges igraph computes
 - This is what I expect as the result instead

**Comment by adamoppenheimer** [comment]
I don't know if this is exactly what you want, but this is the graph representation from the example I gave above:
```python
[(0, 12), (1, 12), (3, 12), (3, 12), (2, 12), (1, 13), (0, 13), (2, 13), (3, 14), (4, 14),
    (5, 14), (4, 15), (7, 15), (3, 15), (7, 15), (5, 15), (6, 16), (7, 16), (8, 16), (7, 17),
    (6, 17), (8, 17), (10, 17), (9, 18), (10, 18), (11, 18), (10, 19), (9, 19), (11, 19)]
```

The result I expect is:
```python
[[10, 17], [7, 15], [3, 12]]
```

However, the result igraph is giving is:
```python
[(10, 17)]
```

**Comment by adamoppenheimer** [comment]
When I look at this, I see that the two edges that are included in the result I expect are duplicated in the graph, could that be the source of the discrepancy?

**Comment by ntamas** [comment]
Yes, I'd say that's most likely the reason. An edge is a bridge if its removal increases the number of connected components in the graph. An alternative definition is that an edge is a bridge if and only if it is not part of any cycle. If there are two edges within the same pair of nodes in the graph, then the two edges themselves form a cycle, so neither can be a bridge.

If in your problem the removal of an edge also means removing all the other edges that go between the same pair of vertices, you can simplify the graph first by calling its `simplify()` method, and then there will be at most one edge between any pair of vertices and `bridges()` will work as expected.

**Comment by adamoppenheimer** [comment]
Thank you for all the help! This seems to be the source of the discrepancy. I will be closing the issue.

**Comment by szhorvat** [comment]
> I don't know if this is exactly what you want

Yes, this was perfect and very helpful. Thanks!

@ntamas It would be useful if the Python interface could give access to the edges that make up a biconnected component. Then it would be possible to reimplement bridges in terms of biconnected components: it's those that have a single non-loop edge.

**Comment by ntamas** [comment]
`biconnected_components()` in Python returns a [`VertexCover`](https://igraph.org/python/doc/api/igraph.clustering.VertexCover.html). It does not provide an easy way to access an edge sequence containing all the edges within a single vertex set in the cover -- would that help if we added one? Something like: `cover.es(idx)` would return an edge sequence containing the edges within the vertex set with index `idx`.
