### ISSUE TITLE
How to add vertex labels for graphs read using Graph.Read_Edgelist

### ISSUE THREAD

**Issue by ayushidalmia** [igraph/python-igraph#55]
I am trying to plot communities based on a given membership for a graph. My graph has vertices from 0-|V-1| and hence I am using ```Graph.Read_Edgelist ``` for reading my graph. 

In order to plot the communities, I simply load the membership list to a vertexClustering object and plot it using plot as follows:

```
v = VertexClustering(g,membership) #here g is a graph read via edge list
plot(v, mark_groups=True).save("graph.png")

```

Now, I need to add vertex labels. One way to do this is to use the argument vertex_labels. However, I don't have any attribute name with the graph. What is a good way to give the vertex_labels using the graph g?

One workaround is to create a list of numbers from 0-|V-1|. But I don't know if it is the only way.

**Comment by ntamas** [comment]
Why don't you simply add the names as a vertex attribute after loading the graph? (E.g., `g.vs["name"] = ["foo", "bar", "baz", ...]`).

Also, please send support questions to the [igraph-help mailing list](https://lists.nongnu.org/mailman/listinfo/igraph-help) in the future; the issue tracker is reserved for bugs and feature requests.
