### ISSUE TITLE
None membership in VertexClustering

### ISSUE THREAD

**Issue by vtraag** [igraph/python-igraph#550]
**Describe the bug**
Passing in `None` values when constructing a `VertexClustering` works fine, but yields an error when calling `sizes()` function:
```
TypeError: list indices must be integers or slices, not NoneType
```

Presumably, it would be easiest to simply disallow `None` as a possible membership value. In case one wants to indicate no cluster for a certain node one could use `VertexCover`. 

**To reproduce**
```python
import igraph as ig

G = ig.Graph.Formula('a-b-c')
clustering = ig.VertexClustering(G, [1, 2, None])
clustering.sizes()
```

**Version information**
Which version of `python-igraph` are you using and where did you obtain it?

0.9.11 from `conda`.

**Comment by ntamas** [comment]
I decided to keep the possibility of having `None` in the membership vector because even certain test cases relied on it (e.g., the normalized mutual information can be calculated between clusterings with `None` values).
