### ISSUE TITLE
Update community_multilevel() to support resolution parameter

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#553]
**What is the feature or improvement you would like to see?**

Update `community_multilevel()` to support resolution parameter.

**Use cases for the feature**

Feature parity with C core.

**Comment by ntamas** [comment]
This has been added already in 0.10 so closing.

**Comment by szhorvat** [comment]
It's not in the docs: https://igraph.org/python/versions/latest/api/igraph.Graph.html#community_multilevel

**Comment by ntamas** [comment]
Darn, thanks. I really need to do something about this. The resolution parameter is implemented in the low-level `GraphBase` class, but the `Graph` class overrides it to provide a more pythonic return value, and the overridden function does not declare this argument. I'll fix this next week.
