### ISSUE TITLE
Pydoctor CSS is outdated 

### ISSUE THREAD

**Issue by tristanlatr** [igraph/python-igraph#555]
**Describe the bug**
Looks like the `apidocs.css` file is overridden at some point. The latest css is not included in the api docs. So the user experience with the search bar is not great.

Directly overriding this file is not a supported manner of customizing the pydoctor css, I’d suggest to use the `extra.css` file instead.

https://pydoctor.readthedocs.io/en/latest/customize.html#tweak-html-templates

**Comment by ntamas** [comment]
> The latest css is not included in the api docs.

This is the latest CSS that we've included in the API docs:

https://github.com/igraph/igraph.org/blob/master/docs/python/api/master/apidocs.css

This seems identical to a version of the official `apidocs.css` around Apr 12, 2022; the diff between our `apidocs.css` and the head revision in `pydoctor` is as follows:

```patch
--- apidocs.css	2022-06-09 09:31:31.000000000 +0200
+++ apidocs.css.upstream	2022-07-20 22:00:26.000000000 +0200
@@ -33,7 +33,6 @@
     float: none;
     width: 100%;
     position: relative;
-    margin: 0;
 }

 .page-header {
@@ -1119,3 +1118,8 @@
 #childList a:target ~ .functionBody{
     box-shadow: -2px -8px 0px 13px rgb(253 255 223);
 }
+
+/* deprecations uses a orange text */
+.rst-deprecated > .rst-versionmodified{
+    color:#aa6708;
+}
```

Note that we don't regenerate the API docs of _earlier_ versions, though, so it may be the case that the API documentation of earlier versions is not based on the latest PyDoctor `apidocs.css`. Is this what you meant?

**Comment by ntamas** [comment]
Closing this as we are migrating to hosting the docs on RTD and we are not going to tweak the PyDoctor CSS any more (as far as I know).
