### ISSUE TITLE
edge_label with matplotlib

### ISSUE THREAD

**Issue by tbuglc** [igraph/python-igraph#556]
Is there a feature to display edge attributes with Matplotlib as with Cairo. 

With Cairo
```
g.es["label"] = g.es["weight"]

```
works perfectly however,
adding this line below in `visual_style` never worked. 

```
visual_style = {
 "edge_label": g.es["weight"],

}
```

**Comment by tbuglc** [comment]
I tested the code from tutorial's gallery for [shortest](https://igraph.org/python/tutorial/develop/tutorials/shortest_paths/shortest_paths.html) path and this is what I got
![igraph](https://user-images.githubusercontent.com/19764908/182969938-b4979555-072f-4ce2-a6dd-0b54e367b456.png)

vs on tutorial's result 

![igraph-2](https://user-images.githubusercontent.com/19764908/182970100-9fb42fcb-891c-4486-b1db-5e30b5d908ce.png)

Any idea what might be wrong?

Running Windows 11 Home

**Comment by iosonofabio** [comment]
Could you please try the develop branch of python-igraph?

**Comment by tbuglc** [comment]
I'll try it out over this week and update you

**Comment by tbuglc** [comment]
I just tried the compiling from `develop` branch and it seems to work well.
Could we have it on PyPI release as well?

**Comment by iosonofabio** [comment]
We redesigned the whole plotting interface in `develop` so it's not easy to do that. Version 0.10 of the C core is out as pre-release and will be release ASAP, after that `python-igraph` 0.10 will follow in a matter of days (I hope).

**Comment by ntamas** [comment]
Yes, that's the plan. If things go according to plan, igraph 0.10 will be released as soon as I get back from holidays in September, and the Python interface will follow in a day or two.

**Comment by tbuglc** [comment]
Alright, thank you all. We'll be waiting then.
