### ISSUE TITLE
`Graph.Tree(1, 42)` returns tree with 0 nodes rather than 1

### ISSUE THREAD

**Issue by yunesj** [igraph/python-igraph#57]
```
from igraph import *
print len(Graph.Tree(1, 42).vs)
```
prints 0, but I expect 1. I haven't checked the C code.

**Comment by ntamas** [comment]
The bug is in the C core; I will commit a patch soon.

**Comment by ntamas** [comment]
Fixed in igraph/igraph@eb3d256.

**Comment by yunesj** [comment]
Can you confirm it's fixed?

    >>> import igraph
    >>>> igraph._igraph.__version__
    '0.7.1'
    >>> print len(igraph.Graph.Tree(1, 42).vs)
    0

Thanks!

**Comment by ntamas** [comment]
Yes, it's fixed, but no new version of the C core has been released since. Version 0.7.1 of the C core was released on Apr 21, 2014; the patch was committed on Jan 10, 2016.
