### ISSUE TITLE
get_k_shortest_paths availability in python-graph

### ISSUE THREAD

**Issue by sombreslames** [igraph/python-igraph#576]
Hello,
I would like to know if it is planned to make available the following function :
https://igraph.org/c/doc/igraph-Structural.html#igraph_get_k_shortest_paths
Or another implementation of the k-shortest-paths algorithm?

I would need these features to propose alternative paths on a DAG, as edge random deletion could happen in our problem.

Let me know if I can help in that.

Best regards, Léon

**Comment by iosonofabio** [comment]
@sombreslames thanks for requesting.

If you can make a PR I'd be happy to help you polish it to our sky-high coding standards 😋

The general process involves:
- adding a CPython function in `src/_igraph/graph object.c` that talks to Python and calls the C function
- writing a docstring
- writing a test in `tests`

If you are interested, open a draft PR against `master` ASAP and I'll keep an eye on your progress.

**Comment by sombreslames** [comment]
Hello Fabio,
I am trying to do so. Sorry but I never did that, I created a fork and a pull request on the fork.
Please see (https://github.com/sombreslames/python-igraph/pull/1)
Should I create it on this repo? If yes I do need specific right no?
Best regards,
Léon

**Comment by iosonofabio** [comment]
No worries.

Fork is good. Making a PR is good, but a PR is not *on* a repo, is *between* a (new) branch in your repo and an (existing) branch on ours. You don't need special rights to do that.

I think if you click in the github interface right below the PR name and number it will let you change the *destination* repo and branch. Please select *this* repo and the *master* branch. If it works, you'll see your PR listed here:

https://github.com/igraph/python-igraph/pulls

**Comment by ntamas** [comment]
Linking PR #577 here
