### ISSUE TITLE
python-igraph install fails.

### ISSUE THREAD

**Issue by se4u** [igraph/python-igraph#58]
Hi folks, thanks for the great library. The following is my issue:

Running  

     $ git clone https://github.com/igraph/python-igraph.git
     $ python setup.py install --user 

leads to the following compilation error in `src/convert.h`. I was able to do a `pip install python-igraph` however. It seems that the version of python-igraph available on pip does not contain the functionality of `random_walk`. So I guess that somehow the C core: 0.7.1.post6 is not compatible with the head of igraph-python. So probably the C core version that `python-igraph` tries to build should be bumped up? The log of the build is [here](https://gist.github.com/se4u/2252db59b76a81bbabf3)

    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    Using temporary directory: /home/hltcoe/prastogi/data/python-igraph/tmp/igraph.mGUepB
    Downloading igraph-0.7.1.tar.gz... 100.00%
    Extracting igraph-0.7.1.tar.gz...
    Configuring igraph...
    building 'igraph._igraph' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iigraphcore/include -I/opt/anaconda/include/python2.7 -c src/igraphmodule.c -o build/temp.linux-x86_64-2.7/src/igraphmodule.o
    In file included from src/igraphmodule.c:30:
    src/convert.h:63: error: expected declaration specifiers or ‘...’ before ‘igraph_layout_grid_t’
    src/convert.h:66: error: expected declaration specifiers or ‘...’ before ‘igraph_random_walk_stuck_t’
    error: command 'gcc' failed with exit status 1

**Comment by ntamas** [comment]
Your hunch is correct; the head of `python-igraph` is compatible with the head of `igraph` itself, not with release 0.7.1. You can try the following:

```
python setup.py install --user --c-core-url https://github.com/igraph/igraph/archive/master.tar.gz
```

Let me know if it works for you.

**Comment by se4u** [comment]
This worked on the first try :)
Thanks a lot.
