### ISSUE TITLE
"path" is an invalid keyword argument for "get_eids"

### ISSUE THREAD

**Issue by Ch0ngWang** [igraph/python-igraph#581]
**Describe the bug**
When calling the function "**get_eids**" (https://igraph.org/python/versions/latest/api/igraph.GraphBase.html#get_eids) with the keyword argument "**path**", I get a TypeError.

`TypeError: 'path' is an invalid keyword argument for this function`

But the arguments of this function returned by `help()` are as follows.

`<function Graph.get_eids(pairs=None, path=None, directed=True, error=True)>`

**To reproduce**
`ig.Graph().get_eids(path=None)`

**Version information**
Python: 3.10.7
igraph: 0.10.1

**Comment by ntamas** [comment]
Thanks for your report; unfortunately the `path` argument was removed from the `get_eids()` function in the C core of igraph so we decided to follow suit in the Python interface as well.

You can easily generate an appropriate `pairs` argument if you have a path; all you need to do is:

```
pairs = [(a, b) for a, b in zip(path, path[1:])]
g.get_eids(pairs=pairs)
```

Sorry for the inconvenience that this may have caused.

**Comment by Ch0ngWang** [comment]
Ok I see, thanks for your reply.

**Comment by Ch0ngWang** [comment]
> Thanks for your report; unfortunately the `path` argument was removed from the `get_eids()` function in the C core of igraph so we decided to follow suit in the Python interface as well.
> 
> You can easily generate an appropriate `pairs` argument if you have a path; all you need to do is:
> 
> ```
> pairs = [(a, b) for a, b in zip(path, path[1:])]
> g.get_eids(pairs=pairs)
> ```
> 
> Sorry for the inconvenience that this may have caused.

Ok I see, thanks for your reply.
