### ISSUE TITLE
setup.py bug: select() from sys.stdin is not supported on Windows

### ISSUE THREAD

**Issue by ntamas** [igraph/python-igraph#59]
setup.py uses `select()` to wait for a keypress or up to a given number of seconds before proceeding with the compilation. This does not work on Windows because `select()` supports sockets only.

**Comment by JanSchulz** [comment]
IMO it should just fail if it can't be detected...

**Comment by ntamas** [comment]
You are probably right, that branch of the code is hopeless on Windows anyway.

**Comment by janschulz** [comment]
Ok, running into this now :-( What is the right way to proceede? Just guard it with a `ON_WINDOWS: raise Error()`?

**Comment by ntamas** [comment]
Seems like `msvcrt.kbhit()` combined with a short `sleep()` in a `while` loop until the given number of seconds have passed should do the trick as well - but I'm totally fine with skipping the ten-second delay altogether on Windows. The only reason it's there is because people did not notice the message at the beginning of the compilation when we were relying on educated guesses about the location of igraph on the target system.

**Comment by janschulz** [comment]
Ok, in my current itaration (stuck at https://github.com/igraph/igraph/issues/909#issuecomment-230936503), I just removed the call on windows... :-)

**Comment by gabefair** [comment]
This is still an issue using `pip install python-igraph` (in Anaconda3 on Windows10) as there isn't a clear way of using the `--no-wait` workaround.

**Comment by ntamas** [comment]
`pip install python-igraph --install-option="--no-wait"` should be the way to go according to the [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides) - but you are right, there should be a new release of `python-igraph` that fixes this. I am still secretly waiting for a new upstream release of `igraph` so I could do a release of `python-igraph` together with that, but if it is not going to happen soon, I will release `python-igraph` 0.7.1post7 with this fix anyway.
