### ISSUE TITLE
Null dereference error in igraphmodule_i_Graph_isomorphic_vf2_callback_fn()

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#595]
This looks like a NULL dereference error:

https://github.com/igraph/python-igraph/blob/master/src/_igraph/graphobject.c#L9329

```
  map21_o = igraphmodule_vector_int_t_to_PyList(map21);
  if (map21_o == NULL) {
    /* Error in conversion, return an error code */
    PyErr_WriteUnraisable(data->callback_fn);
    Py_DECREF(map21_o);
    return IGRAPH_FAILURE;
  }
```

`map21_o` is `NULL` at `Py_DECREF(map21_o);`

**Comment by ntamas** [comment]
Fixed in https://github.com/igraph/python-igraph/commit/648a2bb5710f4fe515172d3494b42b5985136168
