### ISSUE TITLE
"Edit on GitHub" button does not work on RTD

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#597]
There's an "Edit on GitHub" button in the top right of pages like this on RTD:

https://igraph.readthedocs.io/en/master/tutorials/erdos_renyi.html

Clicking it goes to a 404 regardless of whether I'm on master, latest or 0.10.2

Can you also let me know where the source actually is, so I can make some quickfixes @iosonofabio?

**Comment by ntamas** [comment]
I think it affects the gallery pages only as those are generated from other source files. Links on other pages ((like here)[https://igraph.readthedocs.io/en/master/analysis.html]) are okay.

**Comment by szhorvat** [comment]
Where's the source file for this one?

**Comment by ntamas** [comment]
https://github.com/igraph/python-igraph/blob/master/doc/examples_sphinx-gallery/erdos_renyi.py

**Comment by ntamas** [comment]
I've looked into this and it looks like the only way to remove these buttons is to modify the template:

https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html

Furthermore, we would need to remove them _only_ on the gallery pages (they tend to work elsewhere). I think it's too much extra maintenance burden for too little gain so I'm inclined to close this.
