### ISSUE TITLE
igraph installer does not detect 64-bit version of Python

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/python-igraph#6]
_From @gaborcsardi on May 4, 2013 18:58_

Running Python 2.6 on a 64-bit Windows machine, igraph installer does not find Python26 directory.  This appears to be related to the thread discussed here: http://bugs.python.org/issue6792 regarding disutils-based installers. 

I installed the 32-bit version of Python, and problem was solved.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-03-25T00:49:52Z
 * owner: mackaymiller
 * assignee: ntamas
 * the launchpad url was https://bugs.launchpad.net/bugs/546546

_Copied from original issue: igraph/igraph#270_

**Comment by gaborcsardi** [comment]
(by ntamas)
Well, in some sense it is lucky that the installer does not find the 64-bit Python installation -- the extension was compiled on a 32-bit Windows and it is unlikely that the extension would work with a 64-bit version. Unfortunately we cannot provide a 64-bit installer at the moment as we don't have a license for 64-bit Windows. If someone is willing to help (i.e. compile a 64-bit installer after each igraph release and share it with us), I can provide detailed instructions on how to compile the library in Windows.

**Comment by ntamas** [comment]
Christoph Gohlke provides 64-bit builds for `python-igraph` on [his page][1] (and I'm really grateful for that), therefore I consider this issue as resolved.

  [1]: http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph
