### ISSUE TITLE
GraphBase.get_eids() does not have argument "path"

### ISSUE THREAD

**Issue by alejandrocca** [igraph/python-igraph#601]
Latest documentation for [python-igraph](https://igraph.org/python/versions/latest) 0.10.1 says parameter "path" should exist:
https://igraph.org/python/versions/latest/api/igraph.GraphBase.html#get_eids

Inspection of the function as following:

inspect.getargspec(GraphBase.get_eids)
ArgSpec(args=['pairs', 'directed', 'error'], varargs=None, keywords=None, defaults=(None, True, True))

**Comment by ntamas** [comment]
Duplicate of #581
