### ISSUE TITLE
UMAP attractive force and positive sampling scheme

### ISSUE THREAD

**Issue by iosonofabio** [igraph/python-igraph#602]
**Describe the bug**
I found a few bugs in our current, experimental implementation of UMAP.

Basically, we currently attract a vertex each epoch with force mu * force, where mu is the weight of the edge. Instead, what we should be doing is to attract it with force (without the mu), but only every mu epochs. It makes a difference because the learning rate is decreasing, and it also makes it faster.

I have a working fork on my laptop, so let me make a proper PR in the next days against this repo.

note to self: each time we attract we also repel, so rarer and stronger attractions also means less repulsion.

**Comment by szhorvat** [comment]
Sounds like a C core issue, but you opened it in the Python repo. If it was a mistake, please transfer it.

**Comment by iosonofabio** [comment]
Good catch, yes that's correct, thank you!

**Comment by szhorvat** [comment]
For the future, there's a transfer button on the right.
