### ISSUE TITLE
No support for polytree generation 

### ISSUE THREAD

**Issue by include-akshay** [igraph/python-igraph#603]
Polytree have been used as a graphical model for probabilistic reasoning. If a  Bayesian network  has  a structure of polytree, then belief propagation may be used to perform inference efficiently. 
Please add this functionality.

**Comment by szhorvat** [comment]
It is not very clear what you are asking for. When you opened the issue, there was a template for feature requests, which you skipped. Please meet us half way: edit the description and fill out the template in detail, making sure to include a _mathematically precise_ description of the requested functionality.

**Comment by szhorvat** [comment]
I am closing this as the description is not sufficiently clear to be able to tell what is being requested.

The following will sample polytrees on `n` vertices uniformly at random, in case this is what you meant:

```
import igraph as ig

n=10
ig.Graph.Tree_Game(n).as_directed('random')
```
