### ISSUE TITLE
Please expose subset betweenness

### ISSUE THREAD

**Issue by yangfangqun** [igraph/python-igraph#605]
C/igraph 0.10 added the `igraph_betweenness_subset()` function. Please expose this in the Python interface of igraph.

**Comment by yangfangqun** [comment]
Thank you for your reply. I have searched through the documentation carefully.
Yes, there is already some of these functions in the Graph and GraphBase classes.
However, I'm talking about like this:    betweenness_centrality_subset(G, sources, targets)
/**
 * \ingroup structural
 * \function igraph_betweenness_subset
 * \brief Betweenness centrality for a subset of source and target vertices.
 *
 * </para><para>
 * This function computes the subset-limited version of betweenness centrality
 * by considering only those shortest paths that lie between vertices in a given
 * source and target subset.

**Comment by szhorvat** [comment]
Please do not use over-long issue titles and do not open new issues when you simply want to respond to a comment.

I'll edit your post to turn it into a feature request for subset beteweenness.

**Comment by DDMMeng** [comment]
That's a good suggestion. Our team also needs this function.

**Comment by AnZhuoKaiFaZhe** [comment]
Sometimes we need to approximate the betweenness centrality, so that function is very useful.

**Comment by ntamas** [comment]
We're working on this and will be part of the next release.

**Comment by ntamas** [comment]
Fixed in 3047d7d
