### ISSUE TITLE
python-igraph: upgrading and installing problems.

### ISSUE THREAD

**Issue by lesshaste** [igraph/python-igraph#61]
I love python-igraph but I have two problems that are stopping me from using it at the moment.
- The last version is 0.7.0 from February 4, 2014. The newest igraph for R is 1.0.0 from June 24, 2015 .  It would be wonderful if python-igraph could be upgraded to 1.0.0 (or at least 0.7.1) as well.
- My annoying employer will let me install things using pip but I can't download code from the Internet generally and we have some old and stable linux distro with an ancient version of igraph.  Sadly `pip install python-igraph` doesn't download the C code for igraph so I can't upgrade igraph that way.   Would it be possible, please, to package python-graph on pypi so that  `pip install python-igraph` is all you need to do to get the latest version of igraph and python-graph? This is something that is supported I notice in other packages such as networkit (which I just discovered).

**Comment by ntamas** [comment]
> The last version is 0.7.0 from February 4, 2014.
No, that's not true, the last version is 0.7.1post6 from 2015-06-05, see here: https://pypi.python.org/pypi/python-igraph/

Also, 1.0.0 is only the version number of the R interface - the C core of igraph is still at 0.7.1 and `python-igraph` is based on version 0.7.1 of the C core.

> Would it be possible, please, to package python-graph on pypi so that pip install python-igraph is all you need to do to get the latest version of igraph and python-graph? This is something that is supported I notice in other packages such as networkit (which I just discovered).
Networkit can distribute its own C source code because the C source code does not constitute as a library on its own (as far as I know). igraph's C core stands as a separate library that one can use for development in C without ever touching Python. In other words, `python-igraph` just provides a higher-level interface to a C library (i.e. `igraph` itself) - the source code of `igraph` is not an integral part of `python-igraph`. That's why `igraph`'s source code is not bundled with `python-igraph` - just like Cairo's source code is not bundled with PyCairo, or Qt's source code is not bundled with PyQt.

Would that help if I add an option to `setup.py` that tells the setup script to assume that a specific directory already contains a copy of the source code of the C core of igraph? This way you could "prepare" an alternative version of the `python-igraph` tarball downloaded from PyPI by extracting it, adding a folder with igraph's source code, repackaging it, uploading it somewhere and then telling `pip` to install from the given URL (as far as I know, `pip` is able to download packages from arbitrary URLs).

**Comment by JanSchulz** [comment]
AFAIK, PyPI does not allow to upload binary packages for linux. Using conda environments might be a solution (conda installs binary packages on linux). Unfortunately, I haven't found any python igraph packages on conda.

**Comment by lesshaste** [comment]
@ntamas Re: 0.7.1post6 I hadn't seen that as I was looking at the information at http://igraph.org/ which still lists 0.7.0 as the latest version (see http://igraph.org/2014/02/04/igraph-0.7-python.html) .  

"Would that help if I add an option to setup.py that tells the setup script to assume that a specific directory already contains a copy of the source code of the C core of igraph? This way you could "prepare" an alternative version of the python-igraph tarball downloaded from PyPI by extracting it, adding a folder with igraph's source code, repackaging it, uploading it somewhere and then telling pip to install from the given URL (as far as I know, pip is able to download packages from arbitrary URLs)."

Thank you that's an interesting option.  I think it would need to be on pypi for me to be able to install it. I am really only allowed to install things using "pip install" .  Your point about igraph being a separate library on its own is very interesting.  When you pip install numpy or scipy it also installs and compiles all kinds of C libraries ( I think) which I suppose could be used a separate libraries.  If it isn't too difficult, would it be possible to include the igraph C code in whatever form pip install can support for python-igraph separately from the standalone C version?

**Comment by lesshaste** [comment]
@JanSchulz In principle it is possible for pip to download and install C code in support of a python module.  I don't fully understand the process I have to admit when I "pip install scikit-learn" for example which requires all kinds of libraries in different languages (C and fortran at least). But I do know that I don't have to install anything separately for it to work.

**Comment by ntamas** [comment]
> I was looking at the information at http://igraph.org/ which still lists 0.7.0 as the latest version

Thanks for pointing this out - I'll take care of updating the homepage soon.

> Your point about igraph being a separate library on its own is very interesting but I am not sure I fully understand the technical problem.

That's not a technical problem - I _could_ theoretically put igraph's source code in the `python-igraph` bundle. That's more like a _conceptual_ issue - when you develop an interface to a low-level C library in a high-level language like R, Python or Ruby, you usually don't put the source code of the C library in the source code of the interface; it simply doesn't belong there. (Actually, R is an exception, as far as I know).

NumPy and SciPy are not built on _separate_ C libraries - they are Python packages that _happen_ to contain some C code to make certain things faster, but that C code cannot "live" on its own - it is tied so closely to the actual Python module (i.e. NumPy or SciPy) that it makes no sense to distribute it separately. But, igraph exists also for R, for Ruby, and you could even use igraph's functions directly from a C project, hence we distribute igraph's code separately.

> I am really only allowed to install things using "pip install" without specifying a different URL. 

Can you please try it nevertheless? I have uploaded a hacked tarball that contains igraph's source code in it to https://dl.dropboxusercontent.com/u/1911856/python-igraph-0.7.1.post6.tar.gz . Try installing it with:

    pip install https://dl.dropboxusercontent.com/u/1911856/python-igraph-0.7.1.post6.tar.gz

If it doesn't work, let me know and we'll find another workaround.

**Comment by lesshaste** [comment]
@ntamas  I just tried that from my home computer and it worked perfectly.  If there was some way of getting that on to pypi it would be perfect.  Thank you.  

As a one off workaround I could put in an official request to my employer for IT to import the tarball https://dl.dropboxusercontent.com/u/1911856/python-igraph-0.7.1.post6.tar.gz and then try to pip install from a local directory.   However, this doesn't really help anyone else :)

**Comment by ntamas** [comment]
> If there was some way of getting that on to pypi it would be perfect.

Unfortunately not, because it would conflict with the existing `python-igraph` package with the same version.

> However, this doesn't really help anyone else :)

To be honest, your problem seems to be quite specific to the situation at your employer (i.e. the combination of an outdated (probably Debian-based) Linux distribution where you cannot install the official `libigraph` package for a recent version of igraph, combined with the fact that you are not allowed to download things except from PyPI), so I doubt that other people frequently run into the same problem.

Let me know how it goes with the IT department.

**Comment by lesshaste** [comment]
@ntamas  Thank you again. I think the distribution is CentOS 6  which is still supported until Q2 2017.

**Comment by jose2007kj** [comment]
my R version is :R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
> install.packages("igraph")
Installing package into ‘/home/rani/R/i686-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Error in download.file(url, destfile = f, quiet = TRUE) : 
  unsupported URL scheme
Warning: unable to access index for repository https://mirror.ibcp.fr/pub/CRAN/src/contrib:
  unsupported URL scheme
Warning message:
package ‘igraph’ is not available (for R version 3.2.3) )

please help me to install igraph.....thanks in advance

**Comment by gaborcsardi** [comment]
@jose2007kj This is the python-igraph repo, not rigraph. Nevertheless, it seems that your R version does not support HTTPS, so either use an R version that does, or choose a HTTP mirror instead of a HTTPS one.

**Comment by jose2007kj** [comment]
thanks.............
ok
how to install in python...........
when i run igraph(not inside R) i get result as:     
root@rani-System-Product-Name:/home/rani/rigraph-dev# igraph
GRAPH MENU
	1	New Plot
	2	Set Plot Type
	3	Load Plot File
	4	Save Plot File
	5	Change Plot Variable
	6	Change Curve Variable
	7	Output Plot
	8	Escape Command
	9	Computation
	10	Quit

Choice: 

can this igraph help me to add weight to edges of a .gml file based on node name .  i am new to igraph.......please help me...if not please suggest a easy method..........

**Comment by jose2007kj** [comment]
how to install an erly version of R...........i am unable to install earlier version of R due to the presence of latest version.......

**Comment by ntamas** [comment]
@jose2007kj apparently you installed a different igraph package, not ours. The Python interface of igraph is called `python-igraph` on PyPI, so you need to call `pip install python-igraph` to install it.

**Comment by ntamas** [comment]
@jose2007kj If you are on Windows and you try to install the R version of igraph, it might help if you run `setInternet2(TRUE)` before `install.packages("igraph")`. The explanation from the R docs is:

> Note that https:// URLs are only supported if --internet2 or environment variable R_WIN_INTERNET2 was set or setInternet2(TRUE) was used (to make use of Internet Explorer internals), and then only if the certificate is considered to be valid.

**Comment by jose2007kj** [comment]
Thankyou sir....I will try that.......

**Comment by Tara-Morovatdar** [comment]
I have python 2.7 I installed python_igraph-0.7.1.post6 through this link: https://www.lfd.uci.edu/~gohlke/pythonlibs/ for my 64-bit win and I also have installed igraph-0.1.11. but still I get DeprecationWarning when I import igraph. Can some one help??

**Comment by ntamas** [comment]
`igraph-0.1.11` is an unrelated library; please uninstall it, then post the warning message that you are getting here.

**Comment by Tara-Morovatdar** [comment]
then i get : No module igraph found

**Comment by ntamas** [comment]
Then it means that python-igraph is not installed properly or it is not on your Python path.
