### ISSUE TITLE
graph layout matrix expected

### ISSUE THREAD

**Issue by ivan-marroquin** [igraph/python-igraph#610]
**Describe the bug**
I want to generate a layout for a graph using this command:
layout= G.layout_graphopt(niter= 500, node_charge= 0.001, node_mass= 30, 
                              spring_length= 0, spring_constant= 1, max_sa_movement= 5, seed= 1969)

it gives this error message:
File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/igraph/layout.py", line 689, in result
    layout = func(*args, **kwds)
TypeError: matrix expected (list of sequences)

**To reproduce**
import igraph as ig
import pandas as pd

edgelist= pd.read_csv('Wiki-Vote.txt', header= 3, names= ['FromNodeId', 'ToNodeId'], sep= '\t', dtype= np.int32)
G= ig.Graph.DataFrame(edgelist, directed= True)
layout= G.layout_graphopt(niter= 500, node_charge= 0.001, node_mass= 30, 
                              spring_length= 0, spring_constant= 1, max_sa_movement= 5, seed= 1969)

# the 'Wiki-Vote.txt' can be found in the attached zip file

**Version information**
Which version of `python-igraph` are you using and where did you obtain it? 0.10.1

I am using python 3.9.0

[wiki-Vote.txt.gz](https://github.com/igraph/python-igraph/files/9998035/wiki-Vote.txt.gz)

Thanks
Ivan

**Comment by GroteGnoom** [comment]
The seed parameter is supposed to be

> a matrix containing a seed layout from which the algorithm will be started. If None, a random layout will be used.

https://igraph.org/python/versions/0.10.1/api/igraph.GraphBase.html#layout_graphopt

**Comment by ivan-marroquin** [comment]
Hi @GroteGnoom ,

Many thanks for your prompt answer. As you pointed out, a much clearer error message will be beneficial. 

Could you provide an example of how this matrix for the seed can be generated following the example code that I provided?

Best regards,
Ivan

**Comment by szhorvat** [comment]
The `seed` parameter specifies the initial vertex coordinates from which to start the calculation. You don't need to specify this and can leave it a the default `None`. If you just want deterministic results, leave it at `None` at set a random seed instead (`random.seed()`).

**Comment by GroteGnoom** [comment]
The reason I wanted to leave this open was to see if we could make the error message clearer. Is that not a good idea?

**Comment by ntamas** [comment]
I'll do something with it on Thursday. The biggest problem is that these error messages are coming from generic conversion functions in the C layer that do not know (at the moment) what the name of the parameter is that they are converting, so they cannot include it in the error message. We would need to pass the name of the parameter down to the function in every place where we do conversions like this.

**Comment by szhorvat** [comment]
Since this is not a critical issue, it would make sense to postpone it to the new Python interface, unless it's an easy fix. What do you think @ntamas ?

**Comment by ntamas** [comment]
I've improved the error message a bit for matrix conversions:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/igraph/layout.py", line 689, in result
    layout = func(*args, **kwds)
TypeError: matrix expected in 'seed'
```

The documentation clearly states that `seed` has to be matrix:

> a matrix containing a seed layout from which the algorithm will be started. If `None`, a random layout will be used
