### ISSUE TITLE
igraph.GraphBase.cohesive_blocks incorrect output

### ISSUE THREAD

**Issue by mok33** [igraph/python-igraph#615]
The following graph was generated from an image using pixels 8 connectivity.

![image](https://user-images.githubusercontent.com/1212871/203779848-20ed6bbf-9f3b-4d41-81c3-7539261d3d83.png)

When I apply [igraph.GraphBase.cohesive_blocks](https://igraph.readthedocs.io/en/stable/api/igraph.GraphBase.html#cohesive_blocks), I get the following cluster : 

![image](https://user-images.githubusercontent.com/1212871/203773328-9b88f303-45b5-4c56-8586-1a11c6f157be.png)

However, I expected the 3-degree **red node** (EDIT) just below the **ORANGE (EDIT)** cluster to be in the same orange cluster. But it's not the case.
The orange group is 2-cohesive according to [cohesion()](https://igraph.readthedocs.io/en/stable/api/igraph.CohesiveBlocks.html#cohesion). But I see clearly that there are 3-degree nodes so it should be 3-cohesive.
For me, there should be a 3-cohesive cluster with the point I mentioned.

I saved the igraph here : [link](https://raw.githubusercontent.com/mok33/igraph-issue/main/rabbit.net)

**Comment by szhorvat** [comment]
I'm sorry, I can't follow your description.

Can you produce a [_small_ and _complete_ example](https://stackoverflow.com/help/minimal-reproducible-example), show the actual output, and show the output you expect instead?

> When I apply [igraph.GraphBase.cohesive_blocks](https://igraph.readthedocs.io/en/stable/api/igraph.GraphBase.html#cohesive_blocks), I get the following cluster :

`cohesive_blocks()` does not produce a clustering. It outputs a list of overlapping (and nested) vertex subsets.

> the 3-degree node just below the red cluster

It's unclear what this refers to.



> But I see clearly that there are 3-degree nodes so it should be 3-cohesive.

Having degree-3 vertices does not imply 3-vertex-connectivity. On the contrary: if there is a vertex of degree $k$ then vertex connectivity cannot be greater than $k$. Just remove all neighbours of the vertex to disconnect the graph.

**Comment by mok33** [comment]
I am referring to this node : 
https://github.com/mok33/igraph-issue/raw/main/Cohesive_Blocks.PNG
I will provide you with an example to reproduce the problem shortly

**Comment by mok33** [comment]
this code reproduces my argument : https://github.com/mok33/igraph-issue/blob/main/main.py

**Comment by szhorvat** [comment]
I get a crash with your code, which we will look into.

Until then, can you try to produce an example with a smaller graph where we can follow what is happening visually? For example:

```
g=ig.Graph.Formula("0-1-2-3-4-0-5-6-7-8-9-6")
```

Can you indicate what block memberships you see for this vertex (since I can't run the code)?

**Comment by mok33** [comment]
Sorry, you have to download the "rabbit.net" file https://raw.githubusercontent.com/mok33/igraph-issue/main/rabbit.net. And place it in the same folder.
I get the following output when I execute my code : 
`[0, 6]
[0, 6, 15]
[1044, 1060, 1073]
[1028, 1029, 1059]`
which illustrate my point.

**Comment by mok33** [comment]
When I execute your code, I get the following _clusters : 
```
g=ig.Graph.Formula("0-1-2-3-4-0-5-6-7-8-9-6")
CBs = g.cohesive_blocks()
print(CBs._clusters)
```
```
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4], [6, 7, 8, 9]]
```

**Comment by szhorvat** [comment]
You say that the vertex you marked with an arrow (degree 3) is not in all the same blocks as its top left neighbour (degree 2). I don't see why this wouldn't be correct. This situation is analogous to vertex 5 not being part of the exact same blocks as vertex 6 in the above small test graph.

Can you show an example you believe is incorrect with a small graph, ideally one having fewer than 15 vertices, so we can easily discuss what the correct result would be?

For the small graph I posted above the result is correct.

**Comment by mok33** [comment]
> You say that the vertex you marked with an arrow (degree 3) is not in all the same blocks as its top left neighbour (degree 2)
the top left neighbour degree is 3 here. (diagonal pixels are connected  in the graph)
See my comment earlier: https://github.com/igraph/python-igraph/issues/615#issuecomment-1326416415

**Comment by szhorvat** [comment]
That does not imply that they need to be members of the same block. You are claiming that the result is incorrect, but do not clearly explain why. I do not see why it would not be correct, but it's difficult to discuss such a large graph that. I don't think we can proceed here without a small example.

**Comment by mok33** [comment]
Ok, I think my understanding is incorrect. 
From the definition : 
`For a given graph G, a subset of its vertices S is said to be maximally k-cohesive if there is no superset of S with vertex connectivity greater than or equal to k.`
If the orange cluster is the a subset S 3-cohesive, I can define a superset by adding the node I point in blue (https://github.com/igraph/python-igraph/issues/615#issuecomment-1326381296)  which will be 3-cohesive also.
So S should include that node ?

**Comment by mok33** [comment]
I see, thank you for the clear explanation. And I apologize for the inconvenience. 
I will have to manually remove the blue point-like nodes for my purpose.

**Comment by szhorvat** [comment]
Opening this issue led to the discovery of a bug (https://github.com/igraph/igraph/issues/2261) so something good came out of it :-)
