### ISSUE TITLE
VertexCover should accept vertex names in constructor

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#617]
**What is the feature or improvement you would like to see?**

`VertexCover` should accept vertex names in its constructor. Now it only accepts integer IDs.

**Use cases for the feature**

It is reasonable to expect that wherever vertices are expected, one may use either names or IDs.

**References**

 - https://stackoverflow.com/q/74597504/695132

**Comment by 5anperez** [comment]
Hello there! I am new to igraph but would love to contribute. However, I do not see any labels on this issue. Would you mind me asking if this would be a good first issue to contribute, given this would be my first?
