### ISSUE TITLE
Wrong plotting labels

### ISSUE THREAD

**Issue by x66ccff** [igraph/python-igraph#623]
**Describe the bug**
When I try to draw multiple igraphs, it often happens that the first one has the right label, but the second one has the wrong label

Here is part of my code.
```python
# Before this, another graph g0 was drawn in the same way, and problems occurred when drawing g1
g = g1
ig.plot(g, 
        bbox=(0,0,400,200),
        vertex_label=['"'+dict_id_to_symbol[_id] +'":'+ str(i) for i, _id in enumerate(g.vs['type'])],
        vertex_color='lightblue')
```
![image](https://user-images.githubusercontent.com/45335927/209269902-e19ae610-e31b-4bbe-841a-57a429382411.png)

However, the input list of `vertex_label` is correct.
```python
['"'+dict_id_to_symbol[_id] +'":'+ str(i) for i, _id in enumerate(g.vs['type'])]
``` 
List contents.：
```python
['"START":0',
 '"x":1',
 '"x":2',
 '"3":3',
 '"exp":4',
 '"sin":5',
 '"/":6',
 '"*":7',
 '"END":8']
```

**Version information**
0.10.2

**Comment by iosonofabio** [comment]
Thanks for writing. Can you please include the code needed to plot `g0`?

Even more useful if you could actually describe a full example instead of a code snippet. If we can reproduce on our machine it's a lot easier to help you, and we can only do that with the code needed to generate the graph.

**Comment by x66ccff** [comment]
[for_reproduce_error.zip](https://github.com/igraph/python-igraph/files/10292294/for_reproduce_error.zip)

This is the file used to reproduce the error and contains the required pickle file and jupyter notebook file, the pickle file format is 4.0

**Comment by ntamas** [comment]
Most likely a duplicate of #638 (or, more precisely, #638 is a duplicate of this). I'll keep #638 open and close this as the other issue is more detailed.
