### ISSUE TITLE
layout_kamada_kawai() docs inaccurate about 'seed'

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#626]
The `layout_kamada_kawai()` docs say:

```
@param seed: if C{None}, uses a random starting layout for the
  algorithm. If a matrix (list of lists), uses the given matrix
  as the starting position.
```

Unless py-igraph overrides the C behaviour, this is not quite accurate. Normally, the starting layout is a deterministic circle. If vertex positions are constrained to a box, only then is the starting layout random.

**Comment by ntamas** [comment]
Thanks, fixed. This is a generic problem with re-documenting things that depend on the C core; if something changes in the C core (like the behaviour of the seed, some time back around igraph 0.7.x), the changes should be followed up in higher level interfaces if the old behaviour was also documented there. I don't know what the best way would be to handle cases like this; it is bound to happen again sooner or later.
