### ISSUE TITLE
layout_kamada_kawai() maxiter should scale with graph size

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#627]
`layout_kamada_kawai()` uses `maxiter=1000` by default. The recommendation in the C core docs is:

```
 * \param maxiter The maximum number of iterations to perform. A reasonable
 *        default value is at least ten (or more) times the number of
 *        vertices.
```

The Mathematica and R interfaces both use `50*vcount`.

The Python interface should also use a `maxiter` value that at least scales with the vertex count.

**Comment by ntamas** [comment]
Fixed this, see above; tests are failing on my machine, but it seems to be unrelated (they failed even without this change). I'll continue investigating tomorrow.
