### ISSUE TITLE
error plotting VertexDendrogram

### ISSUE THREAD

**Issue by ftheberge** [igraph/python-igraph#628]
**Describe the bug**
As of version 0.10.0, plotting VertexDendrogram does not work
_AttributeError: 'VertexDendrogram' object has no attribute '_item_box_size'_

**To reproduce**
z = ig.Graph.Famous('Zachary')
gn = z.community_edge_betweenness()
ig.plot(gn,bbox=(0,0,300,300))

**Version information**
Any version 0.10.x ; from PyPI

**Comment by ntamas** [comment]
Thanks for the report; it was a relatively simple one-line fix in 346fb49 . It will be released in the next patch version.
