### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by swayson** [igraph/python-igraph#63]
Hi there,

Upon inspection of the [PyPi](https://pypi.python.org/pypi/python-igraph/0.7) page, it seems python-igraph does not have support for Python 3. 

Is this true? Are there any plans to migrate to Python 3?

**Comment by ntamas** [comment]
`python-igraph` supports Python 3, but the stock Python in Mac OS X is stuck on Python 2.x so I don't create Mac OS X installers for Python 3.

If you are on Windows, you can find precompiled installers for Python 3.4 and 3.5 on [Christoph Gohlke's page](http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph). If you are on Mac OS X, you can simply run `pip install python-igraph` and it should download and compile the Python interface as well as the C core of igraph.

**Comment by dougthor42** [comment]
> the stock Python in Mac OS X is stuck on Python 2.x so I don't create Mac OS X installers for Python 3

Just use Travis-CI to build wheels for all supported versions and systems. If you want to build Windows wheels too, [Appveyor](http://appveyor.com) is a good option.
