### ISSUE TITLE
Expose dsatur heuristic in vertex_coloring_greedy()

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#633]
**What is the feature or improvement you would like to see?**

Expose new-in-0.10.4 dsatur heuristic in `vertex_coloring_greedy()`

**References**

 - https://igraph.org/c/html/latest/igraph-Coloring.html#igraph_coloring_greedy_t

**Comment by ntamas** [comment]
https://github.com/igraph/python-igraph/blob/main/src/_igraph/convert.c#L523
