### ISSUE TITLE
igraph 0.10.4 aarch64 wheels

### ISSUE THREAD

**Issue by gruebel** [igraph/python-igraph#634]
Hi 🙂 

just wanted to check, if you didn't release `aarch64` wheels on purpose? It resulted in a Docker build failure in one of our projects, because there was no `cmake` installed, which is not needed, if there are wheels for ARM chips.

Thanks for the great work in general 🍻

**Comment by ntamas** [comment]
Hi!

Thanks for bringing this to my attention; it is definitely a mistake on my end. `aarch64` wheels are built in CI with QEMU, and it looks like the task timed out yesterday after six hours. QEMU builds are terribly slow, but they used to complete well within the allowed timeframe with earlier versions, so I restarted the CI jobs now and I will upload the missing wheels when they are ready. If the build fails again, I'll look for alternatives.

**Comment by gruebel** [comment]
hey @ntamas 

thanks for looking into it. I saw the re-triggered job and it finished successfully, close call with 5:47h 😄 Just an idea, maybe it makes sense to split the `manylinux` and `musllinux` into separate jobs. It doesn't speed up the build itself, but overall the whole pipeline would finish after 3-4 hours and it wouldn't be terminated 😄 

If interested I can easily create a PR for it.

**Comment by ntamas** [comment]
Thanks, a PR would be much appreciated!

The `aarch64` wheels are now uploaded to PyPI.

**Comment by gruebel** [comment]
@ntamas thanks, our ARM Docker build is also working again 🥇
