### ISSUE TITLE
Broken community_leading_eigenvector_naive()?

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#637]
There is a `Graph.community_leading_eigenvector_naive()` method. It does not work because `GraphBase.community_leading_eigenvector_naive()` does not exist. The documentation is puzzling because it states that this function does something incorrectly, yet it doesn't explain what it does in enough detail to be understandable.

Was this meant to be removed?

https://igraph.readthedocs.io/en/stable/api/igraph.Graph.html#community_leading_eigenvector_naive

**Comment by ntamas** [comment]
Yes, it was meant to be removed. It was used by Gábor for demonstration purposes back in the days when the leading eigenvector community detection function was new (the paper itself contained several paragraphs about how the naive approach is wrong and what should be done to make it right -- this function just replicates what the paper did there).

I'll look into removing this from `python-igraph`.
