### ISSUE TITLE
In python interface modularity function does not work correctly with the resolution parameter

### ISSUE THREAD

**Issue by sebkaz** [igraph/python-igraph#640]
**Describe the bug**
The resolution parameter is used in the modularity function to compute its value. 

**To reproduce**
```python
import igraph as ig

g = ig.Graph.Famous('Zachary')
# For resolution = 1 everything is ok 
comms = g.community_leiden(objective_function='modularity',resolution=1)
modularity = g.modularity(comms)
mod = ig.GraphBase.modularity(g, membership=comms.membership, 
                                  weights=None,
                                  resolution=1)

modularity == mod # True
```
but for different values we get: 
```python
def test(g):
    for lam in np.arange(1,2,0.1):
        comms = g.community_leiden(objective_function='modularity',
                                   weights=None,resolution=lam)
        print(f"number of communities = {len(comms)}")
        modularity = g.modularity(comms.membership, 
                                  weights=None, 
                                  resolution=lam)
        mod = ig.GraphBase.modularity(g, 
                                      membership=comms.membership, 
                                      weights=None, resolution=lam)
        print(f"{modularity}, {mod}, {modularity==mod}")

test(g)
```
number of communities = 4
0.41978961209730437, 0.41978961209730437, True
number of communities = 4
0.41978961209730437, 0.3886916502301118, False
number of communities = 4
0.41978961209730437, 0.3575936883629191, False
number of communities = 5
0.40622945430637736, 0.32809829059829054, False
number of communities = 5
0.40622945430637736, 0.3020545693622616, False
number of communities = 5
0.40622945430637736, 0.2760108481262326, False
number of communities = 6
0.3882314266929651, 0.25193951347797494, False
number of communities = 6
0.3914365548980933, 0.22569855358316876, False
number of communities = 6
0.36406969099276787, 0.2040433925049308, False
number of communities = 6
0.3640696909927679, 0.18404010519395123, False

**Version information**
ig.__version__  =>  '0.10.4'

**Comment by szhorvat** [comment]
FWIW, I cannot reproduce this in Mathematica. Thus, is there is a problem, it is not in the C core.

```mathematica
In[2073]:= g = IGFamousGraph["Zachary"];

In[2074]:= result = Table[
  {cl = IGCommunitiesLeiden[g, "Resolution" -> gamma]; cl["Quality"],
   IGModularity[g, cl, "Resolution" -> gamma],
   Length[cl["Communities"]]},
  {gamma, 1, 2, 0.1}
  ]

Out[2074]= {{0.41979, 0.41979, 4}, {0.388692, 0.388692, 4}, {0.357594,
   0.357594, 4}, {0.326496, 0.326496, 4}, {0.302055, 0.302055, 
  5}, {0.272682, 0.272682, 5}, {0.25194, 0.25194, 6}, {0.229224, 
  0.229224, 6}, {0.206509, 0.206509, 6}, {0.18404, 0.18404, 
  6}, {0.16453, 0.16453, 7}}

In[2075]:= And @@ Equal @@@ result[[All, {1, 2}]]

Out[2075]= True
```

Generally, it is good practice to describe the problem in plain words as well, in addition to code. Here you are saying that the generalized modularity values produced by `community_leiden()` are not the same as what is computed by `modularity()`.

**Comment by bkamins** [comment]
@sebkaz - what version of igraph do you use? It seems the issue has been resolved 2 months ago in https://github.com/igraph/python-igraph/commit/7848bcbc8b81fa248362f56d5593d366836deb1f

**Comment by sebkaz** [comment]
At present I use the  ig.version => '0.10.4'. I see just name changing.

**Comment by szhorvat** [comment]
@ntamas Would it make sense to record the `quality` output from `igraph_community_leiden()` in the `VertexClustering` result object, in the same way that the `codelength` is recorded when using Infomap?  This "quality" is not always the same as the generalized modularity.
