### ISSUE TITLE
Doc styling: Need better separation between parameter descriptions

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#648]
Consider e.g. the documentation of this function:

https://python.igraph.org/en/stable/api/igraph.GraphBase.html#motifs_randesu

It looks like this:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/1212871/224991303-62acd087-460f-4102-b51f-5da81bec636c.png">

I find it hard to see where the description of one parameter ends and the other stops.

There should be clearer visual separation. Add lines, greater spacing, different background colour, or whatever works.

![image](https://user-images.githubusercontent.com/1212871/224991783-92f88e31-97f4-46c6-8ade-e0834a1d19e7.png)

**Comment by iosonofabio** [comment]
This is generated by pydoc and we might be able to improve it by messing with the templates

**Comment by szhorvat** [comment]
Perhaps just make the padding larger in this CSS rule?

```css
.fieldTable tr td {
    padding: 2px;
}
```

**Comment by ntamas** [comment]
That CSS rule is superseded later by this (more specific) rule:

```
.fieldTable tr:not(.fieldStart) td:first-child, .valueTable tr:not(.fieldStart) td:first-child {
  padding: 3px 4px 3px 10px;
}
```

So we would either need to supersede it with something even more specific, or do an ugly `!important` hack like this:

```
.fieldTable tr td {
    padding: 3px 4px 10px 10px !important;
    vertical-align: top;
}
```

(The `vertical-align` directive would make sure that the parameter name is flushed to the top of the table cell when the description spans multiple lines).

**Comment by iosonofabio** [comment]
option 1 would be the preference of course
