### ISSUE TITLE
 Plot “vertex_label_angle” and “vertex_label_dist” do not work with Matplotlib backend

### ISSUE THREAD

**Issue by alex180500** [igraph/python-igraph#651]
**Describe the bug**
Some plot parameters do not work when using the matplotlib backend. Currently I've tested `vertex_label_angle` and `vertex_label_dist`.

**Resources**
More info can be found here:
https://igraph.discourse.group/t/vertex-label-angle-and-vertex-label-dist-are-not-working-in-python-with-matplotlib-backend/1279

**Version**
python-igraph = _0.10.4_
Python =  _3.11_

**Comment by iosonofabio** [comment]
thanks for spotting this. This exact syntax as specified in the current docs is a little challenging to implement in `matplotlib` because it does not scale well with zoom-in. However, it might actually look better than I'm imagining.

As stated in the discourse thread linked, could you make a PR?

**Comment by alex180500** [comment]
I don't think it will be too hard, it should just be a matter of changing the parameters on the `ax.text` function in the **drawing/matplotlib/graph.py** file.
I've never contributed here but I can try set this up this weekend.

**Comment by iosonofabio** [comment]
This will be included in #655 - no need to work on it anymore
