### ISSUE TITLE
matplotlib plotting: return Graph artist instead of Axes

### ISSUE THREAD

**Issue by iosonofabio** [igraph/python-igraph#657]
See #655 - this would improve consistency with the Cairo backend and also help users, however it breaks API so let's leave it for 0.11.

Once changed, docs need to be adapted as well, especially the visual style tutorial in the gallery.

Thanks @szhorvat for prompting the issue.

**Comment by ntamas** [comment]
Linking https://github.com/igraph/python-igraph/pull/655 here

**Comment by ntamas** [comment]
This is already done in the `dev` branch, right? I've just tested it and it already returns a `GraphArtist` for me. Can this issue be closed?
