### ISSUE TITLE
Vertex objects should have a wrapper to retrieve their outbound and inbound edges

### ISSUE THREAD

**Issue by kaymes** [igraph/python-igraph#66]
The Vertex object should have an easy way to access the outbound and inbound edges of that vertex.

Currently, the ways to access them is either using `g.incident(...)` or `g.es.select(...)`, both of which are cumbersome to use:

```
g=igraph.Graph(directed=True)
g.add_vertices(3)
g.add_edges([(0,1),(0,2),(2,0)])
vertex = g.vs[0]

# option 1
edges = [g.es[i] for i in g.incident(vertex, mode=igraph.IN)]

# option 2
edges = g.es.select(_target=vertex.index)
```

Instead, a property (or method) should be added to the Vertex class to retrieve the desired edge sequence. Something like the following should work:

```
edges = vertex.in_edges

edges = vertex.out_edges
```

**Comment by ntamas** [comment]
I have decided to implement `in_edges` and `out_edges` as methods, not properties - this is because `Edge` objects in the result are created on-the-fly, so the edges returned by repeated calls to these methods (with the same arguments) are not guaranteed to yield the same objects (according to object identity). A property would have given the false impression that these are pre-calculated.

**Comment by ntamas** [comment]
Some tests and a bugfix added in 55a6ee8

**Comment by kaymes** [comment]
If I see it correctly, the new methods return the index of the edges only (same as incident). It would, however, be much more useful in the Python world to return actual Edge objects. Otherwise one still has to write code like the following all the time:
```
edges = [g.es[i] for i in vertex.in_edges()]
```

**Comment by ntamas** [comment]
No, the new methods (`all_edges()`, `in_edges()` and `out_edges()`) will call the `incident()` method of the `Vertex` object (also newly added), which returns the edges themselves and not the indices. (Just like `neighbors()` called on a `Vertex` object also return `Vertex` objects).

**Comment by kaymes** [comment]
Ah, I see, thank you!
