### ISSUE TITLE
Alpha/Katz centrality in python-igraph

### ISSUE THREAD

**Issue by Marion-Artigaut** [igraph/python-igraph#672]
Related to [#1977](https://github.com/igraph/igraph/issues/1977#issue-1158121630)

**What is the feature or improvement you would like to see?**
Would it be possible to see the alpha_centrality() implemented in the python version of iGraph? This would follow implementation of Katz centrality in the C code as suggest in [#1977](https://github.com/igraph/igraph/issues/1977#issue-1158121630).

**Use cases for the feature**
This may be the most popular centrality measure not yet implemented in iGraph. It is essential for centrality measures in directed network.

**References**
Katz, Leo (Mar. 1953). “A new status index derived from sociometric analysis”. en. In: Psychometrika 18.1, pp. 39–43. ISSN: 1860-0980. DOI: 10.1007/BF02289026. URL: https://doi.org/10.1007/BF02289026 (visited on 05/22/2023).

Bonacich, Phillip and Paulette Lloyd (July 2001). “Eigenvector-like measures of centrality for asymmetric relations”. en. In: Social Networks 23.3, pp. 191–201. ISSN: 03788733. DOI: 10.1016/S0378-8733(01)00038-7. URL: https://linkinghub.elsevier.com/retrieve/pii/S0378873301000387 (visited on 05/22/2023)

**Related**
```alpha_centrality()``` in the R interface is related

**Comment by Marion-Artigaut** [comment]
@szhorvat Sorry I do not have any C programming experience so I am afraid I will not be able to provide any help.

**Comment by ntamas** [comment]
> Do you want to keep this open as a specific request to expose the functionality in Python after it's been implemented in C?

We can keep this open for the time being.

**Comment by ntamas** [comment]
There's a separate issue for this in the C core, and chances are that if the alpha centrality gets implemented there, it will automatically become available (due to code generation) in the upcoming `ctypes`-based variant of the Python interface, so I'm leaving the stale label here.

**Comment by szhorvat** [comment]
Let's just close this now, there's no need for duplicate issues.
