### ISSUE TITLE
Rarely _igraph.GraphBase.community_multilevel method assigns node to community which it has no edges

### ISSUE THREAD

**Issue by bahadirhanfiliz** [igraph/python-igraph#675]
**Describe the bug**

```
_igraph.GraphBase.community_multilevel method assigns node to community which it has no edges.
Example:
Graph:
A -> B
B -> C
D -> E
E -> F

com1: [A, B, C, D]
com2: [E, F]

code:
edges = list(zip(data.FROM_UNDIRECTED, data.TO_UNDIRECTED, data. EXPRESSION))
G = Graph.Tuplelist(edges, directed=False, weights=True)
weights = G.es['weight']
comm = igraph._igraph.GraphBase.community_multilevel (G, weights=weights, resolution=resolution)
communities = zip (G.vs['name'], comm)
igraph_Communities = pd.DataFrame(communities, columns=['Node', 'Community']) 
```

**To reproduce**
It is not possible to reproduce the problem every time. But in large dataset with 9.5M undirected edge data, I have seen a node assigned into a community with no edge relations.

**Version information**
0.9.10

**Comment by ftheberge** [comment]
This is a known issue with Louvain (community_multilevel) algorithm, it can return disconnected communities. This problem is not specific to igraph. You can try Leiden to avoid this issue.
