### ISSUE TITLE
Abnormal write_gml results: conflict with networkx?

### ISSUE THREAD

**Issue by atyakhtmpg** [igraph/python-igraph#679]
I observed that sometimes write_gml produces an abnormal file with non-ASCII symbols.
Apparently, it appears when some attributes of the graph are long and, at the same time, networkx is being imported AFTER igraph module.

**To reproduce**
With the attached 1cp.gml file as input,
this code:

```
import igraph
import networkx as nx
G = igraph.Graph()
G = igraph.read("1cp.gml",  format="gml")
G.write_gml("test_graph.gml")

```
produces trimmed output (see the non-ASCII symbol at the end of "abundances"):
<img width="1410" alt="image" src="https://github.com/igraph/python-igraph/assets/110911314/98d77353-9abd-4315-a1ea-79837eda08da">

And the following code:

```
import networkx as nx
import igraph
G = igraph.Graph()
G = igraph.read("1cp.gml",  format="gml")
G.write_gml("test_graph.gml")

```
produces the output without errors:
<img width="1420" alt="image" src="https://github.com/igraph/python-igraph/assets/110911314/8376e252-87a1-4cbb-bcde-eee3565f5de8">

Without the networkx import line, all works fine.

When the "samples" field is shorter in the input file, the error disappears.

**Version information**
`python-igraph` version 0.10.4 py311hcb6f00c_0 conda-forge

**Comment by szhorvat** [comment]
I think the attachment is missing. Can you add it? You may need to zip it before it can be uploaded

**Comment by atyakhtmpg** [comment]
Sure. Sorry for forgetting! Here it is.
[1cp.gml.zip](https://github.com/igraph/python-igraph/files/11745196/1cp.gml.zip)

**Comment by szhorvat** [comment]
I am not able to reproduce this with the following setup:

Python 3.9.6 on macOS 13.4, English locale.

igraph installed from PyPI with `pip`. `pip freeze` output:

```
igraph==0.10.4
networkx==3.1
texttable==1.6.7
```

Can you post all this information about your system?

**Comment by szhorvat** [comment]
Note that `G = igraph.Graph()` is not necessary in your example code, but this does not make any difference in the end.

**Comment by szhorvat** [comment]
I still can't reproduce it with Python 3.11.3, python-igraph 0.10.4 from conda-forge and NetworkX 2.8.4.

I wanted to let you know that most igraph contributors will be unavailable for a while. We'll get back to looking at this in about 2 weeks.

Since this seems related to NetworkX, also pinging @jarrodmilman

**Comment by szhorvat** [comment]
@atyakhtmpg Can you try to reproduce this without using conda, in an environment as clean as possible? For example, use your Linux distro's default Python, create a new virtual environment, `pip install igraph` and `pip install networkx` there, then try running your code again.

**Comment by vtraag** [comment]
Like @szhorvat, I'm unable to reproduce the problem. Perhaps there are other packages in your environment still that somehow interfere? I agree that it would be best to do this in a clear environment to try to to reproduce this, so that we might also be able to reproduce the problem.

**Comment by szhorvat** [comment]
@atyakhtmpg, are you able to reproduce this in a clean environment?

**Comment by atyakhtmpg** [comment]
Sorry for this delay. Followed your recommendations. Indeed, interestingly, on my Linux the bug did not reproduce in a clean environment with the suggested Python 3.11.3, python-igraph 0.10.4 from conda-forge and networkx 2.8.4. By installing package by package and testing, I will attempt to isolate the exact thing causing the problem to arise. Thank you for your guidance!

**Comment by atyakhtmpg** [comment]
UP: the problem starts manifesting when I adding numpy to the above-described environment.
numpy versions tested: 1.23.5 , 1.24.3 , 1.25.0 (latest)
When numpy is removed, the bug does not show up.

**Comment by ntamas** [comment]
Confirmed on my machine; will take a closer look at it later today.

**Comment by ntamas** [comment]
Hmmm, sorry, revert that. The file looks fine for me; attached is the test setup that I was using on macOS. Python 3.11, English locale.

[gml_bug_test.zip](https://github.com/igraph/python-igraph/files/11965988/gml_bug_test.zip)

You can try this by extracting the ZIP file and running the `run_test.sh` shell script inside it. It will do everything in a clear environment using your primary Python.

**Comment by atyakhtmpg** [comment]
(Of note, macOS does not appear to generate a bug for me too even using my initial setup and data.)

Dear @ntamas , thank you for your test setup, I downloaded it and ran it step by step on my Linux (created a venv, etc). Though it was from within a Conda environment with a fresh Python 3.11 (the primary Python version is lower and failed to run directly on you example). What I added is varied Numpy versions.
The result is: with Numpy 1.23.5 or 1.24.4 - no bug, 1.25.0 - bug.

**Comment by ntamas** [comment]
Okay, I've managed to reproduce this on my machine with a Docker container running Python 3.11.

What's weird is that the extra two bytes at the end of the string are not entirely random; they seem to be related to the length of the attribute somehow. If I start shortening the value of the attribute, the number represented by those two bytes (big endian format) is also decreased. I'll keep on debugging.

**Comment by ntamas** [comment]
This is now fixed in 72240a9. For the record, it had nothing to do with `numpy` or `networkx`; it was a memory management issue in one of the internal functions of igraph's Python interface that copied the internal buffer of a Python `bytes` object right after it was freed. 99% of the time it didn't cause a problem, but it did if the `bytes` object was long enough.

**Comment by szhorvat** [comment]
We need to set up ASan runs in the CI system.

**Comment by atyakhtmpg** [comment]
Thank you @ntamas !
