### ISSUE TITLE
Edges should have direct accessors to source and target Vertex objects

### ISSUE THREAD

**Issue by kaymes** [igraph/python-igraph#68]
Currently, the `source` and `target` properties of Edge objects return the index of the source and target vertex respectively. 

In Python, however, the user is more accustomed to use Vertex objects for interactions with the graph. Thus, the `source` and `target` properties should return Vertex objects instead.

I do realise, that changing this would break existing code that expects integer values. Thus, changing the existing behaviour is a decision that may not be done lightly. Two options come to mind:

**Option 1:**
Introduce new properties, e.g. `source_vertex` and `target_vertex` while keeping the old properties as they were.

**Option 2:**
It may be the case that the vast majority of programs are doing something like the following to retrieve the vertex already:
```
vertex = g.vs[edge.source]
```
In this case, it could be ensured, that the VertexSeq object also accepts a Vertex object as index and simply returns it again. Thus, the line above would remain valid even though `edge.source` isn't numeric any more.

**Comment by ntamas** [comment]
Option 1 seems reasonable. I'd rather not make assumptions about how people are using these attributes so I'd prefer option 1 to option 2. Stay tuned.
