### ISSUE TITLE
bindings for igraph_automorphism_group

### ISSUE THREAD

**Issue by swamidass** [igraph/python-igraph#683]
**What is the feature or improvement you would like to see?**

Bindings for igraph_automorphism_group in the python library.

https://igraph.org/c/doc/igraph-Isomorphism.html#igraph_automorphism_group

**Use cases for the feature**

We need to compute the topologically equivalent vertices (orbits) of a graph, and this can be computed fairly easily from the automorphism group. But there isn't a away to get this currently.

**References**

https://igraph.org/c/doc/igraph-Isomorphism.html#igraph_automorphism_group

**Comment by ntamas** [comment]
This is now implemented in 9cbc955 and will be released soon in a new official release.

**Comment by swamidass** [comment]
Thank you!
