### ISSUE TITLE
Incorrect arrowhead positioning with Cairo

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#684]
**Describe the bug**

Arrowheads are sometimes incorrectly positioned in multi-digraphs.

**To reproduce**

```python
import igraph as ig
g = ig.Graph([(0,1), (0,1), (1,0), (1,2), (2,0)], directed=True)
ig.plot(g, bbox=(300,300))
```

<img width="414" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/9b9818ad-26bb-4954-baf1-2ad2025dea23">

**Version information**

Current `main`, 28647e748cecc57754c9c8236357994b5eb89369

**Comment by ntamas** [comment]
Most likely also depends on other factors such as the random seed; see here:

<img width="366" alt="Screenshot 2023-06-30 at 12 43 09" src="https://github.com/igraph/python-igraph/assets/195637/d13cdfbd-111b-4f14-9a67-4c38eb0b80d9">

**Comment by ntamas** [comment]
<img width="412" alt="Screenshot 2023-06-30 at 12 45 29" src="https://github.com/igraph/python-igraph/assets/195637/fc5c5f5f-d424-4fb1-8127-8db46c36aed9">

Looks like we have problems only at certain angles.

**Comment by szhorvat** [comment]
Why is the outward curvature so different for each instance? There are some weird squiggles. Compare what Mathematica does:

![Uploading image.png…]()

**Comment by ntamas** [comment]
Because I screwed something up with the calculation of the Bezier control points :) Working on it.

**Comment by szhorvat** [comment]
Very nice!

<img width="632" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/b83c19af-9a74-4444-9408-5c89e3b2bac6">

Some edges are partly cut off. Is there a way to increase padding at the boundaries to avoid this?  I am not asking if it can be avoided automatically (which would be nice), but if I can change settings manually to tune the plot.
