### ISSUE TITLE
Notify significant projects that still refer to python-igraph instead of igraph

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#699]
On PyPI, `python-igraph` was renamed to `igraph` in October 2021. The standard way to install igraph is now:

```
pip install igraph
```

The `python-igraph` name [was kept functional](https://pypi.org/project/python-igraph/), with the intention to terminate support in September 2022. However, as of today (July 2023), over a third of downloads are still through `python-igraph`:

 - https://pypistats.org/packages/igraph
 - https://pypistats.org/packages/python-igraph

Here's the the fraction of `python-igraph` downloads based on a 2-week moving average:

<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/f4681761-7ab8-4d26-9eeb-495ce9354769">

This issue is to notify downstream igraph users (packages, educational resources, etc.) to start using the new name.

**Comment by szhorvat** [comment]
- [ ] https://github.com/cytoscape/py4cytoscape, see https://github.com/search?q=repo%3Acytoscape%2Fpy4cytoscape+python-igraph&type=code

**Comment by szhorvat** [comment]
Update on the fraction of `python-igraph` downloads. The following show the fraction based on a 2-week moving average, as well as daily data.

<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/39eae578-c362-481c-809c-3c802412a0e5">

<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/c1998336-4c60-487b-80f8-49d207f9d0f5">

There is a steady improvement, and I assume the situation will continue to improve as more of the above PRs get merged and as more downstream packages release new versions. Closing this issue now.

**Comment by szhorvat** [comment]
Updated plots as of today:

<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/79fbc4f8-d0b2-4b74-9448-47a68a444732">
<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/263cf3b3-0ab9-4310-ae68-2d80962ace27">

It's strange to see the mass of `python-igraph` downloads in March. Notice that the "fraction" value goes above 1 here. The fraction is calculated as `python-igraph` divided by `igraph` downloads, with the assumption that each `python-igraph` download also triggers an `igraph` downloads due to the dependency between the two. Since this ratio went above 1, there must have been lots of `python-igraph`-only downloads for some reason.

**Comment by ntamas** [comment]
Caching may screw the stats up. `pip` has a local cache of downloaded wheels on each machine, on a per-user basis. If the user has already downloaded `igraph==x.y.z` due to some project and another project that depends on `python-igraph==x.y.z` is installed, this will trigger a download for `python-igraph==x.y.z` but not `igraph==x.y.z` since that is already in the cache. Institutions may also use local institution-wise PyPI caches (like `devpi`).
