### ISSUE TITLE
Install issue CentOS release 6.3 due to missing HT_NEEDED in _igraph.so

### ISSUE THREAD

**Issue by dsth** [igraph/python-igraph#70]
-- it might help if i even type the correct section name DT_NEEDED - sorry.

hiya, figured i'd just mention that getting it to install on our cluster was a real pain. it seems it's due to an undefined symbols issue that in the end turned out to be a missing DT_NEEDED entry in igraph/_igraph.so within python_igraph-0.7.0-py2.7-linux-x86_64.egg - no idea why it manifested on CentOS release 6.3 - i'm not a python person at all so sorry if i'm using incorrect terminlogogy. that is LD_LIBRARY_PATH would not help as the linker wasn't even trying to find libigraph.so. added the entry to _igraph.so before realising that it was being stomped on by the egg packaging system and whenever it igraph was run it would extract the original version. when i repackaged the modified _igraph.so into python_igraph-0.7.0-py2.7-linux-x86_64.egg it all worked nicely after setting LD_LIBRARY_PATH etc.. 

dan

**Comment by ntamas** [comment]
Where did you get `python_igraph-0.7.0-py2.7-linux-x86_64.egg` from? Did you compile it yourself on CentOS 6.3?

**Comment by dsth** [comment]
that is a very good question. i had assumed it shipped with the tar i was asked to help out installing. it was python-igraph-0.7.0.tar but 

> tar tvf python-igraph-0.7.0.tar| grep '_igraph.so' -c 

yields nothing so i guess it was compiled as part of the setup.py install process. i've just checked and apparently the tar is that indicated by the package transabys (http://igraph.org/python/#downloads). rummaging in the setup.py. i'm guessing since it's a really outdated tool chain that  detect_from_pkgconfig in setup.py returned false and so the -I & -L requirements were manually specified and the -l one was forgotten. 

so more likely user error. 

thanks!

**Comment by dsth** [comment]
that is to say i'm guessing the -no-undefined flag is not used when generating the .so in the build process such as to allow its generation of the .so in the first place despite the missing definitions.

dan

**Comment by ntamas** [comment]
Chances are that the original `.egg` that you were using was compiled for an older version of CentOS and hence it did not work with the new version then. Building the package again from scratch on the new version should do the trick.
