### ISSUE TITLE
Inconsistent macOS min version between vendored C core and py-igraph glue code

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#703]
When compiling py-igraph in the default configuration on macOS 13.5, I see the following warnings (one for each object):

```
ld: warning: object file (vendor/install/igraph/lib/libigraph.a(z_sqrt.c.o)) was built for newer macOS version (13.0) than being linked (11.1)
```

This usually happens when `MACOSX_DEPLOYMENT_TARGET` or the equivalent `-mmacosx-version-min` compiler flag are set inconsistently between translation units that will be linked together. 

But I can't quite find where the minimum version of 11.1 is set for py-igraph. I suspect that you didn't set this manually, @ntamas, but it's done by setuptools, right? We should compile the C core with the same setting as the py-igraph glue code. The relevant CMake setting is https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by ntamas** [comment]
Does commit 92f0abd1 solve the problem?

**Comment by szhorvat** [comment]
Yes, but I am surprised since just setting the `MACOSX_DEPLOYMENT_TARGET` variable should normally be sufficient. Oh well.
