### ISSUE TITLE
Deprecated pandas usage?

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#705]
Running the test suite produces the following warning:

```
igraph/io/objects.py:422: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
```

The CI runs didn't catch it as it doesn't lead to a test failure.

Can you have a look, @iosonofabio ?

**Comment by ntamas** [comment]
FYI, happens with Pandas 2.1.0 but not with 2.0.3. I think it's an easy fix so I might take a quick look at it now.
