### ISSUE TITLE
Weighted graph support for `eccentricity()` and `radius()`

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#707]
**What is the feature or improvement you would like to see?**

Add weights support to `eccentricity()` and `radius()` (already present in the C core).

**Use cases for the feature**

So that these concepts can be applied to weighted graphs, and that there's feature parity between them and the related `diameter()` function.

**References**

 - https://github.com/igraph/igraph/pull/2385

**Comment by ntamas** [comment]
Implemented in e624df96
