### ISSUE TITLE
Graph.layout_drl() does not process options argument

### ISSUE THREAD

**Issue by Alexander-Eck** [igraph/python-igraph#71]
It seems that `Graph.layout_drl()` does not process the `options` argument properly. I am using igraph-python 0.7.1:
```python
>>> import igraph
>>> print(igraph.__version__)
0.7.1
```

My experiments run with Python 3.4 64-bit on Windows 10, and as input I utilized two different networks derived from real-world data, one consisting of roughly 20.000 nodes and 30.000 edges, the second with roughly 150.000 nodes and 300.000 edges.

Specifically, I attempted to pass a `dict` of options, as specified in the documentation. For example this one:
```python
DRL = {
    'edge_cut': 0.85,  # default: 0.8
    'init_iterations': 0,  # default: 0
    'liquid_iterations': 300,  # default: 200
    'expansion_iterations': 400,  # default: 200
    'cooldown_iterations': 250,  # default: 200
    'crunch_iterations': 400,  # default: 50
    'simmer_iterations': 150  # default: 100
}
```
This seems to have no effect whatsover: The runtime remains roughly constant, no matter how many iterations I specify, and the resulting plot has the same characteristics. This also applies when I provide the full `dict` of possible paramters (like `x_temperature`) or when passing one of the five defaults presets, e.g., `options = coarsest`.

I checked the shipped wrapper code for any inconsistencies, but it seemingly passes the values to the C function just as one would expect (not that I'm an expert in Pyhton->C interfaces, though).

**Comment by benmaier** [comment]
I have the same problem.

**Comment by ntamas** [comment]
I'll look into this.
