### ISSUE TITLE
doc material is not distributed within python-igraph source tarball 

### ISSUE THREAD

**Issue by jgmbenoit** [igraph/python-igraph#711]
The the latest python-igraph source tarball (version 0.10.8) does not contain the material needed to compose the documentation. Please provide it.

**Comment by iosonofabio** [comment]
Good point. Building the docs locally currently has a bug on my machine, even though readthedocs builds are correct. I was trying to debug yesterday night, it has something to do with the proctor sphinx extension.

If anyone wants to/has a chance to take a look, you could start by running `scripts/mkdoc.sh`

**Comment by ntamas** [comment]
I think  I've managed to fix most of the issues with the doc build in the few recent commits. On my machine, checking out the Github repo, building a source tarball with `pipx run build -s`, and then extracting the source tarball to another folder now yields a folder where running `scripts/mkdoc.sh` without doing anything else builds the docs correct in `doc/html`.
