### ISSUE TITLE
Small typo in documentation for Graph().__init__

### ISSUE THREAD

**Issue by lubin-liu** [igraph/python-igraph#716]
Small typo in [`Graph().__init__`](https://python.igraph.org/en/stable/api/igraph.Graph.html#__init__)

> the number of vertices. Can be omitted, the default is zero. Note that if the edge list contains vertices with indexes larger than or equal to **m**, then the number of vertices will be adjusted accordingly.

I think the `m` should be `n`

**Comment by ntamas** [comment]
Fixed, thanks!

**Comment by szhorvat** [comment]
@ntamas Can you also fix it in the `edge_attrs` section of the same docstring?

**Comment by ntamas** [comment]
It does not have to be fixed there; `m` refers to the number of _edges_ and it is clealy stated in the text.
