### ISSUE TITLE
DAG Generation

### ISSUE THREAD

**Issue by SigireddyBalasai** [igraph/python-igraph#724]
**What is the feature or improvement you would like to see?**
I need to create a random Direct Acyclic Graph For some statistical studies and i need to create using list of predefined nodes

**Use cases for the feature**
Explain when and for what purpose the feature would be useful.

**References**
List any relevant references (papers or books describing relevant algorithms).

**Comment by ntamas** [comment]
You can generate a random undirected Erdos-Renyi graph with Graph.Erdos_Renyi() and then convert it into directed with the .to_directed(mode=“acyclic”) merhod. The returned graph will always be acyclic.
