### ISSUE TITLE
Improvement of Readme.md

### ISSUE THREAD

**Issue by CrypticRevenger** [igraph/python-igraph#726]
**What is the feature or improvement you would like to see?**

- Headers: Improved the headers to make them more descriptive and informative.

- Sentence Structure: Rewrote some sentences to enhance clarity and readability.

- Punctuation: Corrected punctuation and capitalization for consistency.

- Grammar: Fixed grammatical errors and awkward phrasings.

- Notes and Warnings: Clarified information under "Linking to an Existing igraph Installation" and added emphasis where necessary.

- Typographical Errors: Corrected typos and spelling errors.

**Comment by szhorvat** [comment]
Are you trying to open a pull request?

**Comment by CrypticRevenger** [comment]
> Are you trying to open a pull request?

yes

**Comment by CrypticRevenger** [comment]
@szhorvat can you please merge it. 
It will be very helpful to me. 
Thank you.

**Comment by szhorvat** [comment]
> > Are you trying to open a pull request?
> 
> yes

In that case there is no need to open an issue. Please open issues only for bugs, or well-motivated feature requests.

> It will be very helpful to me.

What personal benefit do you gain from this PR getting merged? I hope this is not about improving [your contribution stats](https://github.com/CrypticRevenger#-github-stats). Please also consider whether the changes you propose are a clear benefit to the project.

**Comment by CrypticRevenger** [comment]
> What personal benefit do you gain from this PR getting merged? I hope this is not about improving [your contribution stats](https://github.com/CrypticRevenger#-github-stats). Please also consider whether the changes you propose are a clear benefit to the project.
I am trying to contribute in hacksquad and I am totally new to git. That's why  I am trying to contribute in different repos.

**Comment by CrypticRevenger** [comment]
@szhorvat Can you please suggest me what can I do in this repo to make it better.

**Comment by szhorvat** [comment]
I made a suggestion about how to contribute with writing-based tasks within the PR you opened. Please see the comment there.
