### ISSUE TITLE
Test suite error on amd64 architecture involving arpack

### ISSUE THREAD

**Issue by jgmbenoit** [igraph/python-igraph#728]
The Debian package appears to have building issue on amd64 arch at test time as reported in [Debian bug #1054706](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054706). This issue seems related to arpack. I can not reproduce the issue on my amd64 box within an up-to-date  Debian Sid environment.  As such this issue looks reminiscent of the issue [#1469](https://github.com/igraph/igraph/issues/1469) with the `igraph` C library.

**Comment by szhorvat** [comment]
I think the link to the Debian bug is not correct, can you fix it?

**Comment by jgmbenoit** [comment]
On my side the first link leads to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054706 as expected.

**Comment by szhorvat** [comment]
That bug is titled:

```
e-antic: FTBFS: ../../../libeantic/test/main.cpp:4:10: fatal error: catch2/catch.hpp: No such file or directory
```

Is this what you meant to post? I don't see any mention of igraph.

**Comment by jgmbenoit** [comment]
Indeed. I am sorry for that.  The issue is [Debian bug #1054721](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054721). Actually the issue resolved by itself.

**Comment by szhorvat** [comment]
Make sure you are testing with ARPACK 3.9.1 installed, and if you can reproduce it, even intermittently, let us know. 

This problem _may_ be caused by a bug ARPACK 3.9.0. It is going to be random, and we don't have control over the randomness (ARPACK won't let us set a seed). So to make sure, you'd have to run the test multiple times.

**Comment by szhorvat** [comment]
We saw something similar on conda-forge actually, with an older ARPACK that doesn't have the 3.9.0 bug ...  https://github.com/conda-forge/python-igraph-feedstock/issues/77

**Comment by jgmbenoit** [comment]
According to the last [changelog of the Debian ARPACK package](https://metadata.ftp-master.debian.org/changelogs//main/a/arpack/arpack_3.9.1-1_changelog) the test occured with version 3.9.1. Whatever, with respect to your comments, I reopened the Debian bug and I changed its title  so that people can feed it.
