### ISSUE TITLE
Graph.copy does not perform a deep copy

### ISSUE THREAD

**Issue by kaymes** [igraph/python-igraph#74]
The documentation of Graph.copy states:

> copy()
> Creates an exact deep copy of the graph.

This is not true. Copy only creates a shallow copy which means no copies of the graph attributes are created.

The following code should pass if a deep copy was created. However, since the 'foo' attributes are not actually copied, the final three assertions all fail.

```
import igraph

g = igraph.Graph.Full(3)

g['foo'] = []
g.vs[0]['foo'] = []
g.es[0]['foo'] = []

h = g.copy()

assert(h['foo'] == [])
assert(h.vs[0]['foo'] == [])
assert(h.es[0]['foo'] == [])


g['foo'].append('bar')
g.vs[0]['foo'].append('bar')
g.es[0]['foo'].append('bar')

assert(h['foo'] == [])
assert(h.vs[0]['foo'] == [])
assert(h.es[0]['foo'] == [])

```

I suggest to update the documentation to reflect this behaviour.

**Comment by delete000** [comment]
Is there a way to generate a truly deep copy of a graph object?

**Comment by ntamas** [comment]
A pickle-unpickle cycle should do the trick.

**Comment by delete000** [comment]
Pickle/unpickle works, but requires temporary files. Any way to avoid that? I've tried a bunch of different things and somehow attributes of the original graph are affected when performing operations on the copy.

**Comment by delete000** [comment]
Any ideas on how to circumvent pickle and still get a true deep copy? Unfortunately I need to have large numpy arrays as attributes and pickle does not like that: https://stackoverflow.com/questions/28068872/memoryerror-with-pickle-in-python

**Comment by ntamas** [comment]
You can try messing around with the result of calling the `__reduce__()` method of the graph. It returns a 3-tuple containing `(func, args, kwds)` such that calling `func(*args, **kwds)` reproduces the graph. This is what pickling uses, but the `pickle` module processes `args` and `kwds` further, recursively, to ensure that every object in there is deep-copied.

Currently, `kwds` is an empty dict and `args` contains the arguments passed to the graph constructor in the following order:

* number of vertices
* edge list
* whether the graph is directed
* dict of graph attributes
* dict of vertex attributes
* dict of edge attributes

You can deep-copy the values in the three last dicts manually and then pass the copies along with the first three arguments (number of vertices, edge list, directedness) to the `Graph` constructor and it should work.

**Comment by delete000** [comment]
Thank you, that should do it. It would perhaps be useful to have this functionality built into the Graph class.

**Comment by delete000** [comment]
Could one perhaps use deepcopy() from the copy module instead? It seems to be working fine:
`In [41]: dg = deepcopy(tg)
In [42]: id(tg.vs[0]['attr'])
Out[42]: 140706025669768
In [43]: id(dg.vs[0]['attr'])
Out[43]: 140706022699160`

**Comment by ntamas** [comment]
Hmmm, that's true, `deepcopy()` uses `__reduce__` under the hood, which is the same mechanism as the one used by `pickle()`. Maybe NumPy arrays are deepcopy-friendly but not pickling-friendly, so that's why `deepcopy()` works for you but pickling doesn't. I'll extend the documentation nevertheless and mention `deepcopy()` explicitly.
