### ISSUE TITLE
Handling of neighbouring vertices in vertex connectivity calculations not properly documented

### ISSUE THREAD

**Issue by AlainKadar** [igraph/python-igraph#740]
**Describe the bug**
Running `vertex_connectivity` gives inconsistent results when `source` and `target` are connected. The python documentation reports `'error'`, `'infinity'`, and `'ignore'` are valid arguments to deal with this case but the code for conversion to a `C` argument shows that the valid arguments are `'error'`, `'negative'`, `'number_of_nodes'`, `'nodes'`, `'ignore'` are valid and so these should be listed in the python documentation:
https://github.com/igraph/python-igraph/blob/ecace80005600587901c3f135071ae6bfea8597b/src/_igraph/convert.c#L486-L497

**To reproduce**
For example, the following does not return infinity:

```
import igraph as ig

g = ig.Graph()
g.add_vertices(4)
g.add_edges([(0,1),(1,2),(2,3)])
g.vertex_connectivity(source=1, target=2, neighbors='infinity')
```

**Version information**
Which version of `python-igraph` are you using and where did you obtain it?
Version `0.11.3`, obtained from `conda`.

**Comment by ntamas** [comment]
Thank you, this is now fixed in the sense that the documentation now correctly lists all the options that are available in the C core.
