### ISSUE TITLE
load graph from graph-tool

### ISSUE THREAD

**Issue by amwps290** [igraph/python-igraph#741]
**Describe the bug**
I want to load data from a graph-tool graph, but get wrong.

error message:

```
Traceback (most recent call last):
  File "/root/code/python/graph_test/igraph_test.py", line 12, in <module>
    g = Graph.from_graph_tool(gt1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/software/anaconda3/envs/gt/lib/python3.12/site-packages/igraph/io/libraries.py", line 253, in _construct_graph_from_graph_tool
    graph.vs[i][key] = prop[i]
                       ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**To reproduce**
Steps or minimal example code to reproduce the problem.

```python
#!/bin/env python

from igraph import *
import graph_tool.all as gt
import timeit

gt1 = gt.load_graph("pgp.xml")
ut1 = gt.load_graph("escorts.xml")



g = Graph.from_graph_tool(gt1)
u = Graph.from_graph_tool(ut1)
```

**Version information**
Which version of `python-igraph` are you using and where did you obtain it?

igraph:0.11.3
python:3.12.0
graph-tool:2.58

**Comment by szhorvat** [comment]
Can you make the example complete? We don't have the data files that you are loading.

Ideally, make an example that does not rely on any data files. If not possible, please provide the data files.

**Comment by amwps290** [comment]
the pgp.xml download from https://networks.skewed.de/net/pgp_strong/files/pgp_strong.xml.zst,
the escorts download from https://networks.skewed.de/net/escorts/files/escorts.xml.zst.

**Comment by ntamas** [comment]
I'll take a look, stay tuned.
