### ISSUE TITLE
Expose igraph_from_prufer()

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#750]
**What is the feature or improvement you would like to see?**

Please expose `igraph_from_prufer()`

**Use cases for the feature**

Create trees from Prüfer sequences, obviously :-)

**References**

https://igraph.org/c/html/latest/igraph-Generators.html#igraph_from_prufer

**Comment by ntamas** [comment]
This is going to be a static method on the `Graph` class. Would you prefer it to be called `Graph.Prufer()` or `Graph.From_Prufer()`. The latter is a natural translation of the name of the original function, but none of the other static methods start with `From_` yet.

**Comment by ntamas** [comment]
FWIW the code is ready, I just need to know your preference before committing.

**Comment by szhorvat** [comment]
I'm really not sure. I think I'd be happy with `Prufer()`, it seems a bit more consistent, compare e.g. `Adjacency()`

We already have `to_prufer()`, which is lowercase. Constructors are uppercase. There shouldn't be any confusion.
