### ISSUE TITLE
Tutorial makes the impression that `bbox` option should work with Matplotlib

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#752]
The `bbox` plot option does not work with the Matplotlib backend, but the tutorial makes the impression that it should. This should be clarified in the tutorial.

**Comment by ntamas** [comment]
I have updated the tutorial and clarified that htese options are for Cairo only. (I'm not sure whether we could provide a sensible replacement for Matplotlib - there are just too many backends in Matplotlib and for certain backends it does not even make sense to specify a bounding box, plus we are always plotting on a Matplotlib _axis_, which does not have a width or a height anyway).

I could not update the Spanish tutorial, though. @iosonofabio Maybe you or your students could help here?

**Comment by iosonofabio** [comment]
Thanks @ntamas . I can take a look later today.
