### ISSUE TITLE
Tables in the tutorial should wrap text

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#753]
There is no wrapping in the tables in the tutorial. One must scroll repeatedly to read the text.

Example:

https://python.igraph.org/en/stable/tutorial.html#edge-attributes-controlling-graph-plots

<img width="745" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/12607404-6b2f-4ee8-a40a-44fc76c11282">

<img width="746" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/da00ebbe-921a-4867-8411-ced88cd9a7e1">

**Comment by ntamas** [comment]
This is a common issue with `sphinx_rtd_theme` and apparently it's a design decision. There's a pretty long discussion [over there](https://github.com/readthedocs/sphinx_rtd_theme/issues/117). I'll go through it tomorrow and try to distill some workaround.

**Comment by szhorvat** [comment]
If this is difficult, an option is to switch from tables to lists.

**Comment by ntamas** [comment]
Should be fixed now by 16c73795
