### ISSUE TITLE
edge_attrs not available anymore

### ISSUE THREAD

**Issue by pucicu** [igraph/python-igraph#768]
In the past I have used `G = ig.Graph.Adjacency(mat.tolist(), mode="undirected", edge_attrs=["CoWorks"])` to creat a network. But since updating to a more up-to-date igraph version, I get this error:

```Traceback (most recent call last):
  File "/Users/marwan/Volumes/MEGA/rp/./bib2net.py", line 282, in <module>
    G = ig.Graph.Adjacency(mat.tolist(), mode="undirected", edge_attrs=["CoWorks"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _construct_graph_from_adjacency() got an unexpected keyword argument 'edge_attrs'
```

Obviously the argument `edge_attrs` was removed for no reason. It is always a pleasure to revise previously well-running code after updates break downward compatibility. Great job!

**Comment by szhorvat** [comment]
I don't believe `edge_attrs` was ever a valid parameter for `Graph.Adjacency`. This method simply ignored unknown keyword parameters.

We reserve the issue tracker for bug reports and feature requests. If you wish to discuss the usage of igraph, or ask for support, you are welcome to do so [on the forum](https://igraph.discourse.group/) _for as long as you keep your tone civil_.

**Comment by ntamas** [comment]
Indeed, `Graph.Adjacency()` used to accept extra positional and keyword arguments for no reason as it did not do anything with these arguments. So, the `edge_attrs` argument that you were using did not do anything at all if my understanding of the code is correct.

The erroneous handling of extra positional and keyword arguments was added here:

https://github.com/igraph/python-igraph/commit/2680e61fe228726462fa88a99bcb9783417cdd8d

Later on, we moved several graph constructors to separate functions as part of a larger refactoring, and the new signature did not include the erroneous treatment of extra arguments any more:

https://github.com/igraph/python-igraph/commit/7b9267f536c244754ca796362f1f957dd53507db

**Comment by pucicu** [comment]
Hi Tamás,
thanks for understanding and your patience with my comment. It was not supposed to be personal. It is just the general feeling when working with Python or Julia which change so quickly that my code is always broken after some months. 

I used edge_attr to get a specific name of the edge weight in Gephi (after exporting the network as a graphML file where this attribute was indeed recognised) and the weights were directly used from the values in matrix _A_. It was a quite nice feature. Now I have construct the (weighted) graph differently, it seems. I'm still trying out to get it correctly done.

It seems it must be something like
```
G = ig.Graph.Adjacency((mat != 0).astype(int), mode="undirected")
for edge in G.es:
        s = edge.source
        t = edge.target
        G.es[edge.index]['CoWorks'] = mat[s, t]
```

(which is a bit longer than `G = ig.Graph.Adjacency(mat.tolist(), mode="undirected", edge_attrs=["CoWorks"])`)
