### ISSUE TITLE
Request for copy constructor for `igraph.Graph` 

### ISSUE THREAD

**Issue by yunesj** [igraph/python-igraph#77]
I think it would be useful to have a copy constructor for `igraph.Graph`. Having a copy constructor would facilitate subclassing. Without a copy constructor, the subclass needs to know which of the base class attributes need to be copied.

Please let me know if there's a better way.

Thanks!

```
>>> class ProteinNetwork(igraph.Graph):
...     def __init__(self, g=None):
...         super(ProteinNetwork, self).__init__(g)
... 
>>> g = igraph.Graph(1)
>>> protein_network = ProteinNetwork(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
  File "/Users/jeff/Workspaces/agca-directed/venv/lib/python2.7/site-packages/igraph/__init__.py", line 207, in __init__
    GraphBase.__init__(self, nverts, edges, directed)
TypeError: an integer is required
```

**Comment by ntamas** [comment]
I'm not quite sure what you are trying to achieve here. Is an instance of your `ProteinNetwork` class also a `Graph` on its own? In that case, you don't need a copy constructor - you just construct it in exactly the same way as you would do it with any igraph Graph object. The original constructor of the graph would just work, as well as any class method that would create a graph:

```
class ProteinNetwork(igraph.Graph):
    pass

>>> g = ProteinNetwork.Formula("A-->B, B-->C, A-->C, D-->E")
>>> type(g)
__main__.ProteinNetwork
>>> isinstance(g, igraph.Graph)
True
>>> g.decompose(mode="weak")
[<__main__.ProteinNetwork at 0x10778b528>, <__main__.ProteinNetwork at 0x10778b718>]
```

On the other hand, if your `ProteinNetwork` class just _contains_ a graph, then you should do it with object composition instead:

```
class ProteinNetwork(object):
    def __init__(self, g=None):
        self.graph = g
```

Does this solve your problem? If not, please tell me a bit more about what exactly you want to achieve.

For what it's worth, graph have a `copy()` method that let you create an exact copy of a graph, including its attributes, but then the copy will belong to exactly the same class as the one you created the copy from.

**Comment by yunesj** [comment]
It hadn't occurred to me that any class method would produce the extended class. Now I'm as happy as a clam.
```
>>> ProteinNetwork.Tree(2, 2)
<__main__.ProteinNetwork object at 0x104628718>
```
