### ISSUE TITLE
is_directed() method not working properly?

### ISSUE THREAD

**Issue by mcharrak** [igraph/python-igraph#777]
**Describe the bug**
The `is_directed()` method returns `True` for graphs that are undirected.

**To reproduce**

```python
# include the necessary imports to run the below code
import networkx as nx
import numpy as np
import igraph as ig

# do a toy example: 1. create symmetric matrix 2. convert to igraph 3. check if it is directed
# create symmetric matrix
symmetric_matrix = np.array([[0, 1, 2], [1, 0, 3], [2, 3, 0]])

# convert to igraph
G_symmetric = ig.Graph.Adjacency(symmetric_matrix.tolist())

# check if it is directed
print('G_symmetric is directed:', G_symmetric.is_directed())

# double check with is_directed() method from networkx package
G_symmetric_nx = nx.from_numpy_array(symmetric_matrix)
print('G_symmetric is directed:', nx.is_directed(G_symmetric_nx))

**Comment by ntamas** [comment]
`ig.Graph.Adjacency()` has a `mode` argument that specifies whether you want to create a directed graph or an undirected graph (see [here](https://igraph.org/python/doc/api/igraph.Graph.html#Adjacency)). The default value of `mode` is `"directed"`, which means that the returned graph will be directed. Hence, the `is_directed()` method returns the correct value. In contrast.

FWIW, NetworkX's `from_numpy_array()` function defaults to creating an undirected graph unless you specify otherwise with `create_using=nx.DiGraph`.

**Comment by mcharrak** [comment]
Thank you. Why would the default be directed in the igraph method? What advantage would that have?

**Comment by ntamas** [comment]
Adjacency matrices can easily represent directed graphs. Making undirected the default would require a decision about how to handle the case when you pass a non-symmetric adjacency matrix to the function as this can be handled in multiple ways (see all the other options of the `mode` parameter of `Graph.Adjacency`). Making directed the default sidesteps the problem as all inputs are then completely valid.

**Comment by szhorvat** [comment]
You can ask the same question for a default of `"undirected"`. What advantage does it have? What is more useful depends on your specific use case. Backwards compatibility is to be considered as well, so changing this at this point is not productive.

That said there is ongoing work to produce an entirely redesigned Python interface to igraph, which will hopefully be _more consistent_ in its default choices, and therefore more predictable.

**Comment by mcharrak** [comment]
Thanks. 

Given an adjacency matrix, how would you recommend using this library to determine whether the graph represented by the matrix is directed or undirected? From my understanding, the mode value needs to be set correctly when creating the graph. However, if the mode value is unknown, how can one use the is_directed() method to make this determination?

**Comment by szhorvat** [comment]
That's not really a meaningful question.

Here's an undirected graph:

<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/8378ebf9-8654-4871-b8a0-8dd28076bb1f">

Here's a directed graph:

<img width="360" alt="image" src="https://github.com/igraph/python-igraph/assets/1212871/7b61545b-b9ef-4165-92fc-c68cb1805656">

They have the same adjacency matrix. It is up to you to determine how you want to interpret the matrix.

Of course, adjacency matrices of undirected graphs are symmetric, so if you want an undirected graph, you must supply a symmetric matrix.

**Comment by mcharrak** [comment]
Thanks. I do understand the difference; however, I am starting to wonder what the point of the `is_directed` method is at all?

**Comment by szhorvat** [comment]
I suggest you read up on the concept of directed and undirected graphs in a graph theory textbook. In the former, connections are directional, in the latter they are not.
