### ISSUE TITLE
libblas not loaded

### ISSUE THREAD

**Issue by zhulcher** [igraph/python-igraph#781]
Hello,
I have recently updated my mac M1 to Sonoma 14.5, and before, I was using igraph from conda in a couple different packages (wonderful package by the way). However, today, I discovered that I can no longer import igraph at all, and instead get the following:

```shell
(base) [~]$ python3 -c 'import igraph'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/miniconda3/lib/python3.11/site-packages/igraph/__init__.py", line 25, in <module>
    from igraph._igraph import (
ImportError: dlopen(/Users/user/miniconda3/lib/python3.11/site-packages/igraph/_igraph.abi3.so, 0x0002): Library not loaded: @rpath/libblas.3.dylib
  Referenced from: <02509E24-7ACD-33C4-AD2D-6FF0D9929080> /Users/user/miniconda3/lib/python3.11/site-packages/igraph/_igraph.abi3.so
  Reason: tried:  '/libblas.3.dylib' (no such file), '/Users/user/miniconda3/lib/python3.11/site-packages/igraph/../../../libblas.3.dylib' (no such file), '/Users/user/miniconda3/lib/python3.11/site-packages/igraph/../../../libblas.3.dylib' (no such file), '/Users/user/miniconda3/bin/../lib/libblas.3.dylib' (no such file), '/Users/user/miniconda3/bin/../lib/libblas.3.dylib' (no such file), '/usr/local/lib/libblas.3.dylib' (no such file), '/usr/lib/libblas.3.dylib' (no such file, not in dyld cache)
(base) [~]$ ls /Users/user/miniconda3/bin/../lib/libblas.3.dylib
/Users/user/miniconda3/bin/../lib/libblas.3.dylib
``` 

This is strange, because as can be seen from the final line, this dylib is indeed present where it is looking for it.

my current igraph version is 0.11.5

**Comment by szhorvat** [comment]
Have you tried creating a new conda environment and installing packages in it from scratch? Conda environment do sometimes get corrupted.

**Comment by ntamas** [comment]
Also, `ls /Users/user/miniconda3/bin/../lib/libblas.3.dylib` won't tell you if the file is just a dangling symlink to a file that does not exist any more. Try `ls -la /Users/user/miniconda3/bin/../lib/libblas.3.dylib` to get more information.
