### ISSUE TITLE
`VertexCover.__plot__` `mark_groups` argument does not behave correctly and can cause a crash

### ISSUE THREAD

**Issue by Aethor** [igraph/python-igraph#789]
**Describe the bug**
`VertexCover.__plot__` `mark_groups` specifies in the doc that it accepts a "dict mapping cluster indices or tuples of vertex indices to color names". However, giving such a dict results in an `AttributeError`:

`AttributeError: 'dict' object has no attribute 'iteritems'`

This is because `mark_groups` is parsed using `igraph.clustering._handle_mark_groups_arg_for_clustering`, which uses `iteritems` that was removed in Python3. Using `items` instead fixes the issues. I'm happy to provide a PR if needed.

**To reproduce**
```python
import igraph as ig
import matplotlib.pyplot as plt


g = ig.Graph(edges=[[0, 1], [2, 3]])
clusters = [[0, 1], [2, 3]]
cover = ig.VertexCover(g, clusters)
fig, ax = plt.subplots()
ig.plot(
    cover,
    target=ax,
    mark_groups={0: "red", 1: "green"},
)
plt.show()
```

Note that there is a workaround:

```python
import igraph as ig
import matplotlib.pyplot as plt


g = ig.Graph(edges=[[0, 1], [2, 3]])
clusters = [[0, 1], [2, 3]]
cover = ig.VertexCover(g, clusters)
fig, ax = plt.subplots()
ig.plot(
    cover,
    target=ax,
    mark_groups={0: "red", 1: "green"}.items(), # <= ensure correct parsingof mark_groups
)
plt.show()
```

**Version information**
0.11.3, obtained from pypi using pip. (but 0.11.6 should also be subject to the bug as the related code is the same)

**Comment by ntamas** [comment]
Thanks for the report, this is now fixed in the source.
