### ISSUE TITLE
All-to-all shortest paths?

### ISSUE THREAD

**Issue by jlost** [igraph/python-igraph#793]
Hi, I don't see an obvious way to return shortest paths for all-to-all.
I did see `Graph.distances`, however that seems to return a matrix of the shortest path distances, discarding the paths themselves. `output` is not a valid keyword argument, so I can't supply `vpath`.
Other methods like `get_all_paths` would need to be called in a loop because they only accept a single source vertext. The loop would wasteful because Dijkstra's calculates the full all-to-all with each call, correct?
Am I missing something?

**Comment by szhorvat** [comment]
> The loop would wasteful because Dijkstra's calculates the full all-to-all with each call, correct?

No, Dijkstra's algorithm computes one-to-all paths. Just use the loop.

Please use the forum for support in the future.  https://igraph.discourse.group/
