### ISSUE TITLE
please support reading/writing from stream-like objects, such as StringIO

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/python-igraph#8]
_From @gaborcsardi on May 4, 2013 18:59_

this would save having to write temporary files everywhere

$ python
Python 2.5.5 (r255:77872, Feb  2 2010, 00:25:36) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from igraph import Graph
> > > g = Graph()
> > > from cStringIO import StringIO
> > > f = StringIO()
> > > print >>f, "test"
> > > f.getvalue()
> > > 'test\n'
> > > f = StringIO()
> > > g.write_graphml(f)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: string or file handle expected

---

Imported from Launchpad using lp2gh.
- date created: 2010-04-19T19:01:45Z
- owner: infinity0
- assignee: ntamas
- the launchpad url was https://bugs.launchpad.net/bugs/566854

_Copied from original issue: igraph/igraph#326_

**Comment by gaborcsardi** [comment]
(by ntamas)
The Python interface of igraph builds on a core library implemented in C. The core library is almost completely ignorant about the higher level interfaces, it simply expects a FILE* pointer and it uses the usual C functions (fprintf and stuff) to write to it. Hence, only those objects can be used in the IO functions in the Python interface that have an underlying FILE* handle and also have a corresponding Python API call that lets me to extract that pointer from the Python object. This does not hold for cStringIO.StringIO as far as I know.

The only workaround I can think of right now is that whenever a StringIO object (or any other that has a "write" method like Python stream-like objects do) is passed there, I automatically create a temporary file, write the whole stuff there using igraph's C core, then read it back and call the write() method of the StringIO object. This would work, but it's a bit clumsy. I will check the source code anyway and see if it can be added easily.

**Comment by gaborcsardi** [comment]
(by infinity0)
oh, i see - i was under the impression it would be a trivial change, as in just have a less strict test or something. but never mind, i'll just stick with tempfile.TemporaryFile for now, that works alright too.

**Comment by gaborcsardi** [comment]
(by infinity0)
just making a note that if anyone needs to write to RAM for performance reasons, then they can use

  with TemporaryFile(dir="/dev/shm") as fp:
    g = Graph.Read_GraphML(fp)

which is a tmpfs mount on debian systems (and spills over into swap if needed).

**Comment by jeremydouglass** [comment]
I ended up using this approach to import n-column data from a list of tuples without needing to manage 

    import tempfile
    def tempData(edgelist):
        with tempfile.NamedTemporaryFile(delete=False) as fp:
            for line in edgelist:
                fp.write('\t'.join(unicode(v).encode('ascii', 'ignore') for v in line)  + '\n')
        return fp.name

Using tempData as a wrapper around the in-memory list -- this puts it in a tmp file, flushes / closes it, and returns the file handle, making the data readable by Read_Ncol without having to manually manage files on disk.

    g = Graph.Read_Ncol(tempData(edgelist))

**Comment by jeremydouglass** [comment]
@ntamas is this closed because it was added, or is it wont-add?

**Comment by ntamas** [comment]
Right now it can't be added because of the limitations of the underlying C library. (The C library takes `FILE*` only). We are thinking about ways to handle this in the underlying C library such that we could work with not only `FILE*` objects but arbitrary data sources that yield chunks of data until they are exhausted. I'm thinking about having some kind of "parser" objects in the C layer that you can create, push data into it repeatedly, and then close it and ask it to retrieve the graph that was produced from the data. This would allow us to support arbitrary stream-like objects in the Python layer. We will re-open this issue once the underlying C library starts to support this use-case.
