### ISSUE TITLE
Request for adding "cluster_louvain" from R version to Python version

### ISSUE THREAD

**Issue by Kuu6** [igraph/python-igraph#80]
It could be useful to have the method cluster_louvain also in the Python version.

Thanks!

**Comment by ntamas** [comment]
It's there but it's called [`community_multilevel()`](http://igraph.org/python/doc/igraph.GraphBase-class.html#community_multilevel).

**Comment by Kuu6** [comment]
Thanks @ntamas , I couldn't find it.
Cheers!

**Comment by harryprince** [comment]
@Kuu6 it is` igraph::multilevel.community()` in R
