### ISSUE TITLE
`setuptools < 72.2.0` requirement prevents installation in some environments

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#801]
The `setuptools < 72.2.0` requirement prevents installation in some environments.

https://github.com/igraph/python-igraph/blob/cc3e753780d3da8c6cf12a9ddd5fd2ce06d6f67d/pyproject.toml#L4-L6

I can't update the MacPorts port because currently MacPorts has setuptools 75.2.0

Reference for setuptools versions in various package managers: https://repology.org/project/python:setuptools/versions

**Comment by ntamas** [comment]
https://github.com/igraph/python-igraph/commit/1e525dd8a36449022931d763310ec967f7da9187 should hopefully fix this; the pin to setuptools < 72.2 is still needed for PyPy but not for CPython.
