### ISSUE TITLE
union does not keep attributes

### ISSUE THREAD

**Issue by rokroskar** [igraph/python-igraph#82]
apologies if this is the wrong place for such a question, but: it appears that currently union does not keep attributes? I found an [old thread](http://comments.gmane.org/gmane.comp.science.graph.igraph.general/1541) which seemed to suggest that an option `keep_attributes` would be added, but I can't find such an option anywhere. Is there a different method that should be used instead?

**Comment by ntamas** [comment]
True; `union` does not keep attributes and I haven't managed to implement this properly so far due to lack of time. There is no alternative implementation yet, so you'll need to code the `union` operator yourself if you want to keep the attributes. If you manage to come up with an implementation, please send us a pull request and then I'll try to integrate it into the master branch.

**Comment by rokroskar** [comment]
Ok thanks, just wanted to make sure I wasn't reinventing the wheel. Was the plan to implement it on the C library side or in python? My workaround in python is rather naive (keeping lists of weights and combining them in the end) and it will get very slow for large graphs I imagine.

**Comment by ntamas** [comment]
The original plan was to implement it in C because then all the higher level interfaces would get the functionality "for free". But of course it's much more complicated to do in C than in Python or R.

**Comment by rodrigolece** [comment]
+1 for this feature request!

I was recently trying to create hierarchical weighted graphs and my first idea was to used the overloaded addition or multiplication of graphs, but since the `disjoint_union` method does not copy the attributes it couldn't be done in this way.

**Comment by iosonofabio** [comment]
#310 deals only with union/intersection, not disjoint union, however it seems easy enough to include that one as well. @ntamas?

**Comment by ntamas** [comment]
I'd be very grateful if you could add disjoint union as well. I promise to get it reviewed as soon as possible; I have a very long backlog right now but eventually I'll get to it. Thanks a lot!

**Comment by iosonofabio** [comment]
No worries mate, I'll add disjoint union. Let me figure out what it is
