### ISSUE TITLE
Building on top of igraph: Full inheritance of modules seems not consistent

### ISSUE THREAD

**Issue by rajanski** [igraph/python-igraph#83]

**Comment by ntamas** [comment]
Even the first code snippet does not work since `ExtendedIGraph` does not have a `plot()` method. `plot()` is a member of the `igraph` namespace, and it works with any graph subclass. This is a snippet from an empty Python session on my machine that demonstrates that it works:

```
>>> import igraph as ig
>>> class MyGraph(ig.Graph):
...     def __init__(self, *args, **kwds):
...         super(MyGraph, self).__init__(*args, **kwds)
...
>>> g = MyGraph.GRG(100, 0.2)
>>> type(g)
<class '__main__.MyGraph'>
>>> ig.plot(g)
<igraph.drawing.Plot object at 0x106647090>
```
