### ISSUE TITLE
`Edge.source_vertex` missing from documentation

### ISSUE THREAD

**Issue by yunesj** [igraph/python-igraph#85]
`Edge.source` is documented at [python-igraph manual](http://igraph.org/python/doc/igraph.Edge-class.html), but `Edge.source_vertex` is not. And it's really useful. Same for `target_vertex`.
```
>>> import igraph
>>> t = igraph.Graph.Tree(2, 1)
>>> t.es[0].source_vertex
igraph.Vertex(<igraph.Graph object at 0x7fc837e23718>,0,{})
```

**Comment by ntamas** [comment]
Hmmm, probably it's time to regenerate the documentation... Thanks for the bug report, I'll take care of this.

**Comment by ntamas** [comment]
Hang on, are you using a development version of igraph? `source_vertex` and `target_vertex` were not there in 0.7.1-post6, which is still the latest official release.

**Comment by yunesj** [comment]
Sorry! Thanks for the new feature!
