### ISSUE TITLE
graph.read_pajek() doesn't populate graph.vs["name"]

### ISSUE THREAD

**Issue by acattle** [igraph/python-igraph#86]
When reading in Pajek files, igraph doesn't recognize the vertex labels. Thus using commands such as graph["Vertex1", "Vertex2"] results in a ValueError even if "Vertex1" and "Vertex2" are specified in the Pajek file.

I noticed that the vertex labels are actually being read, however instead of storing the labels in vs["name"] as expected it stores them as vs["id"]. Manually assigning the value of vs["id"] to vs["name"] solves this issue.

The attached zip file contains both a simple pajek file and a script demonstrating the issue.

[pajek_bug.zip](https://github.com/igraph/python-igraph/files/329535/pajek_bug.zip)

**Comment by ntamas** [comment]
Would it help if we simply imported the vertex IDs in the Pajek file into both the `id` and `name` vertex attributes? (We cannot stop importing them into `id` because that would break backwards compatibility).

**Comment by acattle** [comment]
That would work for my purposes as it's basically what I'm doing anyway as a work-around.

This won't affect my project but my only concern would be how you implement it. If `id` and `name` both point to the same list object it may not be obvious to a future user that changing the value of one changes the other. If they contain separate copies then you're increasing the amount of memory needed (although it's only a list of strings). Is there any reason someone would want `id` and `name` to have different values?

**Comment by ntamas** [comment]
> If id and name both point to the same list object
No, they would not point to the same list object; I would have to implement the change in the C layer, where this would not be possible anyway. Essentially, you would end up with two independent set of attributes: `id` and `name`. They would happen to contain the same value after having loaded the graph, but it would be possible to modify one of them without affecting the other.

> If they contain separate copies then you're increasing the amount of memory needed
I am not particularly concerned about this; Python does string interning on its own (well, at least CPython does), so short IDs that Python deems worthwhile to intern would still point to the same string object anyway.

> Is there any reason someone would want id and name to have different values?
Well, if the vertices represent people, two people could have the same name but they would probably have different IDs ;) But anyway, we should keep the `id` attribute in place to avoid breaking other people's code who rely on the fact that the IDs of the vertices in a Pajek file are stored in the `id` attribute, so I think that's the best I can do at this point.

**Comment by ntamas** [comment]
FIxed in the C core in https://github.com/igraph/igraph/commit/e423d9edaade2a0dcd130ab7c0e5996832ca123d
