### ISSUE TITLE
example python code for igraph

### ISSUE THREAD

**Issue by idc9** [igraph/python-igraph#93]
I recently started using igraph and find the process of orienting myself to the package a little slow due to the lack of example code. A number of my collaborators had similar experiences. The [tutorial](http://igraph.org/python/doc/tutorial/tutorial.html) is certainly a good starting place and I've found a few other sources of example code. There is a lot of [example code](https://github.com/kolaczyk/sand) in R from the SAND textbook, however, not as many (that I can find) in Python. 

I find that small worked out examples (that display results of the code) are the best way to learn a new package. For example check out the examples of how to do basic tasks with pandas on [Chris Albon's website](http://chrisalbon.com/). These were far more helpful for learning how to use pandas than the pandas documentation.

**igraph is a wonderful package and deserves example python code that lowers the barrier to entry for new users**.

Does anyone know of a good source of example code that I'm missing? If so these should be linked to on the website. Otherwise it might be worth creating a bunch of examples and posting them to the website.

**Comment by ntamas** [comment]
You are totally right, the documentation of python-igraph is a bit lacking, mostly due to lack of spare time on my side (I am not working in academia any more so I am unable to dedicate as much time to igraph as I used to). If anyone is willing to contribute example code, I'd be happy to link to it from the main webpage or even include it on the main webpage.

**Comment by adodell** [comment]
@ntamas I'd be willing to redo the Tutorial on the python-igraph site, since it's written for Python 2.7 and igraph 6.0. It also looks like a few of the visuals are wrong in the tutorial.

I could even write some more documentation or examples, if you give me some direction on what is needed and the format you'd like the docs/examples to be written in.

**Comment by ntamas** [comment]
Thanks for your offer! The tutorial is in the python-igraph repo in the `doc/source` subdirectory; the pages are written in [reStructuredText](http://docutils.sourceforge.net/rst.html) and the figures are plain PNG files (see the `doc/source/figures` subdir). Feel free to make any modifications in a fork and then send a pull request with the documentation improvements.

**Comment by szhorvat** [comment]
@adodell Are you still feeling up for it? :-)

**Comment by vtraag** [comment]
Regarding this, @jboynyc is working on this in PR #279.  Perhaps we should already merge that PR, so that we already include those contributions? We can then continue with improving the documentation.

**Comment by jboynyc** [comment]
My available time to work on the documentation overhaul has shrunk pretty dramatically, so I think merging in incremental changes might be the best bet right now.

**Comment by ntamas** [comment]
Okay, I'm reviewing and merging #279 soon.

**Comment by clncy** [comment]
I'd be happy to contribute to the docs. Unless there is something else that is more of a priority, shall I work on the [graph analysis](https://igraph.org/python/doc/tutorial/analysis.html) section?

**Comment by ntamas** [comment]
That would be awesome. The [graph generation](https://igraph.org/python/doc/tutorial/generation.html) is also a good candidate. Thanks a lot in advance!

**Comment by szhorvat** [comment]
@clncy If you're looking for "cool examples" or visualizations to include, feel free to borrow from [the IGraph/M docs](http://szhorvat.net/mathematica/IGDocumentation/) any way you like.
