### ISSUE TITLE
`MyGraph.Tree` should call `MyGraph.__init__`

### ISSUE THREAD

**Issue by yunesj** [igraph/python-igraph#97]
The following code gives an assertion error.

```
import igraph

class MyGraph(igraph.Graph):
 def __init__(self, *args, **kwargs):
  super(MyGraph, self).__init__(*args, **kwargs)
  print 'initializing MyGraph...'
  self.initialized = True

my_tree = MyGraph.Tree(n=3, children=2)
assert isinstance(my_tree, MyGraph)  # ok
assert 'initialized' in my_tree.__dict__  # error
```

Shouldn't it run error-free like the follwing code?

```
class MyDict(dict):
 def __init__(self, *args, **kwargs):
  super(MyDict, self).__init__(*args, **kwargs)
  print 'initializing MyDict...'
  self.initialized = True

my_dict = MyDict.fromkeys('ABC')
assert isinstance(my_dict, MyDict)  # ok
assert 'initialized' in my_dict.__dict__  # ok
```

Thanks!

**Comment by ntamas** [comment]
Yes, you are right, and further inspection showed that the calling of the `__init__` method is fundamentally broken for "alternative" constructors like `Graph.Tree`. I'll fix this soon.

**Comment by ntamas** [comment]
This has turned out to be more complicated than I initially anticipated, and then I did not have too much spare time to work on python-igraph at all, but now I finally managed to implement a proper fix.

**Comment by yunesj** [comment]
Thanks so much!
