### ISSUE TITLE
bug in coloring vertices

### ISSUE THREAD

**Issue by jkholtzman** [igraph/python-igraph#98]
I want to progressively size and color vertices depending on node degree. Sizing works fine, however, coloring doesn't seem to work. Simple example to demonstrate follows. The Git code renderer is falsely displaying some of the CSS coded vertext_colors with two digits. See the source of this message for actual.

```
import igraph as ig

vertices = ['a','b','c','d','e','f']
edges = [(0,1), (1,2), (1,2), (1,3), (1,4), (2,3), (2,3), (2,3)]

g = ig.Graph(vertex_attrs={"label": vertices}, edges=edges, directed=False)
g.es['weight'] = 1

layout = g.layout_circle()

visual_style = {}
visual_style['vertex_size'] = [10 + 4 * w for w in g.degree()]
visual_style['vertex_label_color'] = 'blue'
visual_style['vertex_label_dist'] = 1.2
visual_style['edge_width'] = [w for w in g.es['weight']]
visual_style['edge_color'] = '#C0C0C0'
visual_style['layout'] = layout
visual_style['bbox'] = (1024,1024)
visual_style['margin'] = 50
visual_style["edge_curved"] = True
visual_style['vertex_color'] = ['#000000', '#000040', '#000080', '#0000C0', '#0000F0']
print visual_style['vertex_color']
ig.plot(g, **visual_style)
```

**Comment by jkholtzman** [comment]
I'll give a more detailed demonstration. This graph shows a dense little subgraph of my dataset. Each vertex is sized and colored according to degree. Each vertex is annotated with an id and the degree on the line below. I used the rainbow palette method here. I would expect nodes with the same degree to have the same color, but that is not occurring. In fact, every single node has a different color. 

<img width="802" alt="igraph_sample_688547" src="https://cloud.githubusercontent.com/assets/556309/19320165/2cf7328a-907e-11e6-8574-ca4d4df1c5ac.png">

Here is the code for the labeling and coloring.

`
        num_colors = len(sub_graph.degree())
        palette = ig.RainbowPalette(n=num_colors)
        color_list = []
        for i in range(num_colors):
            color_list.append(palette.get(i))

        labels = [str(l) +'\n'+str(d) for d,l in zip(sub_graph.degree(), sub_graph.vs['label'])]

`

Then later, `            'vertex_color'  : color_list, `

**Comment by ntamas** [comment]
In your second example, you are creating a rainbow palette that contains as many entries as the number of vertices in your graph, and then you get the i-th color from the palette for the i-th vertex. This will give you unique colors for each vertex. What you (probably) want is to take vertex i, get its degree d(i), and then get the d(i)-th entry from the palette:

```
num_colors = max(sub_graph.degree()) + 1
palette = ig.RainbowPalette(n=num_colors)
color_list = [palette.get(degree) for degree in sub_graph.degree()]
```

This should do what you want.

**Comment by jkholtzman** [comment]
Thanks so much - exactly what I needed.

**Comment by jkholtzman** [comment]
But it still leaves the issue in the original post. I cannot get colors to display correctly using either css '#xxxxxx' or rgb(#, #, #) formats. 
``
#visual_style['vertex_color'] = ['#000020', '#000040', '#000060', '#000080', '#0000A0']
visual_style['vertex_color'] = ['rgb(0,0,40)', 'rgb(0,0,80)', 'rgb(0,0,120)', 'rgb(0,0,160)', 'rgb(0,0,200)']
``

For the latter I got the following plot, where the colors are not incrementing along the blue scale.

<img width="588" alt="screen shot 2016-10-12 at 4 43 29 pm" src="https://cloud.githubusercontent.com/assets/556309/19327034/14a7a2f6-909b-11e6-8207-7536300ecf2a.png">

**Comment by ntamas** [comment]
What is wrong with the plot? For me it seems that the first vertex (i.e. vertex `a`) got `rgb(0, 0, 40)` as its color, the second one (i.e. vertex `b`) got `rgb(0,0,80)` and so on.

**Comment by jkholtzman** [comment]
My bad - the color tool I'm using is giving odd results.
