### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by sulantha2006** [igraph/python-igraph#99]
HI I am trying to install igraph on anaconda python3.5
However, install completes fully. But I get a import error. 

I did install first using pip and then using source 'python setup.py install'

Both times I get this error

File "/home/sulantha/anaconda3/lib/python3.5/site-packages/python_igraph-0.7.0-py3.5-linux-x86_64.egg/igraph/**init**.py", line 34, in <module>
    from igraph._igraph import *
ImportError: /home/sulantha/anaconda3/lib/python3.5/site-packages/python_igraph-0.7.0-py3.5-linux-x86_64.egg/igraph/_igraph.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZdlPvm

**Comment by ntamas** [comment]
Installation works just fine for me with Anaconda Python 3.5. You probably have an older version of python-igraph lying around on your machine; apparently the version number of python-igraph in your `site-packages` folder is 0.7.0, while the current version is 0.7.1-post6.

Try deleting `/home/sulantha/anaconda3/lib/python3.5/site-packages/python_igraph-0.7.0-py3.5-linux-x86_64.egg/` and then reinstall using `pip`. Installation with `pip` should work fine.

**Comment by sulantha2006** [comment]
Hi, 
I removed the dir (/home/sulantha/anaconda3/lib/python3.5/site-packages/python_igraph-0.7.0-py3.5-linux-x86_64.egg/) and installed with pip. 
Successfully installed python-igraph-0.7.1.post6
But I still get this error. 
ImportError: /home/sulantha/anaconda3/lib/python3.5/site-packages/igraph/_igraph.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZdlPvm
Any idea?
S

**Comment by ntamas** [comment]
No idea, sorry, it works just fine for me. It is either something specific to your machine or to Anaconda Python on your particular platform. Try asking around on the support channels of Anaconda Python - maybe they have some ideas.

**Comment by shainova** [comment]
Did you solve this problem? I have this too...

**Comment by hajef** [comment]
Maby Related: I can't make python-igraph work with Anaconda 4.3.1 and Python 3.6.0 under 64-bit windows. I can't even install it - neither with standard pip install nor from wheel.

**Comment by ntamas** [comment]
Others have reported that [these packages](https://anaconda.org/marufr/python-igraph) work on Anaconda Python.

**Comment by hajef** [comment]
I get an unsatisfiableError beacause my python 3.6* does not match the required python 2.7* :/

**Comment by anton-molyboha** [comment]
I think I know what causes it, but don't have a workaround yet.

_ZdlPvm is a symbol in the C++ standard library, libstdc++  -- but it seems to be something new and only present in the more recent versions of it.
When python-igraph is installed, it is compiled against your system's libstdc++
When we try to import igraph, the version of libstdc++ which comes with anaconda is loaded instead. And while the system's version of libstdc++ (libstdc++.so.6.0.24 in my case) does export _ZdlPvm, the version that comes with Anaconda (libstdc++.so.6.0.19) does not.

We need some way to make the same version of the library to be used during compilation and run-time -- but I'm not sure how to achieve that yet.

**Comment by ntamas** [comment]
It seems like other packages are suffering from the same issue; e.g.: https://github.com/Theano/Theano/issues/5845

**Comment by schumannc** [comment]
Same issue. 
conda install libgcc  solve for me!
